### ISSUE TITLE
about LANGUAGE mandarin ，Phrase is too long to be an effective wake word

### ISSUE THREAD

**Issue by SibelJIA** [Picovoice/porcupine#1001]
When I saw that it finally supports Mandarin, I was overjoyed. However, when I tested it, I found that many words were not recognized correctly. Can the length of the words be increased?

Because Chinese names are usually long。

I am eagerly awaiting your response.

**Comment by xiaoqiang1999** [comment]
我也遇到了仅支持3个中文字的问题，请问大佬如何解决
