### ISSUE TITLE
wakeword and intent in one utterance

### ISSUE THREAD

**Issue by mph070770** [Picovoice/porcupine#1011]
Hi.  I'm new to porcupine/rhino and would value some assistance.  In the project I'm working on, I want to use a wakeword as part of the query.  For example:

what time is it in Germany
what time is it in New York
what time is it in London

the keyword is "what time is it".

I've built the shepherd demo for the IMXRT1050 processor and what I've found is that I need a gap between the wakeword and location:

what time is it......... in Germany  [works]
what time is it in Germany         [wakework not spotted]

Is this just a implementation specific issue with shepherd or do I need to consider how i use wakewords and utterances?

Thanks

**Comment by kenarsa** [comment]
The wake word models, by default, expect a pause. So you do need a pause between your wake word and the followup utterance.
