### ISSUE TITLE
ValueError: Invalid frame length. expected 512 but received 169984

### ISSUE THREAD

**Issue by Aashutoshvyas2020** [Picovoice/porcupine#1019]
im making my voice assistant but ive come across this error:

ValueError: Invalid frame length. expected 512 but received 169984

what does this mean how can i fix it?

def recognize_speech():
    with sr.Microphone() as source:
        print("Listening for wake word...")
        
        # Continuously listen for audio until the wake word is detected
        while True:
            audio = r.listen(source)
            
            # Process audio for wake word detection
            pcm = audio.frame_data
            keyword_index = handle.process(pcm)
            
            # If wake word is detected, break out of the loop
            if keyword_index >= 0:
                print("Wake word detected!")
                break

here is relevant code snippet

**Comment by laves** [comment]
Please [read the documentation](https://picovoice.ai/docs/api/porcupine-python/) and refer to our [demos](https://github.com/Picovoice/porcupine/tree/master/demo/python) before posting an issue. As the error message said, you are passing in a frame that is too large to `.process()`. The frame size required is specified by `.frameLength` and is `512` as the message suggested.  You'll need to break up that larger frame into smaller ones.

**Comment by Aashutoshvyas2020** [comment]
oh thanks so much, sorry for that.
