### ISSUE TITLE
Porcupine Issue: When used in docker, the users limit is increasing

### ISSUE THREAD

**Issue by spljs** [Picovoice/porcupine#1020]
Hello,

i'm contacting you because i have some problem with docker & porcupine fingerprint algorithm for max users limit per month on free tier (3)

### Expected behaviour

The users limit (3 max) should remain the same if running on the same host (even in docker)

### Actual behaviour

Each time i rebuild a docker image with my api key , the picovoice console is adding one more user in my usage limit (3 max). Maybe your fingerprint algorithm is based on some characteristics that docker renew each time.

Some precisions about my environment: 

- Same network (not changed between the builds)
- Same hostname
- Same base image 
- Same python version

### Steps to reproduce the behaviour

1. Build a simple app in python with porcupine, with a free tier API key
2. Dockerize it 
3. Run it
4. Make modification & rebuild your image
5. Run it again
6. Users have increased on the console

Do you have any known issue with docker ? Or best pratices to use it for porcupine ? 

The problem is that I can not have a proper deployment process if I reach the 3 users after 3 deployments...

**Comment by mrrostam** [comment]
This question has been asked on [#552](https://github.com/Picovoice/picovoice/issues/552). Unfortunately, there's nothing we can do at the moment.
