### ISSUE TITLE
Porcupine Issue: Cant install the demo project due to missing files

### ISSUE THREAD

**Issue by tannerpace** [Picovoice/porcupine#1021]
# Title: Bug report - Install script failing due to missing .ppn file

## Describe the bug
When running the install script yarn ios-install or yarn android-install, the script fails to complete successfully. The error message indicates a missing .ppn file.

## Expected behavior
I expect the install script to complete successfully, thereby setting up the required environment to run the application.

##Actual behavior
The install script fails with the error: "ENOENT: no such file or directory, copyfile '../../resources/porcupine/resources/keyword_files/android/pico_clock_android.ppn' -> './android/picovoice-rn-clock-app/src/main/assets/pico_clock_android.ppn'".

The error message suggests that it cannot find the 'pico_clock_android.ppn' file.

To Reproduce

Clone the repo.
Create a new Xcode project.
Run 'yarn' to install node modules.
Run 'yarn' again to link pods.
Attempt to run the project.
Additional context
Upon inspecting the file system, I found that the directory that the copy.js script was attempting to access is empty. I tried installing the Android portion of the project in an attempt to generate the required .ppn file. My goal is to run the demo application to use as a reference for an enterprise application. However, due to this issue, I am unable to proceed.

Any assistance with this issue would be greatly appreciated.

**Comment by mrrostam** [comment]
Could you please clarify which demo and SDK you are attempting to run?

**Comment by tannerpace** [comment]
I am trying to run react native, IOS and ANDROID The copy.js script can't seem to find the file . URL for projects.  I pulled down the entire picovoice repo https://github.com/Picovoice/picovoice/blob/master/demo/react-native.  https://github.com/tannerpace/picovoice/blob/master/demo/react-native-clock.

**Comment by mrrostam** [comment]
Understood! The demos you are referring to belong to a different [repository](https://github.com/Picovoice/picovoice). This repository is specifically for the issues related to Porcupine. Therefore, I will close this issue. Please open a new issue there.
