### ISSUE TITLE
ESP32 Support!

### ISSUE THREAD

**Issue by torntrousers** [Picovoice/Porcupine#106]
I've been playing about with Porcupine and love it, but it would be so much better if it ran on an ESP32!

**Comment by kenarsa** [comment]
Happy that porcupine is being useful. Yeah, we would love to add new platforms. We do need a lead commercial customer for a given platform to justify porting to it though. Alternatively , Espressif can choose to cover the cost to make porcupine available on ESP32. Let's keep this issue open and see if we can get more people to upvote. Then we might have a good care for Espressif folks ...

**Comment by frippe75** [comment]
Would we/you expect tons of work? (not having looked at the code at all, sorry)

**Comment by kenarsa** [comment]
Yes, it is substantial work.

**Comment by Kixunil** [comment]
Is this even possible? ESP32 has only 512kB of RAM.

**Comment by kenarsa** [comment]
yes

**Comment by sethcohn** [comment]
With Espressif having their own wakeword tech (see esp-adf) I'm not sure they've got a reason to pay for development of an esp32 version.  This is the problem with closed binary implementing... Yours and theirs to be honest.  They want someone commercial to pay for wakewords beyond their scant few (mostly Chinese), and you want funding to pay for porting this to their hardware.  Neither is likely to be accessible to most of us as a result.

**Comment by kenarsa** [comment]
I am closing this issue for now. It is unlikely that we invest into porting to ESP platform considering other priorities in the next year or so.

**Comment by sumitpatel0911** [comment]
I've been playing about with Porcupine and love it, but it would be so much better if it ran on an ESP32!
