### ISSUE TITLE
how to run code in javascript wake word detection 

### ISSUE THREAD

**Issue by amirx1991** [Picovoice/porcupine#1063]
i want to use picovoice wake word in javascript and see this code 
 let porcupine = await PorcupineWeb.PorcupineWorker.create(
              accessKey,
              [PorcupineWeb.BuiltInKeyword.Picovoice],
              porcupineKeywordCallback,
              { base64: PORCUPINE_MODEL_BASE64 },
      );

but porcupineKeywordCallback not define any where

**Comment by kenarsa** [comment]
read the docs or look into the source code of the relevant demo as an example usage
