### ISSUE TITLE
Android Activity Demo keywords are displayed in Farsi

### ISSUE THREAD

**Issue by ed5464215** [Picovoice/porcupine#1064]
I am running the Android Activity Demo but the keywords are displayed in Farsi. 

Downloaded from Git today, using JDK 11, Gradle 8.0, latest Android Studio Flamingo. I have no non-English apps installed.

**Comment by kenarsa** [comment]
did you select the build variant as pointed out in the [readme](https://github.com/Picovoice/porcupine/tree/master/demo/android/Activity)?

**Comment by ed5464215** [comment]
That fixed it. Thanks!

**Comment by ed5464215** [comment]
Hey I downloaded a custom wake word file (.ppn) and added it to the ${ANDROID_APP}/src/main/assets directory of my Android project (manually copied it into the folder from Windows), but it keeps getting deleted. And I do not see the /keywords or /models subfolders in the  ${ANDROID_APP}/src/main/assets folder.

**Comment by ed5464215** [comment]
I did a "reload from disk" and I do see the /keywords and /models folders now, but my ,ppn still keeps getting deleted.

**Comment by ed5464215** [comment]
I going create a new issue you can close this one.
