### ISSUE TITLE
Custom .ppn being removed from Android APK

### ISSUE THREAD

**Issue by ed5464215** [Picovoice/porcupine#1065]
I created a custom wake word file (.ppn) from the website and added it to the ${ANDROID_APP}/src/main/assets/keywords directory of the Android demo project , but it keeps getting deleted during the build. I'm referencing it like this
            
```
PorcupineManager.Builder builder = new PorcupineManager.Builder()
                    .setAccessKey(MY_ACCESS_KEY)
                    .setSensitivity(0.7f)
                    .setKeywordPaths(new String[]{"keywords/" + "my-test_en_android_v2_2_0.ppn"});
```
                    
The error on the screen is
                    
_Failed to initialize Porcupine java.io.FileNotFoundException: keywords/my-test_en_android_v2_2_0.ppn_
                    
I have tried also tried using assets/ folder with same results. My environment is Java 11, Gradle 8.0, latest Android Studio Flamingo, Android 14, Pixel 7, porcupine 2.2.0.   I have tried adding to Git, synching Gradle, and clean rebuild.
                    
It seems like Android Studio is removing the .ppn files from the APK because they are not recognized. There is a similar issue discussed here (but I am not using Unity):

https://github.com/Picovoice/picovoice/issues/148

**Comment by kenarsa** [comment]
1- Don't label your issue a `bug` unless you are sure it is. You did it for your last issue; it was your mistake, not a software bug.
2- Did you follow the [documentation](https://picovoice.ai/docs/quick-start/porcupine-android/#custom-keywords)?

**Comment by ed5464215** [comment]
I should have used blank issue for help request, sorry.

Yes I followed the docs. The example works with the 'alexa' sample. 

Is there a way to mark the file so that Android Studio does not remove the .ppn from assets? Do I need to do something like mentioned in the linked issue? My .ppn is 3.06 kB.

**Comment by ed5464215** [comment]
kenarsa,

I am not sure what the problem was with modifying the demo, but I went ahead and implemented a porcupine service in my application and added the PPN and it works great!

Awesome product!
