### ISSUE TITLE
Porcupine Issue: account login mysteriously disappears

### ISSUE THREAD

**Issue by skybrian** [Picovoice/porcupine#1074]
### Expected behaviour

Should be able to log in to the account we created yesterday.

### Actual behaviour

Got this error message:

>  an account with this email has been deleted and can no longer be used.

### Steps to reproduce the behaviour

- Created an account.
- Copied the access key. Created a wakeword file.  Wrote a Flutter app using the access key and wakeword file. Tried it out.
- Tried to log in the next day.

This has happened twice so far with two different email addresses.

**Comment by ksyeo1010** [comment]
Picovoice Audit System can delete accounts in case of [Picovoice Terms of Use](https://picovoice.ai/docs/terms-of-use/) violations, such as suspicious activities, creating multiple accounts, providing false or inaccurate information.

If you think there is a mistake, please send an email to [hello@picovoice.ai](mailto:hello@picovoice.ai) with your name, surname, country, city and project details. We’ll investigate it further.
