### ISSUE TITLE
Porcupine Issue: 

### ISSUE THREAD

**Issue by dalealleshouse** [Picovoice/porcupine#1076]
### Expected behaviour
`porcupine_demo_mic` should not throw an error

### Actual behaviour
``` bash
porcupine_demo_mic --access_key ${ACCESS_KEY} --keywords picovoice                              
Porcupine version: 2.2.0                                                                                                                  
Listening ... (press Ctrl+C to exit)                                                                                                      
Traceback (most recent call last):                                                                                                          
File "/usr/local/bin/porcupine_demo_mic", line 8, in <module>                                                                               
sys.exit(main())                                                                                                                       
File "/usr/local/lib/python3.9/dist-packages/pvporcupinedemo/porcupine_demo_mic.py", line 140, in main                                      
pcm = recorder.read()                                                                                                                   
File "/home/dalealleshouse/.local/lib/python3.9/site-packages/pvrecorder/_pvrecorder.py", line 178, in read                                 
raise self._PVRECORDER_STATUS_TO_EXCEPTION[status]("Failed to read from device.")
```

### Steps to reproduce the behaviour
Rasberry Pi 3 Model B
- Fresh install of Rasberry Pi OS
- Installed AIY voice hat (https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/HACKING.md)
- All Google Assistant demos are working, so the mic and speaker are installed correctly.

Additional Information:
``` bash
arecord -l                                                                                      
**** List of CAPTURE Hardware Devices ****                                                                                                
card 0: sndrpigooglevoi [snd_rpi_googlevoicehat_soundcar], device 0: Google voiceHAT SoundCard HiFi voicehat-hifi-0 [Google voiceHAT SoundCard HiFi voicehat-hifi-0]                                                                                                                  
Subdevices: 1/1                                                                                                                           
Subdevice #0: subdevice #0
```

``` bash
porcupine_demo_mic --show_audio_devices
Device 0: Monitor of Built-in Audio Stereo
Device 1: Built-in Audio Stereo
```

Passing in --audio_device_index 0, --audio_device_index 1, and --audio_device_index -1 have no effect.

I'm at a loss on where to go from here. Thank you for your time.

**Comment by ksyeo1010** [comment]
Can you tell me which specific mic are you using for the demo? Do both devices show the same error message or a different one? If possible can you try with another USB mic and see if that has the same issue?

**Comment by dalealleshouse** [comment]
@ksyeo1010 - Thank you for your prompt response.

I'm using the microphone that comes with this kit: https://aiyprojects.withgoogle.com/voice-v1/.

I've tried using `--audio_device_index 0` and `--audio_device_index 1`, which both return the same error. I don't own a USB microphone. I could purchase one if that's the only troubleshooting option. 

FWIW, I am able to run `arecord -f cd test.wav` and then play it back with `aplay test.wav` without an issue.

**Comment by ksyeo1010** [comment]
The recorder uses https://github.com/mackron/miniaudio as the backend. By any chance can you build their simple capture example (https://github.com/mackron/miniaudio/blob/master/examples/simple_capture.c) and see if it works for your current device?

**Comment by dalealleshouse** [comment]
It appears to work fine

```
gcc ../simple_capture.c -o bin/simple_capture -ldl -lm -lpthread -latomic 
dalealleshouse@raspberrypi:~/miniaudio/examples/build $ ./bin/simple_capture test.wav                                                                                  Press Enter to stop recording...
```

**Comment by ksyeo1010** [comment]
ok thanks for reporting, we will take a further look at it. Will let you know back in this thread when there's an update.

**Comment by dalealleshouse** [comment]
Thank you! Let me know if there is any more information I can provide.

**Comment by ksyeo1010** [comment]
We will be updating the libs with latest miniaudio, can you see if the demo for pvrecorder on a separate branch works so we know for sure it is working for you?

1. `git clone https://github.com/Picovoice/pvrecorder.git`
2. `git checkout lib-update`
3. `cd pvrecorder/demo/c`
4. `cmake -S . -B build -DPV_RECORDER_PLATFORM=raspberry-pi3`
5. `cmake --build build`
6. `cd build`
7. `./pv_recorder_demo --output_wav_path test.wav`

**Comment by ksyeo1010** [comment]
we have release new version instead, you can try `pvporcupinedemo==2.2.3` instead of the steps above

**Comment by dalealleshouse** [comment]
Thank you for the update. I will try this weekend. Due to a time constraint, I had to go another route with my project. I'll need to reconstruct the experiment.
