### ISSUE TITLE
Porcupine Issue: 

### ISSUE THREAD

**Issue by JackTWing** [Picovoice/porcupine#1077]
Hello!

My account is not letting me log in, and my Python program that I run Porcupine in is crashing every time I try to run it.  Yesterday, it was working fine.  I suspect it has something to do with both an error message in my program (
raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineActivationRefusedError) and also a message I get when I try to log in to my account (An account registered with '*********.com' has been deleted and can no longer be used).  Is there any way you can help with this problem?

Thanks for your consideration!

**Comment by ErisMik** [comment]
Picovoice Audit System can delete accounts in case of [Picovoice Terms of Use](https://picovoice.ai/docs/terms-of-use/) violations, such as suspicious activities, creating multiple accounts, providing false or inaccurate information.

If you think there is a mistake, please send an email to [hello@picovoice.ai](mailto:hello@picovoice.ai) with your name, surname, country, city and project details. We’ll investigate it further.
