### ISSUE TITLE
False keyword detection

### ISSUE THREAD

**Issue by jhndnnqsc** [Picovoice/Porcupine#108]
### Expected behavior
I have 2 keywords defined - "screen on" and "screen off". Each should trigger independently.
### Actual behavior
When I say "screen on" both keywords are triggered. When I say "screen off" only screen off is detected.
### Steps to reproduce the behavior
I'm running the python 3.6 demo on Windows 10 with the following output. I've attached the keywords in case that helps.
````
python demo\python\porcupine_demo.py --keyword_file_paths "tools\optimizer\windows\i686\screen on_windows.ppn,tools\optimizer\windows\i686\screen off_windows.ppn"
listening for:
- screen on (sensitivity: 0.500000)
- screen off (sensitivity: 0.500000)
[2018-10-26 16:20:39.816331] detected screen on
[2018-10-26 16:20:39.846272] detected screen off
[2018-10-26 16:20:43.906247] detected screen off
````
[keywords.zip](https://github.com/Picovoice/Porcupine/files/2521115/keywords.zip)

**Comment by kenarsa** [comment]
what's the sensitivity value? I suggest lowering it (probably even set to zero). In general, you want the wake words to sound different. https://picovoice.ai/docs/choose-voice-commands/

In your case, there is only a difference in one sound which makes it hard.

**Comment by jhndnnqsc** [comment]
Setting the sensitivity to 0 has the same behavior.
````
python demo\python\porcupine_demo.py --keyword_file_paths "tools\optimizer\windows\i686\screen on_windows.ppn,tools\optimizer\windows\i686\screen off_windows.ppn" --sensitivities 0,0
listening for:
- screen on (sensitivity: 0.000000)
- screen off (sensitivity: 0.000000)
[2018-10-29 09:10:22.767693] detected screen on
[2018-10-29 09:10:22.797011] detected screen off
[2018-10-29 09:10:25.136567] detected screen off
[2018-10-29 09:10:27.153204] detected screen on
[2018-10-29 09:10:27.213926] detected screen off
[2018-10-29 09:10:29.103704] detected screen off
[2018-10-29 09:10:32.015902] detected screen on
[2018-10-29 09:10:32.076151] detected screen off
````

 I understand that 'on' and 'off' are similar words but they seem like very common words used in voice control applications.

**Comment by oziee** [comment]
I thought sensitivity is faulty in 1.4 and we are waiting on 1.5 to fix it?

**Comment by kenarsa** [comment]
yeah, the sensitivity will have a larger impact in v1.5. So that might help.

@jhndnnqsc agreed. but you can use something like "turn on" and "screen off".

**Comment by jhndnnqsc** [comment]
Is there a timeline for when v1.5 is planning on release? I am investigating incorporating voice control in our products and I think to make it effective we need to us commands that would be obvious to the end user like on and off.

**Comment by kenarsa** [comment]
no timeline at this point. If you have a commercial application send us an email with a brief description of use case including scale and we might be able to help sooner.

**Comment by jhndnnqsc** [comment]
I think our product manager is planning on getting in contact with you soon. I'm just working on the technical feasibility portion. Thanks.

**Comment by kenarsa** [comment]
closing for now.
