### ISSUE TITLE
When can we have porcupine_flutter support for Web and Desktop

### ISSUE THREAD

**Issue by mayursaini-pursuit** [Picovoice/porcupine#1086]
I am trying to implement porcupine_flutter in a flutter based project, as per the documents says it supports Cross Platform. But, the Flutter Plugin is only available for Android and iOS in pub dev?

**Comment by mayursaini-pursuit** [comment]
Okay I got it now. It supports multiple platforms. But, the **flutter** SDK only supports Android and iOS, right?

**Comment by mayursaini-pursuit** [comment]
But, Can we have porcupine_flutter support for Web and Desktop in future releases?

**Comment by laves** [comment]
Our Flutter SDKs are for Android and iOS only. We have several SDKs for web and desktop, so it is unlikely we will add Flutter modules for desktop and web. If you are an enterprise user and this is a requirement of your project, please reach out to your account manager.
