### ISSUE TITLE
Use of Bluetooth connected mic on Android

### ISSUE THREAD

**Issue by jwoodwardtfx** [Picovoice/porcupine#1087]
We use Porcupine on Android via the PorcupineManager. However, we have a specific set of users who attach a Bluetooth headset instead of using the phone's built in mic. From testing, it appears Porcupine (or rather PorcupineManager) always uses the built-in mic and we have no way of swapping to use the Bluetooth headset.

Is this a use case that could be supported?

**Comment by ksyeo1010** [comment]
This is a feature that is not supported. If you need  Bluetooth mic support, you should use `Porcupine` instead of `PorcupineManager` and handle the audio source separately. 

If you are a customer and need support, reach out to your account manager.
