### ISSUE TITLE
Where can I find the pre-trained wake words for all the supported languages?

### ISSUE THREAD

**Issue by Nullarity** [Picovoice/porcupine#1088]
### What is the URL of the doc?

https://picovoice.ai/docs/porcupine/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

I couldn't find information about the pre-trained wake words. Empirically, I discovered these words for English: 'alexa', 'americano', 'blueberry', and so on. Is this information documented for all languages?

Thank you!

**Comment by ksyeo1010** [comment]
you can find them in this repo: https://github.com/Picovoice/porcupine/tree/master/resources.
