### ISSUE TITLE
Package Support on Arm64v8

### ISSUE THREAD

**Issue by KertiZhao9** [Picovoice/porcupine#1089]
Currently, I am developing a domain-specific voice AI assistant and would like to include a wake word engine. I noticed that Porcupine does support Jetson Nano, which is great! I have a Jetson AGX Xavier and  I am wondering if it possible to get binary wheel or support on the arm64v8 architecture? Thanks!

**Comment by kenarsa** [comment]
It's not on the roadmap, unfortunately. If this is a commercial application with the budget allocated, feel free to contact the [sales team](https://picovoice.ai/pricing/).
