### ISSUE TITLE
Continual wake word detection

### ISSUE THREAD

**Issue by effigy** [Picovoice/porcupine#1091]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
i expected it to detect the wake word when audio input corresponding to the wake word was recorded

### Actual behaviour
it continually detects the wake word even in silence

### Steps to reproduce the behaviour

setup basic demo python script on raspberry pi running ubntu, usb mic works and records fine, audio files recorded in response to wake word detection play fine and sound fine.

`def wake_word_detected():
    print("Wake word detected. Recording audio...")
    audio_data = record_audio(10)
    save_audio(audio_data, "audio.wav")
    transcribe_audio("audio.wav")
    time.sleep(5) 

if __name__ == "__main__":
    porcupine = pvporcupine.create(access_key="+egBfj3x6kVryxbMrFIPNF0BC1bNFbkGLnYzRAVE/ppqGx7kW5aoBQ==",keywords=['porcupine'], )
    samplerate = porcupine.sample_rate
    num_channels = 1

    print("Listening for wake word 'Porcupine'...")

    with sd.InputStream(samplerate=samplerate, channels=num_channels) as stream:
        while True:
            audio_chunk, overflowed = stream.read(porcupine.frame_length)
            audio_chunk = (audio_chunk * 32767).astype(np.int16).flatten()
            if porcupine.process(audio_chunk):
                wake_word_detected()
`
my output looks like this:

`Recording complete.
Wake word detected. Recording audio...
Recording...
Recording complete.
Wake word detected. Recording audio...
Recording...
Recording complete.
Wake word detected. Recording audio...
Recording...
Recording complete.
Wake word detected. Recording audio...
Recording...
Recording complete.
Wake word detected. Recording audio...
Recording...
Recording complete.
Wake word detected. Recording audio...
Recording...
Recording complete.
Wake word detected. Recording audio...
Recording...
Recording complete.
Wake word detected. Recording audio...
Recording...
Recording complete.
Wake word detected. Recording audio...
Recording...
Recording complete.
Wake word detected. Recording audio...
Recording...
Recording complete.
Wake word detected. Recording audio...
Recording...
Recording complete.
Wake word detected. Recording audio...
Recording...
Recording complete.`

this occurs regardless of which wake word i try to use or whether i lower the sensitivity

**Comment by ksyeo1010** [comment]
Double-check your loop. This forum is only for issues with Picovoice's SDK and Picovoice's official demo.
