### ISSUE TITLE
Go wrapper and demo

### ISSUE THREAD

**Issue by charithe** [Picovoice/Porcupine#110]
Hi there,

I created a Go wrapper and a demo for Porcupine which can be found here: https://github.com/charithe/porcupine-go/

I just wanted to flag the existence of it in case there are other gophers interested in using Porcupine in their projects.

**Comment by kenarsa** [comment]
Awesome! Feel free to submit a PR and add to the main repo if you like . Happy to merge. Thanks for your contribution .

**Comment by charithe** [comment]
Thanks! I submitted PR #111 to add the Go demo to the main repo
