### ISSUE TITLE
Add Custom Words to Porcupine and Rhino Dictionary

### ISSUE THREAD

**Issue by StormDev2project** [Picovoice/porcupine#1109]
How can I add my word to your dictionary.Would I like to add the word "Астра" to use further in my voice assistant?

**Comment by laves** [comment]
For Porcupine and Rhino it is not currently possible to add a word directly. A workaround can be to use a homophone that is in our dictionary or use a couple of existing words to approximate the sounds. E.g) `Picovoice` -> `peek oh voice`
