### ISSUE TITLE
How to generate custom keyword in ARM Cortex A7

### ISSUE THREAD

**Issue by firechen** [Picovoice/Porcupine#113]
Hi All,

Currently, I am developing a voice conrol application in Respeaker core v2.0, which is Linux Debian system, with the core ARM Cortext A7. According to what I find in Porcupine, it is avalilable for us to generate custome keyword in linux with x86_64 and i386. However, I also notice that Raspberry pi is supported by Procupine and Raspberry pi is also with ARM Cortext CPU. Would you please give me some suggestions about how to generate custome keyword for ARM Cortext CPU?

best regards,
James

**Comment by kenarsa** [comment]
Hello James, you need to purchase the commercial license for that.

**Comment by kirsanau** [comment]
Hi,
we wrote to 'contact@picovoice.ai' some time  ago regarding the same, but so far no response. is there any other channel of communication?
