### ISSUE TITLE
windows：pvporcupine._porcupine.PorcupineInvalidArgumentError

### ISSUE THREAD

**Issue by lonngxiang** [Picovoice/porcupine#1132]
pvporcupine-2.2.1

```

porcupine = pvporcupine.create(access_key="VInSKF4MK***84R5NllrROuaey9ysv2PTbjQ==",keyword_paths=[r'C:\User***ds\xiaojie_zh_windows_v2_2_0\***.ppn'])

```

\pvporcupine\_porcupine.py", line 164, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineInvalidArgumentError

**Comment by ksyeo1010** [comment]
can you try in one of the the demos here: https://github.com/Picovoice/porcupine/tree/master/demo/python and see if you get the same error.

**Comment by lonngxiang** [comment]
> can you try in one of the the demos here: https://github.com/Picovoice/porcupine/tree/master/demo/python and see if you get the same error.

run this url file also error  ：
https://github.com/Picovoice/porcupine/blob/master/demo/python/porcupine_demo_mic.py

command：
python .\asr_picovoice_realtime_test.py --access_key "VInSKF4MKk***aey9ysv2PTbjQ==" --keyword_paths C:\Users\l***nloads\xiaojie_zh_windows_v2_2_0\xiaojie_zh_windows_v2_2_0.ppn


error：
![image](https://github.com/Picovoice/porcupine/assets/40717349/f2902750-5d89-40e4-850c-e270be64e574)

**Comment by ksyeo1010** [comment]
can you mail your access key to `kyeo@picovoice.ai` so I have a closer look.

**Comment by lonngxiang** [comment]
> kyeo@picovoice.ai

tks，sended

**Comment by ksyeo1010** [comment]
You need to pass in the chinese porcupine model as well. `--library_path ${PATH_TO_PORCUPINE_LIB}` which is here: https://github.com/Picovoice/porcupine/blob/master/lib/common/porcupine_params_zh.pv
