### ISSUE TITLE
Swift Demo fails on pressing Start due to "INVALID_ARGUMENT"

### ISSUE THREAD

**Issue by RoderickJDunn** [Picovoice/Porcupine#114]
### Expected behavior
Demo app should begin recording/analyzing audio when a keyword is selected and the Start button is pushed.

### Actual behavior
I get an Alert saying "Something went wrong", and an error log saying "loading parameter file failed with 'INVALID_ARGUMENT'".

### Steps to reproduce the behavior
Note: I did not want to clone the entire repo so I used [DownGit](https://minhaskamal.github.io/DownGit/#/home) to download the individual directories that I needed.
**Edit -- I have since confirmed that the issue exists even when cloning the repo as a whole, and running the demo project directly.**

1. Download the Swift Demo project folder (.../demo/ios) and open the xcodeproject file
2. Download the ios library (...lib/ios/libpv_porcupine.a), the parameters file (.../lib/common/porcupine_params.pv), the header files (.../include/picovoice.h, .../include/pv_porcupine.h), the keyword files (.../resources/keyword_files/*ios.ppn), and add them all to the XCode project.
3. Link the library, and add all resources to Copy Bundle Resources build phase. Also add the Headers to the Headers build phase (in project section).
4. Run app, and press Start.
5. Error

Additional Info
From some debugging I found it is the call to _pv_porcupine_multiple_keywords_init_, within the binding file PorcupineManager.swift, that returns the "INVALID_ARGUMENT" error mentioned above. I don't see anything wrong with any of the files being passed to this function. The _modelFilePath_ and _keywordFilePaths_ seem to have been successfully set to their proper locations, due to earlier calls to _Bundle.main.path(...)_.  

Environment
- XCode 9.2
- iOS 11.2 (iPhone 6 device)

Any help would be much appreciated!

**Comment by kenarsa** [comment]
Would it be possible to download the repo as a whole and run the demo without any changes? If that does not work then I'll be happy to look into it.

**Comment by mcgraw** [comment]
Same issue here.
`
[ERROR] loading parameter file failed with 'INVALID_ARGUMENT'`

**Comment by mcgraw** [comment]
Tested with Xcode 10.1 / iOS 12

**Comment by kenarsa** [comment]
Thanks a lot for verification. I'll look into this ASAP.

**Comment by kenarsa** [comment]
could you guys please try again? It should be solved. Please close the issue if it is resolved.

**Comment by mcgraw** [comment]
@kenarsa Verified. I appreciate your time & turnaround on the issue. Best wishes.
