### ISSUE TITLE
Picovoice Console Issue: 

### ISSUE THREAD

**Issue by cmm6758** [Picovoice/porcupine#1150]
Picovoice doesn't let me train any models for any of the sdks.

### Expected behaviour
I would be able to train porcupine models (and rhino models)

### Actual behaviour
porcup

### Steps to reproduce the behaviour

After producing a context or wake word, hit the train button. It states no models are available for me to train despite this being the first time this month I use them.

**Comment by ErisMik** [comment]
Hi, could you send an email to `hello@picovoice.ai` with your AccessKey and account email? Then I can investigate what the issue is.

**Comment by cmm6758** [comment]
Hello,

Thank you for the prompt reply. I have sent it from my picovoice account's email cmellarijo@gmail.com.

**Comment by ErisMik** [comment]
Thanks for reaching out. We investigated it further and found out that your account (along with another) was disabled due to suspicious activities. This might happen when you work on the same project with other Picovoice account owners. 

If you think there is a mistake, please send an email to [hello@picovoice.ai](mailto:hello@picovoice.ai) with your name, surname, country, city and elaborate on your project and whether you work on the same project with others. We’ll investigate it further.

**Comment by cmm6758** [comment]
Hello, I submitted the email as instructed last week but there has been no update in my email. Was it received correctly? This was the message I sent on Nov 2:


Name: Carlos Mella-Rijo
City, Country; Arlington, TX, USA
Email: [cmellarijo@gmail.com](mailto:cmellarijo@gmail.com)
Access Key:  BKZ6QIyCZPIirHUNrqCmxR8mwVJHIPSGFv22P2/rFGpqJilSGLmf/g==

Issue: I have 0/0 trainable models available for all platforms despite not having used them this month

Upon giving out my information in a Github issue in picovoice's repo, I was informed of this:

"Thanks for reaching out. We investigated it further and found out that your account (along with another) was disabled due to suspicious activities. This might happen when you work on the same project with other Picovoice account owners.

If you think there is a mistake, please send an email to [hello@picovoice.ai](mailto:hello@picovoice.ai) with your name, surname, country, city and elaborate on your project and whether you work on the same project with others. We may then investigate it further."

I believe this is a mistake. My project is about developing a voice command platform for a robot arm and can be found on my github, here is a link:

https://github.com/UTADNCLab/ROS_Voicer

I first used it on a turtlebot 2i robot platform to familiarize myself with the robot. The end goal was always to extend the platform to a Kinova Jaco2 arm on a Clearpath Jackal robot, which I have been developing since this summer. I haven't used the picovoice platform since May 2023 when I was doing some preliminary tests on the Jaco arm as a standalone robot before using the entire setup. When I went to train a new model in October, I received the 0/0 models message, which prompted me to reach out initially. I do not have another picovoice account and have been using this one for model training all along. If the issue is the github account, I had to use my college's student account to access the repo since I am using it for an independent research project sponsored by my university's undergraduate research program, but it is all part of this one project. Please enable my account so I may continue my project.

Thanks

Carlos Mella-Rijo
