### ISSUE TITLE
Remote Server Architecture

### ISSUE THREAD

**Issue by muhyuddin** [Picovoice/porcupine#1151]
I am building client server for hotword detection, where i have written python client to capture audio from pyAudio and transmit packets over sockets to server. I am using 512 bytes chunk for processing. 
Client:
```
FORMAT = pyaudio.paInt16
CHANNELS = 1
SAMPLE_RATE = 16000
CHUNK = 512

# Initialize PyAudio
p = pyaudio.PyAudio()

# Open a streaming stream
stream = p.open(format=FORMAT,
                channels=CHANNELS,
                rate=SAMPLE_RATE,
                input=True,
                frames_per_buffer=porcupine.frame_length
                )

# Function to send audio data to the server
def send_audio_data():
    client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    client_socket.connect((SERVER_HOST, SERVER_PORT))
    buffer = b''
    while True:
        try:
            audio_data = stream.read(CHUNK, exception_on_overflow=False)

            if buffer:
                audio_data = buffer + audio_data

            if len(audio_data) >= CHUNK:
                client_socket.sendall(audio_data[:CHUNK])
                buffer += audio_data[CHUNK:]
            else: 
                buffer += audio_data
            

        except Exception as e:
            print(f"Error: {e}")
            break

    # Close the client socket and streaming stream
    client_socket.close()
    stream.stop_stream()
    stream.close()
    p.terminate()
```

Server:
```
def process_audio_data():
    while True:
        try:
            data = audio_queue.get(block=True)
            keyword_index = porcupine.process(data)
            
            if keyword_index >= 0:
                print("Hotword detected! Listening for sentence...")

        except Exception as e:
            print(f"Error processing audio data: {e}", e.with_traceback())
           
```
I am stuck at server side how to process this stream. if this is the right way its not detecting my wakeword. I have verified that send and received packets have same data. Guide me where i am going wrong. Thankyou

**Comment by ErisMik** [comment]
Hi @muhyuddin, repository issues are intended to be used to report issues with Picovoice engines, not the surrounding project code, therefore I cannot help you debug your application code.

Based on a cursory glance I don't see any glaring issues with regards to Porcupine. Please double check and make sure that data is an array of 16bit integer samples, at a sample rate of 16000 with a length of `porcupine.frame_length` samples. Also make sure that it contains valid audio.

If you provide a minimal example project that I can easily run, I can run it here and confirm if it's a system environment issue or an issue with your codebase.
