### ISSUE TITLE
Illegal instruction on Raspberry Pi Zero W (1W)

### ISSUE THREAD

**Issue by phanmemkhoinghiep** [Picovoice/porcupine#1156]
Porcupine 3.0.0 
With Raspberry Pi Zero 1W:  Got crash and  `Illegal instruction`  
With Raspberry Pi Zero 2W: Got crash and
`Porcupine initialization failed: Initialization failed:
[0] Picovoice Error (code '00000136')
[1] Picovoice Error (code '00000136')
[2] Picovoice Error (code '00000136')`

If downgrade Porcupine's version to 2.2.2, it's OK again on both 2 type of Pi Zero

**Comment by mrrostam** [comment]
Hello @phanmemkhoinghiep, thank you for bringing this issue to our attention. We have successfully replicated and identified the problem on the `Raspberry Pi Zero 1W` and are currently working on a solution. I will keep you updated once the patch is released.

Regarding the `Raspberry Pi Zero 2W`, it appears that you might be providing an incorrect model file (.pv) to the engine. Everything is functioning correctly on our end with the same [Python demo available in this repository](https://github.com/Picovoice/porcupine/tree/master/demo/python). Could you please double-check that both the model file (.pv) and the keyword file (.ppn) correspond to version `3.0.0`?

**Comment by Guilleloma** [comment]
How can we train the wakeup work for a previous version?, I have the same problem but I only have the .ppn for the version 3

**Comment by mrrostam** [comment]
@Guilleloma, this question is unrelated to the current issue. Please open a new issue for any future inquiries. Anyway, Picovoice Console only offers models for the most recent release of engines.

**Comment by phanmemkhoinghiep** [comment]
> Hello @phanmemkhoinghiep, thank you for bringing this issue to our attention. We have successfully replicated and identified the problem on the `Raspberry Pi Zero 1W` and are currently working on a solution. I will keep you updated once the patch is released.
> 
> Regarding `Raspberry Pi Zero 2W`, it appears that you might be providing an incorrect model file (.pv) to the engine. Everything is functioning correctly on our end with the same [Python demo available in this repository](https://github.com/Picovoice/porcupine/tree/master/demo/python). Could you please double-check that both the model file (.pv) and the keyword file (.ppn) correspond to version `3.0.0`?

Yes, it works on Pi Zero 02 now

**Comment by mrrostam** [comment]
@phanmemkhoinghiep, a patch has been released, addressing several issues, notably the problem encountered when running Porcupine on Raspberry Pi Zero W. Could you please test it out by trying `pvporcupine 3.0.1`, if you're using Python, and confirm if it resolves your issue?

**Comment by FernandAdam** [comment]
I had the same problem. On my Pi (1)W it's working now. Thank you!

**Comment by mrrostam** [comment]
Great! I consider the issue resolved then and close it.
