### ISSUE TITLE
Using JS/WASM inside AudioWorklet/Worker

### ISSUE THREAD

**Issue by ashubham** [Picovoice/Porcupine#116]
Is there a code sample, on how could I use the JS integration with a AudioWorklet. Current demo runs on the main thread and seems to cause our UI to be unresponsive on low CPU platforms.

Since the SoC we are using has multiple cores, it will be great if we could do the Audio Processing on a separate Worklet making the main thread free to do UI.

I see that the wasm binding has some code related to WEB_WORKERS, but running it on a separate Worker environment. Any pointers, would be appreciated.

**Comment by kenarsa** [comment]
@ashubham this would be a great addition and if you manage to make it work I appreciate a PR.

I think it should be straightforward to do this just following a tutorial such as this: https://developers.google.com/web/updates/2017/12/audio-worklet

I don't have the bandwidth right now but this seems like a fun coding exercise. Happy coding!

**Comment by kenarsa** [comment]
Any updates? I am going to close the issue for now. If you manage to make it work please submit a PR. The community will appreciate.
