### ISSUE TITLE
Will there be an Apple Silicon version released support M2 devices like iPads and MacOS?

### ISSUE THREAD

**Issue by ibytergj** [Picovoice/porcupine#1162]
Will there be an Apple Silicon version released support M2 devices like iPads and MacOS?

**Comment by kenarsa** [comment]
doesn't the current version work?

**Comment by ibytergj** [comment]
Hi I was referring to the documentation here [https://github.com/Picovoice/porcupine/tree/master/binding/unity](https://github.com/Picovoice/porcupine/tree/master/binding/unity) which only specifically mentioned only M1. I have not tried it on a M2 device
