### ISSUE TITLE
Unable to use API key with custom Porcupine wakeword 

### ISSUE THREAD

**Issue by ibytergj** [Picovoice/porcupine#1163]
I should be able to use my generated ppn file in Unity with porcupine manager but I get an error

### Actual behaviour
Porcupine init failed.
Make sure your access key 'redacted for security' is a valid access key.
This key works fine for the demo scene with built-in keywords but is not working when trying to use the custom wake word ppn file that I generated in the console

### Steps to reproduce the behavior

I sent this same message to hello@picovoice.ai with my actual API key.

**Comment by kenarsa** [comment]
how do you know it's the `key` not working? what is in your logs?

**Comment by ibytergj** [comment]
I know it is not working because I get that error msg I posted saying the "Make sure your access key is a valid access key. I do not get this error using the same key in the Unity demo scene.

**Comment by kenarsa** [comment]
do you have the [latest version](https://github.com/Picovoice/porcupine/blob/master/binding/unity/porcupine-3.0.0.unitypackage) of the SDK? What's the version you are on?

**Comment by ibytergj** [comment]
I am using 2.2.0 on windows for my initial test as I did not see a Apple Silicon version for 3.0.0 and I need to eventually run on both platforms so that is why I started with 2.2.0

**Comment by kenarsa** [comment]
OK. 3.0.0 would work on Apple silicon as well. You can't use 2.2.0 with custom keywords and can only use 3.0.0.

**Comment by ibytergj** [comment]
Hi I just updated to 3.0.0 and there is some extended logging now.

Error Starting Porcupine Init: Porcupine init failed:
  [0] Picovoice Error (code `0000006F`)
  [1] Failed to parse AccessKey `${ACCESS_KEY}`.
  [2] Picovoice Error (code `00000136`)
Make sure your access key 'redacted' is a valid access key.

**Comment by ibytergj** [comment]
Sorry my fault, cut and paste error. It is working fine with 3.0.0 (an probably 2.2.0 as well). Closing
