### ISSUE TITLE
Convert wasm ppn to hexadecimal

### ISSUE THREAD

**Issue by ashubham** [Picovoice/Porcupine#118]
Hey, we just got a new license and are trying to integrate the received keyword. We received .ppn file for WASM platform. How to convert it to an hexadecimal ?

**Comment by kenarsa** [comment]
You need to read the file as binary data and transform each byte to a hex value. I personally use xxd utility from commandline. But you can do this using any other utility of choice as well .

**Comment by ashubham** [comment]
I used xxd, then I had to write some code to convert it into a byte array. It would be good to illustrate this process in the docs.
