### ISSUE TITLE
Porcupine Issue: An account registered has been removed by the Picovoice Audit System

### ISSUE THREAD

**Issue by MarnusvanWyk** [Picovoice/porcupine#1181]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
My account has been removed.

### Actual behaviour
"An account registered with '' has been removed by the Picovoice Audit System. Accounts can be removed in cases of Picovoice Terms of Use violations, such as suspicious activities, creating multiple accounts, or providing false information. If you believe this is a mistake, please send an email to [hello@picovoice.ai](mailto:hello@picovoice.ai) with your name, surname, country, city, and project details, and we will investigate further.

I have sent an email to [hello@picovoice.ai](mailto:hello@picovoice.ai) as instructed and got a canned response wrt Sales inquiries, 
Technical support and Investment inquiries.

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

**Comment by mrrostam** [comment]
@MarnusvanWyk I'm unable to assist with account issues here as we focus on technical concerns. If you've emailed [hello@picovoice.ai](mailto:hello@picovoice.ai), our team should get back to you, though it might take some time.
