### ISSUE TITLE
support for raspberry pi 5

### ISSUE THREAD

**Issue by jevylux** [Picovoice/porcupine#1183]
Hi, I am trying to setup rhasspy 3 on a raspberry pi 5.
I am about to configure porcipine but I encounter a problem
when lauching the command : 
script/run bin/wake_detect.py --debug
I get the following error : 
`DEBUG:rhasspy3.program:.venv/bin/python3 ['bin/porcupine_stream.py', '--model', 'porcupine_raspberry-pi.ppn']
WARNING: Please be advised that this device (CPU part = 0xd0b) is not officially supported by Picovoice. Falling back to the armv6-based library. This is not tested nor optimal.
Traceback (most recent call last):
  File "/home/marc/rhasspy3/config/programs/wake/porcupine1/bin/porcupine_stream.py", line 6, in <module>
    from porcupine_shared import get_arg_parser, load_porcupine
  File "/home/marc/rhasspy3/config/programs/wake/porcupine1/bin/porcupine_shared.py", line 5, in <module>
    import pvporcupine
  File "/home/marc/rhasspy3/config/programs/wake/porcupine1/.venv/lib/python3.11/site-packages/pvporcupine/__init__.py", line 15, in <module>
    LIBRARY_PATH = pv_library_path('')
                   ^^^^^^^^^^^^^^^^^^^
  File "/home/marc/rhasspy3/config/programs/wake/porcupine1/.venv/lib/python3.11/site-packages/pvporcupine/util.py", line 94, in pv_library_path
    raise NotImplementedError('Unsupported platform.')
NotImplementedError: Unsupported platform.
DEBUG:rhasspy3.wake:detect: None`

when checking the code of util.py I undertsand that it tries to figure out what type of machine the script is running on.
 `cat /proc/cpuinfo`
returns 
`processor	: 0
BogoMIPS	: 108.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x4
CPU part	: 0xd0b
CPU revision	: 1`

the processor is a Broadcom BCM2712 quad-core Arm Cortex A76 processor @ 2.4GHz

Any chance to adapt the code to allow using the raspberry pi 5 ?

I modified the code to take into account the cortext-a76-aarch64 but then i got an error with missing library `OSError: Couldn't find Porcupine's dynamic library at '/home/marc/rhasspy3/config/programs/wake/porcupine1/.venv/lib/python3.11/site-packages/pvporcupine/lib/raspberry-pi/cortex-a76-aarch64/libpv_porcupine.so'.`
so i copied the directory cortex-a72-aarch64  to cortex-a76-aarch64 but now I am stuck, as I do not know if this works

**Comment by ksyeo1010** [comment]
Raspberry-pi 5 is not supported at the moment. If you would have it working, you should copy another raspberry-pi lib into the corresponding directory but can't help with issues encountered by doing this.

**Comment by micartey** [comment]
Me 3

**Comment by XenioxYT** [comment]
me 4!

**Comment by XenioxYT** [comment]
> Raspberry-pi 5 is not supported at the moment. If you would have it working, you should copy another raspberry-pi lib into the corresponding directory but can't help with issues encountered by doing this.

How would I go about doing this in order to get *something* working on my RPi 5?

**Comment by XenioxYT** [comment]
https://github.com/Picovoice/picovoice/issues/721#issuecomment-1871683196

**Comment by mrrostam** [comment]
Thanks for wanting Raspberry Pi 5 support. It's in our plans for the new year, but I can't say when it'll be ready. We'll let you know at Picovoice/picovoice#721 when it's done.
