### ISSUE TITLE
Picovoice Documentation Issue (/docs/api/porcupine-python/)

### ISSUE THREAD

**Issue by AdrienViala** [Picovoice/porcupine#1185]
### What is the URL of the doc?

https://picovoice.ai/docs/api/porcupine-python/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

https://github.com/Picovoice/Porcupine/issues/395 
If this above issue is true, it's kind of a big deal to mention it in the function documentation that this is NOT at all OPTIONAL outside of EN language. 

I made it work and indeed, the file path to parameters is requiered. 

Nitpicking, I think the vocabulary isn't super clear between model and parameters but that's might make sense for you all. ":param model_path: Absolute path to the file containing model parameters. If not set it will be set to the default location."

**Comment by ErisMik** [comment]
Hi @AdrienViala, thanks for the suggestion. We do try and mention this requirement in the `quick-start` (https://picovoice.ai/docs/quick-start/porcupine-python/#non-english-languages) for each SDK. However, I will make a note to the docs team to add additional clarification in coming updates.
