### ISSUE TITLE
Porcupine Issue: 

### ISSUE THREAD

**Issue by frippe75** [Picovoice/porcupine#1186]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour

Have the initialization work as documented.
I think React example differs from Github and Official docs.

https://github.com/Picovoice/porcupine#react
https://picovoice.ai/docs/api/porcupine-react/#start

 

### Actual behaviour

```
     const initEngine = async () => {
        await init(
          "*****ACCESSKEY*****",
          {
            "base64": HeyMyModel,
            "label": "Hey My Wake"
          },
          {base64: modelParams}
        );
        console.log(error);
        start();
      }

```

But yields

> Porcupine has not been initialized or has been released
>     at _callee2$ (index.js:5076:1)
>     at tryCatch (index.js:202:1)
>     at Generator.<anonymous> (index.js:290:1)
>     at Generator.next (index.js:231:1)
>     at asyncGeneratorStep$2 (index.js:47:1)
>     at _next (index.js:66:1)
> 

Is the access key really being passed correctly. Other code example suggest not.

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

**Comment by frippe75** [comment]
Creating my model:
```

npx pvbase64 \
	-i ./porcupine_params.pv \
	-o ../src/lib/porcupine_params.js

npx pvbase64 \
	-i ./Hey-My_en_wasm_v3_0_0.ppn \
	-o ../src/lib/hey_my.js \
	-n HeyMyModel
```

**Comment by ErisMik** [comment]
Hi @frippe75, you've mentioned a few things in this issue. What is the exact nature of the issue you are facing?

**Comment by frippe75** [comment]
Cannot get the exemple to work. But I got an email my account was marked as fishy so I have been blockad from further testing.

But mic permissions are never requested from the lib. The term model and parameters are somewhat confusing.

**Comment by ErisMik** [comment]
Does it work if you use the official provided demo: https://github.com/Picovoice/porcupine/tree/master/demo/react

**Comment by frippe75** [comment]
Cant test it since my account got canned somehow... AI anomaly detection....

**Comment by frippe75** [comment]
**Guess I'm moving on to other solutions...**
An account registered with 'frippe75' has been removed by the Picovoice Audit System. Accounts can be removed in cases of Picovoice Terms of Use violations, such as suspicious activities, creating multiple accounts, or providing false information. If you believe this is a mistake, please send an email to hello@picovoice.ai with your name, surname, country, city, and project details, and we will investigate further.
