### ISSUE TITLE
Quick Start for ARM Cortex-A / RockChip 3588

### ISSUE THREAD

**Issue by hellofanengineer** [Picovoice/porcupine#1187]
### What is the URL of the doc?
https://picovoice.ai/docs/faq/picovoice/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
The FAQ shows the library being supported on ARM Cortex-A. I'm trying to test on a RockChip 3588 which uses ARM Cortex A76 and A55 processors. When I run the python library I get an unsupported platform error. I see that ARM Cortex-A is not listed in the Platforms section of the quick start for python but neither is it listed in **_any_** quick start section.

So is ARM Cortex-A truly supported and if so, where can I find the documentation for it?

**Comment by ErisMik** [comment]
Hi @hellofanengineer, to clarify the docs & FAQ: `Picovoice` support based on a matrix between per-platform / SDK support and architecture. As you've noticed not all SDKs support all architectures and vice versa. `Cortex-A` in this instance wasn't meant to intend all `Cortex-A` platforms, but that certain platforms that use `Cortex-A` are supported, such as `Raspberry Pi` and `Jetson Nano`, and in those cases their specific CPUs.

So while you could potentially use libraries designed for `Raspberry Pi` or Jetson Nano, there's no guarantee they will function either optimally or at all on your platform.

Alternatively, if this is for a commercial product and you're prepared for a more formal engagement, you can [contact our sales team](https://picovoice.ai/pricing/) to inquire about this support through an enterprise package.
