### ISSUE TITLE
Any plans for other languages?

### ISSUE THREAD

**Issue by BeWe11** [Picovoice/Porcupine#119]
Hey,

Do you plan to release models for other languages like German, French and Spanish?

The English model works incredibly well, great piece of software!

**Comment by kenarsa** [comment]
Thanks! Yeah, definitely on the roadmap. can't comment on timing at this point, unfortunately.

**Comment by rept** [comment]
Dutch would be great too :-)

**Comment by TheBdouilleur** [comment]
French would be terrific :-)

**Comment by TheBdouilleur** [comment]
Maybe you could hold a vote to choose the first new language available.

**Comment by yaleimeng** [comment]
Chinese is wanted strongly！ But I'm not sure how difficult the work will be.

**Comment by kenarsa** [comment]
@yaleimeng thanks. we are considering that. What's the ecosystem like for Chinese wake word / embedded speech? I thought Baidu and other local companies have already enough offerings?

**Comment by yaleimeng** [comment]
As far as I know, companies such as Baidu and Sogou has provided online APIs and smart speakers waked by voice, but  that can't support offline/ on-device applications especially for individual developers. 
Snowboy and PocketSphinx were very poppular in the last few years , but there are some drawbacks and they've been colsed/outdated for a long time.

**Comment by mrhanCH** [comment]
> As far as I know, companies such as Baidu and Sogou has provided online APIs and smart speakers waked by voice, but that can't support offline/ on-device applications especially for individual developers. Snowboy and PocketSphinx were very poppular in the last few years , but there are some drawbacks and they've been colsed/outdated for a long time.

support
