### ISSUE TITLE
Raspberry pi 5 support

### ISSUE THREAD

**Issue by mikael1995** [Picovoice/porcupine#1191]
I am currently experiencing difficulties in implementing voice recognition projects using Porcupine on Raspberry Pi 5. The lack of official support or clear documentation for this specific combination limits my ability to effectively utilize Porcupine's capabilities on the latest Raspberry Pi hardware. This is frustrating because it hinders the development of efficient and responsive voice-controlled applications.

I would like to see official support or a dedicated update from Porcupine that specifically addresses compatibility and optimization with Raspberry Pi 5. This update should include detailed documentation and guidelines on how to seamlessly integrate Porcupine with Raspberry Pi 5, ensuring that users can leverage the full potential of both the voice recognition software and the hardware.

As an alternative, I have considered using other voice recognition software that offers support for Raspberry Pi 5, but these solutions do not match the performance and ease of use provided by Porcupine. Another option could be community-driven patches or workarounds, but these are often not as reliable or efficient as an official update.

The Raspberry Pi 5 offers significant improvements in processing power and capabilities, which can greatly enhance voice recognition projects. Official support from Porcupine would not only benefit individual hobbyists and developers but could also open up new possibilities in educational and professional settings where Raspberry Pi is widely used.

**Comment by kenarsa** [comment]
We are tracking RPI5 support in [this issue](https://github.com/Picovoice/picovoice/issues/721). I am closing this one. Feel free to subscribe to that.
