### ISSUE TITLE
Porcupine Issue: 

### ISSUE THREAD

**Issue by gavinlxh** [Picovoice/porcupine#1193]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

React

### Porcupine package version

3.0.3

### Framework version

React v18.2.0, Electron v23.0.0, node v20.0.0

### Platform

Web (WASM)

### OS/Browser version

Windows 11 Professional X64

### Describe the bug

We trained wakeup word and applied to windows 11 pro demo environment, and encounter two weird issues:
1. Since our company has two branches, we tried the same app (the same access key) in different environment, one good, the other is not functional, we tried new access key but still not working.
2. We use electron frontend package framework, when we deliver the release package, most of time it will show error message when exec init() function, the message like this: 

_PorcupineInvalidArgumentError: Initialization failed: 
[0] Loading parameters failed with `INVALID_ARGUMENT`.
[1] Picovoice Error (code `0000012C`)__

We also tried the react demo app using several registered access key, all are good.

### Steps To Reproduce

As I described above, we encounter issues when using same/different keys in different environments (windows 11 pro, react sdk).

the core code snippet as below:

  const initEngine = useCallback(async () => {
    if (accessKeyRef.current.length === 0) {
      return;
    }

    await init(
      accessKeyRef.current,
      [keyword],
      porcupineModel
    );
  }, [init, keyword])

### Expected Behavior

We expect the same access key can be used on several machine as long as the quota of account is under the limitation.
Currently we are evaluating the possible solution. 
Here I really want to know the root cause of access key validation failed?
Thanks & cheers~

**Comment by laves** [comment]
@gavinlxh - it looks like this is related to loading the Porcupine model file (`.pv` file), not the access key. It's possible you have a previous version of the model file cached. You can force overwrite it in the model type like so:
```typescript
const porcupineModel = {
  publicPath: "models/my_model.pv",  
  customWritePath: "my_model.pv",
  forceWrite: true;
};
```

**Comment by gavinlxh** [comment]
Thank you @laves for your reply. We've tried this forceWrite flag, It showed the same error. We found that when we reinstall a windows OS from win 10 home edition to win 11 pro, the issue resolved, but it persisted on another win 10 home edition OS. Maybe there are some dependencies on OS? We're not sure because we tried another win 10 home, it worked. The win 11 pro is more likely workable than win 10 home.

Besides, We tried the demo (under demo/react folder), all are good. And it seems the demo app doesn't use the forceWrite flag.

Thanks again~

**Comment by laves** [comment]
Hmm, that's curious. If you can isolate it further to an issue with our binding, we can look into a fix. If it's an issue with your project, we can only help so much. At this point, I can only say for sure that it is an issue with reading the `.pv` file into the engine. It is possible that the file is being corrupted somewhere in the chain of delivery and it is just more likely on some machines. It is unlikely that our code is affected by Windows 10 vs. 11.

**Comment by gavinlxh** [comment]
> Hmm, that's curious. If you can isolate it further to an issue with our binding, we can look into a fix. If it's an issue with your project, we can only help so much. At this point, I can only say for sure that it is an issue with reading the `.pv` file into the engine. It is possible that the file is being corrupted somewhere in the chain of delivery and it is just more likely on some machines. It is unlikely that our code is affected by Windows 10 vs. 11.

Thanks @laves for giving me the OS independently info, I will closed this issue and keep an eye on it. We'll dig it out further if we encounter this issue again.
