### ISSUE TITLE
Porcupine Issue: java v3.0.0  FileSystemNotFoundException

### ISSUE THREAD

**Issue by a916003940** [Picovoice/porcupine#1202]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

Android

### Porcupine package version

3.0.0

### Framework version

jdk11 springboot2.2.31

### Platform

Android

### OS/Browser version

macos 12 

### Describe the bug

run with jar （java -jar xxx.jar ） :
Exception in thread "Thread-6" java.lang.ExceptionInInitializerError
	at ai.picovoice.porcupine.Porcupine$Builder.build(Porcupine.java:242)
	at com.damao.sensenova.listener.SmartAssistantRunner.runWakeUpFunc(SmartAssistantRunner.java:225)
	at com.damao.sensenova.listener.SmartAssistantRunner.lambda$run$0(SmartAssistantRunner.java:171)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.FileSystemNotFoundException
	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
	at java.nio.file.Paths.get(Paths.java:143)
	at ai.picovoice.porcupine.Utils.getResourceDirectory(Utils.java:58)
	at ai.picovoice.porcupine.Utils.<clinit>(Utils.java:39)
	... 4 more

### Steps To Reproduce

<img width="857" alt="image" src="https://github.com/Picovoice/porcupine/assets/13843411/7dead593-066b-4301-be45-430050bf32dc">

### Expected Behavior

1

**Comment by a916003940** [comment]
<img width="1069" alt="image" src="https://github.com/Picovoice/porcupine/assets/13843411/e8325c92-cffa-46ab-b91d-31ed64f8ba85">

**Comment by ErisMik** [comment]
It seems Porcupine is unable to find the directory/file containing the resources it needs to extract to run (libs, keyword files, etc.). Could be related to using Springboot Java which we have never tested against.

Can you build and run the repo demos without any issue? https://github.com/Picovoice/porcupine/tree/master/demo/java

**Comment by a916003940** [comment]
> It seems Porcupine is unable to find the directory/file containing the resources it needs to extract to run (libs, keyword files, etc.). Could be related to using Springboot Java which we have never tested against.
> 
> Can you build and run the repo demos without any issue? https://github.com/Picovoice/porcupine/tree/master/demo/java

thanks,i will try it today. and I will use springboot3.2.1 to test my code.

**Comment by a916003940** [comment]
It is probably the springboot(v3.2.1) leadding to the problem.The demo code is running well.
I debugged and traced the code variables when running with 'java -jar', and I found that the directory loaded by the code during this type of startup is incorrect.
So, I gave up on using the Spring framework.

**Comment by ErisMik** [comment]
Thank you for checking. Glad you could get the demo running but it is unfortunate to hear that springboot did not work. If you find or write a fix in the binding feel free to submit a PR.

I am closing this issue. If something else comes up feel free to open another issue.
