### ISSUE TITLE
questions regarding Porcupine 

### ISSUE THREAD

**Issue by Sayanbm** [Picovoice/porcupine#1209]
### What is the URL of the doc?

https://github.com/Picovoice/porcupine/tree/master/binding/python

### What is the nature of the issue?

I am trying to crate python script with porcupine with mic in raspberry pi, so i am looking for simple bare minimum python code example or some kind of tutorial to use porcupine in my python code

**Comment by laves** [comment]
We have [python demos](https://github.com/Picovoice/porcupine/tree/master/demo/python) that show how to use porcupine with audio files or a microphone.
