### ISSUE TITLE
How to Disable Log Outputs?

### ISSUE THREAD

**Issue by SpCoGov** [Picovoice/porcupine#1212]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

Java

### Porcupine package version

3.0.1

### Framework version

Java17

### Platform

Windows (x86_64)

### OS/Browser version

Windows 10.0.26040.1000

### Describe the bug

I am using javasdk 3.0.1 and I've noticed that it generates some logs, as shown below:
 [INFO] Porcupine model path : `xxxxxxx`
 [INFO] Porcupine keyword path [0] : `xxxxxxx`
 [INFO] Porcupine sensitivity [0] : 0.50

### Steps To Reproduce

-

### Expected Behavior

-

**Comment by mrrostam** [comment]
Unfortunately, there is currently no way to disable those info logs with our public libraries.

**Comment by SpCoGov** [comment]
> Unfortunately, there is currently no way to disable those info logs with our public libraries.

Will it be supported in the future?
