### ISSUE TITLE
keyword file belongs to a different version of the library

### ISSUE THREAD

**Issue by pablocaviglia** [Picovoice/Porcupine#122]
I've updated the porcupine's android library to v1.5 and now my ppn file seems to be invalid. How can I make it work again with this version?

**Comment by kenarsa** [comment]
if you have generated using the open source optimizer generate again using the latest version. Otherwise, send an email to Picovoice to get the latest version.

**Comment by pablocaviglia** [comment]
Actually we asked you to generate it. It was a service provided to Hipcam Ltd. to generate the ppn for 'Hello Hipcam'
