### ISSUE TITLE
Is it faster for detection to ignore data artefacts above the length of a single porcupine data frame ?

### ISSUE THREAD

**Issue by weis** [Picovoice/porcupine#1225]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

C

### Porcupine package version

3.0.0

### Framework version

Qt5, Qt6 (c++, Qml)

### Platform

Windows (x86_64)

### OS/Browser version

Windows, Linx, Mac, IOS, Android

### Describe the bug

Hi,
We are currently testing the suitability of Porcupine in the Qt/Qml (Windows/Mac/IOS/Android) environment.
We noticed the following phenomenon:
**The detection of a keyword  is (minimal 2 times) faster when we ignore data artefacts above the length of a single porcupine data frame.**

In the following (c++) example, this is the case if PV_PROCESS_ALL is not defined.
(We can also make the entire project available to you in github).

Is the observation correct?

```
//
// Internal processes a frame of the incoming audio stream and emits the detection result.
//
bool Porcupine::processFrame(const int16_t* pcm, qint32* keywordIndex, QString* errMsg)
{
    pv_status_t porcupine_status = pv_porcupine_process_func(
        static_cast<pv_porcupine_t*>(m_pvInstance),
        pcm,
        keywordIndex);
    bool success = porcupine_status == PV_STATUS_SUCCESS;

    if (success)
    {
        if (*keywordIndex >= 0)
            qInfo("Porcupine detected keyword, index = %d.", *keywordIndex);
    }
    else
    {
        QString message = getMessageDetail("Processing porcubine audiodata", porcupine_status);
        qCritical("%s", qPrintable(message));

        if (errMsg != nullptr)
            *errMsg = message;
    }

    return success;
}

///
/// \brief Processes an incoming audio stream and returns the detection result.
/// \param keywordIndex Outputs a 0-based index of the first observed keyword.
/// If no keyword is detected then value of keywordIndex is -1.
/// \param audioData Raw audio data stream.
/// \param len Length in bytes of the data stream.
/// \param errMsg If not null, an optional output of error messages.
/// \return true on success otherwise false.
///
bool Porcupine::process(int& keywordIndex, const char* audioData, const int len, QString* errMsg)
{
    bool success = true;
    keywordIndex = -1;

    if (m_pvEnabled)
    {
        m_audioBuffer.append(audioData, len);

        // here is m_pvBytesFrameSize = 2*512 = 1024 bytes)
        if (m_audioBuffer.size() >= m_pvBytesFrameSize)
        {
#ifdef PV_PROCESS_ALL
            int bytesProcessed = 0;
#endif
            const char* ptr = m_audioBuffer.constData();
            const char* const end = ptr + m_pvBytesFrameSize;
            while (ptr < end)
            {
                const int16_t* pcm = reinterpret_cast<const int16_t*>(ptr);
                int32_t keyword_index = -1;

                if ((success = processFrame(pcm, &keyword_index, errMsg)) && keyword_index >= 0)
                    keywordIndex = keyword_index;

#ifdef PV_PROCESS_ALL
                bytesProcessed += m_pvBytesFrameSize;
#endif
                // Break loop if a keyword is found or on error
                if (keyword_index >= 0 || !success)
                    break;

                ptr += m_pvBytesFrameSize;
            }
#ifdef PV_PROCESS_ALL
            // Remove only processed audio data
	    // results in longer time to keyword-detection
            m_audioBuffer.remove(0, bytesProcessed);
#else
            // Remove all - including unprocessed - audio data
	    // minimal 2 times faster
            m_audioBuffer.clear();
#endif

        }
    }

    return success;
}

```

### Steps To Reproduce

See code.

### Expected Behavior

The processing of all audio data should be more performant.

**Comment by ErisMik** [comment]
Define faster: is this done on live audio data and it has less CPU usage? Or are you running it against an audio file and it's processing it in less time?

In any case Porcupine takes the same amount of time to process each audio frame, so of course dropping frames or audio data will make it run faster. **There is less data to process**!

**Comment by weis** [comment]
Hi,

this is done on live audio data.
Can you download and run the simple windows test runable   [QtPorcupine](https://drive.proton.me/urls/D5AVJZ198C#eRsKPH06cVg3) ?
(Please don't forget to put libpv_porcupine.dll in the same directory and enable/disable Skip Modulo Artifacts.)

Don't you see that too?

Regards
Alfred Weis

**Comment by ErisMik** [comment]
Sorry, I am not going to run a pre-compiled executable like that. If you can provide me the source for a minimum app that reproduces the issue, then I can help debug. If for some reason you don't feel comfortable sharing it publicly you can send it to `hello@picovoice.ai`.

However, you still haven't explained what you mean by "twice as fast". As I've said the issue seems to be with the outer logic of your code: of course dropping audio will make it run faster as there is less data to process. Any perceived "fastness" is just a symptom of that.

**Comment by laves** [comment]
Sending less data to our engines will speed up your application at the cost of accuracy (because Porcupine is hearing a non-continuous audio stream). This does not seem like an issue, but more of an observation.

**Comment by weis** [comment]
Hi,

here was the error:

`const char* const end = ptr + m_pvBytesFrameSize;`

must be replaced with

`const char* const end = ptr + m_audioBuffer.size() - m_pvBytesFrameSize + 1;`

I put the small test project online:
[QtQmlPorcupine](https://github.com/weis/QtQmlPorcupine)

The detection rate is fast and accurate.

Still remarkable - and that was actually interesting for us:
If I delete the audio buffer completely - including all unprocessed audio data - it apparently has a positive effect on the performance.

Regards
Alfred Weis
