### ISSUE TITLE
How to move licence to another device

### ISSUE THREAD

**Issue by nixilb** [Picovoice/porcupine#1226]
Hello!
In a dev test, I'm unfornately trashing devices so I run out of the 3 free devices.
How to move the licence to new devices? I don't need more licences, just to use 3 at the same time.
Nicolas.

**Comment by ErisMik** [comment]
Unfortunately there is no mechanism to move activations from one device to another. You will have to wait for those activations to expire (30 days) and then you can activate again on the new devices.
