### ISSUE TITLE
Porcupine with react native voice

### ISSUE THREAD

**Issue by wired88** [Picovoice/porcupine#1228]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

Android

### Porcupine package version

3.0.2

### Framework version

React Native 0.71

### Platform

Android

### OS/Browser version

Android 13+

### Describe the bug

Hey, i found a issue with use of porcupine and react native voie.

My Plan: porcupine start listening -> detect keyword -> porcupine stop listening -> update a state variable ("initVoice"->true) -> screen useEffect -> if initVoice && Voice: load all listeners -> in the initVoiceHook in UseEffect -> if true: start react native voice recording.

I have the following listeners: onEnd, onResult and onError.

So. Everything works well till "start react native voice recording."- Process

### Steps To Reproduce

Problem: The listeners wont get triggered when the user Stops talking. Like i sayd the recording starts but never stops. Its absolutely hell.
The strange part is: when i try it without porcupine, everything is working well. Listeners are correct called-> so i thought it must be because the a Listener conflict between porcupine and rn voice. Thats because i first stopped porcupine listening, then update the state and then in the custom Hook start the recording (So there can not be a render conflict)
__wired__ — heute um 14:50 Uhr
// here is my code: 
// first start the porcupine listener
export const startListening = async (
  updateInitVoice: (value:boolean) => void
) => {
  console.log("Start Listening Function called...");
  try {
    if (!porcupineManager) {
      console.log("Create new PorcupineManager instance")
      porcupineManager = await PorcupineManager.fromBuiltInKeywords(
        PORCUPINE_API_KEY,
        [BuiltInKeywords.JARVIS],
        (keyword:number) => {
          console.log("Detected Keyword!");
          startRecordingProcess(updateInitVoice)
        },
        errorListening
      );
    }
    await porcupineManager?.start();
  }catch (e:unknown) {
    if (e instanceof Error) {
      console.error("Error while listening occurred", e);
    }
  }
};
// ...so i stop the porcupine listener and update the state...
const startRecordingProcess = (
  updateInitVoice: (value:boolean) => void
) => {
  stopListening()
    .then(() => {
      updateInitVoice(true);
  })
};
// ... then activate the listeners... 
useEffect(() => {
    if (Voice && initVoice) {
      console.log("Voice Listener active...");
      Voice.onSpeechError = onSpeechError;
      Voice.onSpeechResults = onSpeechResults;
      Voice.onSpeechEnd = onSpeechEnd;

      return () => {
        Voice.destroy()
          .then(() => {
            Voice.removeAllListeners();
            console.log("Remove Listeners in useEffect...");
          })
      }
    }
  }, [initVoice]);

// ... then start the speech process in the hook... (start Speech just call Voice.start with a few logs -> every time successfuly...
export const useInitVoice = () => {
  const [initVoice, setInitVoice] = useState<boolean>(false)
  const updateInitVoice = (value:boolean) => setInitVoice(value);

  useEffect(() => {
    if (initVoice) {
      startSpeech()
        .then(() => {
          console.log("Speech initialized...")
        });
    }
  }, [initVoice]);

  return { initVoice, setInitVoice, updateInitVoice }
}

### Expected Behavior

But as i mentioned,the listeners wont get active. what did i overseen?

**Comment by laves** [comment]
Do you encounter the same issue in our [official react native demo](https://github.com/Picovoice/porcupine/tree/master/demo/react-native)? If not, I would suggest you continue debugging your application as it is difficult at this point to determine if this is an issue with our package or your application.

**Comment by laves** [comment]
I do see that you're calling `startRecordingProcess` every time you detect a keyword. This may cause some of the issues you are experiencing. 
```javascript
(keyword:number) => {
console.log("Detected Keyword!");
startRecordingProcess(updateInitVoice)
},
```

**Comment by ErisMik** [comment]
Closed due to inactivity
