### ISSUE TITLE
Porcupine Issue: visionOS support

### ISSUE THREAD

**Issue by Spencer-L** [Picovoice/porcupine#1229]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

Unity

### Porcupine package version

3.0.1

### Framework version

Unity 2022.3.18

### Platform

iOS

### OS/Browser version

visionOS 1.0.3

### Describe the bug

Hey so great work with Porcupine, it's a fantastic cross-platform package that I love incorporating in pretty much all the projects I do.  I know Porcupine wasn't explicitly marketed to be compatible with Apple's visionOS, but I figured I'd push this as a bug just in case anyone at Picovoice is curious about the compatability of Unity Porcupine with Apple Vision Pro.  Reason being I know a lot of things are interoperatable between visionOS and iOS while a lot aren't...  Short answer for Porcupine is I don't think it's compatible.  I got a barebones project up and running and the only thing I have is pretty much Polyspatial and Porcupine in the project.  Porcupine works well with just the built in wake words both in-editor and on a M3 Max macbook.  But when deploying to visionOS, I get a GPU permissions error it seems.  Thanks!
<img width="507" alt="Screenshot 2024-02-19 at 1 24 52 AM" src="https://github.com/Picovoice/porcupine/assets/31945337/67e30b9e-8897-43c2-a8f5-35152cba3e12">

### Steps To Reproduce

1. Create Unity project with Polyspatial 1.0.3 template.
2. Import Porcupine package
3. Set up a simple test scene ie. Porcupine + play test sound when wake word detected
4. Deploy to visionOS

### Expected Behavior

A confirmation sound should play when a wakeword is detected (this works perfectly well in-editor and on macOS build) but a GPU error is thrown instead when deployed to the Apple Vision Pro.  Please let me know if there's a possible fix or if I'm doing something wrong!

**Comment by laves** [comment]
@Spencer-L thanks for your interest and thank you for giving it a try on visionOS - we have not had a chance to do this. As you mentioned, we don't officially support visionOS so, even if it did work, we can't guarantee that it will function as expected. That said, Porcupine does not use any GPU acceleration and thus shouldn't be the cause of the GPU permission errors you are experiencing. The only permission that Porcupine requires is for the microphone, which is something you may need to acquire in your application before Porcupine will work on device.

**Comment by Spencer-L** [comment]
Yup, mic access is given to the app and I made sure to check that.  Definitely not looking for a bug fix, but more so out of curiosity, any future plans for visionOS support?

**Comment by laves** [comment]
We'd love to, but there are no plans as of yet. I'll leave this issue open though and if it gets enough traction we may add support in the future.

**Comment by ErisMik** [comment]
Closed due to inactivity
