### ISSUE TITLE
Cannot execute optimizer binary on Raspberry Pi 3 Model B

### ISSUE THREAD

**Issue by furqanahmedmtbc** [Picovoice/Porcupine#123]
### Expected behavior
Running the command `tools/optimizer/linux/x86_64/pv_porcupine_optimizer -r resources/ -p linux -o / -w "vancouver"` should execute the optimizer.

### Actual behavior
Executing the command returns the error: **bash: tools/optimizer/linux/x86_64/pv_porcupine_optimizer: Cannot execute binary file: Exec format error**

### Steps to reproduce the behavior
Running the command `tools/optimizer/linux/x86_64/pv_porcupine_optimizer -r resources/ -p linux -o / -w "vancouver"` in the porcupine directory.

I've run the command for both system types i.e x86_64 and i386.
My device is a Raspberry Pi 3 Model B running the Raspbian OS.

**Comment by kenarsa** [comment]
RPi is running on arm. The optimizer in this repo can only run on x86_64 and i386. You need to run it on a Linux desktop with an Intel cpu/amd cpu
