### ISSUE TITLE
ERROR "PV file has incorrect format or belongs to a different platform"

### ISSUE THREAD

**Issue by AppleSeedExp** [Picovoice/porcupine#1238]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

React

### Porcupine package version

2.0.0

### Framework version

Node v20.11.0

### Platform

Web (WASM)

### OS/Browser version

Window 10

### Describe the bug

The issue is the following:
LeopardInvalidArgumentError: Initialization failed: [0] Model (.pv) file has incorrect format or belongs to a different platform. [1] Picovoice Error (code `00000136`

### Steps To Reproduce

1. Copy the "VideoWidget.tsx" file from "Demo".
2. Download the leopard_params.pv file to the Lib directory.
3. Create the model like the following:
const leopardModel = {
        publicPath: "../Lib/leopard_params.pv",
    }

### Expected Behavior

I can't expect about the future. I've clicked the init button with AccessKey but I have an error...

**Comment by mrrostam** [comment]
I'm a bit confused. Is this issue related to Leopard or Porcupine? If it's about Leopard, could you please close this ticket and open a new one in the Leopard repository? Additionally, it seems there's no "VideoWidget.tsx" file in our demo folder. Could you try running our React demo without making any modifications to see if it works for you? Also, remember to set `forceWrite=true` in the [Leopard model settings](https://picovoice.ai/docs/api/leopard-web/#leopardmodel) to overwrite any old model files.

**Comment by mrrostam** [comment]
Closed due to inactivity
