### ISSUE TITLE
Porcupine 1.5 calls "Something went wrong", Android application

### ISSUE THREAD

**Issue by utuM** [Picovoice/Porcupine#124]
### Expected behavior
Porcupine library must to be initialized properly and toast custom "Say to Alexa" after it has been started.

### Actual behavior
Library show toast-message "Something went wrong" during initialization. During debug sessing i've noticed that some exception was occured inside "initPorcupine" method.

### Steps to reproduce the behavior
First of all, in our project, we've used Porcupine 1.3. We've faced that some problems with 'alexa' keyword recognition and want to update the library to the actual version number 1.5. 
So, i've downloaded the *.so-libraries and update local ones with them. Also, i've downloaded the latest 'alexa.ppn' key-file and also updated existed one. After re-building and compiling, library shows 'Something went wrong' message during initialization.
Also, updated the 'param.pv' file from the 'common' folder, but library still cannot init.
Also, i've tested application on 2 devices: one with ARMv7 processor, other one with ARMv8 CPU. In both cases, update library didn't wake up properly: the same message.

**Comment by kenarsa** [comment]
Could you please take a look at error message in the log and attach them to the issue? 
Also, can you run the Android demo application (without any modifications) successfully?

**Comment by Swathi2610** [comment]
Hi, 
I want to create a hotword for my android applications. How can I do this. I referred the readme.md  file and it is a bit confusing. Kindly help I need this feature urgently

**Comment by utuM** [comment]
Here are the porcupine messages:
```
11-29 12:54:58.011 9203-9203/com.willblaschko.android.alexavoicelibrary W/linker: libpv_porcupine.so: unused DT entry: type 0x6ffffffe arg 0xbd0
11-29 12:54:58.011 9203-9203/com.willblaschko.android.alexavoicelibrary W/linker: libpv_porcupine.so: unused DT entry: type 0x6fffffff arg 0x3
11-29 12:54:58.012 9203-9203/com.willblaschko.android.alexavoicelibrary I/PORCUPINE:  [INFO] model file path: /data/data/com.willblaschko.android.alexavoicelibrary/files/params.pv
11-29 12:54:58.012 9203-9203/com.willblaschko.android.alexavoicelibrary I/PORCUPINE:  [INFO] number of keywords: 1
11-29 12:54:58.012 9203-9203/com.willblaschko.android.alexavoicelibrary I/PORCUPINE:  [INFO] keyword file path [0]: /data/data/com.willblaschko.android.alexavoicelibrary/files/alexa.ppn
11-29 12:54:58.012 9203-9203/com.willblaschko.android.alexavoicelibrary I/PORCUPINE:  [INFO] sensitivity [0]: 0.900000
11-29 12:54:58.012 9203-9203/com.willblaschko.android.alexavoicelibrary I/PORCUPINE: [ERROR] keyword file belongs to a different version of the library
11-29 12:54:58.012 9203-9203/com.willblaschko.android.alexavoicelibrary I/PORCUPINE: [ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'
```

**Comment by kenarsa** [comment]
@utuM you need to use the keyword file compatible with the version of the library you are using. The error message "keyword file belongs to a different version of the library" indicates that. If you are using v1.5 library then your keyword file should be v1.5 as well.

**Comment by kenarsa** [comment]
@Swathi2610 please open a separate issue as this is not relevant to this thread.

**Comment by utuM** [comment]
> @utuM you need to use the keyword file compatible with the version of the library you are using. The error message "keyword file belongs to a different version of the library" indicates that. If you are using v1.5 library then your keyword file should be v1.5 as well.

Yeah, i found a mistake that i've made. Thank You.
