### ISSUE TITLE
Porcupine Licensing and Access Key

### ISSUE THREAD

**Issue by rbgreenway** [Picovoice/porcupine#1241]
I'm just curious about the licensing of your porcupine wake word detection engine.  From the Apache license included in this github repo, I'm assuming it's free to use for whatever project you like; however, the requirement for an Access Key concerns me a bit.  Why is an Access Key required?  If I decide to embed your porcupine wake word detection into a commercial product, will there be an issue?  Will the key ever expire?

Thanks for sharing this excellent technology.

**Comment by ErisMik** [comment]
Thank you for you kind words.

Picovoice engines require an `AccessKey`, and therefore intermittent internet connectivity, to be able to offer its services according to your plan limits detailed on our [pricing](https://picovoice.ai/pricing/) and [FAQ](https://picovoice.ai/docs/faq/general/) pages. The Free Plan allows prospects to try the engines and see how they work, including this tracking behaviour. The real-time usage info is available on the [Picovoice Console](https://console.picovoice.ai/signup). The key itself do not expire, only the usage limits they are tied to. The Free Plan has usage limits, but these reset monthly.

We understand some enterprises may not have time or resources to leverage Picovoice’s Free resources. Hence, we offer an optional Support Add-on for those interested in taking the expert-guided path. If you wish, you can send a [support request](https://streaklinks.com/B2xC4LnkpEobskkzXgVUc-4e/https%3A%2F%2Fpicovoice.ai%2Fprofessional-services%2F?email=james%40picovoice.ai) to work with a subject expert who can help you with implementation and optimization. If Free Plan limits do not meet your requirements, you can check our [paid plans](https://picovoice.ai/pricing/)

**Comment by lostmsu** [comment]
The license in this repository is plain wrong. According to the license I can download the binary and do whatever Apache License 2.0 allows to do with it, which includes removing any references to access keys and your service.
