### ISSUE TITLE
No Alexa model for Raspberry Pi

### ISSUE THREAD

**Issue by oort7** [Picovoice/Porcupine#125]
### Expected behavior
There should be resources/keyword_files/alexa_raspberrypi.ppn file in the repository

### Actual behavior
There is no resources/keyword_files/alexa_raspberrypi.ppn file

**Comment by kenarsa** [comment]
Thanks for the message. Alexa RPi model is not one of the free models, unfortunately. You can use any other freely available model for RPi or use Alexa for some other platform.

**Comment by oort7** [comment]
I see, thanks.
