### ISSUE TITLE
Not able to download my ppn model from the website

### ISSUE THREAD

**Issue by WalrusHat** [Picovoice/porcupine#1251]
So the title says it all but not only am I not able to download my custom VPN model, but also each time I tried to download it it counted as a use of the service and caused me to reach my usage limit of porcupine. 

In addition to that on my profile, the section that contains the models that I previously created, contains nothing.

I'm pretty sure there's a bug, but this is pretty upsetting for me since I can't test the custom wake words. 

Is there anyone from support that can help?

**Comment by albho** [comment]
Which platform(s) are you trying to download for? Can you check that your browser isn't blocking downloads?

You should also be able to test wake words in the console regardless of your usage limit. Check out our [tutorial video](https://www.youtube.com/watch?v=T6jxYRSyF2w) on Porcupine - it might be helpful.
