### ISSUE TITLE
Porcupine Issue: Its Taking the audio from Device Speaker 

### ISSUE THREAD

**Issue by Majaveed2002** [Picovoice/porcupine#1265]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

React

### Porcupine package version

3.0.3

### Framework version

React 18.0.0

### Platform

Web (WASM)

### OS/Browser version

chrome latest version

### Describe the bug

I am using it i my react application to implement a wake word but it's taking audio from the devices speaker too 

### Steps To Reproduce

Create a react application and try to add a wake word and play something on your device and try to say the wake word 
this will create the Issue I am Facing

### Expected Behavior

Only It Should take Voice Of a human

**Comment by ErisMik** [comment]
This sounds more like an issue with your application setup than with Porcupine itself. As you control how the audio is passed into Porcupine it's up to the application to ensure that only the desired audio is being processed. In this case sounds like you need a VAD of some sort, for example [Picovoice Cobra](https://github.com/Picovoice/cobra).
