### ISSUE TITLE
RK3588 (0xd05) is 100% working

### ISSUE THREAD

**Issue by Al3XKOoL** [Picovoice/porcupine#1269]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

Python

### Porcupine package version

3.0.2

### Framework version

Python 3.11

### Platform

ARM Cortex-M

### OS/Browser version

Ubuntu 24.04

### Describe the bug

> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/usr/local/lib/python3.11/dist-packages/wyoming_porcupine/__main__.py", line 14, in <module>
>     import pvporcupine
>   File "/usr/local/lib/python3.11/dist-packages/pvporcupine/__init__.py", line 12, in <module>
>     from ._factory import *
>   File "/usr/local/lib/python3.11/dist-packages/pvporcupine/_factory.py", line 15, in <module>
>     from ._util import *
>   File "/usr/local/lib/python3.11/dist-packages/pvporcupine/_util.py", line 78, in <module>
>     _PV_SYSTEM, _PV_MACHINE = _pv_platform()
>                               ^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/pvporcupine/_util.py", line 71, in _pv_platform
>     pv_machine = _pv_linux_machine(platform.machine())
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/pvporcupine/_util.py", line 62, in _pv_linux_machine
>     raise NotImplementedError("Unsupported CPU: '%s'." % cpu_part)
> NotImplementedError: Unsupported CPU: '0xd05'

In continue of https://github.com/Picovoice/porcupine/issues/1187 i hardcoded for testing on RK3588 and it's 100% working

### Steps To Reproduce

bind /proc/cpuinfo with docker portainer because it's a home assistant addon.

### Expected Behavior

If 0xd05 cpu code is added to the python pvporcupine all RK3588 can get is working like a raspberry pi.

**Comment by laves** [comment]
@Al3XKOoL - this isn't a bug. It seems you're requesting that we officially add support for a new platform. While I'm glad that your change to our Python SDK allowed your app to function on your device, adding a new official platform for us is not a trivial undertaking. This platform is not on our roadmap at this time, however, if you are an enterprise user or wish to engage with us on that level, please [contact sales](https://picovoice.ai/pricing/).

**Comment by ssssssssssshuai** [comment]
您好，您的这个问题解决了吗？方便交流一下？

**Comment by Al3XKOoL** [comment]
> 您好，您的这个问题解决了吗？方便交流一下？

They want we paid for this change.

**Comment by leone-spudorato** [comment]
@Al3XKOoL Do you remember how you hardcoded it? Just by adding something like elif '0xd07' == cpu_part:
        return 'cortex-a57' + arch_info in util.py?
