### ISSUE TITLE
How to update to a new version (iOS)?

### ISSUE THREAD

**Issue by fabioknoedtbcgdv** [Picovoice/Porcupine#127]
I was wondering what are the steps to update from an older version, let's say `1.4` to the newest `1.5`, for iOS. A small step-by-step would be very helpful in the README.
I am flagging that here but I did by simply replacing the relevant files and it didn't work.

Also, maybe consider adding support to Cocoapods - then you don't need a step-by-step update instructions 👍

**Comment by kenarsa** [comment]
can you explain what's not working? whats in the log, etc ...

**Comment by fabioknoedtbcgdv** [comment]
Now, it is working but it wasn't straightforward. That's what I mean with my comment.

In an existing project, I had to update:
`porcupine_params.pv`
`libpv_porcupine_Mac.a`
`libpv_porcupine_iOS.a`
and all keyword files (that I didn't know and caused the issue)

**Comment by kenarsa** [comment]
Cool. That's about right. The procedure is about the same for all platforms. You should have seen an error message in the log that the keyword files belong to a different version. Feel free to add your learning as a gist . The ios/watchos community will definitely appreciate it.
