### ISSUE TITLE
Porcupine Documentation Issue: 

### ISSUE THREAD

**Issue by AlexBiscontin** [Picovoice/porcupine#1273]
### What is the URL of the doc?

https://picovoice.ai/docs/faq/general/#:~:text=Picovoice%20Forever%2DFree%20Plan%20offers%20up%20to%203%20users%2Fmonth,Porcupine%20Wake%20Word

### What is the nature of the issue?

Hello, we have just downloaded the demo primarily to test the Porcupine service. We noticed that by installing the demo on two different Android devices, the number of active users (free account) only increased to 1 out of 3 on the portal. We are unable to understand how this aspect is managed.
Why only one if we installed the demo on two devices?
Thanks!

**Comment by laves** [comment]
@AlexBiscontin - apologies for the delay. Porcupine doesn't count devices, it measures monthly active users. The definition of what a user is can change depending on what platform you are running on. For Android, we count number installs of an app once it is out of active development, so you may not see an accurate count if you are just testing stuff out in a dev environment.
