### ISSUE TITLE
Porcupine Issue: Are there any plans to support WebGL on the Unity platform

### ISSUE THREAD

**Issue by ibytergj** [Picovoice/porcupine#1275]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

Unity

### Porcupine package version

Latest

### Framework version

Unity 2022.3

### Platform

Web (WASM)

### OS/Browser version

Chrome

### Describe the bug

Not a bug but a platform support question.

Are there any plans to support WebGL on the Unity platform?

### Steps To Reproduce

None

### Expected Behavior

TBD

**Comment by ErisMik** [comment]
It's not on the roadmap, unfortunately. If this is a commercial application with the budget allocated, feel free to contact the [sales team](https://picovoice.ai/pricing/).
