### ISSUE TITLE
Porcupine Issue: aauthentication issue

### ISSUE THREAD

**Issue by IvanoSaratoga** [Picovoice/porcupine#1276]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

Android

### Porcupine package version

3.0.1

### Framework version

min sdk 25, target sdk 33

### Platform

Android

### OS/Browser version

Android 11

### Describe the bug

Hi all,
we are evaluating your service "porcupine wake word" but we experienced problems with authentication.
We are using just one app with account [ivano.boscolo@saratogadental.it] and we see in your portal the active users indicator to 1, so I suppose we didn't over using your free plan.

We got the error: Activation error 136 randomically, but some times it works finally wih no changes in our code.
We got the same problem also using your own demo APP!!!

Can you please let us know what could be the problem, please?
Can you also explain better what is the active users meaning, please?

For example, we installed an app with the same access key in two different mobile phones and the active users in your portal is always showing 1 (I would expect 2....): should it be in this case active users be 2?

### Steps To Reproduce

PorcupineManager porcupineManager = new PorcupineManager.Builder()
  .setAccessKey("${ACCESS_KEY}")
  .setKeywordPaths(["${KEYWORD_FILE_PATH}"])
  .setModelPath("${MODEL_FILE_PATH}")
  .build(context, wakeWordCallback);

We got the same problem also using your own demo APP!!!
It stops in this source code line, firing the error "activation error 136" 

### Expected Behavior

PorcupineManager porcupineManager = new PorcupineManager.Builder()
  .setAccessKey("${ACCESS_KEY}")
  .setKeywordPaths(["${KEYWORD_FILE_PATH}"])
  .setModelPath("${MODEL_FILE_PATH}")
  .build(context, wakeWordCallback);

It should continue and working normally. This happens sometimes but in other occasions it is firing the activation error 136 without no changes in our source code with no reason.

**Comment by mrrostam** [comment]
The issue seems to stem from an unstable internet connection. Porcupine needs to communicate with our server once in a while, but if you uninstall and reinstall the app, it will need to re-authenticate.

Regarding active users, in developer mode, we only count all activations as one user to give developers more freedom for testing. This is likely why you only see one active user, even if you are testing on multiple devices.
