### ISSUE TITLE
Creating a custom wake word in porcupine

### ISSUE THREAD

**Issue by Din96Boy** [Picovoice/porcupine#1277]
Can we make custom wake words with the porcupine? , Im trying to creake a wake word with my name "Hey Dinoj" but when I yype it under WAKE WORD it shows an error that 
`"Dinoj" is not in our vocabulary. Please try another word.`

how to make a custom word like this?
Thank you

**Comment by mrrostam** [comment]
For words that are not in our vocabulary, you can break them down into shorter, common English words with similar pronunciations. For example, "picovoice" could be entered as "pee ko voice."

**Comment by Din96Boy** [comment]
@mrrostam  thank you very much for your reply. It really works.
