### ISSUE TITLE
[Optimizer - Windows] I/O Error

### ISSUE THREAD

**Issue by maiajhonathan** [Picovoice/Porcupine#128]
### Expected behavior
Hi, I tried to create a new wake word just to test the optimizer, the word is "banana", but I'm receiving the error: keyword optimization failed with 'IO_ERROR'
### Steps to reproduce the behavior
.\pv_porcupine_optimizer.exe -r resources/ -w "banana" -p windows -o C:\Users\MyUsername\Desktop\
I tried without double quotes, simple quotes, terminal as Admin, I changed the wake word,  but in all cases the same error happens, what that could be?

Thanks guys!

**Comment by kenarsa** [comment]
maybe use \\ instead of \?

**Comment by maiajhonathan** [comment]
Hi Kenarsa,

After your reply I started a new battery of tests and finally I could create a new key word. What I had to do is declare the whole path for resources e.g. D:\Library\Porcupine\...\resources and it worked!

So for anyone with this issue in the future, before opening a support request try the above method and see if it will work 😄 

Thanks for your help Kenarsa! Have a good one.

**Comment by vijayvanapalli96** [comment]
I'm also running into the same error, even after linking the whole path file for resources. @maiajhonathan Did you try reading and writing to the same file by any chance? Or could you share the command that you used to bypass the initial issue?

**Comment by Syakiran407** [comment]
@maiajhonathan like this? pv_porcupine_optimizer.exe -r C:\Users\User\Desktop\Porcupine\resources/ -w "Hello E A" -p windows -o  C:\Users\User\Desktop  ? I still got the same error

**Comment by Syakiran407** [comment]
Nevermind, it works now

**Comment by kck278** [comment]
I got the same error, I tried the whole resource path as well as adding optimizer_data as @Syakiran407 so my input was 

pv_porcupine_optimizer.exe -r C:\\...\\...\\Porcupine\resources\opimizer_data -w "start" -p windows -o C:\\...\\...\\Porcupine\resources\keyword_files

Have I done something wrong?

**Comment by Syakiran407** [comment]
> I got the same error, I tried the whole resource path as well as adding optimizer_data as @Syakiran407 so my input was
> 
> pv_porcupine_optimizer.exe -r C:\...\...\Porcupine\resources\opimizer_data -w "start" -p windows -o C:\...\...\Porcupine\resources\keyword_files
> 
> Have I done something wrong?

Open your Porcupine directory. Go to the optimizer.exe folder. Hold shift and then on your mouse right-click, choose "Open with CMD" OR "Open with PowerShell" and then on CMD/PowerShell type the following. I think yours should look like this @kck278 :

.\pv_porcupine_optimizer.exe -r ../../../../resources/optimizer_data -w "start" -p windows -o C:\Porcupine\resources\keyword_files

Without "..\..\" at the output

**Comment by kck278** [comment]
The "..\\.." was just as a placeholder for my system user name, should have mentioned that. Anyways, it worked now when I just entered

.\pv_porcupine_optimizer.exe -r ../../../../resources/optimizer_data -w "start" -p windows -o .

Thanks!
