### ISSUE TITLE
Android x86_64 Support

### ISSUE THREAD

**Issue by mclayton7** [Picovoice/porcupine#1287]
We are interested in using porcupine with Unity on an x86_64 android device, but noticed only ARM/ARM64 is supported. Is this something that would be easy to accomplish with a pull request, or is it a limitation of the underlying libraries?

**Comment by matt200-ok** [comment]
Hi @mclayton7, if this is for a commercial product you can reach out to your sales contact at Picovoice, or otherwise [contact us](https://picovoice.ai/pricing/) through sales to get the feature added. We also take community PRs.

**Comment by mclayton7** [comment]
Thank you! We were able to get this working by swapping the libs, so I'll try to open a PR for it.
