### ISSUE TITLE
Picovoice Console Issue: Wake word is not working

### ISSUE THREAD

**Issue by jhsasdfgijhgfcvbn** [Picovoice/porcupine#1288]
when i import my file into my code it runs and terminated from the code but i doesn't wait for my command

**Comment by matt200-ok** [comment]
Hello,

To best address your issue, please report it using [this template on GitHub](https://github.com/Picovoice/porcupine/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=Porcupine+Issue%3A+). This will provide the necessary details for us to investigate and assist you effectively.

I'll be closing this current issue for now. Please submit your bug report through the link above, and we'll gladly help you resolve the problem.
