### ISSUE TITLE
jarvis wake word

### ISSUE THREAD

**Issue by quanghd96** [Picovoice/Porcupine#129]
In the feature, can you support jarvis wake word in all plaform?

**Comment by kenarsa** [comment]
you can generate it yourself using the optimizer tool on Linux, Mac, and Windows.

the general policy is to not add custom wake-words to resources.

Let's keep the issue open and if the community shows a lot of interest in this specific wake-word I will consider it for the v1.6 release.

**Comment by dinhchinh82** [comment]
@kenarsa we are  testing the smart room solution for my university which is based on voice assistant. We just tested the Alexa wakeword from your Porcupine but the detection quality is not so good enough. That's great if you could support Javis wakeword for the community. 
Thank you.

**Comment by FourierTransformer** [comment]
Are the wakewords in the resource directory just generated via the optimizer or via something different?

**Comment by mohamedsagna** [comment]
Thank you for making great wakeword engine but I guess a lot of people like me are interested in popular wakeword such as Jarvis.

I'm using Snowboy but willing to move on Porcupine if Jarvis is available.
خیلی ممنون

**Comment by burntcrispy** [comment]
I too would like to see Jarvis hot word added. If you want to compete with alternatives like Snowboy, you should match their hot word list.  

I am also disappointed your are not supporting custom hotwords on the raspberry pi.  It confusing since in my mind the raspberry pi is a Linux platform, therefore should be supported as such.

**Comment by hongluu** [comment]
I’d love to see Jarvis wake-word for Android too. Hope  to see the v1.6 will come soon. Thank you for your community support.

**Comment by phobrv** [comment]
Jarvis wakeword is more popular for the community than Alexa so I expect it will be available soon.

**Comment by kenarsa** [comment]
we decided that we are not going to make more keyword files available under Apache 2.0.

**Comment by ChrisHaPunkt** [comment]
Hi, @kenarsa,
awesome work by you guys.
But i have a question: Is there a way where we're able to get (for private use) a jarvis ppn for an arm platform? The training console offers only windows, linux and mac x86_64.

**Comment by dbartle** [comment]
We won't be providing more keywords under Apache 2.0.

You can use Picovoice Console (https://console.picovoice.ai) to generate custom PPN files.

The console currently provides Linux, macOS, and Windows on x86_64. Other platforms like ARM and Raspberry Pi are available with a development license.
