### ISSUE TITLE
Passing in multiple wake word files on iOS only listens for the first wake word passed in

### ISSUE THREAD

**Issue by r-token** [Picovoice/porcupine#1290]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

iOS

### Porcupine package version

3.0.0

### Framework version

Swift 5.10

### Platform

iOS

### OS/Browser version

iOS 17.5.1

### Describe the bug

I'd like to support multiple porcupine wake words on iOS. I have the app compiling and running after extending `PicovoiceManager.swift`, `Picovoice.swift`, `Porcupine.swift`, and `PorcupineManager.swift` to accept multiple `keywordPath` values and multiple `porcupineSensitivity` values, but upon starting pico it is only listening for whatever the **first** `keywordPath` porcupine file I pass in is.

Here's where I initialize the PicovoiceManager:

```Swift
pico = try PicovoiceManager(
  accessKey: accessKey,
  keywordPaths: [
      Bundle.main.path(forResource: "Hey-Otis_en_ios_v3_0_0.ppn", ofType: nil)!,
      Bundle.main.path(forResource: "check-check_en_ios_v3_0_0.ppn", ofType: nil)!,
      Bundle.main.path(forResource: "Hey-Otto_en_ios_v3_0_0.ppn", ofType: nil)!,
      Bundle.main.path(forResource: "Hey-Milo_en_ios_v3_0_0.ppn", ofType: nil)!,
      Bundle.main.path(forResource: "Hey-Miles_en_ios_v3_0_0.ppn", ofType: nil)!,
      Bundle.main.path(forResource: "Hey-Dash_en_ios_v3_0_0.ppn", ofType: nil)!
  ]
```

In this example, "Hey Otis" will fire properly but none of the others will. If I move another file to be the first one in the array, that file will be what is listened for and acted on. I need all of them to be listened for simultaneously so we can test multiple wake words in the wild.

In `Porcupine.swift` I can see that it does check for the proper number of `num_keywords`:

```Swift
pv_set_sdk(Porcupine.sdk)

let status = pv_porcupine_init(
    accessKey,
    modelPathArg,
    Int32(keywordPathsArgs.count),
    keywordPathsArgs.map { UnsafePointer(strdup($0)) },
    sensitivitiesArg,
    &handle)

if status != PV_STATUS_SUCCESS {
    let messageStack = try getMessageStack()
    throw pvStatusToPorcupineError(status, "Porcupine init failed", messageStack)
}
```

I've read three related issues [here](https://github.com/Picovoice/porcupine/issues/759), [here](https://github.com/Picovoice/porcupine/issues/24), and [here](https://github.com/Picovoice/porcupine/issues/164), but none have solved the problem for me on iOS.

Is it possible to run multiple wake words simultaneously on iOS? And if so, what might I be doing wrong?

Thanks for the help. Really am loving pico! Just would love to test out multiple wake words simultaneously and can't figure out what I'm doing wrong here.

### Steps To Reproduce

1. Adjust `PicovoiceManager.swift`, `Picovoice.swift`, `Porcupine.swift`, and `PorcupineManager.swift` to all accept multiple `keywordPaths` and `porcupineSensitivities`
2. Pass multiple `keywordPaths` and `porcupineSensitivities` into PicovoiceManager
3. Run the app
4. Only the first `keywordPath` passed into the array will be listened for/acted on

### Expected Behavior

All of the `keywordPaths` passed into PicovoiceManager should be listened for and acted on

**Comment by laves** [comment]
@r-token - just a disclaimer, we cannot provide support via this forum if you've altered the SDK because it no longer applies to the repo as a whole, but more to the new implementation. That said, I think this is issue may be trivial, so I'm willing to provide assistance. If you've altered `Picovoice-iOS` to accept multiple keywords, you should also alter [this line](https://github.com/Picovoice/picovoice/blob/master/sdk/ios/Picovoice.swift#L125) to trigger on a keyword index that is `>= 0` because an index of `0` will only apply to the first keyword passed in.

**Comment by r-token** [comment]
@laves That makes sense, we don't plan on using the altered SDK long term - just experimenting with multiple wake words for now.

But that worked! Thank you for the tip, I don't think I would've found that myself. We'll go back to using a single wake word after we've concluded the experiment.

Out of curiosity: is native support for multiple wake words planned? Or should we expect to always only use one for the foreseeable future?

**Comment by laves** [comment]
Glad to hear that worked for you! `Porcupine-iOS` supports multiple keywords by default, but it is the `Picovoice-iOS` API that does not. The Picovoice platform is a convenience package meant to demonstrate how one could combine the Porcupine and Rhino engines into a single voice solution. Combining them within an app separately is not much more difficult, so usually if a user is looking for a specific feature from the Picovoice package, we would suggest they combine the engines within their app directly.
