### ISSUE TITLE
Porcupine Issue: Have an issues after changing .ppn file to a new one.

### ISSUE THREAD

**Issue by Kost927** [Picovoice/porcupine#1291]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

React

### Porcupine package version

3.0.3

### Framework version

React 18.2

### Platform

Web (WASM)

### OS/Browser version

macOS 14.5 (23F79)

### Describe the bug

The issue is I want to use a custom wake-up word, and it worked after I set it for the first time. I trained a new one and changed publicPath to the new .ppn file and every time I want to start it I get such kinds of errors as we can see on the screenshots below. Nothing was changed except publicPath to the new file. Is there any cache that should be cleared after files change? 
<img width="852" alt="Screenshot 2024-07-16 at 15 39 19" src="https://github.com/user-attachments/assets/e3a161a5-fef5-47f5-84a1-8923de9e700e">
<img width="834" alt="Screenshot 2024-07-16 at 15 39 11" src="https://github.com/user-attachments/assets/6cc4e960-cdba-4373-965d-c736ea7b015e">

### Steps To Reproduce

1. Create a React app.
2. use hook usePorcupine()
3. in the init function provide configuration with access key, keyword .ppn file, params .pv file.
4. start app
5. stop app
6. change keyword .ppn file
7. start app again

### Expected Behavior

new keyword file should work with an application after init function.

**Comment by albho** [comment]
hey @Kost927, try setting the `forceWrite` flag to `true` on [PorcupineModel](https://picovoice.ai/docs/api/porcupine-web/#porcupinemodel).

**Comment by Kost927** [comment]
Hey. @albho Thank you. I tried forceWrite, and tried to add random versions. (another setting). Nothing helps.

**Comment by albho** [comment]
Can you double check that you changed your keyword public path in the correct place? I think you may have replaced your [PorcupineModel](https://picovoice.ai/docs/api/porcupine-web/#porcupinemodel) (`.pv`) file instead of your [PorcupineKeyword](https://picovoice.ai/docs/api/porcupine-web/#porcupinekeywordcustom) (`.ppn`) file. This would make sense since it looks like your porcupine is having trouble initializing instead of recognizing the new keyword.

**Comment by Kost927** [comment]
<img width="741" alt="Screenshot 2024-07-18 at 09 06 50" src="https://github.com/user-attachments/assets/4a02de7d-f360-4d01-b19b-c7360ecd08c1">
<img width="372" alt="Screenshot 2024-07-18 at 09 07 10" src="https://github.com/user-attachments/assets/dc39c878-ff91-4af3-99dd-8457978340bd">
I'm pretty sure these are the correct files. Porcupine Model I download from this page https://picovoice.ai/docs/quick-start/porcupine-react/. Thank you for trying to help me. Also I tried base64 representation of these files, and got the same error. Does version of Porcupine Model .pv file is correct from [this](https://picovoice.ai/docs/quick-start/porcupine-react/) page? But confusing that it worked, before I changed the files to a new one.

**Comment by albho** [comment]
Can you make sure that you are waiting for `isLoaded` to be `true` before calling `start`?

**Comment by albho** [comment]
Glad you got it working!
