### ISSUE TITLE
Picovoice Console Issue: 

### ISSUE THREAD

**Issue by YourLittleEddyGithub2** [Picovoice/porcupine#1292]
pvporcupine._porcupine.PorcupineActivationError: Initialization failed:
  [0] Picovoice Error (code `00000136`)
  [1] Picovoice Error (code `00000136`)
  [2] Picovoice Error (code `00000136`)

**Comment by ksyeo1010** [comment]
is this error from the console? provide more details.

**Comment by ksyeo1010** [comment]
Closing issue as no action is to be done.
