### ISSUE TITLE
Porcupine Issue: pvporcupine._porcupine.PorcupineActivationRefusedError: Initialization failed.

### ISSUE THREAD

**Issue by dzianisv** [Picovoice/porcupine#1297]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

Python

### Porcupine package version

pvporcupine==3.0.1

### Framework version

Python 3.11.2

### Platform

Android

### OS/Browser version

Linux orangepipc 6.1.63-current-sunxi #1 SMP Mon Nov 20 10:52:19 UTC 2023 armv7l GNU/Linux

### Describe the bug

```
Traceback (most recent call last):
  File "/opt/VoiceAssistant/./main.py", line 150, in <module>
    assistant = VoiceAssistant()
                ^^^^^^^^^^^^^^^^
  File "/opt/VoiceAssistant/./main.py", line 40, in __init__
    self.wakeword = WakeWord(lang=os.getenv("LANGUAGE", "ru"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/VoiceAssistant/wakeword_pvporcupine.py", line 55, in __init__
    recognizer = pvporcupine.create(
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/VoiceAssistant/.venv/lib/python3.11/site-packages/pvporcupine/_factory.py", line 69, in create
    return Porcupine(
           ^^^^^^^^^^
  File "/opt/VoiceAssistant/.venv/lib/python3.11/site-packages/pvporcupine/_porcupine.py", line 198, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status](
pvporcupine._porcupine.PorcupineActivationRefusedError: Initialization failed:
  [0] Picovoice Error (code `00000136`)
  [1] Picovoice Error (code `00000136`)
  [2] Picovoice Error (code `00000136`)
ALSA lib pcm.c:8570:(snd_pcm_recover) underrun occurred
^CException ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1583, in _shutdown
    lock.acquire()
```

### Steps To Reproduce

I start a voice assistant, and when it starts to initialize the library, it fails. Could you help me please to identify the issue?

The code is located there https://github.com/dzianisv/VoiceAssistant/blob/main/src/wakeword_pvporcupine.py

It worked a few months ago, and works on macOS

### Expected Behavior

Libarary initializes

**Comment by laves** [comment]
This indicates that your account was flagged and removed.

Picovoice Audit System can delete accounts in case of [Picovoice Terms of Use](https://picovoice.ai/docs/terms-of-use/) violations, such as suspicious activities, creating multiple accounts, providing false or inaccurate information.

If you think there is a mistake, please send an email to [hello@picovoice.ai](mailto:hello@picovoice.ai) with your name, surname, country, city and project details. We’ll investigate it further.

**Comment by dzianisv** [comment]
Thank you for response. It happens twice in this year. And I don't know the reason. Looks like I have to switch to openwakeword.

**Comment by Joseph513shen** [comment]
> Thank you for response. It happens twice in this year. And I don't know the reason. Looks like I have to switch to openwakeword.

i met the same problem today,so i can't use porcupine now? maybe i have to switch to openwakeword too.
