### ISSUE TITLE
Support for wake up sentences?

### ISSUE THREAD

**Issue by MehdiFal** [Picovoice/Porcupine#13]
Hello, 

First of all, thank you for this engine, it's awesome! 

I've tried to create a small wake up sentence using the optimizer command line too, like the famous "ok google" but it seems not to be supported.

**Command:**
```
tools/optimizer/mac/x86_64/pv_porcupine_optimizer -r resources/ -w "ok test" -p mac -o ~/
```
**Output:**
**[ERROR] Could not find a pronunciation for 'ok test'. If this is not a typo please contact help@picovoice.ai.**

On my real use case the trigger command will be "Ok + 2 small words" 

Is this the expected behavior of Porcupine? Which means Porcupine is designed exclusively for single words detection? If so, any workaround?
Or did I miss something on the optimizer tool?

Thank you.

**Comment by kenarsa** [comment]
Hi Mehdi,

Thank you. Happy that Porcupine is being useful.

You are correct. The optimizer here can only build keyword files for single-word wake-words. That being said, we do have an internal optimizer that can generate multi-word wake-words which is available for commercial customers.

If using "OK Google" would suffice for your use case, I'll be happy to add it to /resources/keyword_files/ as it might be useful to others as well.

Thanks!

**Comment by MehdiFal** [comment]
Hi Alireza, 

Understood. 

Thanks!

**Comment by kenarsa** [comment]
Hi Mehdi,

We've updated the optimizer to allow user create multi-word wake phrases. now you can create keywords like "ok google" or "hey Mehdi".

Hope it helps.

**Comment by MehdiFal** [comment]
@kenarsa that's good news! I'll test it tonight! 

Thanks!
