### ISSUE TITLE
PorcupineManager degrades audio quality

### ISSUE THREAD

**Issue by PaulLafytskyi** [Picovoice/porcupine#1305]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

iOS

### Porcupine package version

3.0.0

### Framework version

3.0

### Platform

iOS

### OS/Browser version

iOS

### Describe the bug

While playing music with spotify or apple music starting PorcupineManager making dramatic effect on music quality. I don't really know if I can call it a bug but testing wake word with for example with Alexa it works fine, music stays on a same level without additional noises. It sounds like you not only listening but also **transmitting audio from microphone**.

### Steps To Reproduce

1. Play music on your iPhone with Airpods 
2. In a app start init`PorcupineManager` and call start
3. Word detection works as expected
4. Verify small pause and then decreasing audio quality

### Expected Behavior

Audio quality stays the same

**Comment by ksyeo1010** [comment]
Thanks for reporting I will let the team know but not really have an estimate for a fix. For now, you can use the low-level API Porcupine instead of PorcupineManager and handle audio management yourself.

**Comment by laves** [comment]
@PaulLafytskyi - this was an issue with our `ios-voice-processor` package not supporting the latest Bluetooth profiles. We've patched the package and updated `Porcupine-iOS` with the fix. Grab the latest version (`3.0.2`) to try out the fix and let us know if it works for you.

**Comment by laves** [comment]
This issue has been addressed.
