### ISSUE TITLE
IOS - Recording and listening for keyword at the same time

### ISSUE THREAD

**Issue by matthewha123** [Picovoice/Porcupine#131]
Using the provided PorcupineManager for ios, I am unable to record audio, using AVAudioRecorder, and listen for keywords at the same time (calling the startListening function in PorcupineManager. Is there a workaround for this?

**Comment by kenarsa** [comment]
whats your use case?

you probably should change PorcupineManger to both record and pass audio to the engine. But the alternative should work as well.

Can't provide more help without understanding context and/or seeing some code ...

**Comment by kenarsa** [comment]
Thanks for the info. And the issue you are seeing is that the Porcupine is not detecting, correct?

I don't have a 100% answer why if that is the case but I suspect that the recorder and manager are forcing microphone to record in two incompatible configurations.

What I meant by changing the porcupine manager is to record audio in it within the callback here https://github.com/Picovoice/Porcupine/blob/5d49042396aa280ef1d64bc1fa5b177b26820b30/binding/ios/PorcupineManager.swift#L84

if you want to feed audio to porcupine it needs to be in raw format without any compression etc. take a look at the header file pv_porcupine.h to learn more about the required format.

**Comment by matthewha123** [comment]
I see, that makes a lot of sense. Porcupine does not detect if I start recording after I start porcupine listening, and porcupine does detect if I start listening after I start recording. In both cases, the recordings are silent. As for the required format, are these the only parameters I need to keep in mind: "sample rate equal to 'pv_sample_rate()' and be 16-bit
 * linearly-encoded. Furthermore, porcupine operates on single channel audio".

**Comment by kenarsa** [comment]
Yes. Those are the only parameters. I suspect this is because of how the audio nodes are set up. I believe what you are trying to do is achievable. Since this seems to be an issue out of the scope of the engine I am going to close this issue. If you find a solution feel free to submit a PR for an additional iOS demo. I am sure the community will appreciate.
