### ISSUE TITLE
Porcupine Documentation Issue: account 

### ISSUE THREAD

**Issue by brekov** [Picovoice/porcupine#1313]
### What is the URL of the doc?

https://console.picovoice.ai/login

### What is the nature of the issue?

An account registered with '****@gmail.com' has been deleted and cannot be reactivated. This may be due to a user request, inactivity, or Picovoice Terms of Use violations.

my account has been deleted，And without any response after “[Contact us](https://forms.gle/bWoPoez1F45J2JZv8) if you believe this is a mistake.”

**Comment by laves** [comment]
Not relevant to this repo
