### ISSUE TITLE
Porcupine Issue: Constantly getting my accounts deleted without any understanding what I have done wrong.

### ISSUE THREAD

**Issue by MMAik100** [Picovoice/porcupine#1316]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

Node.js

### Porcupine package version

I dont know

### Framework version

node.js on Rasberry pi

### Platform

Raspberry Pi

### OS/Browser version

node.js

### Describe the bug

My account has been deleted so I changed to using a different account and now that has been deleted. why?

### Steps To Reproduce

Open an account
build a PPN
load it into my instance of node.js
account get deleted short time later

### Expected Behavior

to not loose my account

**Comment by laves** [comment]
Picovoice Audit System can delete accounts in case of [Picovoice Terms of Use](https://picovoice.ai/docs/terms-of-use/) violations, such as suspicious activities, creating multiple accounts, providing false or inaccurate information.

If you think there is a mistake, please send an email to [hello@picovoice.ai](mailto:hello@picovoice.ai) with your name, surname, country, city and project details. We’ll investigate it further.

**Comment by MMAik100** [comment]
I did all that.  I am honestly following all the rules.  Its annoying to
not be able to keep my simple custom wake word function alive without any
idea why i am getting shutdown..    i have asked twice and you are the only
person who has responded.

**Comment by MMAik100** [comment]
Would someone please get back to me regarding restoring my account.   I
used this one until you deleted it and thought maybe picovoice didn’t like
basic gmail accounts.  So I created another using my ***@***.***
company account.   You deleted that also.    Why?  What is the reason I
can’t have access to you platform to learn and build personal projects?

**Comment by engineer1469** [comment]
Same problem here. 
Did nothing to violate guidelines.
Fix your algorithm please.

**Comment by MMAik100** [comment]
There is no way this ticket should be closed.   With no response from any review of my case, my account was cancelled for no reason and nobody has replied.   This is the absolute worst service by any firm.   Why would someone want to use a system where the company will not only shut the user down but give no reason or chance to resolve the issue.

**Comment by MMAik100** [comment]
> Picovoice Audit System can delete accounts in case of [Picovoice Terms of Use](https://picovoice.ai/docs/terms-of-use/) violations, such as suspicious activities, creating multiple accounts, providing false or inaccurate information.
> 
> 
> 
> If you think there is a mistake, please send an email to [hello@picovoice.ai](mailto:hello@picovoice.ai) with your name, surname, country, city and project details. We’ll investigate it further.

Why does nobody reply to any request?   Is picovoice still in business?
