### ISSUE TITLE
64-bit Libraries iOS

### ISSUE THREAD

**Issue by jon2718** [Picovoice/Porcupine#132]
### Steps to reproduce the behavior

Please include enough details so that the issue can reproduced independently by the resolver.

**Comment by jon2718** [comment]
Hi,

I am trying to compile for iOS 12 and need 64-bit libraries for libpv_porcupine.a  Do you have those

**Comment by kenarsa** [comment]
changed the title to 64-bit ... I don't think anyone will build a 65-bit ... CPU anytime soon.

The lib works on iOS 12. Be sure to build for target and not the simulator, please.
