### ISSUE TITLE
(Question, not bug:) Porcupine SwiftPM support on iOS

### ISSUE THREAD

**Issue by pipacs** [Picovoice/porcupine#1323]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

iOS

### Porcupine package version

Porcupine-iOS-v3.0.1

### Framework version

Xcode 16

### Platform

iOS

### OS/Browser version

iOS 16

### Describe the bug

Our project is using Swift Package Manager, not CocoaPods, for dependency management. Does Porcupine iOS support SPM?

### Steps To Reproduce

Attempt to use Porcupine iOS with Swift Package Manager

### Expected Behavior

Porcupine iOS can be used with Swift Package Manager

**Comment by matt200-ok** [comment]
Porcupine does not currently support SPM. We've had a few requests for moving to SPM and we are looking to make the switch. Unfortunately we don't have an estimate when the change will be done. I'll leave this issue up for now and close it when an SPM package for Porcupine is available.

**Comment by laves** [comment]
@pipacs - Porcupine is now available on SPM ([3.0.4](https://github.com/Picovoice/porcupine/releases/tag/3.0.4)). Let us know if you have any problems adding it.

**Comment by laves** [comment]
Closed as this feature has been added - reopen if there are any issues with it
