### ISSUE TITLE
Codesigning error when trying to build for iOS 12.1

### ISSUE THREAD

**Issue by jon2718** [Picovoice/Porcupine#133]
![screen shot 2018-12-15 at 11 39 23 pm](https://user-images.githubusercontent.com/492958/50050226-fd030600-00c2-11e9-8c87-431accadae21.png)

**Comment by jon2718** [comment]
Please see attached screen shot.  I looked at the certificates and they all seem valid.  I don't see any expired certs.

**Comment by kenarsa** [comment]
I am fairly certain this is not an issue with Porcupine. I can't exactly remember what causes it but something along the lines of not being signed in your apple developer account or so.

Can you build/run any other iOS project?

**Comment by jon2718** [comment]
Ok let me check on this and I’ll get back to you

**Comment by jon2718** [comment]
thanks got it working.  it was it was an annoying certificate problem.  had to remove all certs.  testing it out now.

**Comment by kenarsa** [comment]
great. closing the issue.

**Comment by jon2718** [comment]
Question: with your algorithm is there a way it can be further tuned to particular users so it can improve over time?
