### ISSUE TITLE
Can't initialise PvRecorder with Raspberry Pi 4 with Raspberry Pi OS (Linux kernel 6.6.51)

### ISSUE THREAD

**Issue by Tom-Boscher** [Picovoice/porcupine#1334]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

Python

### Porcupine package version

3.0.3

### Framework version

Python 3.11.2

### Platform

Raspberry Pi

### OS/Browser version

Raspberry Pi OS Bookworm

### Describe the bug

I'm using a ReSpeaker 4-Mic Array for Raspberry Pi with a Raspberry Pi 4.
I'm able to record sound using `arecord -Dac108 -f S32_LE -r 16000 -c 4 test.wav`.

I tried to run a quick test script using pvporcupine and pvrecorder as wrote on the doc:
```
import pvporcupine
from pvrecorder import PvRecorder

ACCESS_KEY = "xxxxxx-xxxx-xxxx-xxxx-xxxxxx"

INDEX_DEVICE = -1

keywords = [
    "picovoice",
    "computer",
    "alexa",
    "bumblebee",
    "jarvis",
    "terminator",
    "porcupine",
]

porcupine = pvporcupine.create(
    access_key=ACCESS_KEY,
    keywords=keywords,
)

print(f"Using {PvRecorder.get_available_devices()[INDEX_DEVICE]} as input device")


# It seems that the recorder is not working properly and there is an infinite loop in the read method
try:
    recoder = PvRecorder(device_index=INDEX_DEVICE, frame_length=porcupine.frame_length)
except Exception as e:
    print(e)
    exit()

try:
    recoder.start()

    while True:
        keyword_index = porcupine.process(recoder.read())
        if keyword_index >= 0:
            print(f"Detected {keywords[keyword_index]}")

except KeyboardInterrupt:
    recoder.stop()
finally:
    porcupine.delete()
    recoder.delete()
```
But I have this error message:
```
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
```
Keyboard interrupt doesn't work to exit the script and any wake words are recognized.

`arecord -L`:
```
null
    Discard all samples (playback) or generate zero samples (capture)
lavrate
    Rate Converter Plugin Using Libav/FFmpeg Library
samplerate
    Rate Converter Plugin Using Samplerate Library
speexrate
    Rate Converter Plugin Using Speex Resampler
jack
    JACK Audio Connection Kit
oss
    Open Sound System
pulse
    PulseAudio Sound Server
speex
    Plugin using Speex DSP (resample, agc, denoise, echo, dereverb)
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
default
playback
ac108
usbstream:CARD=Headphones
    bcm2835 Headphones
    USB Stream Output
usbstream:CARD=vc4hdmi0
    vc4-hdmi-0
    USB Stream Output
usbstream:CARD=vc4hdmi1
    vc4-hdmi-1
    USB Stream Output
hw:CARD=seeed4micvoicec,DEV=0
    seeed-4mic-voicecard, fe203000.i2s-ac10x-codec0 ac10x-codec0-0
    Direct hardware device without any conversions
plughw:CARD=seeed4micvoicec,DEV=0
    seeed-4mic-voicecard, fe203000.i2s-ac10x-codec0 ac10x-codec0-0
    Hardware device with all software conversions
sysdefault:CARD=seeed4micvoicec
    seeed-4mic-voicecard, fe203000.i2s-ac10x-codec0 ac10x-codec0-0
    Default Audio Device
dsnoop:CARD=seeed4micvoicec,DEV=0
    seeed-4mic-voicecard, fe203000.i2s-ac10x-codec0 ac10x-codec0-0
    Direct sample snooping device
usbstream:CARD=seeed4micvoicec
    seeed-4mic-voicecard
    USB Stream Output
```

### Steps To Reproduce

1. `git clone https://github.com/HinTak/seeed-voicecard/tree/v6.6`
2. `cd seeed-voicecard/`
3. `sudo ./install.sh`
4. `sudo apt-get install portaudio19-dev libatlas-base-dev`
5. `curl -LsSf https://astral.sh/uv/install.sh | sh`
6. `cd .. && uv venv`
7. `uv pip install pvporcupine`
8. `uv pip install pvrecorder`
9. `uv run main.py`

### Expected Behavior

The expected behavior would be to recognized the list of default wake words and be able to exit the program when using `ctrl+D`

**Comment by Tom-Boscher** [comment]
`pv_recorder_demo --show_audio_devices`:
```
index: 0, device name: Discard all samples (playback) or generate zero samples (capture)
index: 1, device name: Rate Converter Plugin Using Libav/FFmpeg Library
index: 2, device name: Rate Converter Plugin Using Samplerate Library
index: 3, device name: Rate Converter Plugin Using Speex Resampler
index: 4, device name: JACK Audio Connection Kit
index: 5, device name: Open Sound System
index: 6, device name: PulseAudio Sound Server
index: 7, device name: Plugin using Speex DSP (resample, agc, denoise, echo, dereverb)
index: 8, device name: Plugin for channel upmix (4,6,8)
index: 9, device name: Plugin for channel downmix (stereo) with a simple spacialization
index: 10, device name:
index: 11, device name:
index: 12, device name:
index: 13, device name: seeed-4mic-voicecard, fe203000.i2s-ac10x-codec0 ac10x-codec0-0
```

`pv_recorder_demo --audio_device_index 13--output_wav_path test.wav` doesn't work and seems to cause an overflow error (can't exit the script/kill the process, had to reboot the Raspberry Pi)


`porcupine_demo_mic --access_key ${ACCESS_KEY} --keywords picovoice`:
```

Porcupine version: 3.0.0
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
```

**Comment by albho** [comment]
Seems like there's an issue connecting to your audio input device. PvRecorder uses [miniaudio](https://github.com/mackron/miniaudio) under the hood. Could you give their [simple capture example](https://github.com/mackron/miniaudio/blob/master/examples/simple_capture.c) a try and see if it works with your device? It may also be informative if you try a few other devices as well.

**Comment by Tom-Boscher** [comment]
I didn't try with an other device (I have an Evo 4 souncard, will try with it tomorrow) but here is the result for the ReSpeaker :
```
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
Press Enter to stop recording...
```
Same error and I can't kill the process too, I had to reboot the Pi

I tested with the same Debian on a VM on my MacBook Pro using AirPods Pro 2 and it works perfectly

**Comment by albho** [comment]
Since you're getting that same error, it seems like there's an issue with the ALSA configuration on your device. You'd need to get this working before PvRecorder and Porcupine can run.

I'm going to close this issue for now since it's not exactly a Porcupine issue, but feel free to re-open if you're still having trouble with Porcupine after getting ALSA working.

**Comment by Tom-Boscher** [comment]
The issue is, as I said, ALSA seems to work perfectly when running `arecord`
> I'm able to record sound using `arecord -Dac108 -f S32_LE -r 16000 -c 4 test.wav`.

I only get the error when running PvRecorder (or miniaudio).

**Comment by albho** [comment]
It looks to me like you're using different devices between `arecord` and miniaudio/PvRecorder (`ac108` vs `seeed-4mic-voicecard`)? What happens if you use `seeed-4mic-voicecard` for `arecord` or vice-versa?

**Comment by Tom-Boscher** [comment]
Indeed I was a bit confused about it. I followed the [ReSpeaker documentation](https://wiki.seeedstudio.com/ReSpeaker_4_Mic_Array_for_Raspberry_Pi/#enabling-voice-recognition-at-edge-with-picovoice) to use Picovoice with it and to test the microphone they said to run `arecord -D ac108 -f S32_LE -r 16000 -c 4 hello.wav` [here](https://wiki.seeedstudio.com/ReSpeaker_4_Mic_Array_for_Raspberry_Pi/#getting-started) and it works.

So I naturally try to use `ac108` soundcard as input but when I run `PvRecorder.get_available_devices()` I only got this list of devices:
```
['Discard all samples (playback) or generate zero samples (capture)', 'Rate Converter Plugin Using Libav/FFmpeg Library', 'Rate Converter Plugin Using Samplerate Library', 'Rate Converter Plugin Using Speex Resampler', 'JACK Audio Connection Kit', 'Open Sound System', 'PulseAudio Sound Server', 'Plugin using Speex DSP (resample, agc, denoise, echo, dereverb)', 'Plugin for channel upmix (4,6,8)', 'Plugin for channel downmix (stereo) with a simple spacialization', '', '', '', 'seeed-4mic-voicecard, fe203000.i2s-ac10x-codec0 ac10x-codec0-0']
```

How can I use `ac108` as input for PvRecorder?

If I run `arecord -D seeed-4mic-voicecard -f S32_LE -r 16000 -c 4 seeed-4mic-voicecard.wav` I have this error :
```
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM seeed-4mic-voicecard
arecord: main:831: audio open error: No such file or directory
```
