### ISSUE TITLE
Picovoice Console Issue: 

### ISSUE THREAD

**Issue by Luke1962** [Picovoice/porcupine#1338]
Today is 1st Dec, in previous month I've saturated my  3 free downloads attempting to get the same model for different architectures.
However even if this is a new month, download remains disabled.
By the way, my target platform is a Jetson Orin Nano and  I'd like to try Porcupine for IOS platfrom ( which seems to include Arm64 architecture)

**Comment by samartzidis** [comment]
I had a similar problem when I swapped Raspberry Pi development boards - using the same license. The old device would still count as licensed and I just ran out of licenses so I could not continue developing my project. I was told to wait for 1 month (!) for the old device registration to go away. I came up to the conclusion that Picovoice is not the right way to go for a hobby or open-source project. It might be okay for the enterprise.

**Comment by laves** [comment]
@Luke1962 - model download allowances renew every 30 days, not on the 1st of each month. Porcupine does have an iOS SDK.

@samartzidis - this is different. Model download allowances and active user allowances are handled differently, though renew at 30 days. Using different dev boards will add additional users to your license.
