### ISSUE TITLE
[Feature Req] WASM runtime example

### ISSUE THREAD

**Issue by voidastro4** [Picovoice/porcupine#1342]
We have a requirement where a compiled binary can only be trusted if it's WASM running in a runtime.

Specifically what we use for untrusted WASM binaries is Go & Wazero (https://wazero.io)

A side benefit would be having a Go demo that works on all platforms and which you can advertise as trustless.

**Comment by ksyeo1010** [comment]
Unfortunately supporting a new runtime is not in our backlog, so current Go/WASM support won't be extended any further.
