### ISSUE TITLE
Porcupine Documentation Issue: Wake word problem

### ISSUE THREAD

**Issue by Rainingiii** [Picovoice/porcupine#1346]
### What is the URL of the doc?

(https://github.com/Picovoice/porcupine/tree/master/demo/android)

### What is the nature of the issue?

I want to train a four-character Mandarin wake-up word such as "你好小语", but I was told that it is too long to be a wake-up word, but "一二三四" can be trained into a wake-up word. What should I do to train my four-word wake word?

**Comment by matt200-ok** [comment]
Hello @Rainingiii, The pronunciation of "你好小语" is too long to generate a wake word. It doesn't matter how many characters are in the wake word it all depends on how long the pronunciation is. Unfortunately there is no way to train "你好小语" as a wake word.
