### ISSUE TITLE
Publish application on fdroid

### ISSUE THREAD

**Issue by arthurlutz** [Picovoice/Porcupine#135]
https://play.google.com/store/apps/details?id=ai.picovoice.porcupine.demo&hl=en looks nice

It would be nicer if this android application was also distributed as a APK and on fdroid for android users who don't use the play store. 

Congrats on the absence of trackers https://reports.exodus-privacy.eu.org/fr/reports/33389/ by the way :clap: 

I'm going to add a an issue at the "Request for Packaging" on the fdroid side and reference it here https://gitlab.com/fdroid/rfp/issues

**Comment by arthurlutz** [comment]
https://gitlab.com/fdroid/rfp/issues/858

**Comment by IzzySoft** [comment]
@kenarsa we have an issue with some of the prebuilt libraries. Our scanner reported:

```
ERROR: Found shared library at lib/android/x86_64/libpv_porcupine.so
ERROR: Found shared library at lib/android/armeabi-v7a/libpv_porcupine.so
ERROR: Found shared library at lib/android/x86/libpv_porcupine.so
ERROR: Found shared library at lib/android/arm64-v8a/libpv_porcupine.so
```

As F-Droid builds from source only, could those been replaced by their source code?

**Comment by kenarsa** [comment]
We don't have plans at the moment to release the code for the shared objects. I am going to close the issue for now. If anything changes I will reopen and resume from there. thanks!

**Comment by IzzySoft** [comment]
Fair enough, thanks. I'll then close the request on our end as well – same game: we can reopen if you indicate it's fixed.
