### ISSUE TITLE
[Feature request] generate custom wakewords files for armlinux from optimizer

### ISSUE THREAD

**Issue by itgix** [Picovoice/Porcupine#136]
### Expected behavior
To be able to generate custom wakewords for armlinux so one can run Porcupine based apps on xxPi computers. 

### Actual behavior
./tools/optimizer/linux/x86_64/pv_porcupine_optimizer -r resources/ -w ${WAKE_WORD} \
-p armlinux -o ${OUTPUT_DIRECTORY}
[WARN] Cannot generate keyword file for armlinux 

### Steps to reproduce the behavior
Execute optimizer for the armlinux target platform:
./tools/optimizer/linux/x86_64/pv_porcupine_optimizer -r resources/ -w ${WAKE_WORD} \
-p armlinux -o ${OUTPUT_DIRECTORY}

**Comment by kenarsa** [comment]
We don't have plans to offer optimizer for arm-based platforms. Linux, Mac, and Windows are the only platforms offered.

We do have plans to enable maker community to create custom wake-words for arm-based platforms for PERSONAL USE though. This won't be through the optimizer. We will release more information sometime in 2019.
