### ISSUE TITLE
iOS library needs to be recompiled for arm64e

### ISSUE THREAD

**Issue by ryanaw** [Picovoice/Porcupine#137]
The iOS library seems like it isn't able to be linked with applications targeted for arm64e (for supporting the new iPhones/iPads that were recently released).

Compiling, I get:

```
ld: warning: ignoring file Porcupine/lib/ios/libpv_porcupine.a, file was built for archive which is not the architecture being linked (arm64e): Porcupine/lib/ios/libpv_porcupine.a
Undefined symbols for architecture arm64e
```

And indeed, if I check the binary itself,

```
$ lipo -info Porcupine/lib/ios/libpv_porcupine.a 
Non-fat file: Porcupine/lib/ios/libpv_porcupine.a is architecture: arm64
```

I can see it doesn't have the arm64e slice -- it's not a fat binary . However, the watchOS binary does have the slice necessary for the new series 4 watches,

```
$ lipo -info Porcupine/lib/watchos/libpv_porcupine.a 
Architectures in the fat file: Porcupine/lib/watchos/libpv_porcupine.a are: armv7k arm64_32
```

It seems like it's just the iPhone binary that needs to be rebuilt.

**Comment by kenarsa** [comment]
Thanks, will look into this ASAP.

**Comment by kenarsa** [comment]
Had a quick look. Isn't this feature only in preview mode?

**Comment by ryanaw** [comment]
I just read that as well, but I'm not sure the work around for getting this to build for iPhone XS...

**Comment by ryanaw** [comment]
Ah, I see. I was just using the 10.1 Xcode beta, and switching to the release version seems to fix it.
