### ISSUE TITLE
Having issues with porcupine in a Docker container using node.js wrapper(pv_porcupine)

### ISSUE THREAD

**Issue by ashtonfernandes** [Picovoice/Porcupine#141]
### Expected behavior
Should build with no issues within docker container

### Actual behavior
[ERROR] loading parameter file failed with ‘IO_ERROR’

While building the docker container (Linux environment),  we are experiencing issues. We are getting the error above. If we use a mac keyword, it does detect the wrong file system, so we know that the detection part is working, but if we use the Linux keyword, we get the IO_ERROR. We are using the pv_porcupine wrapper for node.js. Is there anything we can try to help resolve this issue?

Thank you!

**Comment by kenarsa** [comment]
the IO_ERROR means that the path does not exist, is incorrect, or the file is damaged.

Where is the wrapper? Can you provide a link?

**Comment by ashtonfernandes** [comment]
I've been using this wrapper: https://github.com/alexmoon/pv-porcupine
The thing is locally this works but on docker it fails

**Comment by kenarsa** [comment]
Thanks for the info. You should ask for help from the authors of the repository you mentioned. Unfortunately, I cannot help with this as I haven't developed that project. Closing for now. If you find problems with modules maintained in this repo please open another issue. thanks.
