### ISSUE TITLE
Quickstart guide

### ISSUE THREAD

**Issue by Nixellion** [Picovoice/Porcupine#143]
I'm currently researching Porcupine to use with my voice assistant on RPI Zero W.

And after about an hour of reading I can't find any form of quickstart guide anywhere. How do I start? Do I just `git clone` the repo and then `python demo/python/porcupine_demo.py --keyword_file_paths resources/keyword_files/alexa_${SYSTEM}.ppn`? I have a feeling that it won't just work like that, at least because `from porcupine import Porcupine` code that I can see in porcupine_demo.py suggests that Python knows exactly where to look for the binding, but nowhere does it tell how to set it up and whether I should set it up.

It does look like it generates a path and adds it to sys.path, but I had to read the code to see that.

It would be really nice if there was a Quickstart section or something similar in "Running the demo" parts that would say something like:

> To run this test you can do the following:
```
cd /opt/
git clone <repo link>
cd /path/
pip install -r requirements.txt
python <command>
```

And whatever other commands are required to get it running without errors and without spending time on reading code and looking through folders. For devs knowing how this works it should only take a couple minutes to write this, but for other people who want to start using Porcupine it may take much more time to reverse-engineer\research it from the other end.

Thanks

**Comment by kenarsa** [comment]
Thanks for the note. I agree. If you can turn your learning into a quick start guide the community will really appreciate it :-) If you decide to do it on GitHub happy to merge in your PR. If you decide to blog about it somewhere else happy to add a link to the repo. Thanks for your contribution.
