### ISSUE TITLE
How to create PPN files for Android?

### ISSUE THREAD

**Issue by oth-libs** [Picovoice/Porcupine#145]
Is there a way to create new keywords for Android? the pv_porcupine_optimizer only allows to create desktop keywords. and if I run a mac generated file I get the error

 I/PORCUPINE: [ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'

Can anyone help? thanks!

**Comment by kenarsa** [comment]
https://github.com/Picovoice/Porcupine/tree/master/tools/optimizer#how-do-i-create-keyword-files-for-platforms-other-than-linuxmacwindows

**Comment by yapro** [comment]
broken link

**Comment by ankitamygit** [comment]
> https://github.com/Picovoice/Porcupine/tree/master/tools/optimizer#how-do-i-create-keyword-files-for-platforms-other-than-linuxmacwindows

This link is not working
Is there  any other way to create keyword files for android

**Comment by dbartle** [comment]
Porcupine keyword models are trained with Picovoice Console (https://picovoice.ai/console/).

Access to the Android platform requires a development license and enterprise console account.
