### ISSUE TITLE
wake word/phrase length limitation

### ISSUE THREAD

**Issue by rose-jinyang** [Picovoice/Porcupine#148]
Nice work !  Thanks for your sharing.  But sometimes I see an error message "wake phrase is too short or long."  For example when the wake word phrase is "congratulation".  I want to know about the wake word/phrase length limitation.﻿

**Comment by kenarsa** [comment]
Thank you. The last FAQ can provide further information:

https://github.com/Picovoice/Porcupine/tree/master/tools/optimizer
