### ISSUE TITLE
older ppn not working after wasm update

### ISSUE THREAD

**Issue by ashubham** [Picovoice/Porcupine#150]
### Expected behavior
I got a licensed PPN which I used xxd to convert to hexadecimal array for use in the JS wasm flavor of porcupine. It used to work, up until recently when it started to break with the error `"failed to initialize porcupine."`

I see that even on the demo code for JS the byte arrays have changed for the same wake word. Do I need a new PPN file ? Or there is some other postprocess required on the existing ppn ? It will be great if I could get the hexadecimal equivalent of the PPN we recieved.

**Comment by kenarsa** [comment]
If you have a licensed file please contact us directly via email. Most probably you had an evaluation licensed that has expired.
