### ISSUE TITLE
Can't figure out how to properly install it

### ISSUE THREAD

**Issue by TheIronNinja** [Picovoice/Porcupine#153]
I'd expect that by doing pip install porcupine on my terminal I'd install this library as any other library; however it doesn't find the repo, and installing it manually doesn't seem to be a direct way of doing it since it looks like it might need some kind of configuration which isn't specified anywhere either. I can't find any instructions anywhere on the entire internet about this, so maybe someone could help me out with this and I might write a short guide to include on the readme file. In other issues you've linked to the Integration section of the readme, but that assumes you already have it installed.

**Comment by kenarsa** [comment]
we don't have pip support. good item to add for future though. if you clone the repo you should be able to use the python demos right away. if you want just the python binding you can strip other parts. happy to merge a PR for how to do this if you decide to document it.
