### ISSUE TITLE
Clarification of usage of the license restrictions of the default wake words

### ISSUE THREAD

**Issue by dsteinman** [Picovoice/Porcupine#154]
Hi, I have created a fork of this project, simplifying the JavaScript demo a bit and including some of the additional default wake-words.  I'd like to know if my usage in this manner is still within the restrictions of the Apache 2 license, and whether you have any objections to this.

My project is published here but not yet in NPM:

https://github.com/dsteinman/bumblebee-hotword

I didn't generate any new keywords, I took the existing words in this directory, converted them to binary using xxd and included them into the package:

https://github.com/Picovoice/Porcupine/tree/master/resources/keyword_files

Thanks, and great project btw.

**Comment by kenarsa** [comment]
Thanks for doing this! I don't see any legal conflicts.
