### ISSUE TITLE
Which platform to opt while creating a keyword to use WWD in website

### ISSUE THREAD

**Issue by iamporus** [Picovoice/Porcupine#155]
I am trying to use porcupine WWD in my website. For that, I'm using the JS binding. I created a new keyword for the linux/x86_64 platform using the optimizer tool and generated the uint8 array to be used in the voiceControlDemo.js file.

When I open the demo/js/voice_controller_demo.html in firefox, and click on Start Demo, I see an error in the debugger console :

`keyword file has incorrect format or belongs to a different platform`

Please suggest me which platform should I select while creating the keyword, if I intend to use it in my website.

Thanks.

**Comment by mehrdadfeller** [comment]
Wake words model file generated for Linux platform won't work for WebAssembly. You can use any of the wake word model files made available here:

https://github.com/Picovoice/Porcupine/tree/master/resources/keyword_files/wasm

There's a fee for generating custom wake word model files for WebAssembly. You have to contact Picovoice for pricing details and their license terms.
