### ISSUE TITLE
Can we train Porcupine to detect phrases spoken by specific person?

### ISSUE THREAD

**Issue by sam0829** [Picovoice/Porcupine#158]
Hello, Sorry if this question has been asked previously or mentioned somewhere. I am making an Android app where I need to detect that hot phrase is spoken by specific person or not who initially setup my app with his/her voice. Is this supported by this library by default or any other way like to train the library to achieve my goal?

**Comment by kenarsa** [comment]
we don't have a personal wake-word feature. whats your use case?

**Comment by sam0829** [comment]
I need to do certain actions on Android device by user's voice like wifi toggling etc and for this, as per the app's scope, it is required to make sure that the hot phrase for activation is spoken by the same person. Is there anything I can do additionally to implement this feature with Porcupine? Like dynamically creating the required hot phrase, language model etc? Please excuse me if I am using wrong terms as currently this concept is too broad for me and I am getting into it slowly.

**Comment by kenarsa** [comment]
got it. we don't have speaker id feature at the moment, unfortunately.
