### ISSUE TITLE
Performance of Web assembly wake word detection on Raspberry Pi

### ISSUE THREAD

**Issue by iamporus** [Picovoice/Porcupine#159]
I have a use case where I need to use the WWD engine inside chromium-browser (wasm) running on Raspberry Pi 3B. The detection fails several times (5 out of 10) despite increasing the sensitivity to max i.e. 1. However, when tested on Chrome on a Linux machine, the detection is quite impressive and works 9/10 times. Has anyone here has similar observations? 
FWIW I'm using a moderate quality USB PnP microphone with Raspberry Pi and using built-in ones for the Linux machine.

**Comment by kenarsa** [comment]
I think the microphone could be it. but the other thing is that it could be that the wake-word cannot run fast enough and is dropping frames. there are two features that I think are really useful for WASM binding:

1- offload the processing to background thread using worklets, etc.
2- Adding capability to record audio in the browser and then dump into a file that can be saved. 

(2) will help you debug your issue. if you do any please submit a PR and I will look into it.

**Comment by iamporus** [comment]
I'll start with the 2nd suggestion and get back to you. 
Thank you for such a quick response.

**Comment by iamporus** [comment]
Indeed it was the issue of frame drops. I ran multiple tests on the microphone and it's evident that its also affecting the quality of detection. I am tempted to check out the performance on a good quality microphone yet to arrive and still in transit. Meanwhile, I'm looking at AudioWorklets to offload the processing inside picovoiceAudioManager.js. I am kind of stuck at invoking a callback from AudioWorkletProcessor towards Picovoice engine. The documentation on AudioWorklet at this stage seems pretty immature.
@kenarsa, let me know if you have any pointers on the same.

**Comment by kenarsa** [comment]
Good finds. How did you verify that it is dropping frames? Just curious ...
I think your best bet is to find a working example of AudioWorkletProcessor and then use that. I have not spent time on this yet so your knowledge could be more than mine. Let me know how it goes.

**Comment by iamporus** [comment]
I thought of going with your suggestion and recording audio from the browser and analyzing the recordings but it seemed a lot of efforts. We suspected the reason being frame drops, which is, in fact, the result of processing happening on the main thread. I took a hint from that and increased the processing even more by adding dummy code. This made the detection even worse. Hence the conclusion.
Thanks. I'll keep you posted on the progress on the worklets.

**Comment by kenarsa** [comment]
any progress?

**Comment by iamporus** [comment]
I'm afraid I don't have much to share. I'm stuck at a point where documentation and the existing samples on AudioWorklet are failing short to provide what I need to work with. You may want to go ahead and close the issue for now as I've kept the task in my backlog and certainly not be revisiting in a couple of weeks.
