### ISSUE TITLE
static library version for windows

### ISSUE THREAD

**Issue by wolfviking0** [Picovoice/Porcupine#160]
I need to use porcupine on windows, but I am not using mingw.
I would like to use porcupine has a static library on my project but I cannot use the .a
I know it possible to recreate .lib using the dll but I would like just a static .lib in order to avoid be dependent of the dll.
I am currently using porcupine on other platforms without any issue only windows give me headache.

Thanks

**Comment by kenarsa** [comment]
Just a heads up that starting from v1.6 we won't provide static libs anymore and provide shared lib/dll.
