### ISSUE TITLE
ARM Cortex-M Support

### ISSUE THREAD

**Issue by Karveo** [Picovoice/Porcupine#162]
Hi there!

"Support for various ARM Cortex-A/M processors and a growing number of DSPs is available."

It says that it has support for some Cortex-M. Is there any support for it? Since i am developing a prototype on Cortex-M7 for my engineering degree. I found only support for Cortex-A on your GitHub project.

I want to know if there is any available source code for the project, since there are only librairies for the platforms supported.

Thanks in advance!

**Comment by kenarsa** [comment]
cortex-m/DSP support is only available for commercial customers. will add that to the readme for the next release. you might want to look into this from arm https://arxiv.org/abs/1711.07128

**Comment by kenarsa** [comment]
Now, this is supported. Check out the readme for more info!
