### ISSUE TITLE
Is this possible to to train model to detect multiple wake words?

### ISSUE THREAD

**Issue by sainimohit23** [Picovoice/Porcupine#164]
I am actually working on an application where I want to detect and classify Orca calls from acoustic data. Since there are different type of orca calls. Can Porcupine be trained to detect all different type of calls?

**Comment by udaykrishna** [comment]
I think it is possible to detect multiple multiple wake words but am not sure about detecting Ocra calls though.
Take a look at this demo, it shows how to detect multiple triggers https://youtu.be/YQQ5Bq5HqpQ

**Comment by sainimohit23** [comment]
@udaykrishna I haven't tried Porcupine yet. But, can you tell me if it is possible to know the structure of the model used by porcupine? Also, I just read your bio. Can you suggest me some good resources from where I can learn to build good chatbots?

**Comment by udaykrishna** [comment]
I just started evaluating porcupine, and am not sure if one can find out the structure of the model, In theory, one could try to reverse engineer the optimizer and see how a model is trained but it won't be an easy task, plus I don't think that's allowed under the current licence. I think its better if we wait for one of the maintainers to comment on this. 

Also, let's keep this thread specific to this issue. If you need anything else, send me a DM I'll be more than happy to help.

**Comment by kenarsa** [comment]
closing the issue due to inactivity
