### ISSUE TITLE
Precompiled lib for nvidia jetson nano

### ISSUE THREAD

**Issue by KittyMac** [Picovoice/Porcupine#166]
I am trying to run porcupine on an nvidia jetson nano (arm linux), but none of the precompiled libraries will link.  I tried armlinux/a9-neon and all of the pis.

**Comment by kenarsa** [comment]
we don't support jetson currently. is this a commercial application?

**Comment by KittyMac** [comment]
it is not... yet.  I will close the ticket and look elsewhere, thanks.
