### ISSUE TITLE
[C#] recogniton on word Porcupine got worse in release 1.6

### ISSUE THREAD

**Issue by xvlcekp** [Picovoice/Porcupine#169]
Hi, I updated following files: **libpv_porcupine.dll, porcupine_params.pv and porcupine_windows.ppn** with updated ones (1.5 -> 1.6), but recognition got really worse. I compared 2 programs in both versions running at the same time side by side, but the older one recoginzes much better. 

Do you have any idea why? Can you compare it? 
Thank you very much

**Comment by kenarsa** [comment]
we have not observed such an issue. try to adjust the sensitivity. I think c# binding should work but this is a community supported binding and it is best if you reach to the author directly.

**Comment by xvlcekp** [comment]
Hi, thank you for your answer. 

Today I tried the comparission with Python. In version 1.6 it looks like the recognition doesnt work at all (10x worse). Well it recognizes sometimes, but very rarely. Here is my video: On the left side is version 1.6, right side 1.5:
[https://streamable.com/nzlyg](https://streamable.com/nzlyg)

I also tried with another keywords and changing the sensitivity, but always with worse results.
Seconds, what is the cost of one-time NRE fee?

Thanks

**Comment by kenarsa** [comment]
thanks. can you record this using the record flag in the demo and share the WAV file somewhere we can download it? then we can look into it.

**Comment by xvlcekp** [comment]
Hi,

I tried today the same scenario as the last time. It began to recognizing some-how. (Maybe restart of computer helped.) But still the older version(both picrues on the right side) recognized it better by setting the same sensitivity. Maybe this is because my bad pronunciation.
![image](https://user-images.githubusercontent.com/22497922/56868524-b1a71f80-69f3-11e9-898a-39c6b19439f9.png)
Second attempt also with recording:
![image](https://user-images.githubusercontent.com/22497922/56868586-9c7ec080-69f4-11e9-8c69-a9727a110857.png)

This is the record of second sreenshot(output from 1.6) WAV file is in zip, because WAV format is not supported as attachment.
[test.zip](https://github.com/Picovoice/Porcupine/files/3125348/test.zip)

**Comment by kenarsa** [comment]
the audio you've sent is cut after 4K in the frequency domain. something is off with your microphone that's why probably or at least one reason. hope it helps.

**Comment by DrewDaPilot** [comment]
Hello, I just wanted to comment on this myself. The recognition does not appear to function at all. Here is the code I have used to test (using DSharpPlus as a discord bot). Passing a phrase that is in the audio clip many many times (example, "bot"), yields "0 results".

`        [Command("test")]
        public async Task test(CommandContext ctx, string phrase)
        {
            List<string> paths = new List<string>();
            List<float> senses = new List<float>();


            paths.Add($"porcupine_windows.ppn");

            senses = new List<float>();
            for (int i = 0; i < paths.Count; i++)
            {
                senses.Add(0.01f);
            }

            Porcupine p = new Porcupine("porcupine_params.pv", keywordFilePaths: paths, sensitivities: senses);
            WAVFile file = new WAVFile();
            file.Open("jeff.wav", WAVFile.WAVFileMode.READ);
            file.Close();
            List<short> data = new List<short>();
            while (file.NumSamplesRemaining > 0)
            {
                data.Add(BitConverter.ToInt16(file.GetNextSample_ByteArray()));
            }
            int framecount = (int)Math.Floor((decimal)(data.Count / p.FrameLength()));
            int results = 0;
            for (int i = 0; i < framecount; i++)
            {
                int start = i * p.FrameLength();
                int count = p.FrameLength();
                List<short> frame = data.GetRange(start, count);
                PicoVoiceStatus status = p.Process(frame.ToArray(), out bool result);
                if (result)
                    results += 1; 
                if (status != PicoVoiceStatus.SUCCESS)
                {
                    Console.WriteLine(status.ToString());
                }
            }
            await ctx.RespondAsync($"Analysis Complete. {results} results found!");

        }`

**Comment by kenarsa** [comment]
close due to inactivity
