### ISSUE TITLE
Using Porcupine in Java on Windows

### ISSUE THREAD

**Issue by BubbleEgg** [Picovoice/Porcupine#173]
### Expected behavior
I want to use Porcupine in a Java project using JNA and C. I want to compile the files to a dll.
### Actual behavior
I get an error when compiling (using the command below):

c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:\Users\Lzoch\AppData\Local\Temp\ccZxhNhj.o:porcupine.c:(.text+0x63): undefined reference to pv_porcupine_init
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:\Users\Lzoch\AppData\Local\Temp\ccZxhNhj.o:porcupine.c:(.text+0xdb): undefined reference to pv_porcupine_delete
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:\Users\Lzoch\AppData\Local\Temp\ccZxhNhj.o:porcupine.c:(.text+0xf4): undefined reference to pv_porcupine_frame_length
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:\Users\Lzoch\AppData\Local\Temp\ccZxhNhj.o:porcupine.c:(.text+0x104): undefined reference to pv_sample_rate
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:\Users\Lzoch\AppData\Local\Temp\ccZxhNhj.o:porcupine.c:(.text+0x15e): undefined reference to pv_porcupine_process
collect2.exe: error: ld returned 1 exit status

#### I am using:

OS: Windows 10 64-bit
Compiler: MingW
Java; java version "1.8.0_191" 64-Bit

#### In my folder:

> header [Folder]
> - picovoice.h
> - pv_porcupine.h
> - wake_porcupine_Porcupine.h
> 
> src [Folder]
> - c [Folder]
>   - porcupine.c
> - java [Folder]
>   - wakeup [Folder]
>     - porcupine [Folder]
>       - Porcupine.java
> 
> libpv_porcupine.a

#### File info's:
libpv_porcupine.a: from Porcupine-master\lib\windows\amd64
picovoice.h: from Porcupine-master\include
pv_porcupine.h: from Porcupine-master\include

#### Commands:

In the folder I am running the following commands using MingW in windows cmd:

To make the "wake_porcupine_Porcupine.h" [WORKS]:
`javac -h header src/java/wakeup/porcupine/Porcupine.java`

To compile the dll file that I can use as a native lib in java [DONT WORKS]:
`gcc -shared -O3 libpv_porcupine.a -Iheader -I"C:\Program Files\Java\jdk1.8.0_191\include" -I"C:\Program Files\Java\jdk1.8.0_191\include\win32" src\c\porcupine.c -o libpv_porcupine.dll`

I took the C file and the gcc command from [Olical's clojure-wake-word-detection](https://github.com/Olical/clojure-wake-word-detection)

**Comment by kenarsa** [comment]
I am not sure what wrong but clearly the linker cannot find porcupine's API. Since you are using another repo's code maybe it is better to ask the author there. Another suggestion is to do the "Hello World" JNI this way and see if it works. Can you do that?

**Comment by BubbleEgg** [comment]
I compiled it on linux and now it works, but only on linux but thats ok for me.

**Comment by wdavies973** [comment]
@BubbleEgg I have JNI bindings working on Windows, are you still interested?
