### ISSUE TITLE
[Python] Outdated script `test_porcupine.py`

### ISSUE THREAD

**Issue by csukuangfj** [Picovoice/Porcupine#174]
### Expected behavior
The test should pass without any modification

### Actual behavior

Python test fails when running

```
python binding/python/test_porcupine.py
```

The test files listed in
https://github.com/Picovoice/Porcupine/blob/f1ee41acb5fd6ebf38827a620625b9d0cec9b41d/binding/python/test_porcupine.py#L52-L56

do not match the files in https://github.com/Picovoice/Porcupine/tree/master/resources/keyword_files/mac

For instance, there is no `resources/keyword_files/mac/avocado_mac.ppn` but it is
listed in the code.

This commit
https://github.com/Picovoice/Porcupine/commit/2b851bb0333d7b8435320c87a51b1d3972156176

deleted many keyword files but it did not update the test scripts.

### Steps to reproduce the behavior

Just run the above command.

@kenarsa

**Comment by kenarsa** [comment]
Thanks a lot for finding this. It should be resolved now. Please pull and run the test again. Reopen if it still persists.
