### ISSUE TITLE
General question 

### ISSUE THREAD

**Issue by aceisace** [Picovoice/Porcupine#178]
@kenarsa 
Hi, thank you very much for this awesome project. I'd very much like to get this up and working with my rpi zero w, but I wanted to ask some general questions first. I hope you don't mind me opening an issue for that purpose.

I did try to 'install' (clone) this project, but it failed twice (probably a network error). When I looked into the cause, I found out that my rpi was trying to download over 1,5GB of content when cloning. Is this normal?

Next, I wanted to ask you if it's possible to make a user-friendly installer. It's probably because I'm not an expert, but I think it's a little bit difficult to understand how to set this up and use it correctly. As an example of what I mean, you can take a look [here](https://github.com/aceisace/Inky-Calendar) (see file: 'Installer-with-debug.sh'). The advantage would be a faster installation, better set-up and ease-of-use.

If you are interested, I can help you create an installer (at least for the raspberry pi).

**Comment by kenarsa** [comment]
yes, we are aware of the size of the repo. we do have a long-term plan to fix it. I encourage any effort towards packaging pip, npm, maven. But it needs to work across platforms (RPI, Mac, Windows, etc) and also be part of repo so it is maintained. Let me think about this and figure out the best way to attack it.

**Comment by aceisace** [comment]
@kenarsa 
Thanks for your comment. It's good to hear you'll be working on the size of the repo soon.

You are right, the installer would work well with the Raspberry Pi but not on Mac & Windows. Unfortunately, I don't know how to create pip, npm or maven packages yet, but maybe someone else could help you with that.
