### ISSUE TITLE
Pronunciation cannot be found

### ISSUE THREAD

**Issue by EminAgassi** [Picovoice/Porcupine#182]
We get the following error when running 

tools\optimizer\windows\i686\pv_porcupine_optimizer -r resources/ -w serner -p windows -o .

[ERROR] Could not find the pronunciation for 'serner'.

this is using the version 1.5.

**Comment by kenarsa** [comment]
https://github.com/Picovoice/Porcupine/tree/master/tools/optimizer#how-do-i-deal-with-error-could-not-find-the-pronunciation-of-xxx

since v1.6 we only provide out-of-dictionary keywords for commercial customers.

**Comment by EminAgassi** [comment]
We cannot use 1.6
We would like to use 1.5 for now since it has the 32 bit support.
Can this word be available in the 1.5 version?

**Comment by yapro** [comment]
@kenarsa your link is broken

**Comment by yapro** [comment]
@EminAgassi You can find pv_porcupine_optimizer in https://github.com/Picovoice/porcupine/archive/85560f8b3f39543198dc666ed95542fc32d3df74.zip

**Comment by mehrdadfeller** [comment]
@EminAgassi we do provide 32-bit support for version 1.6 for commercial customers if this is for a commercial application
