### ISSUE TITLE
sometimes it freezes and does not response of hot word three or four times we speak. random behavior

### ISSUE THREAD

**Issue by sushilkumar2007** [Picovoice/Porcupine#185]
### Expected behavior
Its need to trigger on hot word listnen

### Actual behavior
sleeps somtimes even we try speak hot word four to five times. 

### Steps to reproduce the behavior

Launch Demo app , try hey pico 10 times you will find that it miss detection 3-4  times

Please include enough details so that the issue can reproduced independently by the resolver.

**Comment by kenarsa** [comment]
unfortunately cannot reproduce the issue.
