### ISSUE TITLE
the power consumption on android phone

### ISSUE THREAD

**Issue by Fisummer** [Picovoice/Porcupine#187]
may i know what's the power consumption running on the android devices ?
does it work on sleep mode or it will keep the device from sleep to keep the always on listening service

**Comment by mehrdadfeller** [comment]
Porcupine requires a very small amount of processing power. For more details on performance metrics, please take a look at run-time metrics here published on the benchmark page [here](https://github.com/Picovoice/wakeword-benchmark#runtime). Basically, on Raspberry Pi 3, it uses less than 5% of the CPU cycles on one single core. Depending on the processors and model of the Android phone, the actual power consumption may vary. You can test this out on your target Android phone by running the [Android demo app](https://github.com/Picovoice/Porcupine#android-demo-application) and monitoring the battery usage.
