### ISSUE TITLE
Use porcupine on tinker board

### ISSUE THREAD

**Issue by wolfviking0** [Picovoice/Porcupine#188]
Hi,
I am currently moving from RPI3 to TinkerBoard. I am not sure which version of porcupine I should use.
TinkerBoard CPU is a Cortex A17 Quad Core @ 1.8GHz.
Do you think I could use the RPI3 library ?
Thanks

**Comment by kenarsa** [comment]
I'm not sure if you can use any of the available versions as we compiler for specific ARM cores to get performance. That being said you might want to try RPI0 as it is ARMv6 and can possibly run on your board. Keep in mind that it will run much slower ...

**Comment by wolfviking0** [comment]
I will try and let you know my result.

Do you plan to add the support of TinkerBoard, it could be really useful ?

Also RPI4 it's released and the performance should be really interesting, having porcupine ready for it will be really nice.

Thanks

**Comment by kenarsa** [comment]
thanks. RPi4 support will be added soon. TinkerBoard is unlikely without a commercial customer.

**Comment by wolfviking0** [comment]
@kenarsa I forgot to keep you updated, so far it seems the version RPI3 of porcupine (Cortex53) work fine on TinkerBoard.
At least I am able to trigger some keyword.
