### ISSUE TITLE
the role of optimizer_data  in resource

### ISSUE THREAD

**Issue by zhanglaplace** [Picovoice/Porcupine#193]
Thank for your very nice keyword spotting engine..
i have try to clone the repo several times but al failed. i find the repo includes 3.7G in .git and 800M in resource/optimize_data,but i don't know what's  role of optimizer_data  in resource. thanks

**Comment by kenarsa** [comment]
thanks for the feedback. we are aware of this and working to come up with a better solution. data is needed by the optimizer tool. we probably retire optimizer tool and move it to a web-based portal. at that point, the size of the repo will be much smaller.
