### ISSUE TITLE
Custom wake-words and open source projects

### ISSUE THREAD

**Issue by tadly** [Picovoice/Porcupine#196]
Porcupine seems to be more targeted towards companies than open source projects and I was curious if there are going to be ways for open source projects to acquire custom wake-words for all (in my case specifically raspberry) platforms.

Given that the only way of acquiring such wake-words currently is through the "Contact Enterprise Team"-Form I assume those don't come cheap.

**Comment by kenarsa** [comment]
The license section clearly states what is available to open-source. Please check here https://github.com/Picovoice/Porcupine#license

**Comment by tadly** [comment]
Not really... It says:
> ...for **non-commercial** and **evaluation purposes**.

As such I was hopeful buuut I get the message...

**Comment by hyansuper** [comment]
What happens when personal custom keyword model expires? Is it still usable after 30 days non-commercially?
