### ISSUE TITLE
Wrong Architecture for watchos libpv_porcupine.a

### ISSUE THREAD

**Issue by shaneboyar** [Picovoice/porcupine#198]
### Expected behavior
Watch App with embedded library builds correctly.

### Actual behavior
App fails to build citing `... libpv_porcupine.a, file was built for archive which is not the architecture being linked (arm64_32)`

This causes there to be undefined symbols in the Porcupine Manager file.

Checking with `lipo` shows `libpv_porcupine.a is architecture: i386` which I believe is for Macs.

### Steps to reproduce the behavior
Check library file with `lipo` or try to build onto an actual apple watch device.

**Comment by kenarsa** [comment]
The lib is a fat library (i.e. contains code both to run on watch and also simulator). we will look into this and get back to you in a few days.

**Comment by kenarsa** [comment]
I believe the latest commit should resolve this. please check and reopen if needed.
