### ISSUE TITLE
Want to create a constantly listening background service for the wake word. (Android)

### ISSUE THREAD

**Issue by ahsansuhail** [Picovoice/Porcupine#20]
Hi, 

Can I initialise and use porcupine in a background service that listens for the wake word continuously?

**Comment by ahsansuhail** [comment]
Thanks I'll give it a try and get back.

**Comment by kenarsa** [comment]
Thanks. Let us know how it goes and if you feel like helping out the community feel free to add a demo to show others how to do it. We will really appreciate it :)
