### ISSUE TITLE
Porcupine cloning failed 

### ISSUE THREAD

**Issue by sophjoe** [Picovoice/Porcupine#201]
### Cloning into 'Porcupine'...
remote: Enumerating objects: 150, done.
remote: Counting objects: 100% (150/150), done.
remote: Compressing objects: 100% (112/112), done.
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by kenarsa** [comment]
this seems like an issue you can bring up with Github. if you cant clone you can also download the latest release.
