### ISSUE TITLE
Training for custom keyword under Windows for Linux fails with "IO_ERROR"

### ISSUE THREAD

**Issue by derOlek** [Picovoice/Porcupine#202]
I want to train porcupine on my own keyword. Unfortunatly my Raspi 4 has not enough memory available to handle the whole 600mb of the repository and is not thus I decided to train the model on my main-pc. Whenever I execute the following command the optimizer stopts with the error "**[ERROR] keyword optimization failed with 'IO_ERROR'**".

The command I run the optimizer with is: `tools\optimizer\windows\amd64\pv_porcupine_optimizer.exe -r resources\ -w "jarvis" -p windows -o genWords\`
I created the folder genWords in my Porcupne-master directory. From this directory I executed the above script resulting in the stated error.

How can I fix this?

**Comment by kenarsa** [comment]
use:
-r resources\ optimizer_data\

**Comment by derOlek** [comment]
Problem persists with command `tools\optimizer\windows\amd64\pv_porcupine_optimizer.exe -r resources\optimizer-data -w "jarvis" -p windows -o genWords\`

**Comment by kenarsa** [comment]
make sure all directories exist and you have cloned correctly with no local changes

**Comment by mehrdadfeller** [comment]
@derOlek It is "optimizer_data" not "optimizer-data". Please first spend some time on your code before reaching out. GitHub issues are only not intended to solve integration issues or help people learn how to code.
