### ISSUE TITLE
Regarding Porcupine repository download

### ISSUE THREAD

**Issue by sophjoe** [Picovoice/Porcupine#204]
I have tried cloning the Porcupine repository and I couldn't clone it and I have raised an issue with you and you have advised me to raise it to github. I have raised this issue with github and I didn't hear from them. So tried the other alternative and downloaded the porcupine repository.
After downloading i have cd into the Porcupine-master folder
and tried to run the tools optimizer
 tools/optimizer/linux/x86_64/pv_porcupine_optimizer -r resources/ -p linux -o . -w "computer"
And i get error as cannot run binary file.
I am trying it in raspberry pi4
pls help me how to run the optimizer after downloading the repo.

As I am trying to incorporate  wake word detector to my project and if successful I would like to request access to licence. Pls help me as I want to try out it first and request access .

**Comment by mehrdadfeller** [comment]
Hundreds of people are cloning the repo from here on a daily basis. Have you ever considered this might be an issue with your computer or GitHub? Did you also bother reading the documentation? 

tools/optimizer/${SYSTEM}/${MACHINE}/pv_porcupine_optimizer -r resources/optimizer_data -w "vancouver" -p mac -o ~/

see this:
-r resources/optimizer_data

makes sense?

**Comment by yapro** [comment]
pv_porcupine_optimizer is gone?
