### ISSUE TITLE
Can I get a build for VS on windows?

### ISSUE THREAD

**Issue by lostinplace** [Picovoice/Porcupine#205]
hey there,

I'd really like to try your library in my windows x86_64 project

Is there a way I could get a build with the .lib and .dll files from msvc?

**Comment by mehrdadfeller** [comment]
What we have on GitHub is all we can offer to try under Apache 2.0 license. If you are working on a commercial project, feel free to fill out a request form on our website [here](https://picovoice.ai/contact), and we might be able to develop and offer these under our development license
