### ISSUE TITLE
Git clone failed multiple times on RPI with error: index-pack died of signal 9

### ISSUE THREAD

**Issue by schadha101** [Picovoice/porcupine#208]
root@slanchor:/anchorrw/vg# git clone https://github.com/Picovoice/Porcupine.git
Cloning into 'Porcupine'...
remote: Enumerating objects: 3623, done.
remote: Total 3623 (delta 0), reused 0 (delta 0), pack-reused 3623
Receiving objects: 100% (3623/3623), 3.62 GiB | 5.18 MiB/s, done.
error: index-pack died of signal 9
fatal: index-pack failed

Same error, multiple times.

**Comment by kenarsa** [comment]
try again. if persists contact GitHub support.
