### ISSUE TITLE
C++ integration?

### ISSUE THREAD

**Issue by tatanpoker09** [Picovoice/Porcupine#21]
Hey, I wanted to use this in a c++ program, I can include the headers but have no idea how to link the dll.
I've tried to look how to link it using CMake for a couple of days now with no success.
I get 
`C:/Users/tatan/CLionProjects/TreeVoiceAssistant/HotwordDetection.cpp:27: undefined reference to `pv_porcupine_process(pv_porcupine_object*, short const*, bool*)'`
every single time.
I'm using CLion as you can probably see, with MINGW and I can sucessfuly include the headers, but dlls just won't.

Please help

**Comment by kenarsa** [comment]
Can you share your CMake? Also, why not statistically link the library?

**Comment by tatanpoker09** [comment]
I'm sorry, just getting started with c++, I come from a c# background where I have never had to use this kind of linking.
```cmake_minimum_required(VERSION 3.10)
project(TreeVoiceAssistant)

set(CMAKE_CXX_STANDARD 11)
INCLUDE_DIRECTORIES("${CMAKE_CURRENT_BINARY_DIR}")
include_directories("include")
add_executable(TreeVoiceAssistant main.cpp HotwordDetection.cpp HotwordDetection.h)
```


will throw a 
```
C:/Users/tatan/CLionProjects/TreeVoiceAssistant/HotwordDetection.cpp:27: 
undefined reference to `pv_porcupine_process(pv_porcupine_object*, short const*, bool*)'
```
while adding a `
target_link_libraries("lib/libpv_porcupine.dll")`

will throw a ` Cannot specify link libraries for target "lib/libpv_porcupine.dll" which is
  not built by this project.`

Thanks for the help.

**Comment by kenarsa** [comment]
Could you add this target_link_libraries("lib/libpv_porcupine.a") instead of .dll?

**Comment by tatanpoker09** [comment]
New CMake:
```
cmake_minimum_required(VERSION 3.10)
project(TreeVoiceAssistant)

set(CMAKE_CXX_STANDARD 11)
INCLUDE_DIRECTORIES("${CMAKE_CURRENT_BINARY_DIR}")
include_directories("include")
target_link_libraries("lib/libpv_porcupine.a")
add_executable(TreeVoiceAssistant main.cpp HotwordDetection.cpp HotwordDetection.h)
```

Throws: 
```
CMake Error at CMakeLists.txt:7 (target_link_libraries):
-- Configuring incomplete, errors occurred!
  Cannot specify link libraries for target "lib/libpv_porcupine.a" which is
  not built by this project.
See also "C:/Users/tatan/CLionProjects/TreeVoiceAssistant/cmake-build-debug/CMakeFiles/CMakeOutput.log".


mingw32-make.exe: *** [Makefile:205: cmake_check_build_system] Error 1
```
Is there any more information you might need?

**Comment by tatanpoker09** [comment]
I just added it after the add_executable as:
```
cmake_minimum_required(VERSION 3.10)
project(TreeVoiceAssistant)

set(CMAKE_CXX_STANDARD 11)
INCLUDE_DIRECTORIES("${CMAKE_CURRENT_BINARY_DIR}")
include_directories("include")
include_directories("lib")
add_executable(TreeVoiceAssistant main.cpp HotwordDetection.cpp HotwordDetection.h)
target_link_libraries(TreeVoiceAssistant "lib/libpv_porcupine.a")
```
And now the cmake compiles, I'm getting another error though:

```
D:/MINGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llib/libpv_porcupine.dll
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[3]: *** [CMakeFiles\TreeVoiceAssistant.dir\build.make:124: TreeVoiceAssistant.exe] Error 1
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:67: CMakeFiles/TreeVoiceAssistant.dir/all] Error 2
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:79: CMakeFiles/TreeVoiceAssistant.dir/rule] Error 2
mingw32-make.exe: *** [Makefile:117: TreeVoiceAssistant] Error 2
```

**Comment by tatanpoker09** [comment]
Rewrote my CMake into this:
```
cmake_minimum_required(VERSION 3.10)
project(TreeVoiceAssistant)

set(CMAKE_CXX_STANDARD 11)
INCLUDE_DIRECTORIES("${CMAKE_CURRENT_BINARY_DIR}")
include_directories("include")
include_directories("lib")
add_executable(TreeVoiceAssistant main.cpp HotwordDetection.cpp HotwordDetection.h)
target_link_libraries(TreeVoiceAssistant ${CMAKE_SOURCE_DIR}/libpv_porcupine.a)
```
Now I'm getting a different error, hopefully that means progress?
```
mingw32-make.exe[3]: *** No rule to make target '../libpv_porcupine.a', needed by 'TreeVoiceAssistant.exe'.  Stop.
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:67: CMakeFiles/TreeVoiceAssistant.dir/all] Error 2
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:79: CMakeFiles/TreeVoiceAssistant.dir/rule] Error 2
mingw32-make.exe: *** [Makefile:117: TreeVoiceAssistant] Error 2
```

**Comment by amiranhari** [comment]
This probably just means make can't find the 'libpv_porcupine.a'. Where did you put the library? print the path in the CMake and make sure you are passing the correct path to make.

**Comment by tatanpoker09** [comment]
Ok it was in a different directory called lib. 
```
cmake_minimum_required(VERSION 3.10)
project(TreeVoiceAssistant)

set(CMAKE_CXX_STANDARD 11)
INCLUDE_DIRECTORIES("${CMAKE_CURRENT_BINARY_DIR}")
include_directories("include")
include_directories("lib")
add_executable(TreeVoiceAssistant main.cpp HotwordDetection.cpp HotwordDetection.h)
message(${CMAKE_SOURCE_DIR}/libpv_porcupine.a)
target_link_libraries(TreeVoiceAssistant ${CMAKE_SOURCE_DIR}/lib/libpv_porcupine.a)
```
But now we're back to the original error:

```
CMakeFiles\TreeVoiceAssistant.dir/objects.a(HotwordDetection.cpp.obj): In function `speech::HotwordDetection::startRecognition()':
C:/Users/tatan/CLionProjects/TreeVoiceAssistant/HotwordDetection.cpp:25: undefined reference to `speech::get_next_audio_frame()'
C:/Users/tatan/CLionProjects/TreeVoiceAssistant/HotwordDetection.cpp:27: undefined reference to `pv_porcupine_process(pv_porcupine_object*, short const*, bool*)'
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[3]: *** [CMakeFiles\TreeVoiceAssistant.dir\build.make:125: TreeVoiceAssistant.exe] Error 1
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:67: CMakeFiles/TreeVoiceAssistant.dir/all] Error 2
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:79: CMakeFiles/TreeVoiceAssistant.dir/rule] Error 2
mingw32-make.exe: *** [Makefile:117: TreeVoiceAssistant] Error 2

```

**Comment by kenarsa** [comment]
Please have a read here how to link a static C lib into a C++ program:

https://stackoverflow.com/questions/19063975/linking-c-compiled-static-library-to-c-program?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by tatanpoker09** [comment]
Thanks! Most of those worked, but now I'm having problems linking get_next_audio_frame(), I noticed those aren't defined in picovoice's headers... Where do they come from?

**Comment by kenarsa** [comment]
you need to implement that method yourself :)

**Comment by tatanpoker09** [comment]
Any references I can look at to implement it myself?

**Comment by kenarsa** [comment]
It really depends what you are doing. The function is supposed to give you a chunk of audio data. So it depends on the OS/API used.

**Comment by kenarsa** [comment]
In our python demo this one line does it https://github.com/Picovoice/Porcupine/blob/4b0f92116b5476b0df78bfe22dce3d66142a0e2c/demo/python/porcupine_demo.py#L104

**Comment by tatanpoker09** [comment]
I mainly want to have a continuous hotword detection on a linux machine, any suggestions where to start looking?

**Comment by veeableful** [comment]
@tatanpoker09
The way I do it is I buffer the audio data from microphone and process them with Porcupine once they are at least the size of Porcupine's frame length. The result should be continuous.

In my case, I use Qt so `mAudioDataBuffer` is a `QByteArray`.

Snippet:

```
// Check if we have enough bytes of audio data for Porcupine to work with
bool PorcupineWaker::hasEnoughSamples(int porcupineFrameLength) const
{
    // We use porcupineFrameLength * 2 because frame length type is int16_t while mAudioDataBuffer's type is byte
    return mAudioDataBuffer.size() >= porcupineFrameLength * 2;
}

// Go through the audio data and detect the wake word if there's any
void PorcupineWaker::processSamples(int porcupineFrameLength)
{
    while (hasEnoughSamples(porcupineFrameLength)) {
        const int16_t *audioData = reinterpret_cast<int16_t*>(mAudioDataBuffer.data());
        bool detected = false;

        pv_porcupine_process(mPorcupineObject, &audioData[0], &detected);
        if (detected) {
            // Detected keyword. Do something!
            emit awake();
        }

        // Remove the audio data that we have processed
        mAudioDataBuffer.remove(0, porcupineFrameLength * 2);
    }
}

// Listen to the microphone's audio data and look for the keyword
void PorcupineWaker::listen(const QByteArray &input)
{
    const int porcupineFrameLength = pv_porcupine_frame_length();

    mAudioDataBuffer.append(input);
    processSamples(porcupineFrameLength);
}
```

**Comment by dimeldo** [comment]
Hey @veeableful!

I'm using Qt too, could you help me with recording the audio from the mic, please?
You can contact me at: solobo11235 AT gmail DOT com
Thanks!

**Comment by veeableful** [comment]
Hi @dimeldo, sorry I didn't see this sooner! I've created a simple example that demonstrate the usage of microphone and Porcupine in Qt. You can see it [here](https://github.com/veeableful/QtPorcupineExample).

**Comment by dimeldo** [comment]
Thank you so much! It helped me a lot!
BTW, can you send me an email at solobo11235@gmail.com, I don't want to spam this thread.

**Comment by tatanpoker09** [comment]
Just spam it! It might help us all, even someone from the future coming to this thread

**Comment by kenarsa** [comment]
@veeableful  would be great if you can add a demo to our demo folder :) we are certainly lacking a c++ one.

**Comment by veeableful** [comment]
@dimeldo I'm glad you find it useful :grin:. Like @tatanpoker09 mentioned, I posted here just in case someone else find it useful. I emailed you the zipped version of the project regardless.

@kenarsa Definitely. I'll send you a PR later.

**Comment by kenarsa** [comment]
@veeableful  looking forward to it :)
