### ISSUE TITLE
Windows IOT Version

### ISSUE THREAD

**Issue by CobraCalle** [Picovoice/porcupine#211]
Hi,

I'working on a private project that will use Windows IOT on Raspberry Pi. Can you provide a version of the library that works on Windows on ARM?

Carl

**Comment by kenarsa** [comment]
no, unless we have a justifiable commercial reason.

**Comment by CobraCalle** [comment]
Thank you for the response. That is totally reasonable.

Would it be possible to provide a keyword file for "Computer"? Than I would try to use the wasm version on Windows IOT. 

Carl
