### ISSUE TITLE
Sample integrations of porcupine with cheetah/rhino?

### ISSUE THREAD

**Issue by ocdtrekkie** [Picovoice/porcupine#213]
What I'm looking to do *seems* super simple, but for some reason it isn't something often done or offered... a la carte. The fact that Picovoice clearly defines wake word functionality, speech-to-intent functionality, and speech-to-text functionality individually is appealing: I wrote my own assistant code already, I just don't understand the voice input side of it. What I am looking for is the wake word functionality, and the speech-to-text functionality, that "just" outputs the text input after the wake word.

It seems like samples of how you would start with Porcupine and then move into Cheetah or Rhino would be pretty commonly desirable for anyone interested in your libraries, whether commercial or community. While my interest in this is definitely for personal use, I honestly would wish for a way to chip in to see this sort of capability become reality for my project. (I mean, I'd like to use RasPis too, so I presume I might be looking at "commercial licensing" just for that capability anyways.)

**Comment by kenarsa** [comment]
Thank you for the feedback. There is an example of porcupine/rhino working together here:
https://github.com/Picovoice/rhino/blob/master/demo/python/rhino_demo.py

no example for porcupine/cheetah yet. but feel free to create one and submit a PR.

**Comment by Stolek007** [comment]
@kenarsa some actual examples, pls ?

**Comment by followkim** [comment]
fyi the link that was posted is broken.  Use:
https://github.com/Picovoice/rhino/blob/master/demo/python/rhino_demo_file.py
