### ISSUE TITLE
Using Porcupine and SpeachRecognition together fails with an error

### ISSUE THREAD

**Issue by gj1118** [Picovoice/porcupine#215]
I am trying to use `Porcupine` with [SpeechRecognition](https://pypi.org/project/SpeechRecognition/) library together.

Following is my use case:
I use Porcupine to wake app. Once the app is awake , I ask it do something. This input of commands via voice is being done via the SpeechRecognition library 

### Expected behaviour
Both of them should work together

### Actual behaviour
I am getting an error 
```||PaMacCore (AUHAL)|| Error on line 2490: err='-50', msg=Unknown Error
||PaMacCore (AUHAL)|| Error on line 2490: err='-50', msg=Unknown Error
```

### Steps to reproduce the behaviour

1. First I call the Porcupine library to wake my app. 
2. The app is awake 
3. Next I input my commands by speaking to my app. At this point it breaks. 

Can you please let me know what I should be doing in order to resolve this issue ? This could be happening because of `PyAudio` as both the packages are using it , although I am not sure. Is there a way I can pass the `PyAudio` instance from `Porcupine` to the `SpeechRecognition` library ?  

I am on a MAC 10.14.6 (I believe this is happening only on Mac, but I could be wrong)
Any help will be well appreciated. 
Thank you for your time and patience. 

With Regards, 
Gagan

**Comment by kenarsa** [comment]
We don't have any official support for the other library you are using and it seems that the error is happening there. you probably want to open an issue there. regardless if you need to feed audio to both engines you should manage the audio streaming yourself. you can do it within python binding of porcupine instead of using the demo app.
