### ISSUE TITLE
Don't know how to use the Porcupine

### ISSUE THREAD

**Issue by PedroPereiraa** [Picovoice/porcupine#216]
Hi, I'm sorry if the window "issues" isn't supposed to answer this type of questions but I didn't find any other place better than this one. So I want to implement a wake word in my code to work like  the "hey siri", but for my AI, but I'm really not understand on how im supposed to input the files on my code... I'm on windows right know because my linux was giving my a lot of errors on audio... Again sorry if this "community" isnt suppost to answer this type of questions

**Comment by dbartle** [comment]
The GitHub issues are just for reporting issues (i.e. bugs) with Porcupine. Check out the Porcupine demo examples to get started: https://github.com/Picovoice/porcupine/tree/master/demo/python
