### ISSUE TITLE
keyword file belongs to a different version of the library, pulled from Master today...

### ISSUE THREAD

**Issue by wjennings** [Picovoice/porcupine#218]
Building my app using C++, trying both the shared library
(using -L/home/wjennings/projects/alexa/porcupine//lib/linux/x86_64 -lpv_porcupine in my Makefile and ensuring LD_LIBRARY_PATH points to that folder)
 and the static lib (using /home/wjennings/projects/alexa/porcupine//lib/linux/x86_64/libpv_porcupine.a in my Makefile)
and using the keyword "/home/wjennings/projects/alexa/porcupine/resources/keyword_files/linux/alexa_linux.ppn"
(and the compressed version, just to check) always fails.

### Expected behaviour
The linux keyword file should belong to the linux library

### Actual behaviour
(DEBUG)16:04:38:618 [src/TAudioRecognize.cpp:PorcupineRecognizer(),365]: using modelpath /home/wjennings/projects/alexa/porcupine/lib/common/porcupine_params.pv and keyword /home/wjennings/projects/alexa/porcupine/resources/keyword_files/linux/alexa_linux.ppn
**[ERROR] keyword file belongs to a different version of the library
[ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'**
(ERROR)16:04:38:618 [src/TAudioRecognize.cpp:PorcupineRecognizer(),369]: Failed to initialize Porcupine
### Steps to reproduce the behaviour
compile and run, it happens on initialization

System: Linux ubuntu16 3.13.0-167-generic #217-Ubuntu SMP Wed Mar 13 16:18:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Compiler: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

**Comment by wjennings** [comment]
FYI, all the other *_linux.ppn files give an error, but usually just a generic "keyword file has incorrect format." error.  For example:

(DEBUG)09:26:56:116 [src/TAudioRecognize.cpp:PorcupineRecognizer(),365]: using modelpath /home/wjennings/projects/alexa/porcupine/lib/common/porcupine_params.pv and keyword /home/wjennings/projects/alexa/porcupine/resources/keyword_files/**linux/blueberry_linux.ppn**
[ERROR] keyword file has incorrect format.
[ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'

**Comment by kenarsa** [comment]
can't reproduce. tried all Linux files and they work. try cloning a fresh copy of the repo.

**Comment by wjennings** [comment]
Sure, I tried it again.  Here are the exact Steps I took:

wjennings@ubuntu16:~/projects/alexa$ rm -rf porcupine/
wjennings@ubuntu16:~/projects/alexa$ git clone https://github.com/Picovoice/porcupine.git
Cloning into 'porcupine'...
remote: Enumerating objects: 313, done.
remote: Counting objects: 100% (313/313), done.
remote: Compressing objects: 100% (158/158), done.
remote: Total 3649 (delta 140), reused 298 (delta 132), pack-reused 3336
Receiving objects: 100% (3649/3649), 19.01 MiB | 2.58 MiB/s, done.
Resolving deltas: 100% (695/695), done.

I'm calling the init function like this:
**pv_status_t status = pv_porcupine_init(modelPath.c_str(), keyWordPath.c_str(), 0.5, &PorcupineObject);**

Rebuilt my specific object file, with this flag: **-I/home/wjennings/projects/alexa/porcupine//include**
Rebuilt the application with this included: **/home/wjennings/projects/alexa/porcupine//lib/linux/x86_64/libpv_porcupine.a**

Re-ran my application using this keyword:
**/home/wjennings/projects/alexa/porcupine/resources/keyword_files/linux/alexa_linux.ppn**

Got the same error:
(DEBUG)11:29:56:665 [src/TAudioRecognize.cpp:PorcupineRecognizer(),365]: using modelpath /home/wjennings/projects/alexa/porcupine/lib/common/porcupine_params.pv and keyword /home/wjennings/projects/alexa/porcupine/resources/keyword_files/linux/alexa_linux.ppn
**_[ERROR] keyword file belongs to a different version of the library
[ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'_**

Something's different between our setups if you did the same steps I did and yours always works.

I can't evaluate this library for our company if I can't even get the basic stuff to work.

**Comment by kenarsa** [comment]
something is probably wrong with your build system. I suggest you use python demo for evaluation and then work backwards to get yours working.

**Comment by wjennings** [comment]
Failed from python as well:

**_wjennings@ubuntu16:~/projects/alexa/porcupine$ python3 binding/python/test_porcupine.py
[ERROR] keyword file has incorrect format.
[ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'
E[ERROR] keyword file belongs to a different version of the library
[ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'_**
E
======================================================================
ERROR: test_process (__main__.PorcupineTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "binding/python/test_porcupine.py", line 34, in test_process
    sensitivity=0.5)
  File "/home/wjennings/projects/alexa/porcupine/binding/python/porcupine.py", line 116, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]('Initialization failed')
ValueError: Initialization failed

======================================================================
ERROR: test_process_multiple (__main__.PorcupineTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "binding/python/test_porcupine.py", line 67, in test_process_multiple
    sensitivities=[0.5] * len(keyword_file_paths))
  File "/home/wjennings/projects/alexa/porcupine/binding/python/porcupine.py", line 116, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]('Initialization failed')
ValueError: Initialization failed

----------------------------------------------------------------------
Ran 2 tests in 0.017s

FAILED (errors=2)

I am doubtful something is wrong with my build system, I have built and ran avs-devie-sdk, google_assistant, pocketSphinx, multiple other packages, so I doubt it only fails with Porcupine because of my build system.

**Comment by EricAndrechek** [comment]
@wjennings Did you ever find a solution to this problem? I'm in the same boat as you with the most recent pull from master and it returning the same error.

**Comment by wjennings** [comment]
@EricAndrechek No, I never got it working, and I just gave up since I didn't get any support from the site.  Which is a shame, I work for a large company and we might have been interested in working with picovoice.

**Comment by EricAndrechek** [comment]
@wjennings That's a bummer, it seems like they're just trying to close their GitHub issues as fast as they can rather than actually helping people out. I spent about 5 hours yesterday rewriting the picovoice library, so it's now a mix of 1.7, 1.6, and 1.5 code all mixed together along with some other files I edited in their library and I actually got it to work! If you are interested I can share the files of my working code, but I only rewrote the code for mac not Linux or windows. The side benefit of rewriting all of it is I can generate as many voice models for trigger words as I want and they don't expire or anything now. Massive pain though and yeah it would be really nice if there was more help from them regarding issues rather than just closing everything and saying it works on their end.

**Comment by jyvern** [comment]
> @wjennings That's a bummer, it seems like they're just trying to close their GitHub issues as fast as they can rather than actually helping people out. I spent about 5 hours yesterday rewriting the picovoice library, so it's now a mix of 1.7, 1.6, and 1.5 code all mixed together along with some other files I edited in their library and I actually got it to work! If you are interested I can share the files of my working code, but I only rewrote the code for mac not Linux or windows. The side benefit of rewriting all of it is I can generate as many voice models for trigger words as I want and they don't expire or anything now. Massive pain though and yeah it would be really nice if there was more help from them regarding issues rather than just closing everything and saying it works on their end.

Hi, I'm interested in your work. May I got your developments ? Best regards.

**Comment by EricAndrechek** [comment]
@jyvern Sorry for the late reply! I will put my code together in a neater repository and then get back to you with it. It's been a while since I've worked on it so I will need to find it and confirm it still works...
