### ISSUE TITLE
Linux keywords don't work on raspberry pi

### ISSUE THREAD

**Issue by janniks** [Picovoice/porcupine#219]
Why do `linux` keyword files not work on raspberry pi debian buster linux?
Is it possible to translate a file from `linux` to `raspberry_pi` (currently the porcupine console does not support raspberry pi)

**Comment by kenarsa** [comment]
Linux is meant to run on x86_64 not arm which is what you have on rpi. the custom models for rpi are only available to commercial customers. more information is in the faq.
