### ISSUE TITLE
Failed to Archive

### ISSUE THREAD

**Issue by dyah10** [Picovoice/Porcupine#22]
### Expected behavior
Archive without failing. 

### Actual behavior
When we Archive the build (iOS demo), it fails with the following error:
`ld: bitcode bundle could not be generated because '/Users/userXXXX/Code/vivaa/native/Scribe/ios/Porcupine/watchos/libpv_porcupine.a(pv_porcupine.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7k`

### Steps to reproduce the behavior
1. Download Porcupine iOS Demo
2. Product > Archive
3. See error

Please include the operating system and CPU architecture. When applicable, provide relevant audio data.
Happens with iOS and watchOS demos.

**Comment by kenarsa** [comment]
Thanks for finding this. I am looking into it right now. I am going to provide an update soon.

**Comment by kenarsa** [comment]
I think this commit fixed the issue: 038ff2b8c988bb6411467f17d02fa82fc3aacd2a

Could you please give it a try?

**Comment by dyah10** [comment]
Looks like it fixed it. Thank you!
