### ISSUE TITLE
keyword file has incorrect format or belongs to a different platform ( we are using latest code and trying to run sample app )

### ISSUE THREAD

**Issue by sushilkumar2007** [Picovoice/porcupine#220]
ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] model file path: ai.picovoice.porcupine.demo/files/params.pv
ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] number of keywords: 1
ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] keyword file path [0]: ai.picovoice.porcupine.demo/files/hey_pico.ppn
ai.picovoice.porcupine.demo I/PICOVOICE:  [INFO] sensitivity [0]: 0.500000
ai.picovoice.porcupine.demo I/PICOVOICE: [ERROR] keyword file has incorrect format or belongs to a different platform
ai.picovoice.porcupine.demo I/PICOVOICE: [ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'

**Comment by devsda-root** [comment]
for me,I'm breaking my head over a Win 10 OS ... does it work  on Win 10

**Comment by devsda-root** [comment]
How do I integrate porcupine into my project on a Windows env using python as a language

**Comment by devsda-root** [comment]
the path structure is a Linux type OS.will changing '/ ' to ' \ ' work?

**Comment by devsda-root** [comment]
so finally after banging my head for several hours..I now got it. The whole time I was calling demo app from C:/ while I had 'junctioned' my python installation at D:/ . Hence no file found errors/IOerrors/OSerrors and whatnot.such a trivial thing!!!!!!!!! I can successfully detect my wake word now..Thank you Ali!!

**Comment by EyaMeddeb** [comment]
[ERROR] license file has incorrect format or belongs to a different platform
Hello ,
I have the same error , how can i fix it please

**Comment by dbartle** [comment]
This is not the same as the original issue posted above as it's a totally different product.

To run Leopard, you need to acquire a Leopard license file from Picovoice Console (https://console.picovoice.ai) and provide it as a command-line argument to Leopard. If there are problems with this, open a new issue under the appropriate repo: https://github.com/Picovoice/leopard
