### ISSUE TITLE
Documentation Required for Angular

### ISSUE THREAD

**Issue by Adityagrao** [Picovoice/porcupine#221]
I am trying to integrate the with Angular, I am not able to export PorcupineManager as an object when I have installed it as a package.

Also reading porcupine_worker.js and downsampling_worker.js from the JS files is inefficient as I am using TS with my Project

**Comment by kenarsa** [comment]
you can always to what you want on top of the low-level binding here: https://github.com/Picovoice/porcupine/tree/master/binding/js/porcupine

we don't have drop-in support for angular.

**Comment by suryakumar-sekar** [comment]
I am also facing same issue.

**Comment by dbartle** [comment]
As mentioned above we don't have drop in support for Angular (or React, or Vue...). The bindings do not care which library you use them with.
