### ISSUE TITLE
Missing compressed keywords for raspberrypi

### ISSUE THREAD

**Issue by dlsniper** [Picovoice/porcupine#223]
Hi,

First, thanks for allowing independent developers to test/work on personal projects for this.
Second, could you please add the compressed versions of the keywords under the resources?

Have a look at: https://github.com/Picovoice/porcupine/tree/1568862f68f8789c7acc99fd1c9126acf63ff825/resources/keyword_files/raspberrypi
versus: https://github.com/Picovoice/porcupine/tree/1568862f68f8789c7acc99fd1c9126acf63ff825/resources/keyword_files/windows.

They also seem to miss from `android`, `beaglebone`, `ios`, and `wasm`. As a reference, they used to be present in an early version of this, and while this won't make up for the time or effort on doing these, I would be grateful if you could do it.

Thank you!

**Comment by kenarsa** [comment]
You are welcome. The compressed models are only intended to be used on MCU/DSP. Hence we only provide then on Linux, Mac, and Windows only for performance evaluation. Why do you want to use them on an RPI?

**Comment by wibimaster** [comment]
Hmm, asking same thing, because the home README itself states:

> Below is the comparison of runtime measurements for different variants of Porcupine on Raspberry Pi3

It shows that compressed model is working "better" on RPI3, so the first desire is to try it on a RPI3 :)
