### ISSUE TITLE
Compatibility issues 

### ISSUE THREAD

**Issue by prashanthsridhar** [Picovoice/porcupine#225]
### Actual behaviour
![image](https://user-images.githubusercontent.com/11289456/67156298-46069500-f33a-11e9-842e-a70f115a390d.png)

### Steps to reproduce the behaviour
i have saved all the js files in an asset folder and integrated it into an angular project

**Comment by prashanthsridhar** [comment]
![image](https://user-images.githubusercontent.com/11289456/67180024-df46b180-f3f5-11e9-886a-a2fc7287aa90.png)

**Comment by kenarsa** [comment]
this clearly is not enough information for us to reproduce the issue, right?
Also, as mentioned before we do NOT have drop-in support for Angular. For commercial customers, we might be able to add such support via commercial engagement. Closing the issue.
