### ISSUE TITLE
Using demo on windows failed  with invalid dll file

### ISSUE THREAD

**Issue by akrewTik** [Picovoice/porcupine#227]
Hello,

I have an issue trying tu use porcupine on windows.
I cloned the repo, installed every libraries pyaudio, etc... but when running from demo or python test file. I get the following error :

listening for:
- alexa (sensitivity: 0.500000)
Traceback (most recent call last):
  File "demo/python/porcupine_demo.py", line 212, in <module>
    main()
  File "demo/python/porcupine_demo.py", line 208, in main
    input_device_index=args.input_audio_device_index).run()
  File "demo/python/porcupine_demo.py", line 102, in run
    sensitivities=self._sensitivities)
  File "demo/python\../../binding/python\porcupine.py", line 69, in __init__
    library = cdll.LoadLibrary(library_path)
  File "D:\Tools\python-3.7.4\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "D:\Tools\python-3.7.4\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 n’est pas une application Win32 valide

### Expected behaviour

Keyword Alexa detection without any error ?

### Actual behaviour
Invalid dll error (see above)

### Steps to reproduce the behaviour

I'm on Windows 10 64bits x64 technology.

Is it possible for me to build my own dll ?
 or are you able to give an adapted dll ?

Thanks for your help, keep the good work porcupine seems to be an amazing tool !

**Comment by kenarsa** [comment]
Is it possible for me to build my own dll ?

no, source code is private.

or are you able to give an adapted dll ?

it should work fine on windows. make sure your python is also 64bit.

**Comment by akrewTik** [comment]
Thanks for your reply !

In fact, i had a 32 bit version of python.

Resolved using 64bit, well done !
