### ISSUE TITLE
Unable to run wake up word

### ISSUE THREAD

**Issue by MarianaTS** [Picovoice/Porcupine#23]
### I used this tutorial https://youtu.be/3z7LBW_Rl9c. 

I have Ubuntu 16.04,  Intel Core i3 7th Gen. 
As a result of running service I got error.
Error log: 
Traceback (most recent call last):
  File "demo/python/porcupine_demo.py", line 207, in <module>
    input_device_index=args.input_audio_device_index).run()
  File "demo/python/porcupine_demo.py", line 92, in run
    sensitivities=[self._sensitivity] * num_keywords)
  File "demo/python/../../binding/python/porcupine.py", line 114, in __init__
    byref(self._handle))
  File "/home/scale/.local/lib/python2.7/site-packages/enum.py", line 199, in __init__
    raise EnumBadKeyError(key)
enum.EnumBadKeyError: Enumeration keys must be strings: 0

**Comment by kenarsa** [comment]
Whats the version of Python you are using?

Could you make sure you have the prerequisites mentioned here: https://github.com/Picovoice/Porcupine/tree/master/demo/python

**Comment by MarianaTS** [comment]
Python 2.7.12
I've installed all packages https://people.csail.mit.edu/hubert/pyaudio/, https://github.com/Picovoice/Porcupine/tree/master/binding/python

**Comment by kenarsa** [comment]
OK. Whats the OS that you are using? Could you give me the version of packages you have installed? Then we can try to reproduce or identify a possible version mismatch.

**Comment by MarianaTS** [comment]
Currently, we are using Ubuntu 16.04. 
Pyaudio -  0.2.8
Enum34 -1.1.6
PySoundFile - 0.9.0

Tests are failed too 
![screenshot from 2018-05-30 15-13-24](https://user-images.githubusercontent.com/14802962/40719457-61d2fb06-641c-11e8-9de3-2aca4e275e25.png)

**Comment by fquirin** [comment]
What worked for me was
sudo pip uninstall enum
sudo pip install enum34
but I see you already have enum34 ... maybe it still uses the other enum?

**Comment by MarianaTS** [comment]
Right!
It helped. 
But there is another issue. 
ALSA lib pcm_dsnoop.c:606:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
Cannot lock down 82274202 byte memory area (Cannot allocate memory)

Service works, but I see these warnings in the console.
Thanks

**Comment by kenarsa** [comment]
The warnings as OK as mentioned in the demo's README here https://github.com/Picovoice/Porcupine/tree/master/demo/python

If the service is working feel free to close the issue. Thanks.

**Comment by MarianaTS** [comment]
Thanks!
