### ISSUE TITLE
Support for all RaspberryPi variants

### ISSUE THREAD

**Issue by Flux9665** [Picovoice/porcupine#230]
### Expected behaviour
The documentation says, that porcupine is available for **all** RaspberryPi variants.

### Actual behaviour
When executing my script in my little home project on a Pi 4 B I got a NotImplementedError: unsupported platform. 

### Steps to reproduce the behaviour
Looking into the code, I found that only Pis up to model 3 B are supported. 

I hope you plan on supporting the new Pi as well in the future, this library is awesome and it would go so well with the new hardware. Thank you!

**Comment by kenarsa** [comment]
we do have an intention to add support for rpi4. at this point i can't give you a timeline though.

**Comment by hofst** [comment]
@kenarsa Do you have an update on this? Just installed my new mic on my raspberrypi4 (cortex-a72) and was disappointed to learn that picovoice does not support the platform :(
Wouldn't it simply be a matter of recompiling/uploading the shared-library for the new architecture, or do you expect compatibility problems?
I wouldn't like to move to another speech recognition engine but currently I don't have the choice.
