### ISSUE TITLE
Node version dependency

### ISSUE THREAD

**Issue by prashanthsridhar** [Picovoice/porcupine#239]
### Expected behaviour
Function normally at any node version
### Actual behaviour
Lags and page becomes unresponsive when node 10.17 is used
### Steps to reproduce the behaviour
Change node version to 10.17

### Need input
Does picovoice have a specific node version dependency.

**Comment by kenarsa** [comment]
we don't have a node binding. how do you use porcupine with node?

**Comment by prashanthsridhar** [comment]
Sorry for that , there was a misnomer in the team that picovoice uses node to bind the js files
