### ISSUE TITLE
"Computer" Keyword file

### ISSUE THREAD

**Issue by CobraCalle** [Picovoice/porcupine#240]
Hello,

would it be possible to add a free to use Keyword file for "computer"?

Thanks slot

Carl

**Comment by kenarsa** [comment]
You can generate that for x86_64 using console.picovoice.ai

**Comment by CobraCalle** [comment]
yes, I`ve done that, but that only works for 30 days... I need a solution that works without an expiration date...

**Comment by CobraCalle** [comment]
> yes, I`ve done that, but that only works for 30 days... I need a solution that works without an expiration date...

To be more specific... I would need that Keyword file for raspberry... Just saw that it is already available for Linux (but not for other platforms)

@kenarsa
