### ISSUE TITLE
Adding Custom PPN to Project, Looking in user path instead of project

### ISSUE THREAD

**Issue by Advtech92** [Picovoice/porcupine#241]
Make sure you have read the documentation and have put reasonable effort to find an already-existing answer.

### Expected behaviour
Being able to set the keyword to a local file created via the console in the project resources
### Actual behaviour
Any time I set the path for the ppn, it can not find it due to it looking in the user home directory while the file is in my local project folder
### Steps to reproduce the behaviour
1. Install pvporcupine
2. Run Python 3 64-bit
3. Create new .py script to use with pvporcupine
4. import pvporcupine and make handle line
5. set path to custom ppn (in my case, I tried to set it to use my ppn I made which I placed in the same folder that all my other scripts for the project are in)
6. Receive OSERROR saying that it can't find the keyword file in the specified path 'r' (Path was 'resources/$CUSTOM_ppn)
7. Remove resource from path and received the same error but this time with 'h' (start of my custom keyword)
Include enough details so that the issue can be reproduced independently.
I am running on windows 10 with the most recent version of python 3 64-bit
My project is in a custom project folder located in my  documents.
The Error points to line 88 of __init__ of binding/python/porcupine.py, line 42 in create in __init__.py

**Comment by kenarsa** [comment]
It doesn't look into home only. If expands the path if you are using "~". Provide full path and it should work. don't use relative path ...
