### ISSUE TITLE
pvporcupine_mic --keywords porcupine not working on pycharm IDE

### ISSUE THREAD

**Issue by SpydyMasu** [Picovoice/porcupine#243]
pvporcupine_mic --keywords porcupine is working on cmd but not working on pycharm IDE
my pyhton version is 3.6.0 64bit

pycharm console--

import pvporcupine
pvporcupine_mic --keywords picovoice

output-
pvporcupine_mic --keywords picovoice
                                       ^
SyntaxError: invalid syntax
unresolve referecne pvporcupine_mic 

that's all error 
And sir if u can please provide me a python script like demo script where i can manually put  keyword files in the script and get output in a variable (like keyword detected)  to turn on my virtual assistane by if condition

Thanking you in advance sir

**Comment by kenarsa** [comment]
Its a command line not a python object. the rest you should do yourself.
