### ISSUE TITLE
PV_STATUS_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by lovelynitar** [Picovoice/porcupine#244]
I tried to run the qt demo porcupine example but the application is crushed with the following error.
My OS version Ubuntu 16.04.6. qt version is qt5.12.0

### Actual behaviour
Run the Qtporcupineexample and got the segmentation fault error:
status(PV_STATUS_OUT_OF_MEMORY | PV_STATUS_IO_ERROR | PV_STATUS_STOP_ITERATION | unknown: 32760)(32765)

This is my model path & keyword path
static QString modelPath = "/home/nitar/porcupine-master/lib/common/porcupine_params.pv";
static QString keywordPath = "/home/nitar/porcupine-master/resources/keyword_files/linux/blueberry_linux.ppn";

May I know what is wrong?
Thanks in advance.

**Comment by Warren93** [comment]
Since nobody else has answered, I notice your modelPath string has a double slash in it; is that intentional? Could be causing an IO error leading to a segfault. Or something.

**Comment by lovelynitar** [comment]
This is the mistake when I copy from ide . I still have this issue. Anyway, thanks for reply
