### ISSUE TITLE
Install pv-porcupine npm package with old gcc

### ISSUE THREAD

**Issue by Warren93** [Picovoice/porcupine#245]
I am trying to install porcupine from npm (https://www.npmjs.com/package/pv-porcupine), but I'm running into some issues that seem to be related to my c++ compiler being too old.

Here is the output:

`
> pv-porcupine@1.0.0 install /home/my_user_name/projects/node_app/node_modules/pv-porcupine
> node-gyp rebuild

make: Entering directory '/home/my_user_name/projects/node_app/node_modules/pv-porcupine/build'
  CXX(target) Release/obj.target/pv_porcupine/src/porcupine.o
../src/porcupine.cc: In function ‘bool node_porcupine::parseKeyword(v8::Local<v8::Value>, std::string&, float&)’:
../src/porcupine.cc:131:119: error: conversion from ‘Nan::imp::ValueFactoryBase<double>::return_t {aka Nan::Maybe<double>}’ to non-scalar type ‘v8::Maybe<double>’ requested
         v8::Maybe<double> sensitivityVal = Nan::To<double>(Nan::Get(keywordObject, sensitivityKeyStr).ToLocalChecked());
                                                                                                                       ^
../src/porcupine.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE node_porcupine::Porcupine::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/porcupine.cc:166:13: error: ‘unique_ptr’ is not a member of ‘std’
             std::unique_ptr<std::string, std::default_delete<std::string[]>> keyword_file_path_strings(new std::string[length]);
             ^
../src/porcupine.cc:166:40: error: expected primary-expression before ‘,’ token
             std::unique_ptr<std::string, std::default_delete<std::string[]>> keyword_file_path_strings(new std::string[length]);
                                        ^
../src/porcupine.cc:166:42: error: ‘default_delete’ is not a member of ‘std’
             std::unique_ptr<std::string, std::default_delete<std::string[]>> keyword_file_path_strings(new std::string[length]);
                                          ^
../src/porcupine.cc:166:73: error: expected primary-expression before ‘[’ token
             std::unique_ptr<std::string, std::default_delete<std::string[]>> keyword_file_path_strings(new std::string[length]);
                                                                         ^
../src/porcupine.cc:166:74: error: expected primary-expression before ‘]’ token
             std::unique_ptr<std::string, std::default_delete<std::string[]>> keyword_file_path_strings(new std::string[length]);
                                                                          ^
../src/porcupine.cc:166:127: error: ‘keyword_file_path_strings’ was not declared in this scope
             std::unique_ptr<std::string, std::default_delete<std::string[]>> keyword_file_path_strings(new std::string[length]);
                                                                                                                               ^
../src/porcupine.cc:167:13: error: ‘unique_ptr’ is not a member of ‘std’
             std::unique_ptr<const char *, std::default_delete<const char *[]>> keyword_file_paths(new const char *[length]);
             ^
../src/porcupine.cc:167:29: error: expected primary-expression before ‘const’
             std::unique_ptr<const char *, std::default_delete<const char *[]>> keyword_file_paths(new const char *[length]);
                             ^
../src/porcupine.cc:167:29: error: expected ‘;’ before ‘const’
../src/porcupine.cc:168:13: error: ‘unique_ptr’ is not a member of ‘std’
             std::unique_ptr<float, std::default_delete<float[]>> sensitivities(new float[length]);
             ^
../src/porcupine.cc:168:29: error: expected primary-expression before ‘float’
             std::unique_ptr<float, std::default_delete<float[]>> sensitivities(new float[length]);
                             ^
../src/porcupine.cc:168:29: error: expected ‘;’ before ‘float’
../src/porcupine.cc:171:108: error: ‘sensitivities’ was not declared in this scope
                 if (!parseKeyword(Nan::Get(array, i).ToLocalChecked(), keyword_file_path_strings.get()[i], sensitivities.get()[i]))
                                                                                                            ^
../src/porcupine.cc:177:21: error: ‘keyword_file_paths’ was not declared in this scope
                     keyword_file_paths.get()[i] = keyword_file_path_strings.get()[i].c_str();
                     ^
../src/porcupine.cc:181:83: error: ‘keyword_file_paths’ was not declared in this scope
             status = pv_porcupine_multiple_keywords_init(model_file_path, length, keyword_file_paths.get(), sensitivities.get(), &object);
                                                                                   ^
../src/porcupine.cc:181:109: error: ‘sensitivities’ was not declared in this scope
             status = pv_porcupine_multiple_keywords_init(model_file_path, length, keyword_file_paths.get(), sensitivities.get(), &object);
                                                                                                             ^
pv_porcupine.target.mk:82: recipe for target 'Release/obj.target/pv_porcupine/src/porcupine.o' failed
make: *** [Release/obj.target/pv_porcupine/src/porcupine.o] Error 1
make: Leaving directory '/home/my_user_name/projects/node_app/node_modules/pv-porcupine/build'
gyp ERR! build error 
gyp ERR! stack Error: 'make' failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm4/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.4.104-18.44-default
gyp ERR! command "/usr/bin/node4" "/usr/lib64/node_modules/npm4/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/my_user_name/projects/node_app/node_modules/pv-porcupine
gyp ERR! node -v v4.8.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.4.104-18.44-default
npm ERR! argv "/usr/bin/node4" "/usr/bin/npm-default" "install" "pv-porcupine"
npm ERR! node v4.8.7
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! pv-porcupine@1.0.0 install: 'node-gyp rebuild'
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pv-porcupine@1.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pv-porcupine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pv-porcupine
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls pv-porcupine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/my_user_name/projects/node_app/npm-debug.log

`

Perhaps this is more of a general npm question, but I wanted to ask here in case anyone else has seen this. Is this problem in fact due to a too old c++ standard? Is there a way I can force the "-std=c++11" option when using npm install?

**Comment by kenarsa** [comment]
as mentioned this is not the correct repo for this question.
