### ISSUE TITLE
Android demo fails to compile: invalid SDK path

### ISSUE THREAD

**Issue by vicianm** [Picovoice/porcupine#247]
### Expected behaviour
Android client is successfully built after Android demo is imported to IntellijIDEA or similar IDE.

### Actual behaviour
Build fails due to invalid SDK path in local.properties files.

### Steps to reproduce the behaviour
Open Porcupine Android demo on PC where Android SDK path differs from "/home/alireza/Android/Sdk".

I suppose that the "local.properties" file should not be commited to repo at all.
So far I noticed two of them:
- porcupine/demo/android/Activity/local.properties
- porcupine/demo/android/Service/local.properties

Import succeeded after I deleted these files. My IDE (IntellijIDEA with Android) plugin created them after import based on my Android SDK path.

I also suggest to update .gitignore file by https://www.gitignore.io/ or any similar utility which could prevent this situation in future.

**Comment by kenarsa** [comment]
can you submit a PR to remove these files, please?

**Comment by kenarsa** [comment]
close due to inactivity
