### ISSUE TITLE
java.io.IOException: Initialization of Porcupine failed.

### ISSUE THREAD

**Issue by shabshekan** [Picovoice/porcupine#248]
After running the project I face with this error "java.io.IOException: Initialization of Porcupine failed." in this line "object = init(modelFilePath, new String[]{keywordFilePath}, new float[]{sensitivity});"
I follow former questions and I am sure about my address because I test it, but there is one point.
getFilesDir() method return "/data/user/0/ai.picovoice.porcupine.demo/files/" but I on my device file explorer I have this path "/data/data/ai.picovoice.porcupine.demo/files/". So in code I use second path as hard code just for test and all files can be opened. 
I have no idea how can I go forward.

![Screenshot (21)](https://user-images.githubusercontent.com/15563965/71248251-b0c45480-231a-11ea-8ed0-2fa83d9d5ce9.png)

**Comment by kenarsa** [comment]
hardcoding doesn't sound right. try to actually read the file programmatically within Java and make sure its content is correct.

**Comment by shabshekan** [comment]
how can I change path from "/data/data/ai.picovoice.porcupine.demo/files/" to  "/data/user/0/ai.picovoice.porcupine.demo/files/"
