### ISSUE TITLE
Error loading procupine newest version: "keyword file belongs to a different version of the library"

### ISSUE THREAD

**Issue by nuttyartist** [Picovoice/porcupine#251]
I generated keyword files using the Picovoice Wake-up-word Console but I get error loading them. I'm using the latest version of this repo. Using C++/C code. On Mac. I get this error:

```
[ERROR] keyword file belongs to a different version of the library
[ERROR] loading keyword file failed with 'INVALID_ARGUMENT'
```

Can you help me solve this?

**Comment by kenarsa** [comment]
can you use the in-browser testing for your model? if yes, then the repo you have is somehow old. if no, somehow provide the model and we can look into it.

**Comment by nuttyartist** [comment]
I checked again and it doesn't work.

Here's my keyword_file generated from the Console: https://we.tl/t-qwYAfo7vB9

**Comment by kenarsa** [comment]
I tried it and it works: python3 demo/python/porcupine_demo.py --keyword_file_paths ~/Downloads/hey_deus_mac_2020-01-26.ppn

try to clone a clean version and try again.

**Comment by nuttyartist** [comment]
True, it is!

I was pointing to the library of the old version! Sorry about that, thanks!
