### ISSUE TITLE
Please open source a "Computer" WASM keyword

### ISSUE THREAD

**Issue by dsteinman** [Picovoice/porcupine#252]
Is there any way I can convince Picovoice to release an open source "computer" keyword under the Apache 2.0 license? (wasm version)

I bet a lot of people worldwide have been wanting to say "computer" and have their computers obey their commands like on Star Trek.  And your codebase can do it.   I've been working the latest version of Porcupine for a little while now and I think it's really awesome.  You guys have something really amazing here.  It's like a foundational level technology.

I don't know if you've been keeping tabs on what I've been working on but I've got Porcupine working as a wake word for DeepSpeech, I think the two systems working together is really amazing:

https://github.com/jaxcore/deepspeech-plugin/tree/master/examples/node-wakeword

The WASM keywords you've open sourced so far (like "bumblebee", "hey edison') are sufficient, but I think most people would probably prefer to say "computer" like on Star Trek.  I think it would be the \#1 requested keyword.

So why not just open source "Computer"?

I understand you guys are trying to create a business around your keywords and need people to pay.  But what I'd like to try to convince you of, is if you open source a "computer' hotword it could become a sort of defacto open source alternative to "Alexa".  And the more people who use Porcupine the more opportunity there will be to sell them custom alternatives to the open sourced "Computer" keyword.

**Comment by mehrdadfeller** [comment]
Hi there, I appreciate the comment. Currently, we are focused on servicing enterprise clients. The sole purpose of the code we have published on GitHub is to allow our customers to freely evaluate the performance and ease-of-integration before signing up for added services and development tools. From our standpoint, we'd rather people say "hey picovoice" to promote our brand than promoting a movie.
