### ISSUE TITLE
PyPi Pip Package omits Windows files

### ISSUE THREAD

**Issue by hofst** [Picovoice/porcupine#253]
The repository itself contains the Windows resource files and libs and lists Windows as supported platform.
However, the uploaded pip package does not (and it also omits Windows from supported platforms):
https://pypi.org/project/pvporcupine

When I install the pip package first and then copy over the resource files/lib manually, I can resolve that problem (however then I'm stuck at a pyaudio error which may be unrelated). 
Is this intended?

**Comment by kenarsa** [comment]
pip package is not intended to support windows as described here: https://pypi.org/project/pvporcupine/

for windows, you need to clone the repo and then install pyaudio yourself.

**Comment by hofst** [comment]
@kenarsa oh that's a pitty. I saw that note, but is there a technical reason for it?
