### ISSUE TITLE
Request to extend lifetime limit of keywords and allow the creation of more than one per major os

### ISSUE THREAD

**Issue by nuttyartist** [Picovoice/porcupine#254]
I'm developing a program to help people control their computers using their voice called Deus: https://www.deus-ai.com. [Github link](https://github.com/nuttyartist/deus). Deus is open-source and free.

I'm using Porcupine for the wake-up-word detection but have 2 problems:
1. The 30 day limit on the keyword lifetime makes it impractical to ship my software to a consumer, so I'd really appreciate it if you could lift up the limit.
2. I'd like users to be able to choose more than one voice that will go with a different personality, e.g "Samantha", but you currently limit the number of keywords that can be generated. Can you help lift that limit also?

Your technologies are incredibly impressive and I think Deus will be an interesting way to show them off.

**Comment by mehrdadfeller** [comment]
Currently, we are focused on servicing mid to large scale enterprise clients. The sole purpose of the code we have published on GitHub is to allow our customers to freely evaluate the performance and ease-of-integration before signing up for added paid services and development tools. Feel free to use "hey picovoice" as the wake word in your project.
