### ISSUE TITLE
Non key-word sound as the wakeup trigger

### ISSUE THREAD

**Issue by hasagar97** [Picovoice/porcupine#256]
I am working on a project that requires the system to trigger up when a particular sound event happens(e.g. glass shattering or guitar playing), is it possible to use porcupine for such application?

If not, is it possible to re-train the used Deep Learning Model to recognize such sound events?

Microphone device: 4-mic array mounted on a raspberry pi(I also have a jetson nano which I can use if needed). 

Thanks

**Comment by kenarsa** [comment]
porcupine is only intended for keyword detection.
