### ISSUE TITLE
example JS binding does not work with node.js

### ISSUE THREAD

**Issue by Sammons** [Picovoice/porcupine#257]
I cannot instantiate `.create(['porcupine'])` using the pv_porcupine.js, pv_porcupine.wasm, and porcupine.js files

### Expected behaviour

does not throw on instantiation

### Actual behaviour

Throws with error "Cannot read property 'apply' of undefined"

The undefined behavior sems related to Module["asm"]["_malloc"] not existing in 
at Object._malloc (/home/sammons/test-porc/node/pv_porcupine.js:7:24680)

### Steps to reproduce the behaviour

Copy pv_porcupine.wasm, pv_porcupine.js, porcupine.js from the demo folder. Export the objects returned via module.expors. Invoking porcupine.create will throw, tried using node 8, 12, 13.

Include enough details so that the issue can be reproduced independently.

**Comment by kenarsa** [comment]
the JS binding is only meant to run within browser not node as doc states: https://github.com/Picovoice/porcupine#javascript
