### ISSUE TITLE
Create new keywords

### ISSUE THREAD

**Issue by likegeo** [Picovoice/porcupine#258]
Hello, how can i create new keyword? keyword files are stored in binary format but how to generate them? from microphone data or...? can you pease explain for js users how to create these keywords and read them on demo file?

Thank you!

**Comment by kenarsa** [comment]
https://github.com/Picovoice/porcupine/tree/master/resources/keyword_files#wasm-webassembly

https://github.com/Picovoice/porcupine#porcupine

read the docs, please.

**Comment by suryakumar-sekar** [comment]
Can i able to add new keyword apart from existing keyword?
