### ISSUE TITLE
Picovoice/Porcupine

### ISSUE THREAD

**Issue by ShivamSpm** [Picovoice/porcupine#259]
I ran the demo/android/service on my android studio. But it only works for the word 'porcupine'. Is there a way to develop it for my own custom word?

**Comment by dbartle** [comment]
You can use the Picovoice Console to train custom wake words. Please read and understand the terms of service and documentation and reserve GitHub issues for bug reports.

https://github.com/Picovoice/porcupine#picovoice-console
