### ISSUE TITLE
navy_blue_wasm.ppn doesn't target wasm

### ISSUE THREAD

**Issue by ianb** [Picovoice/porcupine#261]
I was trying all the ppn files in the wasm/ directory, and navy_blue_wasm.ppn (https://github.com/Picovoice/porcupine/blob/master/resources/keyword_files/wasm/navy_blue_wasm.ppn) didn't load, with an error that it belongs to a different platform. The rest of the files worked fine.

**Comment by kenarsa** [comment]
Thanks, @ianb. Could you please try the latest? Keep in mind that this is a new release and you to update your WASM file as well.
