### ISSUE TITLE
Using PIP install not including test files/keyword file paths

### ISSUE THREAD

**Issue by raystrods** [Picovoice/porcupine#264]
Tried to run demo using PIP install but was getting errors about keyword file paths.

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\users\\strod\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pvporcupine\\resources\\util\\python\\../../../resources/keyword_files\\windows'

Also noticed the pip install didnt include the test files in the python bindings so I manually added it but still seems to be trying to referencing a directory that doesnt exist. 

Traceback (most recent call last):
  File "binding/python/test_porcupine.py", line 21, in <module>
    from util import *
  File "binding/python\../../resources/util/python\util.py", line 99, in <module>
    KEYWORD_FILE_PATHS = _keyword_file_paths()
  File "binding/python\../../resources/util/python\util.py", line 92, in _keyword_file_paths
    for x in os.listdir(keyword_files_dir):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'binding/python\\../../resources/util/python\\../../../resources/keyword_files\\windows'

**Comment by kenarsa** [comment]
PIP installation is not supported on windows. the documentation on PIP page clearly lists the supported platforms
