### ISSUE TITLE
Cannot compile (for simulators) in Xcode 11.4 - Target integrity error

### ISSUE THREAD

**Issue by backslash-f** [Picovoice/porcupine#267]
I recently upgrade from Xcode 11.3.1 to Xcode 11.4 and it seems I'm now unable to compile Porcupine for simulators. It works fine against physical devices.

I'm using Porcupine 1.7.

### Expected behaviour
Is should compile successfully when targeting iOS simulators.

### Actual behaviour
Xcode fails to compile for simulators. The error message says:

`PROJECTNAME.xcodeproj Building for iOS Simulator, but the linked library 'libpv_porcupine.a' 
was built for iOS.`

### Steps to reproduce the behaviour
Download Porcupine 1.7, integrate `libpv_porcupine.a` with an iOS Xcode project, build for simulators. Build fails with the above error message.

**Comment by kenarsa** [comment]
Can you build to run on target?

**Comment by backslash-f** [comment]
> Can you build to run on target
If you are asking about building and running against physical devices, then yes.

The issue happens when the target is a simulator. I'm am unable to build / run when the target is an iOS simulator. This, in turn, breaks our CI platform.

**Comment by backslash-f** [comment]
Perhaps Porcupine for iOS could be distributed as a [`XCFramework`](https://medium.com/trueengineering/xcode-and-xcframeworks-new-format-of-packing-frameworks-ca15db2381d3)?

This would make integration easier.

Here's another successful `XCFramework` example: https://github.com/50ButtonsEach/flic2lib-ios/issues/15 

> The main purpose of XCFrameworks is to solve the multi-architecture issues of a regular framework. An added bonus of this would be that it would be easy for us to add additional platforms (such as macOS) to the same package in the future.

**Comment by kenarsa** [comment]
thanks! will look into this as a candidate for v1.8 release.

**Comment by backslash-f** [comment]
Would you have any idea on the release date for 1.8?
We are currently unable to update Xcode due to this issue.
Thanks.

**Comment by kenarsa** [comment]
no. if you are a commercial customer you should reach out to your point of contact directly and we can provide a patch on an expedited fashion.

**Comment by kenarsa** [comment]
Please try the latest (v1.8). We confirm that we can run the demo on the simulator using XCode 11.5. re-open if the issue persists
