### ISSUE TITLE
Convert old WASM keyword to versions 1.6 and 1.7 ?

### ISSUE THREAD

**Issue by fquirin** [Picovoice/porcupine#269]
WASM keywords that were created for versions below 1.5 don't work with 1.5 and since the format was changed again for 1.7 I'd expect they are not compatible as well.

### Expected behaviour

Offer a tool to convert keyword files to new versions.

### Actual behaviour

I can't upgrade my Porcupine version because my keyword does not work. 

### Steps to reproduce the behaviour

Try to use a WASM keyword created before version 1.5 in version 1.5+.

I'm writing this here because I've tried to contact Picovoice via Email 2 times, but got no reply so far :-(. The Keyword is "Hey SEPIA" and was created around October 2018 for SEPIA open-source assistant. Any help would be greatly appreciated.

**Comment by mehrdadfeller** [comment]
Hi there, GitHub issues are reserved for software issues or suggestions for improvement. For commercial license inquiries, please fill out the contact form on our website:

[](https://picovoice.ai/contact/)

In the description, please let us know if you have purchased an annual service maintenance package and include the order number.
