### ISSUE TITLE
(C++) Errors when trying to build in QT from demo example.

### ISSUE THREAD

**Issue by socketopp** [Picovoice/porcupine#270]
I found [this ](https://github.com/beevesuw/Porcupine/tree/master/demo/cpp) demo on how to use Porcupine together with C++ and Qt. 
I have these compilers to choose from.
MinGW 32/64-bit
MSVC 2015-2017 32/64-bit
UWP 64-bit (MSVC 2017)

The .pro file looks like this
```
QT -= gui
QT += multimedia

CONFIG += c++11 console
CONFIG -= app_bundle

SOURCES += \
        main.cpp

qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

win32 {
    contains(QT_ARCH, x86_64){
        LIBS += \
            -L/lib/windows/amd64
    } else {
        LIBS += \
            -L/lib/windows/i686
    }
}

LIBS += -lpv_porcupine

HEADERS += \
    picovoice.h \
    pv_porcupine.h


INCLUDEPATH += \
    picovoice.h \
    pv_porcupine.h

DISTFILES += \
    keyword.ppn
```

I used MSVC 2017, 64-bit

I am running with MSVC I am receiving these kinds of errors: 
![bild](https://user-images.githubusercontent.com/20456621/79273549-766f5c00-7ea3-11ea-8009-ad07eddeb32c.png)

However with MinGW, I only receive these errors:
![bild](https://user-images.githubusercontent.com/20456621/79273614-8edf7680-7ea3-11ea-9dcb-c46fbb290d70.png)

Is Porcupine not compatible with MSVC? What are the erros due to? 

This [issue ](https://github.com/Picovoice/porcupine/issues/21 )seem to have address QT demo before. 

If I comment out everything in the .cpp file I get this error for the MSVC compiler:
: - 1: error: LNK1104: cannot open file 'pv_porcupine.lib'

Am I not suppose to link `LIBS += -lpv_porcupine` with MSVC compiler?

From my investigation, if I add  `LIBS += -lpv_porcupine` and run with MinGW the compiler does not seem to complain. 

Thanks
Socke

**Comment by kenarsa** [comment]
It should work with MSVC. Since you are using someone else's fork you should ask the developer of that fork directly.

**Comment by socketopp** [comment]
> 
> 
> It should work with MSVC. Since you are using someone else's fork you should ask the developer of that fork directly.

`#define PV_API __attribute__((visibility ("default")))`

Does not seem to jazz with MSVC. 

However, I suspect that it translates to:

`#define PV_API __declspec("default")`

But I am not an expert.
