### ISSUE TITLE
Picovoice enterprise / commercial support

### ISSUE THREAD

**Issue by stcleezy** [Picovoice/porcupine#271]
Is Picovoice still offering enterprise support for their products? I have attempted to contact them via their website form, email and even LinkedId -- no reply.

**Comment by kenarsa** [comment]
https://picovoice.ai/contact/

fill the above form. If information is complete, someone will get back to you in a couple of weeks time.

**Comment by mehrdadfeller** [comment]
Hi there, Have you filled out the [contact form](https://picovoice.ai/contact/) on our website? LinkedIn is not the right channel for inquiries. We receive a very large number of inquiries and our team only responds to inquiries with complete and accurate information provided on the contact form. Please also note that we only offer enterprise software services to corporations and we do not engage with individuals or early-stage startups.
