### ISSUE TITLE
error while using pip to install porcupine

### ISSUE THREAD

**Issue by supreet21** [Picovoice/porcupine#272]
Make sure you have read the documentation and have put reasonable effort to find an already-existing answer.
error in 
 pip install pvporcupine

### Actual behaviour
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    numpy from https://files.pythonhosted.org/packages/3a/5f/47e578b3ae79e2624e205445ab77a1848acdaa2929a00eeef6b16eaaeb20/numpy-1.16.6-cp27-cp27mu-manylinux1_x86_64.whl#sha256=1680c8d5086a88d293dfd1a10b6429a09140cacee878034fa2308472ec835db4 (from pvporcupine):
        Expected sha256 1680c8d5086a88d293dfd1a10b6429a09140cacee878034fa2308472ec835db4
             Got        6c29d9afd4eb4ad61afeceeb981773b2c0e6c4bc3adf6812c572ddba79d21845

    cffi>=0.6 from https://files.pythonhosted.org/packages/08/29/8001b940ef40e7a25ffe8f3188bc9b118934b513d64f769dbf461e46f4ed/cffi-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl#sha256=cab50b8c2250b46fe738c77dbd25ce017d5e6fb35d3407606e7a4180656a5a6a (from pysoundfile>=0.9.0->pvporcupine):
        Expected sha256 cab50b8c2250b46fe738c77dbd25ce017d5e6fb35d3407606e7a4180656a5a6a
             Got        dddd866eb827c3d2c4ef11dfca9ee3afe485f615458f97d6ff833d305c790e10

### Steps to reproduce the behaviour

Include enough details so that the issue can be reproduced independently.

**Comment by kenarsa** [comment]
I'm not clear whats the problem. Elaborate and provide steps to produce otherwise can't help.

**Comment by supreet21** [comment]
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.

This error pops up while the installation the requirements in setup.sh

**Comment by kenarsa** [comment]
this does not seem like a porcupine problem. try installing again on a different system and if it occurs again provide detailed steps (platform, os, etc) to reproduce.
