### ISSUE TITLE
React Native / XCode build failure

### ISSUE THREAD

**Issue by JJB1980** [Picovoice/porcupine#274]
### Expected behaviour
Build for iOS in XCode (11.4.1) / terminal  (React Native project)

### Actual behaviour
Compilation fails with:
`Undefined symbols for architecture x86_64:
  "_pv_porcupine_multiple_keywords_init", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Owned To Guaranteed, Arg[2] = Owned To Guaranteed> of iCommand.PorcupineManager.init(modelFilePath: Swift.String, wakeKeywordConfigurations: [iCommand.WakeWordConfiguration], onDetection: (iCommand.WakeWordConfiguration) -> ()?) throws -> iCommand.PorcupineManager in PorcupineManager.o
  "_pv_porcupine_multiple_keywords_process", referenced from:
      closure #1 (Swift.UnsafePointer<Swift.Int16>) -> () in iCommand.PorcupineManager.init(modelFilePath: Swift.String, wakeKeywordConfigurations: [iCommand.WakeWordConfiguration], onDetection: (iCommand.WakeWordConfiguration) -> ()?) throws -> iCommand.PorcupineManager in PorcupineManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

### Steps to reproduce the behaviour
Run for iPhone 11 (simulator)
Using latest libpv_porcupine.a (https://github.com/Picovoice/porcupine/blob/master/lib/ios/libpv_porcupine.a)

**Comment by kenarsa** [comment]
can be related to https://github.com/Picovoice/porcupine/issues/267
we will look into it for next release

**Comment by kenarsa** [comment]
Please try the latest (v1.8). We confirm that we can run the demo in the repository on the simulator using XCode 11.5. Please note that we don't have drop-in support for react-native. It is possible that you need to do some config/plumbing yourself.

**Comment by JordanProtin** [comment]
> Please note that we don't have drop-in support for react-native

Hi @kenarsa,

Do you plan to work on a support for react-native ?

**Comment by kenarsa** [comment]
No. But you can add it yourself either using native libs or WASM. some of our customers did it already. if you do and open-source happy to take a look and possibly merge into main repo.

**Comment by JordanProtin** [comment]
No problem, it's the open-source idea ! :-). 
Thank you for your feedback. 
I have to meet deadlines with my business react-native project. So, I'll try to begin a work about a react-native package.

Best regards
