### ISSUE TITLE
keyword file has incorrect format.

### ISSUE THREAD

**Issue by Ahmedhassan50** [Picovoice/porcupine#275]
I/PICOVOICE(24326): [ERROR] keyword file has incorrect format.
I/PICOVOICE(24326): [ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'

**Comment by kenarsa** [comment]
The issue template clearly asks for "Include enough details so that the issue can be reproduced independently". This description has NO information for the reproduction of issue and hence we cannot help.
