### ISSUE TITLE
Keyword file belongs to a different version of the library

### ISSUE THREAD

**Issue by backslash-f** [Picovoice/porcupine#277]
This is more like a question / follow up of: https://github.com/Picovoice/porcupine/issues/267
(Thanks for that BTW. It works fine in Xcode 11.5 now. 👍🏻)

We upgraded from 1.6 to 1.8 and noticed that some of the keyword files are missing.

For example, in **1.6** we have the following keyword files:

<img width="194" alt="1 6" src="https://user-images.githubusercontent.com/664951/83120447-5ef5d680-a0d1-11ea-8fed-46a9c6980d0e.png">

But in **1.8**, the keyword files list is:

<img width="168" alt="1 8" src="https://user-images.githubusercontent.com/664951/83120481-69b06b80-a0d1-11ea-99b2-28fd34003cc6.png">

That leads our project to fail with the following error (in case we try to use some of the old keyfiles, for example `avocado`:
```
[ERROR] keyword file belongs to a different version of the library
[ERROR] loading keyword file at '/private/var/containers/Bundle/Application/D49299F3-5582-4E5C-8CF7-83B8809B709C/
```

👉🏻 So question is: was this intentional?
👉🏻 If so: are you dropping support for those 1.6 keyword files?

### Expected behaviour
It would be great to be able to continue using 1.6 keyword files.

### Actual behaviour
```
[ERROR] keyword file belongs to a different version of the library
[ERROR] loading keyword file at '/private/var/containers/Bundle/Application/D49299F3-5582-4E5C-8CF7-83B8809B709C/
```

### Steps to reproduce the behaviour
Upgrade Porcupine from 1.6 to 1.8 and try to use a keyword file from 1.6.
Xcode 11.5

**Comment by kenarsa** [comment]
keyword files are version-dependent. we are not planning to expand the number of freely-available models from what it is in v1.8.
