### ISSUE TITLE
optimizer for iOS fails

### ISSUE THREAD

**Issue by moshekr** [Picovoice/Porcupine#28]
### Expected behavior
A generated ppn file with the request keyword

### Actual behavior
> [WARN] This version of optimizer cannot create keyword files for ios. Please contact help@picovoice.ai.

### Steps to reproduce the behavior
> tools/optimizer/mac/x86_64/pv_porcupine_optimizer -r resources/ -w "ok google" -p ios -o ~/

Running on macOS High Sierra 10.13.4

**Comment by kenarsa** [comment]
The optimizer in this repo cannot create keyword files for iOS. Keyword files for iOS are only provided with a purchase of the commercial license. Please have a read here: https://github.com/Picovoice/Porcupine/tree/master/tools/optimizer

**Comment by moshekr** [comment]
Ok. thank you

**Comment by ychw** [comment]
@kenarsa what does the commercial license look like? Can you send me more details?

**Comment by bbrooksluth** [comment]
We cannot start an evaluation process without knowing pricing and performance of new custom keywords. It won't make sense to spend time evaluating unless we can evaluate custom wake words for ios with more syllables such as 'ok google' for example. This library is not open source and should not come under the heading of being included as open source.
Maybe you should consider a time limited version like OpenEars (RapidEars).
Even your preset wake word response times are a slow compared to OpenEars on iOS.
