### ISSUE TITLE
Please provide aarch64 64-bit ELF shared library for RPi4

### ISSUE THREAD

**Issue by mweinelt** [Picovoice/porcupine#282]
I'm using porcupine via rhasspy on the RPi4 using NixOS.

```
# uname -a
Linux dione 4.19.118 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 aarch64 GNU/Linux
# lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
CPU max MHz:                     1500.0000
CPU min MHz:                     600.0000
BogoMIPS:                        108.00
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid
```

### Expected behaviour

Porcupine should work on the RPi4 since v1.7.0.

### Actual behaviour

The dynlib for the Cortex A72 was built for 32-bit ARM, not aarch64.

```
# file /lib/raspberry-pi/cortex-a72/libpv_porcupine.so
/lib/raspberry-pi/cortex-a72/libpv_porcupine.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), statically linked, BuildID[sha1]=033a8c14484a7721728d5f68d966058159cc4e78, not stripped
```

```
OSError: [...]/lib/python3.8/site-packages/rhasspywake_porcupine_hermes/porcupine/lib/raspberry-pi/cortex-a72/libpv_porcupine.so: wrong ELF class: ELFCLASS32
```

### Steps to reproduce the behaviour

Try porcupine on the RPi4 using a 64-Bit Linux distribution. I tried it on NixOS, but that's a tough ask I guess.

**Comment by kenarsa** [comment]
We support the official Raspbian OS on RPI4 at the moment. For commercial inquiries we do new platform support from time-to-time. but unfortunately this wont fall into that category.

**Comment by kenarsa** [comment]
this should be fixed now

**Comment by ArlindoFNeto** [comment]
I got this same error message when I tryed to use porcupine via Rhasspy docker (latest - 2.5.10) on Raspbery Pi 4 with Raspibian Buster OS. It is the same problem or maybe docker cause this? Is there any information can I provide to clarify this problem? I'm happy to help whatever I can. At this moment I'm using Snowboy and it works weel.

```
[DEBUG:2021-04-24 23:51:56,005] rhasspywake_porcupine_hermes: Namespace(debug=True, host='localhost', keyword=['alexa_raspberry-pi.ppn'], keyword_dir=['/profiles/pt/porcupine'], lang=None, library=None, log_format='[%(levelname)s:%(asc
time)s] %(name)s: %(message)s', model=None, password=None, port=12183, sensitivity=['0.5'], site_id=['default'], stdin_audio=False, tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_k
eyfile=None, tls_version=None, udp_audio=None, username=None, wakeword_id=None)
[DEBUG:2021-04-24 23:51:56,006] rhasspywake_porcupine_hermes: Keyword dirs: [PosixPath('/profiles/pt/porcupine'), PosixPath('/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/resources/keyword_files/raspberry-pi')]
[DEBUG:2021-04-24 23:51:56,007] rhasspywake_porcupine_hermes: Loading porcupine (kw=['/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/resources/keyword_files/raspberry-pi/alexa_raspberry-pi.ppn'], kwdirs=['/profiles/pt/p
orcupine', '/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/resources/keyword_files/raspberry-pi'], sensitivity=[0.5])
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__main__.py", line 260, in <module>
    main()
  File "/usr/lib/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__main__.py", line 127, in main
    keyword_paths=[str(kw) for kw in args.keyword], sensitivities=sensitivities
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/__init__.py", line 68, in create
    sensitivities=sensitivities)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/porcupine.py", line 60, in __init__
    library = cdll.LoadLibrary(library_path)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/lib/raspberry-pi/cortex-a72-aarch64/libpv_porcupine.so: wrong ELF class: ELFCLASS64
2021-04-24 23:51:56,076 INFO exited: wake_word (exit status 1; not expected)
2021-04-24 23:51:57,078 INFO gave up: wake_word entered FATAL state, too many start retries too quickly
```

**Comment by ArlindoFNeto** [comment]
Hey guys, I changed the library from cortex-a72-aarch64 to cortex-a72 and porcupine worked normally. It's interesting because my architecture is aarch64 as you can see below. Is it correctly? Anyway, now it's works.

```
pi@Pi4:~ $ uname -a
Linux Pi4 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux

```

> I got this same error message when I tryed to use porcupine via Rhasspy docker (latest - 2.5.10) on Raspbery Pi 4 with Raspibian Buster OS. It is the same problem or maybe docker cause this? Is there any information can I provide to clarify this problem? I'm happy to help whatever I can. At this moment I'm using Snowboy and it works weel.
> 
> ```
> [DEBUG:2021-04-24 23:51:56,005] rhasspywake_porcupine_hermes: Namespace(debug=True, host='localhost', keyword=['alexa_raspberry-pi.ppn'], keyword_dir=['/profiles/pt/porcupine'], lang=None, library=None, log_format='[%(levelname)s:%(asc
> time)s] %(name)s: %(message)s', model=None, password=None, port=12183, sensitivity=['0.5'], site_id=['default'], stdin_audio=False, tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_k
> eyfile=None, tls_version=None, udp_audio=None, username=None, wakeword_id=None)
> [DEBUG:2021-04-24 23:51:56,006] rhasspywake_porcupine_hermes: Keyword dirs: [PosixPath('/profiles/pt/porcupine'), PosixPath('/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/resources/keyword_files/raspberry-pi')]
> [DEBUG:2021-04-24 23:51:56,007] rhasspywake_porcupine_hermes: Loading porcupine (kw=['/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/resources/keyword_files/raspberry-pi/alexa_raspberry-pi.ppn'], kwdirs=['/profiles/pt/p
> orcupine', '/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/resources/keyword_files/raspberry-pi'], sensitivity=[0.5])
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/lib/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__main__.py", line 260, in <module>
>     main()
>   File "/usr/lib/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__main__.py", line 127, in main
>     keyword_paths=[str(kw) for kw in args.keyword], sensitivities=sensitivities
>   File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/__init__.py", line 68, in create
>     sensitivities=sensitivities)
>   File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/porcupine.py", line 60, in __init__
>     library = cdll.LoadLibrary(library_path)
>   File "/usr/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
>     return self._dlltype(name)
>   File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /usr/lib/rhasspy/.venv/lib/python3.7/site-packages/pvporcupine/lib/raspberry-pi/cortex-a72-aarch64/libpv_porcupine.so: wrong ELF class: ELFCLASS64
> 2021-04-24 23:51:56,076 INFO exited: wake_word (exit status 1; not expected)
> 2021-04-24 23:51:57,078 INFO gave up: wake_word entered FATAL state, too many start retries too quickly
> ```
