### ISSUE TITLE
feature request: porcupine.process() to detect silence as well

### ISSUE THREAD

**Issue by hyansuper** [Picovoice/porcupine#285]
Can `porcupine.process()` detect silence like snowboy?
ref: https://github.com/Kitt-AI/snowboy/blob/master/examples/Python3/snowboydecoder.py#L231

**Comment by kenarsa** [comment]
No. I don't think this functionality should be part of wake word engine. It is clearly a VAD task. Whats the use case?

**Comment by hyansuper** [comment]
Use case:
In the above snowboy example, when the wake word is detected, it starts recording a piece of sound (for speech recognition later), when silence is detected longer than silence_timeout, that meaning the speaker stops speaking, so recording stops too and speech recogntion starts.

**Comment by nitrix** [comment]
For what it's worth, I'm implementing the exact same right now and would've liked if porcupine supported it.

**Comment by hyansuper** [comment]
workaround: use `pydub.AudioSegment(data).dBFS` to get loudness of the the piece of sound
