### ISSUE TITLE
iOS Watch Demo App "undefined symbol: _pv_file_size"

### ISSUE THREAD

**Issue by vogler75** [Picovoice/porcupine#286]
Hi, I am trying to build the iOS Watch Demo App, but it fails with "undefined symbol: _pv_file_size" (btw.: the Demo without watch works well). I just opened the project in Xcode Version 11.5 (11E608c) and tried to build the project (I only changed the team and bundle identifier). Do I miss something? 
regards,
Andreas

**Comment by kenarsa** [comment]
Thanks for reporting the issue. We've updated the library. Could you pull the repo again and try with the new lib?

**Comment by vogler75** [comment]
Hi, sorry that it took some time... I did a pull and tried again, but now i get other errors - missing .ppn files. 
/Users/vogler/Workspace/porcupine/resources/keyword_files/ios/avocado_ios.ppn: No such file or directory
/Users/vogler/Workspace/porcupine/resources/keyword_files/ios/vancouver_ios.ppn: No such file or directory
/Users/vogler/Workspace/porcupine/resources/keyword_files/ios/raspberry_ios.ppn: No such file or directory
/Users/vogler/Workspace/porcupine/resources/keyword_files/ios/pineapple_ios.ppn: No such file or directory
/Users/vogler/Workspace/porcupine/resources/keyword_files/ios/iguana_ios.ppn: No such file or directory
/Users/vogler/Workspace/porcupine/resources/keyword_files/ios/francesca_ios.ppn: No such file or directory
I think I can remove that resources - I don't need all that hotwords ... or you can check in those files...

**Comment by kenarsa** [comment]
You are correct. I removed those resources and now you should be able to build successfully. Let me know if you succeed this time ...

**Comment by vogler75** [comment]
great! no errors anymore. Thank you!
