### ISSUE TITLE
Custom wake words on Raspberry Pi

### ISSUE THREAD

**Issue by cap10curt** [Picovoice/porcupine#288]
I have porcupine running on a raspberry pi for a personal project (a robot car). I'd like to add a dozen or so custom wake words. The eight words it comes with aren't very helpful for a robot :-) I see I can create them for Windows, Mac, or Linux, but not Raspberry Pi. Do I need an enterprise account to do that or is there a way to download additional wake words?

**Comment by kenarsa** [comment]
https://github.com/Picovoice/porcupine#license
