### ISSUE TITLE
unable to enable SpeechRecognition in android service 

### ISSUE THREAD

**Issue by sanath-ai** [Picovoice/porcupine#289]
I just modified the Porcupineservice.java file with speech recognition 

##Expected behaviour
wanted it to convert speech to text

### Actual behaviour
It detects the wape-word and does nothing of speech recognition 
and it wont detectkey word again
Edited(as you can see the log ... it dosent display the log after speech recognition 

### Steps to reproduce the behaviour
install process:
1)cloned using git
2)open android studio and open Service folder
3)Project started syncing
4)build directly into phone
only Porcupineservice was modified

Porcupineservice.java

package ai.picovoice.porcupinedemoservice;
import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.app.Service;
import android.content.Context;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.os.IBinder;
import android.speech.RecognitionListener;
import android.speech.RecognizerIntent;
import android.speech.SpeechRecognizer;
import android.util.Log;
import androidx.annotation.Nullable;
import androidx.core.app.NotificationCompat;
import java.io.File;
import ai.picovoice.porcupinemanager.PorcupineManager;
import ai.picovoice.porcupinemanager.PorcupineManagerException;
public class PorcupineService extends Service  {
    private static final String CHANNEL_ID = "PorcupineServiceChannel";

    private PorcupineManager porcupineManager;

    private int numKeywordsDetected;

    Context c;

    protected static SpeechRecognizer mSpeechRecognizer;
    protected Intent mSpeechRecognizerIntent;

    private void createNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel notificationChannel = new NotificationChannel(
                    CHANNEL_ID,
                    "PorcupineServiceChannel",
                    NotificationManager.IMPORTANCE_HIGH);

            NotificationManager manager = getSystemService(NotificationManager.class);
            assert manager != null;
            manager.createNotificationChannel(notificationChannel);
        }
    }

    class SpeechRecognitionListener implements RecognitionListener
    {

        @Override
        public void onReadyForSpeech(Bundle bundle) {
        }

        @Override
        public void onBeginningOfSpeech() {
        }

        @Override
        public void onRmsChanged(float v) {
        }

        @Override
        public void onBufferReceived(byte[] bytes) {
        }

        @Override
        public void onEndOfSpeech() {
        }

        @Override
        public void onError(int i) {
        }

        @Override
        public void onResults(Bundle bundle) {
            String s = bundle.getString(SpeechRecognizer.RESULTS_RECOGNITION);
            Log.i("text =", "onResults: " + s);
        }
        @Override
        public void onPartialResults(Bundle bundle) {
        }

        @Override
        public void onEvent(int i, Bundle bundle) {
        }
    }

    @Override
    public void onCreate( ) {
        super.onCreate();
        c= getApplicationContext();
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        createNotificationChannel();

        SpeechRecognitionListener h = new SpeechRecognitionListener();
        mSpeechRecognizer = SpeechRecognizer.createSpeechRecognizer(this);
        mSpeechRecognizer.setRecognitionListener(h);
        mSpeechRecognizerIntent = new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);
        mSpeechRecognizerIntent.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,
                RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);

        mSpeechRecognizerIntent.putExtra(RecognizerIntent.EXTRA_CALLING_PACKAGE,
                this.getPackageName());

        PendingIntent pendingIntent = PendingIntent.getActivity(
                this,
                0,
                new Intent(this, MainActivity.class),
                0);

        numKeywordsDetected = 0;

        Notification notification = new NotificationCompat.Builder(this, CHANNEL_ID)
                .setContentTitle("Porcupine")
                .setContentText("num detected : " + numKeywordsDetected)
                .setSmallIcon(R.drawable.ic_launcher_background)
                .setContentIntent(pendingIntent)
                .build();

        startForeground(1234, notification);

        String modelFilePath = new File(this.getFilesDir(), "porcupine_params.pv").getAbsolutePath();

        String keywordFileName = intent.getStringExtra("keywordFileName");
        assert keywordFileName != null;
        String keywordFilePath = new File(this.getFilesDir(), keywordFileName).getAbsolutePath();

        try {
            porcupineManager = new PorcupineManager(
                    modelFilePath,
                    keywordFilePath,
                    0.5f,
                    (keywordIndex) -> {
                        numKeywordsDetected++;
                        CharSequence title = "Porcupine";
                        PendingIntent contentIntent = PendingIntent.getActivity(
                                this,
                                0,
                                new Intent(this, MainActivity.class),
                                0);

                        Notification n = new NotificationCompat.Builder(this, CHANNEL_ID)
                                .setContentTitle(title)
                                .setContentText("num detected : " + numKeywordsDetected)
                                .setSmallIcon(R.drawable.ic_launcher_background)
                                .setContentIntent(contentIntent)
                                .build();

                        NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
                        assert notificationManager != null;
                        notificationManager.notify(1234, n);
                        Log.d("created", "onBeginingOfSpeech");
                        mSpeechRecognizer.startListening(mSpeechRecognizerIntent);
                        Log.d("created", "onEndOfSpeech");
                    });
            porcupineManager.start();
        } catch (PorcupineManagerException e) {
            Log.e("PORCUPINE_SERVICE", e.toString());
        }

        return super.onStartCommand(intent, flags, startId);
    }

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }

    @Override
    public void onDestroy() {
        try {
            porcupineManager.stop();
        } catch (PorcupineManagerException e) {
            Log.e("PORCUPINE_SERVICE", e.toString());
        }

        super.onDestroy();
    }
}

log :
2020-07-25 11:44:17.109 18653-18653/com.example.androidforegroundservice I/regroundservic: Late-enabling -Xcheck:jni
2020-07-25 11:44:17.124 18653-18653/com.example.androidforegroundservice E/regroundservic: Unknown bits set in runtime_flags: 0x8000
2020-07-25 11:44:17.129 18653-18653/com.example.androidforegroundservice W/regroundservic: Core platform API violation: Ljava/lang/reflect/Field;->accessFlags:I from Landroid/os/Build; using reflection
2020-07-25 11:44:17.486 18653-18653/com.example.androidforegroundservice W/regroundservic: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2020-07-25 11:44:17.487 18653-18653/com.example.androidforegroundservice W/regroundservic: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2020-07-25 11:44:17.650 18653-18703/com.example.androidforegroundservice I/AdrenoGLES: QUALCOMM build                   : dc7175c, I423ca2612a
    Build Date                       : 09/12/19
    OpenGL ES Shader Compiler Version: EV031.27.05.01
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2020-07-25 11:44:17.650 18653-18703/com.example.androidforegroundservice I/AdrenoGLES: Build Config                     : S P 8.0.11 AArch64
2020-07-25 11:44:17.652 18653-18703/com.example.androidforegroundservice I/AdrenoGLES: PFP: 0x016ee187, ME: 0x00000000
2020-07-25 11:44:17.663 18653-18703/com.example.androidforegroundservice W/Gralloc3: mapper 3.x is not supported
2020-07-25 11:44:25.925 18653-18653/com.example.androidforegroundservice I/PICOVOICE:  [INFO] model file path: /data/user/0/com.example.androidforegroundservice/files/porcupine_params.pv
2020-07-25 11:44:25.925 18653-18653/com.example.androidforegroundservice I/PICOVOICE:  [INFO] number of keywords: 1
2020-07-25 11:44:25.925 18653-18653/com.example.androidforegroundservice I/PICOVOICE:  [INFO] keyword file path [0]: /data/user/0/com.example.androidforegroundservice/files/porcupine_android.ppn
2020-07-25 11:44:25.925 18653-18653/com.example.androidforegroundservice I/PICOVOICE:  [INFO] sensitivity [0]: 0.500000
2020-07-25 11:44:35.126 18653-18793/com.example.androidforegroundservice D/created: onBeginingOfSpeech

.

**Comment by kenarsa** [comment]
this is obviously not a porcupine issue. the server demo shows how to use porcupine in a foreground server. for a general android question you should try an android forum ...

**Comment by TackleIt** [comment]
So the issue may be closed, but just in case someone visits it later, since I had the same issue and came to see if there was any solution. Before android 10 there is only one microphone instance allowed so two audio record (one by porcupine one by speech recognition may not work) may not work on some devices (though some devices still support it.. The audio recorder set by porcupine manager is priority..

So if someone is facing that then call a function porcupinemanager.stop() which actually deletes the porcupine class to, so comment out that line and then try porcupinemanager.start() to start the hotword detection again. Also if it works then check audiorecorder class that also may need some modification to properly run on older devices

**Comment by vp2305** [comment]
> 
> 
> So the issue may be closed, but just in case someone visits it later, since I had the same issue and came to see if there was any solution. Before android 10 there is only one microphone instance allowed so two audio record (one by porcupine one by speech recognition may not work) may not work on some devices (though some devices still support it.. The audio recorder set by porcupine manager is priority..
> 
> So if someone is facing that then call a function porcupinemanager.stop() which actually deletes the porcupine class to, so comment out that line and then try porcupinemanager.start() to start the hotword detection again. Also if it works then check audiorecorder class that also may need some modification to properly run on older devices

Hey, Thanks for the reply I'm actually trying so hard to solve this problem currently. I understand that we need to stop porcupine from listening to the microphone so that speechRecognition can start listening but when I try to do porcupineManager.stop() it simply just doesn't work after that. I even commented out porcupineManager.destroy() line but it still doesnt help. I posted the question of stackoverflow but not many people care about portcupine I suppose: The link -> https://stackoverflow.com/questions/67394993/how-to-make-porcupine-detect-a-wake-word-and-then-start-listening-for-user-input.
