### ISSUE TITLE
An issue with my input audio file. Need make sure it's single-channel 16kHz, 16-bit PCM (was stereo)

### ISSUE THREAD

**Issue by ECG-Jacob** [Picovoice/porcupine#290]
### Expected behavior 
better exception handling and readable error messages with non-complying audio formats
an issue with your input audio file. Please make sure it's single-channel 16Hz, 16-bit PCM (seems like it's stereo)
possibly convert the stereo to single channel and throw warning 
### Actual behavior
type error explaining size-1 arrays
### Steps to reproduce the behavior
provide porcupine_demo_file.py with stereo audio file .wav 16kHz, 16bit
Include enough details so that the issue can be reproduced independently.
![porcupineError](https://user-images.githubusercontent.com/63876747/89666503-b665af00-d897-11ea-8a97-d920b19b3502.JPG)

**Comment by kenarsa** [comment]
Thanks for this. The new PR addressed this.
