### ISSUE TITLE
Feature request: just detect if user speeks

### ISSUE THREAD

**Issue by MHX792** [Picovoice/porcupine#291]
Would love to see such a feature.

Use case: if a user starts speaking (any word), it should trigger an action.

**Comment by kenarsa** [comment]
that won't be a wake-word engine. it is known as a voice activity detector (VAD). porcupine is and will remain a wake word engine. we do have VAD in picovoice but its meant for enterprise customers at this point we might release it in the future on GitHub as well. thanks for the feedback.
