### ISSUE TITLE
Using porcupine in software as an independent OSS developer

### ISSUE THREAD

**Issue by jagrosh** [Picovoice/porcupine#292]
As per the license/documentation, custom wake word models are only for personal use, and are only valid for 30 days. It appears that the only way to obtain wake word models that can be used beyond personal use (and I would assume without the time limit) is to purchase an enterprise license. However, the picovoice contact form, as well as the reply to #271, both imply that it is only possible to purchase this as a corporation.

Is my deduction correct that it is impossible to purchase an enterprise license (or any alternative to the free-tier availability) for using porcupine as an independent developer?

Note: I realize that github issues are not the ideal location for this type of query, but I am unable to use the contact form, as I am not inquiring about this on behalf of a company.

**Comment by kenarsa** [comment]
Thanks for the note. I do my best to clarify below.

1- You can use the model files available in the repo under permissive Apache 2.0. There are about 10 of them. That is all we have available for OSS development at the moment.
2 - The enterprise license is not necessarily without a time limit. Also, it does not fit OSS development requirements as it comes with a commercial license that has certain restrictions.
3- The personal models are made for "personal" use. i.e. education, research, or hobbyist projects.
