### ISSUE TITLE
8 kHz sampling rate, performance question

### ISSUE THREAD

**Issue by ltatakis** [Picovoice/porcupine#295]
Hello, 

I am limited by the hardware we have and its samples only at 8KHz.
I have noticed there is a slight reduction in performance compared to my laptop microphone sampled at 16 or 44kHz.
Do you have any numbers on how much that might be?  10-20% less accuracy? 
Could I fine tune that sensitivity?

Many thanks

**Comment by dbartle** [comment]
Porcupine is trained to process 16kHz audio. You can upsample 8kHz, but there will be degradation, as you have observed. As to quantifying that, we don't have any benchmarks for 8kHz as the product is not built for that use case.

Please see this related section of the Porcupine FAQ:
[https://picovoice.ai/faq/porcupine/#can-i-use-picovoice-software-for-telephony-applications](https://picovoice.ai/faq/porcupine/#can-i-use-picovoice-software-for-telephony-applications)
