### ISSUE TITLE
Recognition fails when in background on wear OS

### ISSUE THREAD

**Issue by mikeHalo** [Picovoice/porcupine#301]
Run the demo app on a watch device (I have tried on 3 different models, including a DM100). 
Leave the app front with the screen active, and it recognises the trigger word.
Lock the screen, and it does not.

This is a critical bug for a "wake word" service, and a show-stopper for us at the moment.

Here is a video of it in action
https://www.dropbox.com/s/npyg8m6f3r6pygv/pico_demo_failing_watch.mp4?dl=0

I believe the issue is within this method:

class ai.picovoice.porcupine
 private native int process (long object, short [] pcm); - This method

**Comment by kenarsa** [comment]
The demos are tested for Android (phone, tablets, and devices). They are NOT made to run on "Wear OS" and hence not tested on watches. We don't have support for "Wear OS" at this time. This is different from Apple counterpart where we support both iOS and watchOS. I'm keeping the issue open as a reference for the future if/when we add support for "Wear OS".

**Comment by mikeHalo** [comment]
Thanks for clarifying @kenarsa, that really wasn't clear to me at all from the website and sales materials. Do you know if Picovoice will intend to support "Wear OS"?

In the meantime, do you know of any alternatives that would support this please?

**Comment by kenarsa** [comment]
Wear OS is not on the roadmap at this point. If you have a large-scale commercial opportunity you can contact Picovoice https://picovoice.ai/contact/ and see if its something we can accommodate.
