### ISSUE TITLE
requirements.txt for OS X install?

### ISSUE THREAD

**Issue by butteryak** [Picovoice/porcupine#302]
Attempting to follow this installation procedure for porcupine on OSX.: https://picovoice.ai/quick-start/wake-word-macos/

There is no “requirements.txt” file in the repository.

How to proceed?

Thanks much++

Chris

**Comment by dbartle** [comment]
We're in the middle of a big reorganization of the code and that document is out of date. We will update it soon. Sorry about that and thanks for letting us know.

As part of this refactor, Porcupine and Rhino are receiving PIP package upgrades that make them easier to use than before. For now, check out the updated README here for instructions: https://github.com/Picovoice/porcupine/tree/master/binding/python
