### ISSUE TITLE
Compile libpv_porcupine

### ISSUE THREAD

**Issue by moritzschaefer** [Picovoice/porcupine#308]
Make sure you have read the documentation and have put reasonable effort to find an already-existing answer.

### Expected behaviour

Support/Instructions available to compile libpv_porcupine

### Actual behaviour

Not available

### Steps to reproduce the behaviour

Read the README

It's extremely frustrating that such a nice product (porcupine) is not made available to a major part of the open source community (e.g. Nixos on ARM64, compare #282). Please provide binaries for widely used hardware or provide information on how to compile the binaries ourselves.

Thank you

**Comment by kenarsa** [comment]
When opening an issue make an effort to properly edit the template in the future. _"Make sure you have read the documentation and have put reasonable effort to find an already-existing answer."_ could have been deleted before creating the issue, right?

Picovoice, as a company, **chooses** which platforms to support. We only provide binaries and SDKs for platforms we support. If this is not what you are looking for we understand and hope you find a better match somewhere else. We welcome your feedback though. The best way to influence our direction is to create an issue with a label such as "Feature Request: Support Platform XXX". If the issue gets a lot of traction (thumbs up) we **might** be able to add it to our roadmap.

**Comment by moritzschaefer** [comment]
Thank you for the explanation. I have thumbed up the according issue (https://github.com/Picovoice/porcupine/issues/282)
