### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by butteryak** [Picovoice/porcupine#310]
Hello, I'm trying to run porcupine_demo_mic --keywords picovoice after installation with pip3 install pvporcupine, the installation seems to run fine with no errors, I get a successfully installed pvporcupine-1.8.7 on a raspberry pi.  

### Actual behaviour

bash porcupine_demo_mic: command not found

### Steps to reproduce the behaviour

Include enough details so that the issue can be reproduced independently.

**Comment by butteryak** [comment]
pip3 list shows pvporcupine as an installed package.

**Comment by kenarsa** [comment]
you installed the engine package and not the demo. Please follow this:

https://github.com/Picovoice/porcupine/tree/master/demo/python#installation

**Comment by butteryak** [comment]
ah yes, I see, thanks++ got it

**Comment by shikhar2402** [comment]
I have run this command pip3 install pvporcupinedemo but porcupine_demo_mic --keywords porcupine this giving error porcupine_demo_mic --keywords porcupine please explain @kenarsa
