### ISSUE TITLE
Porcupine SDK for flutter

### ISSUE THREAD

**Issue by praharshbhatt** [Picovoice/porcupine#311]
Feature request: Porcupine SDK for flutter

**Comment by beevelop** [comment]
That would be highly appreciated on our site. Considering the recent adoption of Flutter this could be interesting for a growing developer base. We are happy to assist. :v:

**Comment by laves** [comment]
Hey @beevelop - good news, I'm currently working on Flutter SDKs for all of our core products here at Picovoice! I've created a plugin called [flutter-voice-processor](https://github.com/Picovoice/flutter-voice-processor) to deliver us native audio and am working over on a [flutter branch of Porcupine](https://github.com/Picovoice/porcupine/tree/flutter/binding/flutter) on the SDK. Our plan is to have Flutter SDKs available in the next couple weeks. Feel free to browse the code and let me know your thoughts!

**Comment by laves** [comment]
@beevelop @praharshbhatt Porcupine Flutter [SDK](https://github.com/Picovoice/porcupine/tree/master/binding/flutter) and [demo](https://github.com/Picovoice/porcupine/tree/master/demo/flutter) are officially out!

If you have any feedback, feel free to open a new issue to discuss it.
