### ISSUE TITLE
Demo jar compatibility with java 14+ only

### ISSUE THREAD

**Issue by achatellier** [Picovoice/porcupine#312]
### Expected behaviour

The command : `java -jar porcupine-mic-demo.jar -k picovoice` should work with java 8+(or at least java 11 LTS)

### Actual behaviour

Only works with Java 14+

### Steps to reproduce the behaviour

Execute the command : `java -jar porcupine-mic-demo.jar -k picovoice` with java 13 or less.

PS: actually, even the lib porcupine 1.8.7 is java 14+ only. (https://github.com/Picovoice/porcupine/tree/master/binding/java/bin)

**Comment by laves** [comment]
The documentation was inaccurate - the SDK had been built with JDK 15 and supported only 14+. We're added Java 11+ support and updated the documentation. Thank you for bringing this to our attention! Let us know if you're still having trouble running in 11+.

**Comment by kenarsa** [comment]
@achatellier I'm going to close the issue assuming it's resolved. if not, re-open, please.
