### ISSUE TITLE
Android showed as Restricted Platform in dashboard.

### ISSUE THREAD

**Issue by janesh001** [Picovoice/porcupine#314]
I have an Enterprise Account still I can't be able to create custom New Wake up word for Android.
Account address = sales@levelrideairsuspension.com.
Please help me.
![Screenshot (109)](https://user-images.githubusercontent.com/31646400/99580366-699c8300-2a05-11eb-829a-49d7920c00ec.png)

**Comment by dbartle** [comment]
When signing up for an account on Picovoice Console, the documentation stated that the trial includes only Linux, macOS, and Windows platforms, and that access to other platforms required contacting Picovoice. The dropdown was working as intended.

Today is your lucky day, as Enterprise account 30-day trials now have Porcupine training for the Android platform (and all others).

For continued use of Enterprise accounts beyond 30 days, and access to platforms and training allowances, use the contact form here: https://picovoice.ai/contact/. GitHub is intended for bugs only, not commercial enquiries.
