### ISSUE TITLE
.Net Mic demo not working

### ISSUE THREAD

**Issue by alvaromongon** [Picovoice/porcupine#317]
### Expected behaviour
Mic demo works when getting master branch and running the documented dotnet command.

### Actual behaviour
It fails with this error:
`System.ArgumentException: Both 'keywords' and 'keywordPaths' were set. Only one of the two arguments may be set for intializtion.
es)
   at PorcupineDemo.MicDemo.RunDemo(String modelPath, List`1 keywordPaths, List`1 keywords, List`1 sensitivities, Nullable`1 audioDeviceIndex, String outputPath) in C:\Code\voicecontrol\porcupine\demo\dotnet\PorcupineDemo\MicDemo.cs:line 58
   at PorcupineDemo.MicDemo.Main(String[] args) in C:\Code\voicecontrol\porcupine\demo\dotnet\PorcupineDemo\MicDemo.cs:line 318`

I made it work locally, but by reading at the "Porcupine.Create" method, it looks like the demo code should work as it is.

### Steps to reproduce the behaviour
- Get master branch updated locally
- Navigate to the correct directory where the MicDemo.cs file is located
- Copy/Paste the command to test it as defined in the readme file: "dotnet run -c MicDemo.Release --keywords porcupine"
- Run the command

Include enough details so that the issue can be reproduced independently.

**Comment by laves** [comment]
Hi there, thanks for reporting this. We recently identified this regression and will have a fix being merged to master shortly.

**Comment by laves** [comment]
The fix has been merged into master. Let us know if you have any additional problems.
