### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by StuartIanNaylor** [Picovoice/porcupine#321]
Just wondered if you guys had ever thought about a ESP32 version?

Just some feedback as yeah that would be awesome.

**Comment by kenarsa** [comment]
@StuartIanNaylor thanks a lot for this. Let's keep the issue open and see how many people would have the same request. Also, just a note that Espressif has some audio libraries for their ESP32 as well. Have you looked into them?

**Comment by StuartIanNaylor** [comment]
Yeah they also have a closed source KWS that operates in a similar way with a few free KW models.
Also there are some homebrew opensource tensorflow repo's that are also quite good.

I was just having a recap of 1.9 and looking at the additional models for the Pi and just had a thought as generally I rate porcupine as one of if not the best KWS that it would be really cool to have this on a ESP32.

I am starting to see distributed KWS mics as a way forward in interoperable voice equipment and the ESP32 has an excellent ADF and starting to have preference over a Pi.

**Comment by gigawatts** [comment]
Also very interested in this! I've got [this ESP32 based conference badge](https://github.com/poplicola/Thotcon0xA_Pub/tree/master/AudioStreaming) with a I2S Microphone and a very basic audio streaming VoIP demo. I would love to do native simple word recognition locally with something like this library!

**Comment by Romkabouter** [comment]
+1

**Comment by ayavilevich** [comment]
Thanks for making Picovoice Porcupine available for micro-controlers. Unfortunately STM32 MCs have no built-in networking. It would be great to see the same offered to the ESP32 modules. This would allow to make more interesting devices/projects.

**Comment by philosoapy** [comment]
I'd love to see ESP32 support for picovoice. Just recently Arduino Nano 33 BLE support was released. ESP32 is even more powerful an even less energy consuming from what I read. Which makes it perfect for distributed voice recognition.
Would be perfect to have it implemented in Romkabouter's project, too.

**Comment by krembuk** [comment]
waiting for this, too. they have lovely audio boards.

**Comment by StuartIanNaylor** [comment]
The new esp32-S3 have vector instructions that garner approx 4-6x ML performance with optimised code.
Also the dsp FFT libs for 16bit fixed point have been optimised and give just short of x10 over the previous ESP32.

https://docs.espressif.com/projects/esp-dsp/en/latest/esp-dsp-benchmarks.html

**Comment by kenarsa** [comment]
out of curiosity ... why not use libraries provided by ESP for voice recognition? We have ESP on our radar for sure but from far it seems that it should be self-contained for voice recognition already. comments are super welcome and helpful for Picovoice team to figure out prioritization.

**Comment by StuartIanNaylor** [comment]
> out of curiosity ... why not use libraries provided by ESP for voice recognition? We have ESP on our radar for sure but from far it seems that it should be self-contained for voice recognition already. comments are super welcome and helpful for the Picovoice team to figure out prioritization.

To be honest that is very much an option but Espressif have chosen a closed source blob option with prebuilt KW models so if you don't like 'Hi Lexin' or 'Hi ESP' tough as that is your lot unless you want to pay Espressif to do training for you.

One thing that is available on ESP32-S3 is there ADF of AEC->BSS->NS which I mention as have you guys got any plans as noticed you had added VAD to your offerings.

Combination of Picovoice and ESP ADF so you do get custom KW could be very interesting but really many are expecting the esp32-S3 to garner economies of sale where it will be a very cost effective KWS platform and to not be present on that platform is a big loss.
Currently its new but when silicon starts shipping in qty and clones start to appear its likely to become much cheaper and the x4-6 ML improvements < x10 FFT over the ESP32 make it a very interesting propisition.

There is always tflite-micro as opposed to ESP-DL as ESP-DL omits GRU & LSTM layers but currently tflite-micro IDF implementation points to the older tensorflow repo and again it might be down to Espressif if they try force limited support for ESP-DL or update the IDF & wakenet offerings to be more open.

**Comment by kenarsa** [comment]
This is helpful. We don't have current plans for `audio-frontend` engines but as you mentioned with `VAD` things can change.

Thank you for the information. It helps. I think we will add support for a `non-Arm` MCU/DSP in 2022. Not clear who is the winner but a `RISC-V`-based platform is at the top of our list at the moment.

**Comment by StuartIanNaylor** [comment]
The IDF gets a major update in https://github.com/espressif/esp-idf/releases/tag/v4.4-beta1 where much is S3 concentric.
Not sure what system features are currently supported and which CPU instruction extensions for DSP/AI will be in 4.4

**Comment by kenarsa** [comment]
We didn't manage to make this a priority over time and unfortunately, it doesn't seem like we can in the coming months. I am closing this for now. I hope that espressif changes their policy regarding their SDK and help out their users a bit more but we don't have resources right now to help out with this. If things changes I will re-open to track.

**Comment by StuartIanNaylor** [comment]
> Came across this issue today (2023) and sadly the issue still remains. ESP32 _should_ have pretty much all the native functionality built-in to both the hardware and the ESP-IDF, but the inability to specify a custom wake word cripples it for most people :(

It does have both hardware and ESP-IDF built in https://github.com/espressif/esp-nn and supports the TF4Micro like examples here https://github.com/espressif/tflite-micro-esp-examples

They only provide prebuilt and customization services for those who are clueless how to build there own.

**Comment by ohmguru** [comment]
Just wanted to add another request for ESP32 support.
