### ISSUE TITLE
node.js binding for Windows

### ISSUE THREAD

**Issue by soerson** [Picovoice/porcupine#327]
**Is your feature request related to a problem? Please describe.**
I updated porcupine to version 1.9.0 and noticed that it doesn't support Windows any more. Do you have plans to add node.js binding for Windows?
Thank you

**Comment by kenarsa** [comment]
We moved away from FFI to N-API in v1.9 as FFI was unstable. This meant that we needed to compile the engine on Windows using VisualStudio which proved to be hard and hence we put it in our queue for now. There is the intention to add Windows support in the future. If you know a way to use GCC toolchains (e.g. Mingw) for N-API compilation on Windows we might be able to accelerate this. Thanks!

**Comment by soerson** [comment]
Unfortunately I don't have any experience with N-API on Windows

**Comment by kenarsa** [comment]
Thanks. I will close this for now. But will comment on the issue when we add support for Windows in the future as we don't have dates for it yet.
