### ISSUE TITLE
Details on dataset used to train alexa wakeword

### ISSUE THREAD

**Issue by MatthewScholefield** [Picovoice/Porcupine#33]
I was looking at the [wakeword-benchmark](https://github.com/Picovoice/wakeword-benchmark) utility and I was wondering what data was used to train the [alexa_\<PLATFORM\>.ppn](https://github.com/Picovoice/Porcupine/tree/master/resources/keyword_files) models.

**Comment by kenarsa** [comment]
The testing dataset is available here: https://www.kaggle.com/aanhari/alexa-dataset

We don't train our engine on recordings of specific wake-word. Hence, we can be self-service in the sense that we don't need training data for specific wake-words. For training Porcupine we use a set of open-source datasets including common voice, librispeech, etc.

**Comment by MatthewScholefield** [comment]
That's interesting to hear. Thanks for the info!

**Comment by GEORGJOSE007** [comment]
Is data available at https://www.kaggle.com/aanhari/alexa-dataset same as the one given in this repository?
