### ISSUE TITLE
Ability to fine tune voice model

### ISSUE THREAD

**Issue by mboudreau** [Picovoice/porcupine#330]
I'm currently trialing Porcupine for a small subset of commands and it seems to work decently well with my Canadian accent with some occasional misses, but the problem becomes much worse for the Australian accent.  We are building a product that is to be piloted in Australia.  I tried reducing the sensitivity without much luck.

Is there a way for me to train the model further? We can train it using local voices and further more once we have the pilot out.  the commands are fairly simple: "Ok Chef" as a wake word, then "Next step", "Previous Step", "Repeat Step", "Mute", "Unmute", "Pause" and "Resume". "Ok Chef" seems to be the one that's the most difficult to detect and the most important as it's the wake word that activates the next command.

It would be great if you had something like Snowboy where you could build up your model for your commands based on real voice input from people.  I think it would add a lot of value as your customers could feed in more data to make the model more accurate for their use case over time.

Thanks.

**Comment by kenarsa** [comment]
Did you mean increasing the sensitivity? Cause reducing won't definitely help :)

We don't have that capability but for enterprise users who are engaged with us, we can fine-tune internally for any given accent given a set of a sample dataset.

**Comment by mboudreau** [comment]
@kenarsa Right.  I misunderstood that since it's called `sensitivity` and figured it meant the inverse since high sensitivity would mean less false positive.  Wouldn't it be better to call it `tolerance` instead?
