### ISSUE TITLE
Porcupine Issue Android Service :  Can't use my microphone in other apps while the foreground service is running

### ISSUE THREAD

**Issue by hussaintt** [Picovoice/porcupine#331]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
The microphone run in the background and stop recording when other application request the microphone.
### Actual behaviour
The app prevent the other apps from using the microphone , like phone calls etc

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

**Comment by laves** [comment]
We've looked into this and it seems sharing audio between services and apps is not supported in Android < 10. You can read more about it [here](https://developer.android.com/guide/topics/media/sharing-audio-input). 

If you require Android < 10 support and you plan to use Porcupine on a background service to trigger another audio recording source, you would have to communicate to the Porcupine service to stop recording audio temporarily and then restart it after your other device has finished recording audio.
