### ISSUE TITLE
Raspberry or RaspberryPi as a keyword?

### ISSUE THREAD

**Issue by StuartIanNaylor** [Picovoice/porcupine#332]
Would be so great and would get a lot of use as apols guys porcupine just feels odd :)

**Comment by kenarsa** [comment]
Thanks! Let's keep this open and see how many community members would want it. If there is a lot of interest happy to add in the next release :)

**Comment by RaspiManu** [comment]
I would be interested because "Porcupine" is hard to pronounce the correct way if you are no native speaker of English.

**Comment by Jeinzo** [comment]
That would be great and it sounds cool

**Comment by StuartIanNaylor** [comment]
If there are enough takers I have no probs uploading several samples to my google drive in a zip as we could quickly make a distributed dataset of 'raspberry' or 'raspberrypi'

**Comment by ionultd** [comment]
Raspberry KW would be good. I would also contribute.

**Comment by StuartIanNaylor** [comment]
https://drive.google.com/file/d/1nUymdKwznGxQgiec7rbhhXihkGaJ-nnL/view?usp=sharing
https://drive.google.com/file/d/1chI26qc7quhUq2RcK1y2ojFG3qMgP1yq/view?usp=sharing

**Comment by ionultd** [comment]
Is this your contribution? Is this being considered?

**Comment by StuartIanNaylor** [comment]
Yeah if it ever does they have 20xraspberry & 20xraspberrypi of my dulcet voice :)

Hopefully

**Comment by ionultd** [comment]
@stuartlannaylor Oh right. u being proactive. Nice!

**Comment by kenarsa** [comment]
@StuartIanNaylor thanks for this and I appreciate you being proactive! We will be able to provide the model without you guys providing audio data. If the interest level goes up with the same cadence since the issue is opened I think we can include it in the next release of Porcupine!

**Comment by glcos** [comment]
Great idea, I'm supporting this and looking forward to seeing the "raspberry" wake word to be included in the next release.

**Comment by kenarsa** [comment]
Since the release of `v2`, 2 good things happened for makers: (1) you can create `PPN` models for RPI (2) models don't expire. Go ahead now and create the models requested above on Console yourself! As part of `v2` release, the only limitation is the number of devices you can deploy to which should not be a problem for hobbyist users.
