### ISSUE TITLE
How do you show the last hit score

### ISSUE THREAD

**Issue by StuartIanNaylor** [Picovoice/porcupine#333]
Sure it must be documented somewhere but how do you get the the hit score of the last KW result in python?

Thanks

**Comment by StuartIanNaylor** [comment]
Apols to ask again as only been a couple of days but have a hunch this should be easy but nothing google wise is pointing me the right way.

Is there a method to give the confidence level of the last key word hit?

**Comment by kenarsa** [comment]
The current API doesn't give you that. What's a use-case? We might be able to brainstorm another solution ...

**Comment by StuartIanNaylor** [comment]
I wanted to run 2 KWS on separate mics and pic the best hit.

**Comment by kenarsa** [comment]
Got it. Yeah unfortunately we don't have confidence metric in our API. You can try running several engines with different sensitivity params to emulate this but it would consume extra resources obviously. Hope it helps.

**Comment by StuartIanNaylor** [comment]
Just for feedback not being able to access the confidence metric in the API which must exist is actually quite a bit of a showstopper on employment.
Its not just for best hit instances but also judging how well a current setup is performing so choice can be made on sensitivity params which currently is a guess ?!?

**Comment by kenarsa** [comment]
Not a guess. One can create a ROC curve using the framework here: https://github.com/Picovoice/wake-word-benchmark

**Comment by StuartIanNaylor** [comment]
> Not a guess. One can create a ROC curve using the framework here: https://github.com/Picovoice/wake-word-benchmark

To create multiple instances of incrementing sensitivity with a recorded KW might be ok but to do it on a stream would seem very much a guess.

its a shame such a simple return is missing.
