### ISSUE TITLE
React-Native : ppn file not found

### ISSUE THREAD

**Issue by jordan-tpz** [Picovoice/porcupine#336]
I use Porcupine with my React-Native project. All works fine using `PorcupineManager.fromKeyword` with a keyword as string.

But I have decided to create my wake word model using the [Picovoice console](https://picovoice.ai/console/). Therefore, I have moved the downloaded **.ppn** file within a specific folder in my app src folder.
Then, I use `PorcupineManager.fromKeywordPaths` by passing the given file path. But, it seems like React-Native doesn't support the **.ppn** extension by default (for instance, I have used another extension than .ppn and the file exists for my app).

Any idea to enable the .ppn external files in React-Native ?

**Comment by laves** [comment]
A limitation of React Native seems to be that you can't store and load binary files as part of your JS package. However, you can add them as assets in the Android/iOS projects and get their file paths with [react-native-fs](https://www.npmjs.com/package/react-native-fs/v/1.2.0). You can see an example of how we do this with Rhino context files (.rhn) in our [React Native demo](https://github.com/Picovoice/rhino/blob/master/demo/react-native/App.tsx). An extra annoyance of using binary files as Android assets is that you have to extract them before you load them. 

If you know of any way around this, please let us know! For now, I'll be sure to add this limitation to our docs so it doesn't cause further confusion.

**Comment by jordan-tpz** [comment]
@laves thanks for your quickly feedback ! 

I'll check your [React Native demo](https://github.com/Picovoice/rhino/blob/master/demo/react-native/App.tsx), particularly the [react-native-fs](https://www.npmjs.com/package/react-native-fs/v/1.2.0) package. 

I'll do my feedback ASAP.

**Comment by jordan-tpz** [comment]
So, I have tried to use [react-native-fs](https://www.npmjs.com/package/react-native-fs/v/1.2.0) in order to store and load binary files (ppn files), and all works fine for me !

If it can help somebody, I share a code snippet and all main steps : 

1) Like the [copy.js](https://github.com/Picovoice/rhino/blob/master/demo/react-native/copy.js) demo file, I copy my ppn file within the Android assets folder.

2) Then, I use the [react-native-fs](https://www.npmjs.com/package/react-native-fs/v/1.2.0) package in order to get my ppn file path :

```js
const RNFS = require('react-native-fs');

let keywordName = 'your_keyword_name';
let keywordFilename = `${keywordName}.ppn`;

if (isAndroid) {
  keywordPath = `${RNFS.DocumentDirectoryPath}/${keywordFilename}`;
  await RNFS.copyFileRes(keywordFilename, keywordPath);
} else if (isIos) {
  keywordPath = `${RNFS.MainBundlePath}/${keywordFilename}`;
}
```

3) To conclude, I can use the `PorcupineManager.fromKeywordPaths` function to load my custom wake word model :

```js
await PorcupineManager.fromKeywordPaths(
  [keywordPath],
  detectionCallback
); 
```

**Comment by laves** [comment]
Great! Glad to hear it worked out. We'll be adding this to our documentation to help users in the future

**Comment by jeet-mehta** [comment]
> So, I have tried to use [react-native-fs](https://www.npmjs.com/package/react-native-fs/v/1.2.0) in order to store and load binary files (ppn files), and all works fine for me !
> 
> If it can help somebody, I share a code snippet and all main steps :
> 
> 1. Like the [copy.js](https://github.com/Picovoice/rhino/blob/master/demo/react-native/copy.js) demo file, I copy my ppn file within the Android assets folder.
> 2. Then, I use the [react-native-fs](https://www.npmjs.com/package/react-native-fs/v/1.2.0) package in order to get my ppn file path :
> 
> ```js
> const RNFS = require('react-native-fs');
> 
> let keywordName = 'your_keyword_name';
> let keywordFilename = `${keywordName}.ppn`;
> 
> if (isAndroid) {
>   keywordPath = `${RNFS.DocumentDirectoryPath}/${keywordFilename}`;
>   await RNFS.copyFileRes(keywordFilename, keywordPath);
> } else if (isIos) {
>   keywordPath = `${RNFS.MainBundlePath}/${keywordFilename}`;
> }
> ```
> 
> 1. To conclude, I can use the `PorcupineManager.fromKeywordPaths` function to load my custom wake word model :
> 
> ```js
> await PorcupineManager.fromKeywordPaths(
>   [keywordPath],
>   detectionCallback
> ); 
> ```

So to work in react native you must use rhino manager for getting the wake words from ppn files ?
