### ISSUE TITLE
porcupine support on Jetson Nano

### ISSUE THREAD

**Issue by xtendDemo** [Picovoice/porcupine#339]
hello,
Porcupine can be installed on Jetson Nano?

**Comment by kenarsa** [comment]
Not officially. You might be able to run RPI or BB builds on it but it is essentially hacky. Let's keep the issue open to measure interest from the community and we might be able to add support for Jetson family in the future.

**Comment by mrrostam** [comment]
Jetson nano has been added to the supported platforms. For more information please refer to [Jetson Quick Start](https://picovoice.ai/docs/quick-start/porcupine-jetson/).

**Comment by hannesa2** [comment]
Great, thank you ! I write here to show you I'm interested too

**Comment by kenarsa** [comment]
@hannesa2 it is supported already!!!!

**Comment by XIA-ncepu** [comment]
> Jetson nano has been added to the supported platforms. For more information please refer to [Jetson Quick Start](https://picovoice.ai/docs/quick-start/porcupine-jetson/).

Subject: Inquiry about Jetson Support for Custom Wake Words

Hi there,

According to the information at the link you provided, I noticed that the Jetson platform is no longer listed as an option for custom wake word functionality. Could you confirm whether support for Jetson Nano (or Jetson devices in general) has been discontinued?

Thanks for clarifying!
