### ISSUE TITLE
run javasript demo happend error: no such files

### ISSUE THREAD

**Issue by MuuuJian** [Picovoice/porcupine#340]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
npm install
npm install -g copy-files-from-to
--> copy-files-from-to     ( theres no such files )
npx serve

### Actual behaviour
Starting copy operation in "default" mode: (overwrite option is on)

 ✗ Failed to copy rhino.js
 ✗ Failed to copy pv_rhino.js
 ✗ Failed to copy pv_rhino.wasm
 ✓ Copied [ utf8 ] ../shared/picovoice_worker.js to picovoice_worker.js
 ✓ Copied [ utf8 ] ../shared/picovoice_manager.js to picovoice_manager.js
 ✗ Failed to copy pv_porcupine.js
 ✗ Failed to copy pv_porcupine.wasm
 ✗ Failed to copy porcupine.js

sorry to disturb you, Im a green hand to learn javascript voice demo, and I dont know why the project lack the such files (rhino.js, pv_rhino.js....), do I supposed to npm install others?

**Comment by dbartle** [comment]
It looks like you're running these commands from the JavaScript demos of the _Picovoice_ repository (not the Porcupine repository).

No, you do not need to do any additional NPM installs. The reason it's failing to find those files is that the Picovoice repository includes git submodules, and by default when you `git clone` a repo, it does not recursively clone all of the submodules. Initialize the submodules with this command:

```git submodule update --init --recursive```

**Comment by MuuuJian** [comment]
> It looks like you're running these commands from the JavaScript demos of the _Picovoice_ repository (not the Porcupine repository).
> 
> No, you do not need to do any additional NPM installs. The reason it's failing to find those files is that the Picovoice repository includes git submodules, and by default when you `git clone` a repo, it does not recursively clone all of the submodules. Initialize the submodules with this command:
> 
> `git submodule update --init --recursive`

--------
thanks a lot for helping, as you say, I don't realize git clone the "Picovoice" repository until your help,  and now I clone the Porcupine repository ,JavaScript demo runs excellent well! thanks again~
