### ISSUE TITLE
Support Cortex-A55

### ISSUE THREAD

**Issue by quanghd96** [Picovoice/porcupine#343]
I have a linux machine arm64. Can you support Cortex-A55?

**Comment by kenarsa** [comment]
If this for a personal project include your board information and change the title accordingly, please. If a lot of people ask for the same board then we can consider if. If this is for a commercial project please close the issue and submit a formal request https://picovoice.ai/contact/sales/

**Comment by quanghd96** [comment]
I'm working on a device at school. I want to use wake word to wake it up. Unfortunately you do not support this chip yet. 
It uses arm64 architecture (chip s905 x3). Can you support it in future?

**Comment by 16120176** [comment]
Same issue. I try it on linux arm machine. But it not work

**Comment by kenarsa** [comment]
The repo's readme mentions the list of the supported platform. What you are using is not supported at this time.
