### ISSUE TITLE
Add support for Ubuntu on Raspberry Pi

### ISSUE THREAD

**Issue by andrejmlyncar** [Picovoice/porcupine#345]
### Expected behaviour
Python SDK should be working correctly on Raspberry PI 4 Model B (arm cortex-a72) with Ubuntu arm64bit OS installed. 

### Actual behaviour
OS distribution: https://ubuntu.com/download/raspberry-pi/thank-you?version=20.04.1&architecture=server-arm64+raspi (Linux ubuntu 5.4.0-1026-raspi #29-Ubuntu SMP PREEMPT Mon Dec 14 17:01:16 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux)

In python SDK, there is method _pv_linux_machine(machine) which extract cpu information from /proc/cpuinfo file. Problem is that this file does not contain "model name" information. Only valid available information are:
```
Hardware	: BCM2835
Model		: Raspberry Pi 4 Model B Rev 1.4
```
Because of this, following error is thrown when initializing SDK:
``` 
 File "/usr/local/lib/python3.8/dist-packages/pvporcupine/__init__.py", line 13, in <module>
    from .util import *
  File "/usr/local/lib/python3.8/dist-packages/pvporcupine/util.py", line 54, in <module>
    _PV_SYSTEM, _PV_MACHINE = _pv_platform()
  File "/usr/local/lib/python3.8/dist-packages/pvporcupine/util.py", line 47, in _pv_platform
    pv_machine = _pv_linux_machine(platform.machine())
  File "/usr/local/lib/python3.8/dist-packages/pvporcupine/util.py", line 24, in _pv_linux_machine
    model_info = [x for x in cpu_info.split('\n') if 'model name' in x][0]
IndexError: list index out of range
```
After manually adjusting method to return harcoded string "cortex-a72", following error is displayed:
```
 File "/usr/local/lib/python3.8/dist-packages/pvporcupine/__init__.py", line 64, in create
    return Porcupine(
  File "/usr/local/lib/python3.8/dist-packages/pvporcupine/porcupine.py", line 60, in __init__
    library = cdll.LoadLibrary(library_path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.8/dist-packages/pvporcupine/lib/raspberry-pi/cortex-a72/libpv_porcupine.so: wrong ELF class: ELFCLASS32
```
I am assuming that this error occurs because binary is compiled for 32bit arch. 
### Steps to reproduce the behaviour

1. Install 64bit Ubuntu version (https://ubuntu.com/download/raspberry-pi) on RPi with ARM Cortex-A72
2. Run command `pip3 install pvporcupine`
3. Run command `python3 -c "import pvporcupine;  pvporcupine.create(library_path=pvporcupine.LIBRARY_PATH, model_path=pvporcupine.MODEL_PATH, keyword_paths=[pvporcupine.KEYWORD_PATHS['computer']], sensitivities=[0.5])"`

**Comment by kenarsa** [comment]
We only officially support Raspbian on RPI at this time. Switching to Raspbian would solve your problem for sure. We will look into adding Ubuntu support with the next couple of months though.

**Comment by pga-avionics** [comment]
Hi,
I'm also experiencing the same issue after trying to "tweak" the code so the machine name returned is "cortex-a72".
Unfortunatly it failed afterwarrd.
That's a tricky issue as we're prototyping an ASR applicaztion on a Rpi4-64 8GB model. The linux installed is created with Yocto.
Do you plan to support rpi4-64 in the close future ?

**Comment by CobraCalle** [comment]
+1 for me... running my voice assist on ubuntu 64bit... would be perfect if it would be possible to use porcupine here...

**Comment by kenarsa** [comment]
this should be fixed now! If you upgrade to the latest PIP package you should be able to run on 64-bit Raspbian/Ubuntu. Please reopen this issue if you still have issues.
