### ISSUE TITLE
Porcupine Issue: Failed to archive iOS build (react-native)

### ISSUE THREAD

**Issue by superserg8** [Picovoice/porcupine#346]
### Expected behaviour
Archive without failing.

### Actual behaviour
Can't archive react-native build (demo), have the same error as in #22

`bitcode bundle could not be generated because '.../node_modules/@picovoice/porcupine-react-native/ios/pv_porcupine/libpv_porcupine.a(pv_porcupine.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64`

### Steps to reproduce the behaviour
1. Download Porcupine iOS Demo
2. Product > Archive

**Comment by superserg8** [comment]
@kenarsa @laves any updates on that?

As a temporary solution, I disabled bitcode in Build Settings for the whole project but this is the wrong way for production...

**Comment by laves** [comment]
@superserg8 we were able to reproduce the bug and we're testing the fix now. Expect a patch in the coming days!

**Comment by laves** [comment]
@superserg8, the fix to the porcupine iOS lib has been merged in. On our end we're able to archive all of our demos. Please confirm this and we'll close the issue. Thanks for reporting!

**Comment by superserg8** [comment]
@laves yep, it works now, thanks a lot!
