### ISSUE TITLE
Flutter/iOS Error: Failed to lookup symbol (dlsym(RTLD_DEFAULT, pv_porcupine_init): symbol not found)

### ISSUE THREAD

**Issue by nermolov** [Picovoice/porcupine#353]
Attempting to use the Flutter library in an Archive -> Test Flight environment causes an error. Works fine in Ad Hoc debug and release builds.

### Expected behaviour

* Initializing porcupine in a release (Archive) environment works

### Actual behaviour

* Error `Failed to lookup symbol (dlsym(RTLD_DEFAULT, pv_porcupine_init): symbol not found)` occurs

### Steps to reproduce the behaviour

* Set up new flutter project
* Add porcupine
* Initialize porcupine with built in keyword
* Archive and upload application to testflight
* Download and test on device

**Comment by laves** [comment]
Thanks for reporting. Looks like the default archiving process is stripping out the Porcupine library. We'll look into this and get back to you.

**Comment by nermolov** [comment]
Editing the Runner build setting Deployment -> Strip Style -> Non-Global Symbols fixes this issue. Maybe that should be documented?

**Comment by laves** [comment]
Ah, yes - we had come across this workaround before! With our SDKs, we're really trying to avoid asking devs to change their project compilation settings, so we favoured another solution. However, this issue you encountered proved that the other solution wasn't 100% effective.  We'll document your project settings change for now, but we'll return to the Flutter SDK shortly to find something air-tight. Thanks!

**Comment by laves** [comment]
@nermolov - good news! We've just upgraded our iOS libraries to frameworks and it seems to have fully addressed this issue of symbol stripping in Flutter. Pull latest and retry the Testflight process - you shouldn't have that error anymore. Thanks for reporting this!
