### ISSUE TITLE
iOS Porcupine Issue: 

### ISSUE THREAD

**Issue by windowmirror** [Picovoice/porcupine#359]
I'm running a test in Xcode and keep coming up with this error: 

<module-includes>:1:1 warning: umbrella header for module 'porcupine' does not include header 'pico voice.h'
#import "Headers/porcupine-umbrella.h"

I've added an image as well 

Thoughts?

<img width="979" alt="picovoice-issue" src="https://user-images.githubusercontent.com/34893202/108412905-f9fa8780-71ef-11eb-9aa8-edc97baf7ca9.png">

**Comment by laves** [comment]
Update porcupine to latest (1.9.6) and you should no longer receive this warning.
