### ISSUE TITLE
Does Porcupine have NodeJS Windows support?

### ISSUE THREAD

**Issue by kingofsquirrel** [Picovoice/porcupine#360]
So, whenever I'm trying to implement porcupine in my code it says platform not supported and on the npm website it also says windows not supported, but on the picovoice website it says that Porcupine is supported on windows. So I was wondering does the npm package or NodeJs in general support Porcupine on Windows? Thanks in advance!

**Comment by kenarsa** [comment]
NodeJS binding doesn't support Windows. You can use C#, Java, Python, Unity, or C on Windows.
