### ISSUE TITLE
Porcupine in AVS SDK

### ISSUE THREAD

**Issue by GitHubUser4234** [Picovoice/porcupine#372]
Hi,

Is there a Keyword Detector class for the AVS SDK yet? Or is there at least a plan/roadmap to provide such class? It would be great to use the SDK with porcupine instead of Sensory/Kitt.AI.  Thanks!

**Comment by kenarsa** [comment]
We don't have a plan at Picovocie to do this. But if someone writes one and prove that it works I'll be up for looking into the PR.
