### ISSUE TITLE
Do not understanding making own keyword files

### ISSUE THREAD

**Issue by cshaw16** [Picovoice/porcupine#374]
Hello,

I know this is not a code issue but I am unsure how to make my own keyword file. Following the python demo I see I do this in a file name new_keywords_.py 

import pvporcupine

handle = pvporcupine.create(keywords=['stop', 'go'])

Would I save this as a python file in resources/keyword_files and then convert the python file to binary using xxd -i -g 1 resources/keyword_files/new_keywords_.py and then run porcupine_demo_mic --keyword_paths ../../resources/keyword_files/new_ketwords.py?

I simply do not understand the ppn files required.

**Comment by cshaw16** [comment]
I also tried using PicoVoice to train a model and downloaded the yml file, how would I utilize that with the python demo if it is not a ppn file.

**Comment by dbartle** [comment]
PPN files are trained Porcupine keyword models representing a wake word / wake phrase. They are binary files (i.e. they're not text or yaml format). There are some included in this GitHub repo that are freely licensed under Apache 2.0. To generate custom ones, you need to train them in Picovoice Console: https://picovoice.ai/docs/quick-start/console-porcupine/.

Those docs, along with the Python docs and the demo should be enough to get going.
