### ISSUE TITLE
Porcupine Documentation Issue

### ISSUE THREAD

**Issue by bramses** [Picovoice/porcupine#380]
### What is the URL of the doc?

https://picovoice.ai/docs/faq/porcupine/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

I'd like to know if Porcupine can handle wake words on-device, and then hand off voice processing and intent to a third party solution (in this case Jovo). We have already built much of our intent work into Jovo, and switching off isn't really an option. I couldn't find anything in the FAQ that addressed this kind of workflow.

Thanks!

**Comment by kenarsa** [comment]
yes! the description of the repository says "On-device wake word detection powered by deep learning."

you need to implement the handoff logic yourself. Porcupine really doesn't care what you use after for intent parsing and if you use anything at all.
