### ISSUE TITLE
Porcupine Issue: spanish models don't work

### ISSUE THREAD

**Issue by manucaro** [Picovoice/porcupine#381]
I've tried every keyword file for Raspberry Pi in spanish and I get the same error. I work with Python.
![Captura](https://user-images.githubusercontent.com/79217115/111507204-b2154480-874a-11eb-9dbc-6ec8c42bfb64.PNG)

**Comment by kenarsa** [comment]
whats the actual error?

**Comment by kenarsa** [comment]
can you produce a repo with the code you are using? then I can try to reproduce and help out. the screenshot really doesn't help out with that.

**Comment by manucaro** [comment]
OK, sorry. Here is my code. https://github.com/manucaro/picovoice

**Comment by kenarsa** [comment]
OK. makes more sense now. Though I expected you to get a different error. You need to pass in the porcupine and rhino PV files for Spanish as well as the defaults are for English. The documentation can be better.

[porcupine_model_path](https://github.com/Picovoice/porcupine/blob/master/lib/common/porcupine_params_es.pv)
[rhino_model_path](https://github.com/Picovoice/rhino/blob/master/lib/common/rhino_params_es.pv)

**Comment by manucaro** [comment]
That was the problem. Thank u so much!
