### ISSUE TITLE
JNI for Raspberry Pi

### ISSUE THREAD

**Issue by TadejLogar** [Picovoice/porcupine#384]
Java is currently supported on Linux, macOS and Windows. It would be great to also add JNI libraries for Raspberry Pi.

**Comment by kenarsa** [comment]
Thanks for the feedback. What would be the use case? I'm wondering what people are using Java for on RPI these days...

**Comment by TadejLogar** [comment]
I am working on a home assistant for my own needs. Backend is written in Java and Spring boot framework.
Microphone, speakers and zigbee coordinator are connected to Raspberry Pi. I have couple smart devices that is sending data to RPI. In frontend application you can make request from web server, for example to show you inside temperature chart or turn on the light.
When Ikea zigbee button is pressed, RPI starts recording audio, send it to Amazon for speech recognition and then for example turn on light or tell you current temperature inside.
Instead of Ikea button press, it would be more convinient to use Picovoice hotword detection.

**Comment by kenarsa** [comment]
support has been added in #475
