### ISSUE TITLE
Porcupine Issue: Unsupported CPU in RPI 

### ISSUE THREAD

**Issue by rsmanik** [Picovoice/porcupine#389]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
I am unable to import pvporcupine python library or run demos on raspberry pi on 32bit 

### Actual behaviour
pi@raspberrypi:~ $ sudo pip3 install pvporcupine
Collecting pvporcupine
  Using cached https://files.pythonhosted.org/packages/ed/e8/8071f2e470639a97f714bbb98ee4e334ec2810b9cd2bf7530db073ef8e62/pvporcupine-1.9.4-py3-none-any.whl
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from pvporcupine)
Requirement already satisfied: enum34 in /usr/local/lib/python3.5/dist-packages (from pvporcupine)
Installing collected packages: pvporcupine
Successfully installed pvporcupine-1.9.4

pi@raspberrypi:~ $ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pvporcupine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pvporcupine/__init__.py", line 13, in <module>
    from .util import *
  File "/usr/local/lib/python3.5/dist-packages/pvporcupine/util.py", line 57, in <module>
    _PV_SYSTEM, _PV_MACHINE = _pv_platform()
  File "/usr/local/lib/python3.5/dist-packages/pvporcupine/util.py", line 50, in _pv_platform
    pv_machine = _pv_linux_machine(platform.machine())
  File "/usr/local/lib/python3.5/dist-packages/pvporcupine/util.py", line 41, in _pv_linux_machine
    raise NotImplementedError('Unsupported CPU.')
NotImplementedError: Unsupported CPU.
>>>

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

sudo pip3 install pvporcupine
porcupine_demo_mic 

Please advise.

**Comment by mrrostam** [comment]
@rsmanik can you please provide the output of "lscpu" command?

**Comment by mrrostam** [comment]
@rsmanik got the root of the issue! a fast solution would be updating your Raspbian OS to the newest version if that is possible. Meanwhile we are working on this to fix it.

**Comment by rsmanik** [comment]
Thanks for the quick response and workaround. Here is the output of the lscpu command, in case its still useful. I can confirm that with the latest Raspbian OS porcupine v1.94 works great. 

Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Model:                 4
Model name:            ARMv7 Processor rev 4 (v7l)
CPU max MHz:           1400.0000
CPU min MHz:           600.0000
BogoMIPS:              89.60
Flags:                 half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32

**Comment by kuumaur** [comment]
Hi Guys,
I have the same issue here.

Armbian Legacy (Armbian_21.02.3_Rockpi-s_buster_legacy_4.4.247)
Linux pi3 4.4.247-rockpis #1 SMP PREEMPT Mon Mar 8 08:35:13 UTC 2021 aarch64 GNU/Linux
root@pi3:~# lscpu
Architecture: aarch64
Byte Order: Little Endian
CPU(s): 4
On-line CPU(s) list: 0-3
Thread(s) per core: 1
Core(s) per socket: 4
Socket(s): 1
Vendor ID: ARM
Model: 2
Model name: Cortex-A35
Stepping: r0p2
CPU max MHz: 1296.0000
CPU min MHz: 408.0000
BogoMIPS: 48.00
L1d cache: 32K
L1i cache: 32K
L2 cache: 256K
Flags: fp asimd aes pmull sha1 sha2 crc32

History information:
https://github.com/rhasspy/rhasspy/issues/206

**Comment by kenarsa** [comment]
@kuumaur that's not an RPI. It is a rockpi that Porcupine doesn't support out of the box. You might be able to run one of the RPI builds on it but you gotta do some hacking on your own.

**Comment by kuumaur** [comment]
Is there a reason why its focus on rpi only?
What about NanoPi's and BananaPi's, are there also restrictions?

**Comment by kenarsa** [comment]
Because we only compiled it for RPI CPUs. Each of those boards has a different Arm Cortex. The RPI build might work on them but we have not tested them.

**Comment by kuumaur** [comment]
As far as I understand you right, you identify the CPU type.
If it does not match, then the scripts stops.
Could it be a solution, to just let the Program run with warnings in log file?
Now a can only use rpi's.
They do not fit all my needs for my use cases. Too big (rpi 3,4) or too slow (rpi0).
Other brands will fit better.

**Comment by kenarsa** [comment]
@kuumaur the issue you have is obviously not related to this thread. feel free to open a new one
