### ISSUE TITLE
Can't create a new wake word

### ISSUE THREAD

**Issue by MaoHasan** [Picovoice/Porcupine#39]
i tried creating a new wake word using the following command
`tools/optimizer/mac/x86_64/pv_porcupine_optimizer -r resources -w “hello world” -p mac -o ~/Users/mahmoud/Desktop `
when I use one word, example `hello` it gives the pronunciation error "tried many other words", when i use two or more i get 
` [ERROR] invalid arguments ` 
the test file is working fine, but i can't add any other words.

any ideas?

OS: Mac OS high sierra (10.13.4)

**Comment by kenarsa** [comment]
Could you please let me know which version of repo are you using? Is it the latest?

I can create "hello world" using the command you provided on Mac.

You cannot create "hello" using this optimizer as it is too short for a wake-word. You should get an error message "[ERROR] Wake phrase is too short or long for this optimizer. Please contact contact@picovoice.ai." Internally we can create shorter wake-words. But it would require us to do some manual work and therefore we only provide those for commercial customers.

What are the other wake-words that you are trying to generate and can't? Can you generate something like "banana" using:

tools/optimizer/mac/x86_64/pv_porcupine_optimizer -r resources/ -w "banana" -p mac -o ~/

**Comment by MaoHasan** [comment]
Hello Kenarsa, Yes i cloned the library yesterday, i tried *lots* of words tbh, even banana gives 
`[ERROR] could not find the pronunciation for '“banana”'. If this is not a typo please contact contact@picovoice.ai.`
![image](https://user-images.githubusercontent.com/9074166/41785078-24104810-764a-11e8-88af-c5ac9ca8495f.png)

**Comment by kenarsa** [comment]
Can you try a simple word like banana without " ?

**Comment by MaoHasan** [comment]
@kenarsa so apparently it was a command problem, I had the output like this `-o ~/xxx`
it's supposed to the without the **~**, so it worked fine, great work on the accuracy!
but unfortunately, the word "apps" is not in the dictionary, any way users can help train specific words or it be added?

**Comment by Swathi2610** [comment]
Hi, sorry in advance if this question is already answered. I want to know how can I exactly create a custom wake word in windows which I can use in my android app. Will the trial wake be universal or personal. I am pretty new this. Kindly reply
