### ISSUE TITLE
Porcupine Issue: wakeword detecting as inference?

### ISSUE THREAD

**Issue by johnbowdenatfacet** [Picovoice/porcupine#397]
### Expected behaviour
Wakeword should be detected and callback run

### Actual behaviour
Inference callback running instead

### Steps to reproduce the behaviour
Running in react-native app using "picovoice" wakeword.

**Comment by johnbowdenatfacet** [comment]
Looks like create needs to be called after each activation...

**Comment by laves** [comment]
@johnbowdenatfacet, it sounds like you are using Picovoice instead of Porcupine. Porcupine does not have an inference callback. For wake word only on react native, install porcupine-react-native.
