### ISSUE TITLE
Support Flutter Null Safety

### ISSUE THREAD

**Issue by jtmuller5** [Picovoice/porcupine#401]
**Is your feature request related to a problem? Please describe.**
Flutter 2.0 added support for null safety which makes your code safer and faster. If all of the dependencies in your project do not support null safety, you need to run your code in unsound null safety mode.

**Describe the solution you'd like**
I would like to see the porcupine package support null safety.

**Describe alternatives you've considered**
For the time being I can run my project in mixed mode but porcupine is one of the three packages I'm using that does not support null safety.

**Additional context**
Here's a link to the [Flutter null safety guide](https://dart.dev/null-safety/migration-guide).

**Comment by kenarsa** [comment]
@jtmuller5 would you like to take the lead on this and submit a PR for it? :)

**Comment by jtmuller5** [comment]
I think I can do that, let me dig into it today!

**Comment by laves** [comment]
thanks @jtmuller5 !
