### ISSUE TITLE
Android kickstart. It's not working

### ISSUE THREAD

**Issue by hannesa2** [Picovoice/porcupine#402]
I evaluate the Android sample https://github.com/Picovoice/porcupine/tree/master/demo/android/Activity on a Pixel 4 with Android 11 but nothing happen. I expect a wakeword call back here

<img width="532" alt="image" src="https://user-images.githubusercontent.com/3314607/115150049-015ed580-a067-11eb-9ad6-d07d13da1b18.png">

I see in logcat a proper wakeword usage
<img width="996" alt="image" src="https://user-images.githubusercontent.com/3314607/115150000-d6748180-a066-11eb-9585-e11af410d8b3.png">

and in APK the wakewords are there 

<img width="454" alt="image" src="https://user-images.githubusercontent.com/3314607/115150095-2f441a00-a067-11eb-9ad5-da39cf809ac7.png">

Do I expect too much, or does someone knows what's wrong here ?

**Comment by hannesa2** [comment]
I even uninstalled the own build apk and installed it from [Play store ](https://play.google.com/store/apps/details?id=ai.picovoice.porcupine.demo&hl=en) with same result. Nothing happens at all.

Do I need some credentials to make it work anyhow ?

**Comment by kenarsa** [comment]
I think this is related to this [issue](https://github.com/Picovoice/porcupine/issues/307). Can you please do what is suggested there. changing target SDK version and if that is the case then we close this and track it in the other one

**Comment by hannesa2** [comment]
Yes, this is the solution. I will switch to the other ticket
