### ISSUE TITLE
Add native Java SDK support for Apple Silicon M1

### ISSUE THREAD

**Issue by hannesa2** [Picovoice/porcupine#403]
When I test `java -jar demo/java/bin/porcupine-mic-demo.jar -k terminator` I run into 

<img width="872" alt="image" src="https://user-images.githubusercontent.com/3314607/115150865-87305000-a06a-11eb-85b6-4f22d2452f6e.png">

**Comment by kenarsa** [comment]
It [says](https://github.com/Picovoice/porcupine/tree/master/binding/java#compatibility) that is only runs on x86_64 macOS natively! There are ways to run x86_64 code on Arm-based macOS. I keep this open as a possible enhancement for the future but nothing immediate will be planned.

**Comment by hannesa2** [comment]
I'm happy to have my arm64 brew/Java installation stabil, next to x86 Android Studio and my arm64 M1 Emulator.
I will not change this anymore, when I'm not forced to do it. 

I tried it only for test purpose, that's why I will wait for a future fix. 

In the meantime I say .... thank you for this repository !

**Comment by hannesa2** [comment]
Without any change it works on a Apple Silicon M1 too

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/3314607/115183679-8d5f1480-a0dc-11eb-9bde-f34a7a8ab27a.png">

**Comment by kenarsa** [comment]
`v2` release added this.
