### ISSUE TITLE
Flutter porcupineManager.delete() when app is closing don't release resources correctly

### ISSUE THREAD

**Issue by maddionatoplus** [Picovoice/porcupine#407]
Hello, 
When I call manually `porcupineManager.delete()` before closing app the resources are released correctly, and when I reopen the app I can create and start a new porcupineManager in a correct way.
But when I try to call `porcupineManager.delete()` automatically when the StatefulWidget is closed I continue to receive the following message in the debug:

`
W/FlutterJNI(18227): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter_voice_processor_events. Response ID: 0
`
The problem is that even if I close and restart the app I continue to receive this message and the voice recognition doesn't work properly.

How can I solve this?

**Comment by laves** [comment]
@maddionatoplus are you awaiting the call to delete? It's an async function so you need to await the return.

**Comment by laves** [comment]
@maddionatoplus we're having trouble reproducing this issue with our Flutter demo. Can you share a private repo with the issue isolated?

**Comment by maddionatoplus** [comment]
I have invited you in a private repository with the issue isolated. I use Get X for state management in this project.
You can see that if you exit from the app with back button you receive:

`W/FlutterJNI(29724): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter_voice_processor_events. Response ID: 0`

I've put a CLOSE button to manually delete the porcupineManager and if you press the button and then you close the app you don't receive the error message

**Comment by laves** [comment]
Thanks, I can reproduce it in this repo. Not sure why I couldn't reproduce with our demo, maybe it's a bad interaction with Get. I'll look into this today and see if we can address it.

**Comment by laves** [comment]
@maddionatoplus I was also able to reproduce this in our demo as well, however, this behaviour is only ever observed while trying to delete `porcupineManager` from the `paused` state when the back button is pressed on an Android device. If you call delete on back button press from the `inactive` state it works fine. If you call delete from the `paused` state in any other situation it works as intended. This seems to be a shortcoming of Flutter and not a bug in our SDK (though we will document this). I would suggest you either call delete when the state enters `inactive` or handle the Android back button event separately using the [WillPopScope](https://api.flutter.dev/flutter/widgets/WillPopScope-class.html) class.

**Comment by laves** [comment]
We've documented this, so I'm going to close.

**Comment by maddionatoplus** [comment]
Thank you! WillPopScope worked well!
