### ISSUE TITLE
React-Native Build error on Xcode 12.5

### ISSUE THREAD

**Issue by johnbowdenatfacet** [Picovoice/porcupine#408]
### Expected behaviour
Build and run successfully after latest xcode version update

### Actual behaviour
Build fails with error:
`Undefined symbols for architecture x86_64:
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in libporcupine-react-native.a(Porcupine-ea8bad61783061f627b13c6a90d62901b47c3925d5e72941ede7605540e5281b.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

### Steps to reproduce the behaviour
react-native init testerror
yarn add @picovoice/react-native-voice-processor
yarn add @picovoice/porcupine-react-native
yarn add @picovoice/rhino-react-native
yarn add @picovoice/picovoice-react-native

can provide private repo test repo if necessary

**Comment by kenarsa** [comment]
@johnbowdenatfacet what version of Xcode are you using?

**Comment by johnbowdenatfacet** [comment]
@kenarsa  Version 12.5 (12E262)

**Comment by kenarsa** [comment]
Thanks! We will try to reproduce and will circle back

**Comment by johnbowdenatfacet** [comment]
Have removed the swift-5 reference and now builds.  Though in my sample app, I'm now running into an error with PvRhino after several successfull voice commands.  I can provide an invite to the repo, just need a github user.

**Comment by kenarsa** [comment]
@johnbowdenatfacet I have changed the title of the issue to reflect that the initial issue reported is related to Xcode 12.5.

We will only track that in this thread. If you face a different problem please open a separate GitHub issue. Please be sure to have: (1) descriptive and accurate title (2) code snippets and explanation for us to be able to help (3) if (2) doesn't work we sometimes ask for a GitHub repo share but this should be used as a last resort and we can only accommodate this from time to time as it is very time-consuming.

**Comment by laves** [comment]
@johnbowdenatfacet it seems that this is not an issue with our react native binding, but an issue with react native itself. XCode 12.5 has broken several things in react native, so for now there are several workarounds to deal with them until a new version of react native is released. Reference [this thread](https://github.com/facebook/react-native/issues/31179#issuecomment-829536845) on React Native's GitHub for the applicable workarounds.
