### ISSUE TITLE
Windows No positive results

### ISSUE THREAD

**Issue by dwilday** [Picovoice/Porcupine#41]
### Expected behavior
I expect to see a positive result when saying the wake word when running the demo on Windows.
### Actual behavior
No result is reported.
### Steps to reproduce the behavior
on a windows machine run:
python demo/python/porcupine_demo.py --keyword_file_paths alexa_windows.ppn

Please include the operating system and CPU architecture. When applicable, provide relevant audio data.  Windows 10, Intel Core i7

**Comment by kenarsa** [comment]
Have taken a look at the FAQ of the demo? It is available here https://github.com/Picovoice/Porcupine/tree/master/demo/python.
Could you please take a look at the first item and see if it applies to you?

**Comment by dwilday** [comment]
Actually I'm going to close this.  It appears that the built in mic on my laptop was compatible with pyaudio.  When I plugged in a USB mic everything worked just fine.
