### ISSUE TITLE
'porcupine_demo_mic' is not recognized in Windows

### ISSUE THREAD

**Issue by shikhar2402** [Picovoice/porcupine#414]
Hello, I'm trying to run porcupine_demo_mic --keywords picovoice after installation with pip3 install pvporcupinedemo,
But it is giving this error.

### Actual behaviour
'porcupine_demo_mic' is not recognized as an internal or external command,
operable program or batch file.
![porcupine](https://user-images.githubusercontent.com/46794327/117359318-d84a9b80-aed4-11eb-9e7f-f6d3bb9dada9.png)

**Comment by mrrostam** [comment]
My guess is that you are using a Windows machine. In this case, you should add the python scripts folder to the PATH variable. As a quick test just go to `C:\Users\{your username}\AppData\Roaming\Python\Python{version}\Scripts` and run the command again. The system should be able to find and execute `porcupine_demo_mic` here.
