### ISSUE TITLE
Flutter background service 

### ISSUE THREAD

**Issue by FadiChaalab** [Picovoice/porcupine#421]
Am trying to run it in background service but it keeps give me error about missing plugin exception no implementation found for method listen on channel flutter_voice_processor_events.
I need to run it in background service, how to fix this issue?

**Comment by kenarsa** [comment]
duplicate of https://github.com/Picovoice/picovoice/issues/82

creating duplicate issues won't accelerate resolution and simply delays it by creating extra admin work.

**Comment by FadiChaalab** [comment]
I recreated the issue because i used porcupine flutter package and forgot to close it in the other one. Forgive me for my mistake but could you reopened again, i really need help on this issue.

**Comment by FadiChaalab** [comment]
This is my main page:


![main dart - background_voice - Visual Studio Code 5_21_2021 6_43_29 PM](https://user-images.githubusercontent.com/58008170/119179376-bf122500-ba66-11eb-8115-73b019c09897.png)

And speech_service.dart file has the initialize method for porcupineManager and all the logic that i need to fire get location and record sample of audio when the wake word detected. 
Everything work fine in foreground but when i try to run it in background service it fails with the error above.

**Comment by laves** [comment]
@FadiChaalab we've never claimed or attempted Porcupine Flutter on a background service. There is definitely some complications around running the cross-platform audio recorder outside the app. This is definitely a valid use-case that we'd like to support, but I can't promise we'll add this capability right away. We'll keep the issue open and hopefully someone can help you out in the meantime.

**Comment by teganscott** [comment]
Would this be why I can't get the flutter example on iOS to work with wake word when the app is not in the foreground?

**Comment by olivermoo** [comment]
Hi
@kenarsa this issue was closed as completed, is there a background listener available for flutter, I don't seem to see anything?
Similar to @FadiChaalab commented I get MissingPluginException(No implementation found for method listen on channel flutter_voice_processor_error_events) if I run it in Flutter Background Service
Thank you in advance for any assistance.

**Comment by kenarsa** [comment]
@olivermoo that was my mistake. I closed the issue as not planned. We do have background recording for native Android and iOS but never claimed nor planned to add it to cross-platform mobile SDKs. If contributors what to add this based on our native SDKs we are very much open to PRs. Sorry about the confusion.

**Comment by callmephil** [comment]
Has there been any development on this feature since?
