### ISSUE TITLE
Not working with Hey siri on iOS device

### ISSUE THREAD

**Issue by maddionatoplus** [Picovoice/porcupine#429]
Hello I have no problem using "Ok Google" wakeword with Android device, but I want to use Hey Siri with iOS device.
Porcupine can't recognize "Hey Siri" but it works fine if I use "Ok Google" or "Alexa" instead. 
Do you have any advice?

**Comment by dbartle** [comment]
Follow the issue template and provide us with information so that we can help you. What you've described does not give us anything to go on. Closing the issue.
