### ISSUE TITLE
Making keyword problem

### ISSUE THREAD

**Issue by imispell2** [Picovoice/Porcupine#43]
### Steps to reproduce the behavior

Please include the operating system and CPU architecture. When applicable, provide relevant audio data.

Hi, I'm making some prototype and try to make my keyword like below.
But it's not work with pronunciation error.
Can you suggest the way to resolve this problem or add a keyword "ariot" (not "a riot")??
Please advice about it.

Thanks.

C:\Users\1\Porcupine-master\Porcupine-master>tools\optimizer\windows\i686\pv_porcupine_optimizer.exe -r resources\ -w "ariot" -p windows -o .
[ERROR] could not find the pronunciation for 'ariot'. If this is not a typo please contact contact@picovoice.ai.

**Comment by imispell2** [comment]
can you refer to here?
https://endic.naver.com/search.nhn?sLn=en&query=ariot&searchOption=all

**Comment by kenarsa** [comment]
OK. We will add it to next release which is coming next week. Thanks.

**Comment by kenarsa** [comment]
added the keyword to new release ...

**Comment by SRI-VISHVA** [comment]
Hey, I am trying to create a snake game but it doesn't recognize the word "go left"?.
