### ISSUE TITLE
Flutter Failed to load dynamic library libpv_porcupine.so 

### ISSUE THREAD

**Issue by FadiChaalab** [Picovoice/porcupine#438]
Somehow i got this exception after it was working fine.
**Device** is **SM G532F**.
When it try to initialize porcupine manager it fails.
**Logs:**

`[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libpv_porcupine.so': dlopen failed: library "libpv_porcupine.so" not found`

**Comment by dbartle** [comment]
Please follow the issue template and provide enough information that we can reproduce your issue. A single line of an error message with no context is not sufficient.

**Comment by FadiChaalab** [comment]
Code (was working fine with the same device):

`import 'dart:async';
import 'dart:io';

import 'package:flutter/services.dart';
import 'package:forher/src/db/auth.dart';
import 'package:forher/src/db/storage.dart';
import 'package:forher/src/models/alert.dart';
import 'package:forher/src/models/user.dart';
import 'package:get/get.dart';
import 'package:injectable/injectable.dart';
import 'package:location/location.dart';
import 'package:path_provider/path_provider.dart';
import 'package:porcupine/porcupine_error.dart';
import 'package:porcupine/porcupine_manager.dart';
import 'package:record/record.dart';

@singleton
class SpeechService extends GetxController {
  final storage = Get.find<StorageRepo>();
  final auth = Get.find<AuthService>();

  Rx<String> wordKey = Rx<String>('');
  Rx<int> occurance = Rx<int>(0);
  static const int maxDuration = 10;

  bool _isRecording = false;
  int _remainingDuration = maxDuration;
  Timer? _timer;
  LocationData? locationData;

  late PorcupineManager porcupineManager;
  String keywordAssetAndroid = "assets/sounds/harm-it-android.ppn";
  String keywordAssetIos = "assets/sounds/harm-it-ios.ppn";

  Future<String> _extractAsset(String resourcePath) async {
    // extraction destination
    String resourceDirectory = (await getApplicationDocumentsDirectory()).path;
    String outputPath = '$resourceDirectory/$resourcePath';
    File outputFile = new File(outputPath);

    ByteData data = await rootBundle.load(resourcePath);
    final buffer = data.buffer;

    await outputFile.create(recursive: true);
    await outputFile.writeAsBytes(
        buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
    return outputPath;
  }

  // Get Location
  void getUserLocation() async {
    Location location = Location();

    bool serviceEnabled;
    PermissionStatus permissionStatus;

    serviceEnabled = await location.serviceEnabled();
    if (!serviceEnabled) {
      serviceEnabled = await location.requestService();
      if (!serviceEnabled) {
        return;
      }
    }

    permissionStatus = await location.hasPermission();
    if (permissionStatus == PermissionStatus.denied) {
      permissionStatus = await location.requestPermission();
      if (permissionStatus != PermissionStatus.granted) {
        return;
      }
    }

    locationData = await location.getLocation();
    print(locationData);
  }

  /// Create Alert
  Future<void> createAlert(String record) async {
    UserModel? currentUser = await auth.getUser();
    Alert currentAlert;
    if (currentUser != null && locationData != null) {
      currentAlert = Alert(
        active: true,
        date: DateTime.now().toString(),
        long: locationData!.longitude!,
        lat: locationData!.latitude!,
        userId: currentUser.uid!,
        userImageUrl: currentUser.avatarUrl!,
        username: currentUser.firstName! + ' ' + currentUser.lastName!,
        record: record,
        markerId: currentUser.uid!,
      );
      auth.createAlert(currentAlert);
    }
  }

  /// Send Alert
  Future<void> sendAlert() async {
    getUserLocation();
    await start();
  }

  /// Initialization function called when the app is first opened
  Future<void> initializeSpeechService() async {
    await createPorcupineManager();
    listenForWakeWord();
  }

  /// Create an instance of your porcupineManager which will listen for the given wake words
  /// Must call start on the manager to actually start listening
  Future<void> createPorcupineManager() async {
    try {
      String extractedKeywordPathAndroid =
          await _extractAsset(keywordAssetAndroid);
      String extractedKeywordPathIos = await _extractAsset(keywordAssetIos);
      String words = Platform.isAndroid
          ? extractedKeywordPathAndroid
          : extractedKeywordPathIos;
      porcupineManager =
          await PorcupineManager.fromKeywordPaths([words], wakeWordCallback);
    } on PvError catch (err) {
      // handle porcupine init error
      print('Porcupine error: ' + err.message!);
    }
  }

  /// The function that's triggered when the Porcupine instance recognizes a wake word
  /// Input is the index of the wake word in the list of those being used
  Future<void> wakeWordCallback(int word) async {
    occurance.value += 1;
    print('Wake word activated ${occurance.value} index: ' + word.toString());
    wordKey.value =
        'Wake word activated ${occurance.value} index: ' + word.toString();
    // Terminator - resets audio resources
    if (word == 13) {
      await createPorcupineManager();
      listenForWakeWord();
    } else {
      sendAlert();
    }
  }

  /// Begin listening for a wake word
  void listenForWakeWord() async {
    try {
      await porcupineManager.start();
    } on PvAudioException catch (ex) {
      // deal with either audio exception
      print('PvAudioException: ' + ex.message!);
    }
  }

  /// Stop listening for a wake word
  void stopListeningForWakeWord() async {
    try {
      await porcupineManager.stop();
    } on PvAudioException catch (ex) {
      // deal with either audio exception
      print('PvAudioException: ' + ex.message!);
    }
  }

  Future<void> start() async {
    try {
      if (await Record.hasPermission()) {
        final dir = await getApplicationDocumentsDirectory();
        await Record.start(path: '${dir.path}/danger.aac');

        bool isRecording = await Record.isRecording();

        _isRecording = isRecording;
        _remainingDuration = maxDuration;

        _startTimer();
      }
    } catch (e) {
      print(e);
    }
  }

  Future<void> _stop() async {
    _timer?.cancel();
    await Record.stop();

    _isRecording = false;
    _remainingDuration = maxDuration;
  }

  void _startTimer() {
    const tick = const Duration(milliseconds: 500);

    _timer?.cancel();

    _timer = Timer.periodic(
      tick,
      (Timer t) async {
        if (!_isRecording) {
          t.cancel();
        } else {
          _remainingDuration = maxDuration - (t.tick / 2).floor();
          print(_remainingDuration);
          if (_remainingDuration <= 0) {
            _stop();
            String? record;
            final dir = await getApplicationDocumentsDirectory();
            String path = dir.path + '/danger.aac';

            File audio = File(path);
            await storage
                .uploadAudio(audio, '/danger')
                .then((value) => record = value);

            createAlert(record!);
          }
        }
      },
    );
  }
}
`

**Comment by FadiChaalab** [comment]
Debug console output in vscode: 

```
E/flutter (25711): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
E/flutter (25711): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
E/flutter (25711): #2      _load
package:porcupine/porcupine.dart:294
E/flutter (25711): #3      _porcupineLib
package:porcupine/porcupine.dart:290
E/flutter (25711): #4      _porcupineLib (package:porcupine/porcupine.dart)
package:porcupine/porcupine.dart:1
E/flutter (25711): #5      _porcupineInit
package:porcupine/porcupine.dart:306
E/flutter (25711): #6      _porcupineInit (package:porcupine/porcupine.dart)
package:porcupine/porcupine.dart:1
E/flutter (25711): #7      Porcupine._create
package:porcupine/porcupine.dart:197
E/flutter (25711): <asynchronous suspension>
E/flutter (25711): #8      PorcupineManager.fromKeywordPaths
package:porcupine/porcupine_manager.dart:86
E/flutter (25711): <asynchronous suspension>
E/flutter (25711): #9      SpeechService.createPorcupineManager
package:forher/…/utils/speech_service.dart:120
E/flutter (25711): <asynchronous suspension>
E/flutter (25711): #10     SpeechService.initializeSpeechService
package:forher/…/utils/speech_service.dart:105
E/flutter (25711): <asynchronous suspension>
E/flutter (25711):
V/ActivityThread(25711): updateVisibility : ActivityRecord{fdfb330 token=android.os.BinderProxy@4307ff7 {com.example.forher/com.example.forher.MainActivity}} show : true
2
I/System.out(25711): (HTTPLog)-Static: isSBSettingEnabled false
D/libc-netbsd(25711): [getaddrinfo]: netid=0; mark=0
D/libc-netbsd(25711): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
D/libc-netbsd(25711): [getaddrinfo]: netid=0; mark=0
D/libc-netbsd(25711): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
D/libc-netbsd(25711): getaddrinfo: get result from proxy gai_error = 0

```

**Comment by dbartle** [comment]
Are you able to run the demos in this repo on this device successfully?

**Comment by FadiChaalab** [comment]
I told you it was working fine with the same code, i tested on my emulator and still works fine on it but just fails on my real device.

**Comment by kenarsa** [comment]
@FadiChaalab If you want our help you need to be respectful! You ignored the issue template and your last message ("I told you ...") is disrespectful. I will ban you from all the Picovoice repositories if you do this again.

**Comment by FadiChaalab** [comment]
There was no disrespect with what i said and i didn't know what you mean
about template issue.
