### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/picovoice-react/)

### ISSUE THREAD

**Issue by DanielJDupont** [Picovoice/porcupine#439]
### What is the URL of the doc?
https://picovoice.ai/docs/quick-start/picovoice-react/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
I think the Vue documentation was copied into the React documentation with a mention of Vue not replaced. Located right underneath the subtitle **Demo application**. I believe that there is a typo where React should be written instead of Vue. I thought there was no React template project for a second until I saw Create React App.

> There is a **Vue** demo project available on the Picovoice GitHub repository. The demo project was bootstrapped with Create React App.

Should be:

> There is a **React** demo project available on the Picovoice GitHub repository. The demo project was bootstrapped with Create React App.

**Comment by dbartle** [comment]
I can see how that would be confusing. It's fixed now, thanks for reporting.
