### ISSUE TITLE
missing wake word

### ISSUE THREAD

**Issue by markjerkulovitch** [Picovoice/Porcupine#44]
HI,

[ERROR] could not find the pronunciation for 'trello'.

Is it possible to add this word to the dictionary?

**Comment by markjerkulovitch** [comment]
Hi @kenarsa 

Thank you very much! 
I saw in the FAQ you say "**We can provide you with requested keyword file** and will add the word to optimizer's internal dictionary for next release."

Is it possible for you to create me a keywordfile 🙏 🙏 🙏

**Comment by kenarsa** [comment]
Next release if coming next week. Is it ok for you to wait a week? If not send an email to contact@picovoice.ai

**Comment by kenarsa** [comment]
delivered the model. closing the issue.
