### ISSUE TITLE
Picovoice Issue: React Demo workerChunk.workerFactory may need to be workerChunk.factory

### ISSUE THREAD

**Issue by DanielJDupont** [Picovoice/porcupine#440]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

**Edit: I made the mistake of publishing this issue under porcupine when I meant to make an issue for picovoice.**

### Expected behaviour
![workingExample](https://user-images.githubusercontent.com/43941960/122504099-8c0c7400-cfc7-11eb-87bf-24487b80a5d0.gif)

### Actual behaviour
![notWorking](https://user-images.githubusercontent.com/43941960/122504775-f376f380-cfc8-11eb-8c73-8373f536a915.gif)

### Steps to reproduce the behaviour

Follow the steps outlined in the documention on https://picovoice.ai/docs/quick-start/picovoice-react/ to setup and start the demo react app. It should not work as shown above.

### Repair

I think the issue is with **VoiceWidget.jsx** on line 59: https://github.com/Picovoice/picovoice/blob/ebbce93bc852aebee7f8efc70ef5a855f4e6a5f3/demo/react/src/VoiceWidget.jsx#L59

I noticed that .factory exists on the workerChunk object but not .workerFactory and I noticed a line in the documentation here under **Dynamic Import / Code Splitting** https://picovoice.ai/docs/api/picovoice-react/ states:

`    if (workerChunk.workerFactory === null) { // <-- We only want to load once!`

The VoiceWidget.jsx appears to be a more recent version of the code where line 14 in VoiceWidget.jsx has been changed to:

`    if (workerChunk.factory === null) {`

I suspect that the line 59 in VoiceWidget.jsx was meant to be updated to have .workerFactory changed to .factory as well. This change allowed the demo to work for me.

**Comment by dbartle** [comment]
Fixed in https://github.com/Picovoice/picovoice/commit/905a0f100f2fd2291317d839d497264bfea28814 thanks for reporting
