### ISSUE TITLE
[C] Allow silencing/redirecting the logging output

### ISSUE THREAD

**Issue by kalipka** [Picovoice/porcupine#450]
I use the Porcupine C library and noticed that the library outputs some log messages at runtime (like `[WARN] license expires in 28 days`). It would be nice to have a function in the API to silence or redirect this output. This function may take as parameter a function pointer so that the user can decide on what to to with the log messages.

**Comment by dbartle** [comment]
Thanks for your suggestion. I understand that they can be annoying, but those messages serve an important purpose of setting expectations about why the engine does (or does not) start, so we do want them to be visible. Adding the possibility of redirecting them wouldn't provide a commensurate benefit for the amount of effort that would be involved.
