### ISSUE TITLE
Visual Studio claims DLLs are invalid (both 32-bit and 64-bit)

### ISSUE THREAD

**Issue by astewart-xmos** [Picovoice/Porcupine#46]
I'm running Visual Studio 2017 on a Windows 10 machine.

I've tried this with both 32- and 64-bit projects.

The result I get is similar in each case:
`4>..\..\porcupine\lib\libpv_porcupine.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x430` (64-bit)
`1>..\..\porcupine\lib\libpv_porcupine.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x3F8` (32-bit)

I also tried previous committed versions with no luck.

**Comment by astewart-xmos** [comment]
Ah, my mistake. Not sure how I spaced on that. When I change it to link against `libpv_porcupine.a` it looks for `m.lib` and cannot find it. I've also tried linking dynamically and that doesn't work either.

Is Visual Studio not supported with these binaries?

**Comment by kenarsa** [comment]
This is much better. I think you are missing standard C library in the mix.

**Comment by kenarsa** [comment]
What version of VS are you using?

**Comment by astewart-xmos** [comment]
When you built it for Windows, which compiler/toolchain did you use?

**Comment by kenarsa** [comment]
We use CMake across all platforms. For windows we used MinGW.

**Comment by astewart-xmos** [comment]
Alright, I would greatly appreciate that! Thanks!

**Comment by kenarsa** [comment]
Sorry for the delay. Did you manage to overcome the linking problem? If not I will try to build a sample app using VS and share my findings. Let me know ...

**Comment by astewart-xmos** [comment]
Sorry, I just noticed your response. No, I haven't gotten it to link with VS yet

**Comment by kenarsa** [comment]
I've spent some time trying to fix this issue and it the only possibility is to compile the lib again using VS. I'll put it as a TODO for next release and try to get to it. Until then using something like [Mingw](http://www.mingw.org/) should resolve the issue. thanks.

**Comment by astewart-xmos** [comment]
Sorry, should have updated. We actually got this working with Visual Studio using [this](https://adrianhenke.wordpress.com/2008/12/05/create-lib-file-from-dll/).

Note, when running the lib command, you'll also want to specify the machine

 > lib /def:C:\mypath\mylib.def /OUT:C:\mypath\mylib.lib /MACHINE:X64

**Comment by kenarsa** [comment]
thank you, @astewart-xmos! I am sure this is going to be useful to the next person using VS.

**Comment by CasonTsai** [comment]
@astewart-xmos  hello,could you tell the detail,i use the msvc(x64 ) to export lib,when use this lib in cmake,it still be an  error.

![Image](https://github.com/user-attachments/assets/d70b9db5-2532-4bd2-b5a9-f4d6a81771e6)

![Image](https://github.com/user-attachments/assets/9a349f3a-ff6c-4bd6-9f16-0f47feb03d15)
