### ISSUE TITLE
How to adjust duration between wake word recognition and following command

### ISSUE THREAD

**Issue by sophyf** [Picovoice/porcupine#460]
### https://picovoice.ai/docs/api/porcupine-python/

I might be looking at the wrong place, but I couldn't seem to find any other resource with porcupine documentation.

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
Specifically, I couldn't find anything in the documentation about **how to shorten the duration between recognition of the wake word and listening for the actual command**. Right now, the user needs to pause for about one second after the wake word is recognized and then speak the command. Is there some code that can be added to shorten this time?

**Comment by dbartle** [comment]
You're looking in the right place as this concerns wake word (Porcupine).

To answer your question, that duration is not configurable, it is required by the wake word to conclude a detection. Without requiring a gap in speech after the wake phrase, there is a large increase in false alarms.

From a UI perspective, we've found that it greatly helps to add audiovisual feedback for the wake word detection, to give the user confidence to know that their wake word utterance was recognized, and that they may continue.
