### ISSUE TITLE
Can't get custom wake word into demo model

### ISSUE THREAD

**Issue by bspolk** [Picovoice/porcupine#464]
I’m trying to use a custom wake word model created in the picovoice console for android within the Porcupine Activity demo app. I extracted the .ppn file from the zip folder downloaded from the console and placed it in the /res/raw folder as mentioned in the readme, but when I rebuild the project in Android Studio and run the demo app on my device, the custom wake word fails to appear in the demo. How do I get my custom wake word to work in the demo app?

**Comment by laves** [comment]
@bspolk did you follow [this section](https://github.com/Picovoice/porcupine/tree/master/binding/android#custom-wake-word-integration) of the docs? You just need to put your keyword files into `assets` and pass the relative path to the Porcupine Builder.

**Comment by laves** [comment]
You don't need a .pv, that is optional. You simply put the .ppn you want to use in `src/main/assets` and reference it like so:
```java
// (let's say your keyword file is named keyword.ppn)
try {    
    Porcupine porcupine = new Porcupine.Builder()
                        .setKeywordPath("keyword.ppn")
                        .build(context);
} catch (PorcupineException e) { }
```
Also, I see you're modifying the unit tests for some reason? If you are trying to build an app using our PorcupineDemo as a starting point, you would want to add your source code to 'src/main/java'.

**Comment by bspolk** [comment]
I'm just trying to add the wake word to the demo app, not build an app
around it. I guess I just don't know where that code you just showed me is
supposed to go. Where am I referencing the .ppn? Is it in
MainActivity.java, or PorcupineTest.java, or somewhere else?

**Comment by laves** [comment]
MainActivity.java.

I'm going to close this issue as it's not an issue with our library and I've pointed you towards relevant documentation to help you.
