### ISSUE TITLE
How am I supposed to add this library to my Android project?

### ISSUE THREAD

**Issue by Ab-Appletic** [Picovoice/Porcupine#48]
I've been trying for the past 5 hours. Any tutorial on how to import it?

**Comment by kenarsa** [comment]
Take a look at how it is done in Android demo application please:

https://github.com/Picovoice/Porcupine/tree/master/demo/android

**Comment by Ab-Appletic** [comment]
I get this error when running the application:

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.[censored].[censored]-1/base.apk", zip file "/data/app/com.[censored].[censored]-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.[censored].[censored]-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.[censored].[censored]-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.[censored].[censored]-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.[censored].[censored]-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.[censored].[censored]-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.[censored].[censored]-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.[censored].[censored]-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.[censored].[censored]-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.[censored].[censored]-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.[censored].[censored]-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.[censored].[censored]-1/lib/arm, /system/lib, /vendor/lib]]] couldn't find "libpv_porcupine.so"

I replaced my package name with [censored]

**Comment by kenarsa** [comment]
The log says it cannot find the shared object. I guess you have not included it in your app ...

**Comment by Ab-Appletic** [comment]
Shared object? What is that?

**Comment by Ab-Appletic** [comment]
Where do I get the "shared file" (I'm assuming the file is libpv_porcupine.so) and where do I put it?

**Comment by kenarsa** [comment]
.so files are here: https://github.com/Picovoice/Porcupine/tree/master/lib/android
you can use the android binding here: https://github.com/Picovoice/Porcupine/tree/master/binding/android
it gives you a ready to use AAR...

**Comment by Ab-Appletic** [comment]
Where am I supposed to put the .so files?

**Comment by Ab-Appletic** [comment]
I get `ai.picovoice.porcupinemanager.PorcupineManagerException: ai.picovoice.porcupine.PorcupineException: java.lang.IllegalArgumentException: Initialization of Porcupine failed.`

**Comment by Ab-Appletic** [comment]
How do I tell what's the issue? This also happens when I try to run your demo app.

**Comment by kenarsa** [comment]
I just tested the demo app and managed to build and run it on an Android phone.
have you looked into the logs?

**Comment by Ab-Appletic** [comment]
The demo app doesn't even have the library imported properly. I don't know where you're getting at. I had to manually add the library to the demo app. I'm getting the same error. I got nothing from the logs. This library has 0 error reporting, if there's an exception, no matter what it is, it throws a PorcupineException.

**Comment by Ab-Appletic** [comment]
Which folder do you open in Android Studio to see the demo application?

**Comment by Ab-Appletic** [comment]
https://i.imgur.com/VOrvtxj.jpg

I get this error in the `Porcupine` class.

**Comment by Ab-Appletic** [comment]
I've imported the library successfully:
https://i.imgur.com/55VOhAJ.png

However I still get this error. None of the `native` methods seem to work. The .so files are there.

**Comment by Ab-Appletic** [comment]
I get the same error in your demo application without changing anything.

**Comment by kenarsa** [comment]
what do you mean by none of the native methods work? I don't know what is the issue here. I know that other developers have successfully loaded and used the demo app. from the information you provide I can't figure out the issue here. could be something related to your android studio ...

**Comment by Ab-Appletic** [comment]
In the porcupine class, I get "cannot resolve corresponding JNI function" on methods like 
```
public native long init();
```
and etc.

**Comment by kenarsa** [comment]
can you run any NDK project other than this? I suspect something is wrong with your IDE/toolchain setup ...

**Comment by Ab-Appletic** [comment]
Hi man. Sorry, it turns out the NDK is importing properly and that error isn't real.
I decided to debug, and I found this error:

`[ERROR] loading parameter file failed with 'IO_ERROR'`

I have verified that `params.pv` exists. The path is `/data/user/0/com.package.name/files/params.pv`

**Comment by Qamar4P** [comment]
Facing same error, [aar link](https://ufile.io/2c73b)

**Comment by shabshekan** [comment]
Hello, I have error "java.lang.IllegalArgumentException: Initialization of Porcupine failed". I'm sure about address of files "*.ppn and *.pv" and I can open them.  but I have this error on this line "object = init(modelFilePath, new String[]{keywordFilePath}, new float[]{sensitivity});"
I'm developing on android studio in windows 10.
