### ISSUE TITLE
Making keyword issue on Linux

### ISSUE THREAD

**Issue by rakeshkandukuri6** [Picovoice/Porcupine#49]
### Steps to reproduce the behavior

Hi I am using Porcupine on Linux (Ubuntu 64-bit) for making a wake-up word "dayo". But I could not do that. I am getting error mesage like **[ERROR] could not find the pronunciation for 'dayo'. If this is not a typo please contact contact@picovoice.ai.**
Can you please add the word to Porcupine to make the word as wakeup keyword or can you suggest a procedure to create a custom wakeup word like I used above(dayo)?
The 'dayo' is pronounced as: https://www.howtopronounce.com/dayo/

**Comment by kenarsa** [comment]
Thanks. Will add to next release.

**Comment by kenarsa** [comment]
added the keyword to the new release ...
