### ISSUE TITLE
What is RAM requiremenets for porcupine? (stm32)

### ISSUE THREAD

**Issue by Inviz** [Picovoice/porcupine#491]
Hello. I'd like to use porcupine on my smaller controllers, but i don't think I've got 20kb of memory to allocate for that. What's the hard requirement? I wonder if i can stream to eeprom instead?

**Comment by kenarsa** [comment]
It depends on your model(s) (`.PPN` files). You need around 20 KB. EEPROM is ROM not RAM so it won't work.
