### ISSUE TITLE
Porcupine Issue: Not registering wake word

### ISSUE THREAD

**Issue by cjw16** [Picovoice/porcupine#492]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour

Once wake word is registered, wait for next command.

### Actual behaviour

I am trying to implement both Porcupine and Rhino onto my Raspberry Pi 4 with the Seeed Mic Array v2.0. The demos for both engines work perfectly in the terminal.

In my code to implement commands for the different inferences, however, the wake word is not being understood. The system is  listening and recording the correct snippets, but the wake word is not being identified from there.

The following warnings are being shown:
        ALSA lib confmisc.c:767:(parse_card) cannot find card '0' 
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
        ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
        ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
        ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM sysdefault
        ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
        ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
        ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
        ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM sysdefault
        ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
        ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
        ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
        ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM front
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
        ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
        ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
        ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
        ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround21
        ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
        ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
        ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
        ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround21
        ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
        ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
        ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
        ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround40
        ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
        ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
        ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
        ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround41
        ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
        ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
        ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
        ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround50
        ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
        ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
        ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
        ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround51
        ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
        ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
        ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
        ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround71
        ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
        ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
        ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
        ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM iec958
        ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
        ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
        ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
        ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM spdif
        ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
        ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
        ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
        ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM spdif
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
        ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
        ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
        ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
        ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
        ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
        ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
        Cannot connect to server socket err = No such file or directory
        Cannot connect to server request channel
        jack server is not running or cannot be started
        JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
        JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
        Cannot connect to server socket err = No such file or directory
        Cannot connect to server request channel
        jack server is not running or cannot be started
        JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
        JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
        ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
        ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
        ALSA lib pcm_a52.c:823:(_snd_pcm_a52_open) a52 is only for playback
        ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
        ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
        ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
        ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM iec958:{AES0 0x6 AES1 0x82 AES2 0x0 AES3 0x2  CARD 0}
        ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
        ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
        ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
        ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
        ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
        ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
        ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
        ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
        ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
        ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
        ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
        ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM dmix
        Cannot connect to server socket err = No such file or directory
        Cannot connect to server request channel
        jack server is not running or cannot be started
        JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
        JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

I have seen that some people have also received these warnings in the past, but any solutions offered have not worked on my side. I was also unable to find where this was said to have been addressed in the FAQs, as pointed out in some of the assistant's answers.

Is it possible that these warnings are what is causing the system not to register the wake word, and if so would you please be able to assist in getting rid of them, or should I be looking for other issues that would cause this?

Any help would be greatly appreciated.

**Comment by kenarsa** [comment]
@cjw16 I understand that the demos are working for you and then when you try to implement your code it does not? Can you confirm? If that's the case the problem is most likely in your code. If you attach a small relative snippet of your code we might be able to help. The warnings from ALSA are common.

**Comment by cjw16** [comment]
Thank you for your response - yes, that is the case.

Please find the first part of my code below, after which is the implementation of Rhino.

import RPi.GPIO as GPIO 
from pvrecorder import PvRecorder
import wave
import numpy as np
import pyaudio
import pvporcupine
import pvrhino
from time import sleep

GPIO.setmode(GPIO.BCM)
GPIO.setup(17, GPIO.OUT)
GPIO.setup(27, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)
GPIO.setup(23, GPIO.OUT)

handle = pvporcupine.create(keywords=['picovoice'])
print(handle.sample_rate)
print(handle.frame_length)

def get_next_audio_frame():
    
    RESPEAKER_RATE = 16000
    RESPEAKER_CHANNELS = 6 # change base on firmwares, default_firmware.bin as 1 or i6_firmware.bin as 6
    RESPEAKER_WIDTH = 2
    # run getDeviceInfo.py to get index
    RESPEAKER_INDEX = 0  # refer to input device id
    CHUNK = 512
    RECORD_SECONDS = 5
    WAVE_OUTPUT_FILENAME = "output.wav"

    p = pyaudio.PyAudio()

    stream = p.open(
                rate=RESPEAKER_RATE,
                format=p.get_format_from_width(RESPEAKER_WIDTH),
                channels=RESPEAKER_CHANNELS,
                input=True,
                input_device_index=RESPEAKER_INDEX,)

    print("* recording")

    frames = []

    for i in range(0, int(RESPEAKER_RATE / CHUNK * RECORD_SECONDS)):
        data = stream.read(CHUNK)
        
        a = np.frombuffer(data,dtype=np.int16)[0::6]
        frames.append(a.tostring())

    print("* done recording")
    
    stream.stop_stream()
    stream.close()
    p.terminate()

    wf = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
    wf.setnchannels(1)
    wf.setsampwidth(p.get_sample_size(p.get_format_from_width(RESPEAKER_WIDTH)))
    wf.setframerate(RESPEAKER_RATE)
    wf.writeframes(b''.join(frames))
    wf.close()
    
    return a

while True:
    keyword_index = handle.process(get_next_audio_frame())
   
    if keyword_index >= 0:
        handle = pvrhino.create(context_path= '/home/pi/Desktop/Smart_Shower.rhn')

**Comment by kenarsa** [comment]
`get_next_audio_frame` should only read audio and pass it out. I'm not sure why you do all the file operations there. Please try to follow the [demo code](https://github.com/Picovoice/porcupine/blob/master/demo/respeaker/ppnrespeakerdemo/porcupine_demo.py#L68-L87) for reading and processing audio.

**Comment by cjw16** [comment]
Thank you very much, with this I was able to fix my problem.
