### ISSUE TITLE
Musl (Alpine Linux) incompatibility

### ISSUE THREAD

**Issue by sdomi** [Picovoice/porcupine#497]
While running porcupine on Alpine Linux (or, any other musl-based distro), it crashes on `libpv_porcupine.so: __vfprintf_chk: symbol not found`. The source code is unavailable, so the library can't be rebuilt by the user. Will you also provide libraries linked against musl instead of glibc in the future?

**Comment by kenarsa** [comment]
If there is a commercial request we can accommodate for the given customer but in terms of public availability, we will stick to `glibc` for now.
