### ISSUE TITLE
 detect multiple keywords concurrently

### ISSUE THREAD

**Issue by zhangsta-ang** [Picovoice/Porcupine#50]
"Below is a quick demonstration of how to construct an instance of it to detect multiple keywords concurrently"

 I'm a beginner in code, so I'm not sure how this works. Do I edit the python  binding code? and when I call it in my command prompt do I still need the keyword_file_path header?

**Comment by kenarsa** [comment]
I am not sure if I understand the question. could you please elaborate?

**Comment by zhangsta-ang** [comment]
You know on the instructional page, you give sample code on how to detect
multiple keywords concurrently?
I haven't figured out how to integrate it yet. Need more guidance in how to
edit the python sample code.

*Best,*
*Angela Zhang*

B.S., Electrical Engineering
University of Southern California | 2018
Tel: (323)-615-9233
