### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/porcupine-raspberrypi/)

### ISSUE THREAD

**Issue by OmarCloud20** [Picovoice/porcupine#500]
### What is the URL of the doc?
[https://picovoice.ai/docs/quick-start/porcupine-raspberrypi/](https://picovoice.ai/docs/quick-start/porcupine-raspberrypi/)

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
The following command is incorrect: 
pvporcupine_mic --keywords porcupine

It should be:
porcupine_demo_mic --keywords porcupine

![Por](https://user-images.githubusercontent.com/9620570/138573177-2dbd0e28-8392-4eb4-b09f-fed16f68f32a.JPG)

**Comment by kenarsa** [comment]
@mrrostam can you please update/close this issue after we are done with updating quick starts?

**Comment by mrrostam** [comment]
With new release (v2.0), all docs on our website got updated, and the mentioned issue is fixed now.
