### ISSUE TITLE
Porcupine C SDK pv_porcupine_init() num_keywords

### ISSUE THREAD

**Issue by jp-ertola** [Picovoice/porcupine#524]
### What is the URL of the doc?
https://picovoice.ai/docs/api/porcupine-c/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
Is this supposed to represent the number of total words across all .ppn files running on the device?  For example, if I have one .ppn file which contains the keyword for "hello picovoice", should my num_keywords be 2 or 1?  2 because that is the number of words in the keyword file or should it be 1 because that is the number of keyword files being supplied to the pv_porcupine_init() function?

**Comment by kenarsa** [comment]
`1`
