### ISSUE TITLE
Porcupine pv_porcupine_frame_length()

### ISSUE THREAD

**Issue by jp-ertola** [Picovoice/porcupine#525]
### What is the URL of the doc?
https://picovoice.ai/docs/api/porcupine-c/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
`pv_porcupine_frame_length()` returns 512.  Do I need to internally buffer my PCM frames so I pass Porcupine exactly 512 frames per `pv_porcupine_process()` transaction?  Or will Porcupine do the buffering for me so I can pass an arbitrary number of frames per transaction.

Thanks,
JP

**Comment by kenarsa** [comment]
You need to buffer and pass exactly `pv_porcupine_frame_length()` PCM samples. Porcupine does not internally buffer. See also the [doc](https://github.com/Picovoice/porcupine/blob/master/include/pv_porcupine.h#L66-L67)
