### ISSUE TITLE
Can't run the demo.

### ISSUE THREAD

**Issue by fredrikj31** [Picovoice/Porcupine#53]
I tried to run the demo command like this: 
```python demo/python/porcupine_demo.py --keyword_file_paths resources/keyword_files/blueberry_windows.ppn```

But i got this error:
```
Traceback (most recent call last):
  File "demo/python/porcupine_demo.py", line 204, in <module>
    input_device_index=args.input_audio_device_index).run()
  File "demo/python/porcupine_demo.py", line 92, in run
    sensitivities=[self._sensitivity] * num_keywords)
  File "demo/python\../../binding/python\porcupine.py", line 69, in __init__
    library = cdll.LoadLibrary(library_path)
  File "C:\Python\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

What can i do to fix this problem

- Fredrik

**Comment by kenarsa** [comment]
Hi Fredrik, What version of Windows and Python are you using? (32/64bit).

**Comment by fredrikj31** [comment]
I'm using python 3.6.6 and windows 10 $

**Comment by kenarsa** [comment]
32-bit or 64-bit? I suspect that you are using a 64-bit OS but 32-bit python ...

**Comment by fredrikj31** [comment]
Hmmm. Yes i'm using 64-bit... But how does i check if python is 32-bit? @kenarsa

**Comment by fredrikj31** [comment]
Thanks @kenarsa it worked. I reinstalled python because i had python 32-bit and i installed the 64-bit and it helped 👍  Thanks again - Fredrik :)

**Comment by kenarsa** [comment]
anytime. happy it worked.
