### ISSUE TITLE
Can't compile the iOS demo build

### ISSUE THREAD

**Issue by pawan4476** [Picovoice/Porcupine#55]
I tried to compile the iOS demo, but i am getting errors while compiling
 Error is:
Undefined symbols for architecture x86_64:
  "_pv_porcupine_delete", referenced from:
      PorcupineDemo.PorcupineManager.stop() -> () in PorcupineManager.o
  "_pv_sample_rate", referenced from:
      PorcupineDemo.PorcupineManager.start() throws -> () in PorcupineManager.o
  "_pv_porcupine_frame_length", referenced from:
      PorcupineDemo.PorcupineManager.start() throws -> () in PorcupineManager.o
  "_pv_porcupine_multiple_keywords_init", referenced from:
      PorcupineDemo.PorcupineManager.start() throws -> () in PorcupineManager.o
  "_pv_porcupine_multiple_keywords_process", referenced from:
      closure #1 (Swift.UnsafeMutableRawPointer?, Swift.OpaquePointer, Swift.UnsafeMutablePointer<__C.AudioQueueBuffer>, Swift.UnsafePointer<__C.AudioTimeStamp>, Swift.UInt32, Swift.UnsafePointer<__C.AudioStreamPacketDescription>?) -> () in variable initialization expression of PorcupineDemo.PorcupineManager.(audioCallback in _BEC5063E4C49B2A2811E8F4D93649EFF) : @convention(c) (Swift.UnsafeMutableRawPointer?, Swift.OpaquePointer, Swift.UnsafeMutablePointer<__C.AudioQueueBuffer>, Swift.UnsafePointer<__C.AudioTimeStamp>, Swift.UInt32, Swift.UnsafePointer<__C.AudioStreamPacketDescription>?) -> () in PorcupineManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can you please help me to compile the demo build

**Comment by kenarsa** [comment]
are you try to compile for the simulator?

**Comment by kenarsa** [comment]
For some reason, I don't think you are building for the device based on this message "Undefined symbols for architecture **x86_64**:". x86_64 is not the CPU architecture for any iOS device AFAIK. 

Regardless, Porcupine does not support building for the simulator. You need to build for a target iOS device.

**Comment by pawan4476** [comment]
Thank you for your help

**Comment by pawan4476** [comment]
One more help, I want Porcupine to be running continuously in the background listening for wake word without red band on the top when application is minimised, like Siri. Is it possible? if possible please let me know how to bring it into a shape.

**Comment by kenarsa** [comment]
I don't know about that. if you figure it out please share here with the community. thank you in advance!
