### ISSUE TITLE
Install instructions needed

### ISSUE THREAD

**Issue by slloyd88** [Picovoice/Porcupine#56]
### Expected behavior
Install instructions needed.
### Actual behavior
none
### Steps to reproduce the behavior
I want to install it on a RPI but cannot see any instructions on how to do so
Please include the operating system and CPU architecture. When applicable, provide relevant audio data.
RPI 3 B+ running debian stretch

**Comment by kenarsa** [comment]
There are a couple of ways you can integrate (install) Porcupine on RPI.

The integration section of the main README has some information: https://github.com/Picovoice/Porcupine#integration. Also, you can check the Python demo application if you like to use the Python binding.
