### ISSUE TITLE
why porcupine could training without giving my own voice sample?

### ISSUE THREAD

**Issue by dragen1860** [Picovoice/porcupine#577]
Dear all:
   I am supervised by the very-easy own keywords training pipeline. But i felt confused why porcupine does not need any my own keyword samples to train a well network? what the algorithm behand its work? any one give some tips? thank you very much.

**Comment by kenarsa** [comment]
[this article](https://medium.com/@alirezakenarsarianhari/yet-another-wake-word-detection-engine-a2486d36d8d4) has some info about how we think about data efficiency for voice recognition and why.
