### ISSUE TITLE
Access Key causes PICOVOICE_STATUS_TO_EXCEPTION

### ISSUE THREAD

**Issue by sreinders** [Picovoice/porcupine#581]
Hi.

Upon updating porcupine to v2.0 and registering and adding my access key to code I am unable to get wake words working as follows:

- When attempting to run an instance in Python I get a RuntimeError [self._PICOVOICE_STATUS_TO_EXCEPTION[status]()]
- When attempting to test through the Picovoice console I get - Microphone error: "Error: 'pv_porcupine_init' failed with status ACTIVATION_ERROR"

Previously I was testing on v1.9 and had no issues.

Regards

**Comment by kenarsa** [comment]
@sreinders we do need more information to be able to first reproduce and then help. I don't know what OS you are running, what is the CPU, the full error message is missing, etc. I did try the Picovoice Console and it worked just fine for me. I am closing this issue as there is no information to help. Feel free to open a separate issue for each of the items above and provide full information and we can take another look.
