### ISSUE TITLE
Access Key activation errors

### ISSUE THREAD

**Issue by sreinders** [Picovoice/porcupine#582]
Hi.

On what seems to have coincided with updating porcupine to v2.0 and registering/adding my access key to code I am unable to get wake words working. My set up is as follows:

- Device: Raspberry Pi 3 Model B (ARM Cortex-A53)
- OS: Raspbian Buster
- Language: Python v3.7.3
- Package: pvporcupine v2.0.1
- Account: Free (evaluation)

The following code below was working with porcupine v1.9: 

```
import pvporcupine
import pyaudio

porcupine = pvporcupine.create(keyword_paths=['./wake_word.ppn'])

pa = pyaudio.PyAudio()
audio_stream = pa.open(rate=porcupine.sample_rate, channels=1,format=pyaudio.paInt16, input=True, frames_per_buffer=porcupine.frame_length)

while True:
pcm = audio_stream.read(porcupine.frame_length)`
pcm = struct.unpack_from("h" * porcupine.frame_length, pcm)
keyword_index = porcupine.process(pcm)
if keyword_index >= 0:
print("Hotword Detected" , keyword_index)
print("done ", keyword_index)
keyword_index=-1
```

Upon updating to porcupine v2.0 the access key was added to the porcupine instance as follows:

```
import pvporcupine
import pyaudio

access_key = "accessKeyHere"

porcupine = pvporcupine.create(access_key=access_key, keyword_paths=['./wake_word.ppn'])
pa = pyaudio.PyAudio()
audio_stream = pa.open(rate=porcupine.sample_rate, channels=1,format=pyaudio.paInt16, input=True, frames_per_buffer=porcupine.frame_length)

...
```

Now when the script is executed  a run time error as below occurs: 

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/models/tts/agent_voice.py", line 1183, in <module>
    main()
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/models/tts/agent_voice.py", line 955, in main
    porcupine = pvporcupine.create(access_key=access_key, keyword_paths=['./wake_word.ppn'])
  File "/home/pi/.local/lib/python3.7/site-packages/pvporcupine/__init__.py", line 70, in create
    sensitivities=sensitivities)
  File "/home/pi/.local/lib/python3.7/site-packages/pvporcupine/porcupine.py", line 110, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
RuntimeError
```

To further diagnose I have attempted to run the python demo script and test through the pico voice console website, both of which return similar errors that lead me to believe this might be an activation issue with my access key:

```
Traceback (most recent call last):
  File "/usr/local/bin/porcupine_demo_mic", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pvporcupinedemo/porcupine_demo_mic.py", line 202, in main
    input_device_index=args.audio_device_index).run()
  File "/usr/local/lib/python3.7/dist-packages/pvporcupinedemo/porcupine_demo_mic.py", line 88, in run
    sensitivities=self._sensitivities)
  File "/home/pi/.local/lib/python3.7/site-packages/pvporcupine/__init__.py", line 70, in create
    sensitivities=sensitivities)
  File "/home/pi/.local/lib/python3.7/site-packages/pvporcupine/porcupine.py", line 110, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
RuntimeError

```

`"Error: 'pv_porcupine_init' failed with status ACTIVATION_ERROR"`

Any pointers would be greatly appreciated. 

Regards

**Comment by kenarsa** [comment]
Thanks! Do you have internet connectivity? e.g. can you ping google.com or something similar?

**Comment by sreinders** [comment]
Thank you for your reply. Yes, I can confirm internet connectivity. I can ping google.com and other API services that I utilise are able to establish network connections as required. 

In attempts to further diagnose:
- Testing through the pico voice console website now works without activation error as before, potentially an unrelated issue that was fixed?
- I have created a new free account to rule out the access key, and issue persists on the Pi with new access key 

Having seen recent updates to https://github.com/Picovoice/porcupine/issues/579 it looks as though this issue might closely related or in fact be a duplicate: like #579 picovoice is attempting to establish connection through a university firewall.

**Comment by laves** [comment]
@sreinders - we are unable to reproduce with a standard firewall/network config on an RPi 3, so any additional information you could provide would be helpful.

- Can you tell us more about your network configuration? Is it highly restrictive when it comes to accessing external endpoints? - If you move the device to another network does the behavior continue? 
- If you run the python code on a desktop machine (Windows/Linux/macOS) does the issue persist?
- Is your file system on the RPi read-only?

**Comment by sreinders** [comment]
Thanks for the response @laves. 

1. I am connecting through a university connection that is locked down to some degree. I don't have much info regarding the inner workings of its config, but I haven't ran into any issues accessing other endpoints that I require. I try and dig a little deeper, and additionally look into whether I can whitelist any specific external addresses
2. I have just connected the Pi to my home network and both porcupine_demo_mic and my own script work 
3. If I run either of porcupine_demo_mic or my own script via Mac on the same network the behaviour continues, but both work on home network
4. The file system I am running has not been configured to be read-only

**Comment by laves** [comment]
As part of investigating #579, we've tried many different firewall/network configurations and only a full blocking of external IPs caused connection problems, but we got a proper timeout and connection failure. Could you try testing a wake word or context using the [Picovoice Console](https://console.picovoice.ai/) on your network? Once you've tried that, you can whitelist `*.picovoice.net` for your development purposes and we'll keep watch for more related issues.

**Comment by kenarsa** [comment]
close due to inactivity. please re-open if needed
