### ISSUE TITLE
Access Key Activation Limit reached immediately after access key creation upon accessing porcupine in web-frontend

### ISSUE THREAD

**Issue by LarsScha** [Picovoice/porcupine#588]
Hi,

I have porcupine running in Angular and when I called the local web-frontend for the first time right after creating the access key, I immediately exceed the number of allowed devices (3 of 3) and I got the following error.
```
Error: 'pv_porcupine_init' failed with status ACTIVATION_LIMIT_REACHED
```

There is no other device in the network accessing the web-frontend and this behaviour was observed right after creation of the access key.

Expected behaviour: Only 1 of 3 devices should be "used up".

I call the ```@picovoice/porcupine-web-de-worker``` v2.0.1 workers directly:

```
const porcupineFactoryDe = (await import('@picovoice/porcupine-web-de-worker')).PorcupineWorkerFactory
porcupineWorker  = await porcupineFactoryDe.create(accessKey, [customKeyword]) 
```

My setup is the following:

* Web-App Framework: Angular 12.2.8 
* Language: Typescript 4.3.5

The Web-App is running in Docker:

* Docker: 20.10.2
* Docker Base Image: node:12-alpine

The docker container is running on: 
* Ubuntu 18.04.5 
* in Virtualbox v6.1.18

I access the web-frontend from my home system (Windows 10, version 21H2) running on the same Device as the virtual machine.

I have two questions:
* Could you clarify what counts as a device? Maybe this helps me understand the unexpected behavior.
* And is there a way to reset the access key, other than deleting my account and setting up a new one? 

Thank you in advance

**Comment by fquirin** [comment]
I think they store machine-ID in localStorage and if you clear the storage you get a new ID which is basically a new device ... thus after 3 reloads you have reached the limit :-|.
Currently there seems to be no way to reset the key or generate a new one :-(

**Comment by mrrostam** [comment]
I need a bit more information to say what's happening exactly. Are you using the same url address and port for testing your app? Can you check to see if any items exist in the localStorage of the app page?

**Comment by LarsScha** [comment]
Thank you for the quick responses.

Yes, I use the same URL and Port for testing. To be precise I use a specific domain name that is resolved to a specific IP. I have a reverse proxy (nginx) set up to configure the https server and handle the communication between web-frontend and backend.  

The localStorage does not contain any information other than app specific data, such as the nebular auth_app_token, Log, loglevel etc.

**Comment by mrrostam** [comment]
I believe this is addressed in the v2.1 release of Porcupine web binding.
Could you please try the new version with your setup and let us know if the number of the devices increases as expected with your dev flow?

**Comment by LarsScha** [comment]
Thank you, with the new version the number of devices increments as expected by 1 when accessing the web Application and after multiple reloads the number stays that way. 

However, if I call the Web Application on the same device in Incognito-Mode in Chrome (v97.0.4692.99), I use up one device for each incognito window. If this behaviour is intended the issue can be closed. In this case it would be great to have the possibility to reset the activation keys, because for dev purposes I have to access the web app within an incognito window.

**Comment by mrrostam** [comment]
Cool! Given your setup, the incognito-mode behaviour is expected, and it cannot be altered since each window seems like a new device from our perspective. Regarding the activation keys, they reset after 30 days automatically, which might not be helpful in your case.

**Comment by fquirin** [comment]
> However, if I call the Web Application on the same device in Incognito-Mode in Chrome (v97.0.4692.99), I use up one device for each incognito window

I haven't tested this but what if you'd dump your IndexDB after first creation and then restore it for every new incognito window?

**Comment by mrrostam** [comment]
> > However, if I call the Web Application on the same device in Incognito-Mode in Chrome (v97.0.4692.99), I use up one device for each incognito window
> 
> I haven't tested this but what if you'd dump your IndexDB after first creation and then restore it for every new incognito window?

you mean dumping indexDB manually?

**Comment by fquirin** [comment]
Dump it manually and then hardcode the import for your test-page so it gets restored in the new window. I'd assume the machine-ID is generated using some available device and browser parameters, so maybe you have a chance if you use the exact same device + browser + incognito-mode (export in incognitio as well!).

Here is a little page I wrote to test it ... but ... I didn't dare to delete my Index-DB yet :laughing: . Let me know if it works :-p

```
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Porcupine Activation</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <style>
        body {
            font-family: sans-serif;
            padding: 0 16px 16px 16px;
        }
        #results {
            box-sizing: border-box;
            width: 100%;
            height: 250px;
        }
        input {
            margin: 8px;
        }
        li {
            font-size: 15px;
            margin: 8px 0;
        }
    </style>
</head>
<body>
    <div>
        <h3>Porcupine Activation Manager</h3>
        <p>How to:</p>
        <ul>
            <li>'Export' your IndexDB when your client is activated and write down key-value pairs.</li>
            <li>When your client deleted the IndexDB 'create' a new one on the SAME device + browser ...</li>
            <li>... and 'import' previously exported key-value pairs.</li>
        </ul>
        <br>
        <div>
            <button onclick="picovoiceDbExport();">Export</button>
            <button onclick="picovoiceDbCreate();">Create DB</button>
            <button onclick="importAllKeyValuePairs();">Import Key-Value Pairs</button>
        </div>
        <br>
        <div>
            <label>Key 1:<input id="key1"></label>
            <label>Value 1:<input id="val1"></label>
        </div>
        <div>
            <label>Key 2:<input id="key2"></label>
            <label>Value 2:<input id="val2"></label>
        </div>
        <br>
        <textarea id="results">- events -</textarea>
    </div>
    <script>
        var key1 = document.getElementById("key1");
        var val1 = document.getElementById("val1");
        var key2 = document.getElementById("key2");
        var val2 = document.getElementById("val2");
        var results = document.getElementById("results");

        //Porcupine import/export
        function picovoiceDbExport(){
            var requestDb = window.indexedDB.open("pv_db");
            requestDb.onerror = function(err){
                console.error("IndexDB error opening 'pv_db'", err);
                results.value = "IndexDB error opening 'pv_db'";
            };
            requestDb.onsuccess = function(ev){
                var indexDbPp = ev.target.result;
                indexDbPp.onerror = function(ev){
                    console.error("IndexDB error: " + ev.target.errorCode);
                    results.value = "IndexDB error: " + ev.target.errorCode;
                };
                //read
                var pvStore = indexDbPp.transaction(["pv_store"]).objectStore("pv_store");
                results.value = "pv_store data\n\n";
                console.log("pv_store indexNames:", pvStore.indexNames);
                console.log("pv_store keyPath:", pvStore.keyPath);
                console.log("pv_store autoIncrement:", pvStore.autoIncrement);
                results.value += "pv_store indexNames: " + pvStore.indexNames.length + "\n";
                results.value += "pv_store keyPath: " + pvStore.keyPath + "\n";
                results.value += "pv_store autoIncrement: " + pvStore.autoIncrement + "\n\n";
                var n = 0;
                pvStore.openCursor().onsuccess = function(ev2){
                    n++;
                    var cursor = ev2.target.result;
                    if (cursor) {
                        console.log("pv_store key " + n + ": " + cursor.key + ", value " + n + ":" + cursor.value);
                        results.value += "pv_store key " + n + ": " + cursor.key + "\n";
                        results.value += "pv_store value " + n + ": " + cursor.value + "\n\n";
                        cursor.continue();
                    }
                };
            };
        }
        function picovoiceDbCreate(){
            var requestDb = window.indexedDB.open("pv_db");
            requestDb.onerror = function(err){
                console.error("IndexDB error opening 'pv_db'", err);
                results.value = "IndexDB error opening 'pv_db'";
            };
            requestDb.onupgradeneeded = function(ev){
                console.log("IndexDB 'pv_db' upgrade needed");
                results.value = "IndexDB 'pv_db' upgrade needed. \n\n";
                var indexDbPp = ev.target.result;
                if (indexDbPp.objectStoreNames.contains('pv_store')) return;
                indexDbPp.onerror = function(ev){
                    console.error("IndexDB error: " + ev.target.errorCode);
                    results.value = "IndexDB error: " + ev.target.errorCode;
                };
                //create
                var pvStore = indexDbPp.createObjectStore("pv_store");
                pvStore.transaction.oncomplete = function(ev2){
                    console.log("Created object store 'pv_store'");
                    results.value += "Created object store 'pv_store'";
                };
            };
        }
        function importAllKeyValuePairs(){
            results.value = "Importing\n";
            if (key1.value && val1.value) picovoiceDbImport(key1.value, val1.value);
            if (key2.value && val2.value) picovoiceDbImport(key2.value, val2.value);
        }
        function picovoiceDbImport(key, value){
            var requestDb = window.indexedDB.open("pv_db");
            requestDb.onerror = function(err){
                console.error("IndexDB error opening 'pv_db'", err);
                results.value = "IndexDB error opening 'pv_db'";
            };
            requestDb.onsuccess = function(ev){
                var indexDbPp = ev.target.result;
                indexDbPp.onerror = function(ev){
                    console.error("IndexDB error: " + ev.target.errorCode);
                    results.value = "IndexDB error: " + ev.target.errorCode;
                };
                //write
                results.value += "\npv_store write:\n";
                var pvStore = indexDbPp.transaction(["pv_store"], "readwrite").objectStore("pv_store");
                pvStore.put(value, key).onsuccess = function(ev2){
                    console.log("set key: " + key + " to value: " + value);
                    results.value += "set key: " + key + "\n";
                    results.value += "to value: " + value + "\n";
                };
            };
        }
    </script>
</body>
</html>
```
