### ISSUE TITLE
Initiate the ppn engine inside web workers using porcupine-web-**-factory packages

### ISSUE THREAD

**Issue by fquirin** [Picovoice/porcupine#589]
### Expected behaviour

The 'Porcupine' WASM module created via one of the web factories (e.g.: porcupine-web-en-factory) should work inside and outside of web workers.

### Actual behaviour

Outside of Javascript web-workers (UI main thread) the `Porcupine.create` method works, inside of web workers it hangs indefinitely at pv_porcupine_init async (_context12, step 76).

### Steps to reproduce the behaviour

- Get the '@picovoice/porcupine-web-en-factory' lib
- set up your webpage
- call `const handle = await Porcupine.create(accessKey, [{builtin: "Bumblebee", sensitivity: 0.7}]);` in UI main thread
- call same function inside a web-worker

I'm assuming this is related to the validation of the access key, because data is stored in localStorage which cannot be accessed from web worker thread.

A related issue is that each time the localStorage is cleared a new machine ID will be generated and thus the browser will be regarded as new device. Since many systems will regularly clear the cache you will generate new ID constantly and run into the free tier limit immediately.

**Comment by mrrostam** [comment]
Thanks for pointing out this. `porcupine-web-en-factory` can no longer be used in a custom worker, and it's only suitable for creating a `porcupine` instance on the main thread. I noticed the package readme is a bit confusing; we'll update all docs soon to clarify this point.

**Comment by fquirin** [comment]
Are you saying this is by design and will not be fixed? :disappointed: Is the 'porcupine-web-en-worker' working around this limitation or is it actually processing in the main thread as well?
Under the current conditions I don't think I'll be able to update to v2.0 :-/

**Comment by mrrostam** [comment]
We are working on this. However you can easily use `porcupine-web-en-worker` to create a web worker from the main thread. I am wondering why you need to use `porcupine-web-en-factory` for such a task?

**Comment by fquirin** [comment]
I'm using [SEPIA Web-Audio](https://github.com/SEPIA-Framework/sepia-web-audio) library to build a custom pipeline of audio worklets and workers and each module has to implement a specific interface. I cannot use the existing Porcupine worker in this context that's why I need to create the Porcupine instance inside the worker. Besides that I'm preloading the WASM file dynamically and inject it into the worker since it is half the size (1MB) and I can skip the base64 to Uint8 array conversion. Keyword files are loaded on-demand as well to avoid more overhead.

**Comment by ksyeo1010** [comment]
https://github.com/Picovoice/porcupine/pull/612 now solves this issue. Get the latest package: 2.0.3.

**Comment by fquirin** [comment]
Awesome, its working :partying_face: 
Ty!
