### ISSUE TITLE
Porcupine Issue: Run time error while running inside docker

### ISSUE THREAD

**Issue by arjun-027** [Picovoice/porcupine#599]
Hi  ,

I need to run porcupine_demo_mic (python) inside docker . While running inside docker it shows run time error. Could anyone please help me to sort this out.

Error log:
Traceback (most recent call last):
  File "porcupine_demo_mic.py", line 205, in <module>
    main()
  File "porcupine_demo_mic.py", line 201, in main
    input_device_index=args.audio_device_index).run()
  File "porcupine_demo_mic.py", line 88, in run
    sensitivities=self._sensitivities)
  File "/usr/local/lib/python3.6/dist-packages/pvporcupine/__init__.py", line 70, in create
    sensitivities=sensitivities)
  File "/usr/local/lib/python3.6/dist-packages/pvporcupine/porcupine.py", line 110, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
RuntimeError

**Comment by kenarsa** [comment]
Thanks @arjun-027 for the report. Can you give us step-by-step instructions on how to re-create your environment so we can re-create your issue? then we are able to debug and help.

**Comment by arjun-027** [comment]
I am doing a  voice recognition based project (Jetson nano) . Am already using a docker container for that project. Now , I am trying to integrate wake word detection by the help of picovoice.  I cloned the github repository (picovoice/porcupine) inside that docker container. But while trying to run the program above mentioned error occurs. 
[Command : - porcupine_demo_mic  --show_audio_devices had executed successfully]. 
Please , help me to sort this out. Kindly ask any other details you need

**Comment by kenarsa** [comment]
To clarify you have a docker running on Nano? If you want to use Porcupine from Python you can simply install the PIP packages. Can you try that?

**Comment by arjun-027** [comment]
I have already pip installed pvporcupinedemo  , but still the problem persists. Outside the docker container program works perfectly.

**Comment by kenarsa** [comment]
What's the version of `pvporcupinedemo`? Can you make sure it is the latest (`2.0.3`) and give us the error message again? The latest version gives better error messages.

**Comment by arjun-027** [comment]
I have installed the latest version...Even installed today with the latest version.

Error log:
Traceback (most recent call last):
File "porcupine_demo_mic.py", line 205, in
main()
File "porcupine_demo_mic.py", line 201, in main
input_device_index=args.audio_device_index).run()
File "porcupine_demo_mic.py", line 88, in run
sensitivities=self._sensitivities)
File "/usr/local/lib/python3.6/dist-packages/pvporcupine/init.py", line 70, in create
sensitivities=sensitivities)
File "/usr/local/lib/python3.6/dist-packages/pvporcupine/porcupine.py", line 110, in init
raise self._PICOVOICE_STATUS_TO_EXCEPTIONstatus
RuntimeError

**Comment by kenarsa** [comment]
OK. I just updated the package. Can you please install `pvporcupinedemo 2.0.4`. Once you have it, it should give you a more descriptive error code and I can use that to help out.

**Comment by kenarsa** [comment]
close due to inactivity. please re-open if needed
