### ISSUE TITLE
Unable to train more wake words, unable to delete trained wake words

### ISSUE THREAD

**Issue by hrishim** [Picovoice/porcupine#604]
How do I delete a custom wake word. I am still testing how well PicoVoice will suit me. I trained the same wake word three times for different platforms. Since the recognition of the wake word is not good I want to change it. Now Porcupine (in Pico Console) says I cannot add another wake word since the limit is 3 wake words. There seems to be no way to delete the wake word I created.

Please help

Hrishi

**Comment by kenarsa** [comment]
You cannot delete them and you don't need to. You can train a certain number of models per 30 days. `free tier` is 3, `starter tier` is 10, etc ... you need to wait for your training allowance to reset (max 30 days) and you can train 3 more.
