### ISSUE TITLE
 Linux arm64 support

### ISSUE THREAD

**Issue by GiviMAD** [Picovoice/porcupine#609]
Are there plans to support linux arm64?

**Comment by kenarsa** [comment]
please read the docs before opening an issue. the supported platforms are clearly listed in the readme

**Comment by GiviMAD** [comment]
Sorry @kenarsa but it still unclear to me, I saw Linux (x86_64) as if any device with that SO and architecture was supported, but for arm64 I only saw specific linux devices like the raspberry. 
Should I asume that the raspberry binary will work on other arm64 linux boards? I didn't saw any references to that.

**Comment by GiviMAD** [comment]
Or a arm64 docker container which is what I want to try using the java sdk, but the host is not a raspberry. Anyway trying to save some time I will give a try, sorry to bother.
