### ISSUE TITLE
[ERROR] could not find the pronunciation of XXX

### ISSUE THREAD

**Issue by dduwoye** [Picovoice/Porcupine#61]
Hello!
I tried to use the optimizer with paired keywords like "ok" + the name of a french brand but without success. Typically, "OK <BRAND>" as a wake-word. 

Is there any way to extend the pronunciation directory ? For example by providing audio data samples of french users saying this brand name?  

Best,
Denis

**Comment by kenarsa** [comment]
This is mentioned in the second FAQ [here](https://github.com/Picovoice/Porcupine/tree/master/tools/optimizer).

If you provide the words missing we add them to the dictionary for next release. If you have a commercial application we can help earlier.

**Comment by kenarsa** [comment]
Thank you. I'll get back to you over email.
