### ISSUE TITLE
Need a way to set microphone device id for WebVoiceProcessor

### ISSUE THREAD

**Issue by mikob** [Picovoice/porcupine#611]
We have a microphone selector in the UI (web platform), and need to change the device id for the wake word engine. Perhaps `WebVoiceProcessor.init`  should accept another optional parameter for deviceId?

**Describe the solution you'd like**
Would like to set it when initialized. I already have mic permission from the user.

**Describe alternatives you've considered**
Not sure if something like this will work:
```ts
const stream = await navigator.mediaDevices.getUserMedia({
  audio: { deviceId: micDeviceId ? { exact: micDeviceId } : undefined },
});
const audioContext = new (window.AudioContext ||
  // @ts-ignore
  window.webkitAudioContext)();
this.webVp.audioSource.connect(
  audioContext.createMediaStreamSource(stream)
);
```

**Additional context**
Misplaced originally here: https://github.com/Picovoice/web-voice-processor/issues/16

**Comment by mikob** [comment]
Made a PR: https://github.com/Picovoice/web-voice-processor/pull/17

**Comment by kenarsa** [comment]
Thank you @mikob! Just realized the original repo you opened the issue at was the correct one and I was mistaken. sorry about that. this is good and we get it sorted out. looking into PR ...

**Comment by ksyeo1010** [comment]
Merged https://github.com/Picovoice/web-voice-processor/pull/17.
Releasing a new package soon.
