### ISSUE TITLE
Keyword boundaries

### ISSUE THREAD

**Issue by valeri-atamaniouk** [Picovoice/porcupine#614]
**Is your feature request related to a problem? Please describe.**
Currently Porcupine library consumes audio frames and notifies client code if the keyword has been detected. However the library doesn't provide information about keyword start/end samples. In other words, user never knows when (at which sample) the keyword has started, and when it has finished.

**Describe the solution you'd like**
pv_porcupine_process should return not only keyword index, but also offset in samples for the keyword start and end.

**Comment by kenarsa** [comment]
what's the use case?

**Comment by valeri-atamaniouk** [comment]
The use case is that the audio stream must be post-processed and the stream must include the keyword itself.

**Comment by kenarsa** [comment]
got it. is this an AVS use case?

**Comment by kenarsa** [comment]
closing due to inactiviity. reopen if needed
