### ISSUE TITLE
Detection not working properly on iOS 15.1, iOS 15.2

### ISSUE THREAD

**Issue by dlfk99** [Picovoice/porcupine#621]
### Expected behaviour

Tried the example on your webpage (https://picovoice.ai/platform/porcupine/) with iOS 15.1 on my iPhone 7 and iPad.

### Actual behaviour

Detection doesn't work properly. The status bar shows that the microphone records audio.
1. On the iPhone "English" and the appropriate colors worked. The other three wake words ("Deutsch", "Español"...) did not.
2. On the iPad I needed to reload the page twice. After that I got the same behaviour as with the iPhone. After reloading again suddenly "Español" worked but none of the others.
3. Behaviour with iOS 15.2 is the same. I tested again after updating the phone.

### Steps to reproduce the behaviour

1. Open https://picovoice.ai/platform/porcupine in Safari on iOS 15.1, iPhone 7.
2. Start the demo.
3. Try the different wake words.

I also built an Angular App but cannot test it because of "Error: 'pv_porcupine_init' failed with status ACTIVATION_LIMIT_REACHED".

**Comment by ErisMik** [comment]
Thank you for the issue report.

With regards to the `ACTIVATION_LIMIT_REACHED` error: Currently the free tier allows 3 active "devices" per month. You need to wait 30 days and not use a device and it will be decommissioned automatically.

**Comment by ErisMik** [comment]
The issue with the lamp demo on iOS Safari has been resolved. Feel free to open another issue if you run into any more problems.
