### ISSUE TITLE
Flag show_audio_devices fails to list connected USB sound card 

### ISSUE THREAD

**Issue by g0ierli** [Picovoice/porcupine#626]
### Expected behavior
I expect --show_audio_devices lists my connected USB sound card like "arecord -l" and audacity do

### Actual behavior
porcupine doesn't detect the USB sound card (or does the parsing of the device list from miniaudio fail?)
therefore, it cannot be selected to capture audio.
output is:
index: 0, name: Discard all samples (playback) or generate zero samples (capture)

Note: microphone from the USB sound card was successfully tested by recording via audacity.

### Steps to reproduce the behavior
raspbian stretch on raspi 3B - fully updated, porcupine compiled with cmake 3.21.0
sound card: https://www.ugreen.com/products/usb-external-stereo-sound-card

**Comment by kenarsa** [comment]
I just tried it on an Ubuntu box with a USB mic and it worked fine. I tried the Python demo. What is the demo you are using? What is the USD sound card? What is the output of `arecord` when you list audio devices? Keep in mind that you can create your own demo using ALSA as well as it seems like `arecord` is working for you.

**Comment by g0ierli** [comment]
I'm using the C demo. The sound card is the one as shown in the original message.
"arecord -l" output:
**** List of CAPTURE Hardware Devices ****
card 0: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0


Yes, i probably will analyse the demo code later and hopefully find a nice solution for my setup. Maybe it's just a simple config that needs to be adapted. Just wanted to let you know, because it might be a bug.

**Comment by kenarsa** [comment]
@g0ierli, thank you! We will def look into it. This could be the limitation of `miniaudio` but even if that is the case we better figure it out.

**Comment by kenarsa** [comment]
We did take a look and couldn't reproduce with the USB mic we have on RPI. I think it is the combo of `miniaudio` backend your specific mic that causes it. If you can reproduce it with another USB mic as well we can try to buy it and reproduce it. Thanks!
