### ISSUE TITLE
pronunciation not found

### ISSUE THREAD

**Issue by erfan-tivakoli** [Picovoice/Porcupine#63]
Hi, and thanks for your great product

My problem is that When i try to run
 tools/optimizer/mac/x86_64/pv_porcupine_optimizer -r resources/ -p mac  -o . -w "hey rimon"
I will get the following error:
[ERROR] could not find the pronunciation for 'hey rimon'
When I've read the docs, it was mentioned that only the words in english are supported.
I wanted to know is there anyway that I can add the pronunciation to the dictionary so I will be able to get my costume keyword wake up model?
Thanks

**Comment by kenarsa** [comment]
Hello! Unfortunately, there is no API to add pronunciation by developers. We can add the pronunciation to the next release fo engine. Can you provide an example pronunciation of rimon?

**Comment by erfan-tivakoli** [comment]
Hi!
The pronunciation goes something like /rʌɪməʊn/ and /rʌɪmɔːn/ (The first one is preferred if porcupine just needs one).
I don't know wether the phonetic I provided is enough or not?
Thanks :)

**Comment by kenarsa** [comment]
Hi @erfan-tivakoli ! Thank you, this is perfect. We will add it to the dictionary for our next release. I will comment on the issue here when done. Thanks.

**Comment by tejasparekh** [comment]
can you please add "adbot" keyword and also it would be great if you can provide functionality where the developer can add custom keyword it would be great.

**Comment by erfan-tivakoli** [comment]
Hi @kenarsa !
hope you're doing well

I don't want to seem rude
but I wanted to know if you can give me an estimation of your next release
I want to add your feature to my project, I liked to have an estimation for myself to complete it

thanks again
Erfan

**Comment by kenarsa** [comment]
Unfortunately, I don't have an estimation at the moment. I will keep you posted.
