### ISSUE TITLE
Pronunciation not found

### ISSUE THREAD

**Issue by michaelsobczak-qeexo** [Picovoice/Porcupine#64]
### Expected behavior
Train optimizer with "homie"

### Actual behavior

```[ERROR] could not find the pronunciation for 'homie'```

### Steps to reproduce the behavior
tools/optimizer/mac/x86_64/pv_porcupine_optimizer -r resources -w homie -p mac -o my_models

Please include enough details so that the issue can reproduced independently by the resolver.

**Comment by kenarsa** [comment]
Thanks. Will add it to next release.

**Comment by michaelsobczak-qeexo** [comment]
Any idea when next release might be occurring?

**Comment by kenarsa** [comment]
within the next two months
