### ISSUE TITLE
Porcupine Issue: wake word not recognized python(rpi)

### ISSUE THREAD

**Issue by Dikkedibbes** [Picovoice/porcupine#650]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Actual behaviour
The demo is listening but not detecting. In my .asoundrc I tried putting the rate at 16000 and I know the device card and number are correct. Mic also shows in show_audio_devices and when removed while listening I get an error. 

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

**Comment by Dikkedibbes** [comment]
I checked sample rate of my soundcard and it gived 48k and 44k

**Comment by Dikkedibbes** [comment]
--output_path gives me a file of 8 bit 8khz so something is going wrong with sample rate for input I think? How should I change my .asoundrc? Solutions online havent worked

**Comment by kenarsa** [comment]
the audio recording setup is out of the scope of this repo. I do suggest trying to follow tutorials such as [this](https://pimylifeup.com/raspberry-pi-porcupine/).
