### ISSUE TITLE
Porcupine Issue: Respeaker-rpi0/porcupine_demo_mic.c demo doesn't work on Raspberry OS Bullseye

### ISSUE THREAD

**Issue by hedgemybets** [Picovoice/porcupine#662]
### Expected behaviour

The instructions in the README are to first install wiringpi:
sudo apt-get install wiringpi.

Expect behavior is for the library to install without errors.

### Actual behaviour

E: Package 'wiringpi' has no installation candidate

In researching this, it appears that if your RPi OS has the gpio command, wiringpi is already installed and you're in luck.
If you have Bullseye, gpio is not installed since wiringpi has been deprecated.

I see two ways to fix this. One is to use another library to communicate via SPI, such as [spidev-lib](https://github.com/milekium/spidev-lib). The demo C program would need to be modified.
The other is to build and install wiringpi from the clone of the git repo of [wiringpi](https://github.com/WiringPi/WiringPi).

**Comment by kenarsa** [comment]
I think it works on Raspbian. If you can reproduce we can take a look. Otherwise, feel free to open issues on those repos if you have not done already.

**Comment by hedgemybets** [comment]
Thanks, it probably does work on Raspbian per my research, however it doesn't work on Raspberry Pi OS (rebranded name of Raspbian) Bullseye, the latest release, since the library required is deprecated and not available. Maybe it's more of a documentation issue to specify the demo doesn't work on Bullseye or provide a workaround.

**Comment by kenarsa** [comment]
@hedgemybets thank you for the information. this is super helpful. We do want to be able to run on the latest official OS anyway. So we need to fix this. PRs are really welcome as I think it would be hard for me to prioritize this near-term. If you find a solution I appreciate a PR :)

**Comment by hedgemybets** [comment]
Thanks, FYI, I did compile the WiringPi library without error on my Pi Zero W, but I seem to have an issue with my GCC toolchain as I get a segmentation fault when running the "gpio -v" command or linking/running the porcupine demo program.

My workaround will be to take the easy way out and downgrade the O/S and try again. As for the bug tag, maybe "enhancement request" is more accurate. I believe there are probably a lot of libraries and dependencies that haven't caught up with the recent release of Bullseye.
