### ISSUE TITLE
Raspberry Pi Pico 2040

### ISSUE THREAD

**Issue by IndianTinker** [Picovoice/porcupine#665]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to use PicoVoice with RP2040. KWS is possible with Edge impulse. However, it is hard to find a nice speech-to-intent provider. Plus I would love to have an integrated solution, where KWS and S2I is on the same platform.

**Describe alternatives you've considered**
Edge Impulse

**Additional context**
I think edge ASR could get big and I want to use PicoVoice to prototype use cases.

**Comment by kenarsa** [comment]
let's keep this open and see how much traction it gets. then we can prioritize long-term. what's the board you are using?

**Comment by Technerder** [comment]
+1 for this, Porcupine and Cheetah support for the RP2040 would be awesome.

**Comment by kenarsa** [comment]
I don't think we will be able to prioritize this in the coming months. hence closing for now. If things changes on our end we will re-open to track progress.
