### ISSUE TITLE
Node.js on RPI Zero 2W: PvStatusActivationLimitReached

### ISSUE THREAD

**Issue by dmca-glasgow** [Picovoice/porcupine#668]
I am running Node.js v16.14.0 on a Raspberry Pi Zero 2 W with Raspberry Pi OS Lite (Bullseye 32-bit).  I am using the [Adafruit voice bonnet](https://www.adafruit.com/product/4757) for microphone (tested and working).

I'm trying to run the [mic demo](https://github.com/Picovoice/picovoice/blob/0b1142884c180a4f6ee05a41622db0b64a04d55a/demo/nodejs/mic.js).

### Expected behaviour

I can run the demo using the above hardware.

### Actual behaviour

I come across the following error:

```sh
Error: Porcupine failed to initialize
```

Upon debugging I see this error comes from [here](https://github.com/Picovoice/porcupine/blob/e35caa75aff42a904695fdf0cfd26a70cd595a5b/binding/nodejs/index.js#L144).

What is the cause of this?  Is there anything I can do to get around it?

### Steps to reproduce the behaviour

* Install fresh Raspberry Pi OS Lite (32 or 64 bit I tried both) from the official imager and insert into Raspberry Pi Zero 2 W
* Install Adafruit voice bonnet following [this](https://learn.adafruit.com/adafruit-voice-bonnet/audio-setup)
* Install Node.js following [this](https://snapcraft.io/install/node/raspbian#install)
* Install Picovoice demo following [this](https://github.com/Picovoice/picovoice/tree/0b1142884c180a4f6ee05a41622db0b64a04d55a/demo/nodejs#install-npm-package)
* Run the following:

```sh
pv-mic-demo \
  --access_key ${ACCESS_KEY} \
  --audio_device_index 3 \
  --keyword bumblebee \
  --context_file_path ./smart_lighting_raspberry-pi.rhn
```

**Comment by mrrostam** [comment]
`PvStatusActivationLimitReached` error means that your AccessKey has reached its active-device limit. You may confirm this by going to the Picovoice Console and seeing if there is any available device to use (out of 3). Beware that you can use up more than one device on the same board if the OS is changed/updated.

**Comment by dmca-glasgow** [comment]
Ahh, thanks for your help @mrrostam.

I had trouble with a different microphone HAT (ReSpeaker 2) and while trying to problem solve I have re-flashed my SD card several times.  (I didn't realise anyone was counting!)

I just logged into the Picovoice Console and see that I have one access key that is maxed out, but I can't delete it or create a new one. I have zero seconds usage!  Is it possible to reset my devices, or just delete the access key so I can start again?

**Comment by mrrostam** [comment]
You're welcome, regarding the AccessKey, there is no way to delete/reset it, but the good news is the number of active-devices is reset after 30 days.
