### ISSUE TITLE
children voices (<= 5)

### ISSUE THREAD

**Issue by cap-blackbeard** [Picovoice/porcupine#671]
My Raspberry Pi 3b is very responsive when my wife or I speak. But when our child (5Years) speaks the ww, the Rpi rarely responds.
Is it because the ww may be trained with adult voices?

Can you consider children's voices for the future?

**Comment by kenarsa** [comment]
thank you for the report. we currently don't have plans to add data for children around the age of 5. there is a company that focuses on this specific use case in the UK (I cant recall their now right now). but they might be able to help?
