### ISSUE TITLE
iOS simulator binary

### ISSUE THREAD

**Issue by herlihalim** [Picovoice/Porcupine#68]
### Expected behavior
When embedded for iOS project, it should be compilable for both deploying to device and simulator.

### Actual behavior
It'll only compile if the target is to actual device.

### Steps to reproduce the behavior

Compile the demo project on simulator, it will fail due to the binary was built only for device architecture.

I think it's probably worth it to provide a universal binary for iOS, otherwise it'll mean that adding this library to the project will cause that the project no longer compilable for simulator. The barrier of entry to adopt this library will be really high.

**Comment by kenarsa** [comment]
Thanks for bringing it up. You are correct. We had this request multiple times now.

I am going to put it on our task list for the next sprint. I'll keep you posted.

**Comment by herlihalim** [comment]
Thanks!! Also noticed that the .a is compiled with the target deployment of 11.2. Is it possible to lower it down maybe to 10.0 or 11.0, unless there's a specific reason that might cause difficulty?

This is just again, about lowering barrier of entry.

**Comment by kenarsa** [comment]
I will check to make sure there is no good reason for it. Much appreciate the contribution. I'll keep you posted. I think a good time for pushing all this in would be v1.5 release. But I see how we can accelerate it.

**Comment by fabioknoedtbcgdv** [comment]
Also waiting for that. Thanks!

**Comment by keyurhirani** [comment]
Hello,
I am getting some error like,

No such module 'pv_porcupine' in PorcupineManager.swift class

**Comment by benrudhart** [comment]
Are there any news on this issue? I'd at least like to get rid of the warnings when building for simulator or device that the other framework (libpv_porcupine_iOS/ libpv_porcupine_Mac respectively) is throwing

**Comment by kenarsa** [comment]
I still like to get this done. It is unlikely to have it ready in 2018. But I expect it to be out Q1 2019.

**Comment by syedhali** [comment]
Great library guys! Any chance there's been any progress on this?

**Comment by JohnBRTS** [comment]
any chance there's been progress on this? It would be very helpful to be able to run this on a simulator instead of having to use physical devices

**Comment by kenarsa** [comment]
the new release (v1.6) should run on the simulator as well.
