### ISSUE TITLE
Allow training of wake words for older versions via Picovoice console

### ISSUE THREAD

**Issue by fquirin** [Picovoice/porcupine#680]
**Is your feature request related to a problem?**

Wake words trained for Porcupine v2.0 won't work with v2.1 and vice versa. Since developers cannot always update right away and release new versions they depend on support for older versions at least for some transition period. Currently it is not possible to train v2.0 wake words anymore via the online console which effectively breaks the custom wake word feature for all apps and devices that still have to run v2.0.

**Describe the solution you'd like**

Let users train custom wake words for older versions (v2.0 atm) via the console or release offline tools to train older wake words.

**Comment by kenarsa** [comment]
you can keep using trained v2.0 models, no?

**Comment by fquirin** [comment]
Yes, but users who are just getting started cannot create custom wake words at the moment :-(

**Comment by kenarsa** [comment]
got it.  we don't have plans to provide this at the moment as it incurs lots of ops and almost all customers are either happy to stay with already trained (older) models or upgrade to the newest version. I will keep this in mind for the future but closing now as there is no immediate action.

**Comment by fquirin** [comment]
Ok. I'm about to update to 2.1 soon ... any immediate plans for 2.2? ^^ :see_no_evil:
