### ISSUE TITLE
Porcupine Issue: v1.9 and Android 11

### ISSUE THREAD

**Issue by jwoodwardtfx** [Picovoice/porcupine#688]
I have downloaded the repository for Porcupine v1.9 and have built/run the demo activity (in porcupine-1.9\demo\android\Activity).

This works fine on an Android 10 device (i.e. command phrases are recognized), but fails on an Android 11 device (a stock Pixel 4a).

Looking at the manifest, it has a compileSdkVersion/targetSdkVersion of 30 (i.e. Android 11), so I'm assuming it is intended to support Android 11?

If I drop the targetSdkVersion to 29, then the app works fine on the Android 11 device. Given that Google are going to mandate an API level of 30 for the Play Store, this isn't really a long term solution.

Initially, I assumed this may be due to some permission difference or because scoped-storage is now enforced. However, the permissions seems fine and Porcupine doesn't report any exception when starting. Therefore, I'm assuming it can load the voice model/param files. Also, if I breakpoint I can see valid samples being passed from the microphone to porcupine.process (inside PorcupineManager).

Any ideas?

**Comment by kenarsa** [comment]
Can you try the latest? We can support you if you use the latest version. We cant actively support all the older versions in our public repositories.

**Comment by jwoodwardtfx** [comment]
I’m afraid it’s not that simple for us. Our customer has tested and approved v1.9 with the wake words we previously purchased that only work with this version of Porcupine.

Also, looking at the newer releases (v2 onwards), it appears that they call out to a Picovoice server (and hence require Internet access) – our requirement is for the wake word detection to work in a hard offline system.

Thanks,
Joe



Joe Woodward    [cid:terrafix_logo_c4846a8b-bd81-47d8-bb06-1ac36c68a730.png]
Senior Design Engineer


[cid:bigp_81c2f6a6-a62b-46d8-9e3d-a17bea6d30ab.png]     01782 577 015

[cid:newemail_b5e090f0-e18d-412b-8217-7f2796c0c338.png] ***@***.***       [cid:big_web_a2f679e7-4123-474c-9f33-faa3fca2d2a8.png]  www.terrafix.co.uk<http://www.terrafix.co.uk/>

[cid:big_add_5c6b5340-6064-4031-bce1-2389ab7d7127.png]  Bladon House, Festival Way, Stoke-on-Trent, Staffordshire, ST1 5SH

[cid:bsi-acc_330930ab-3b8a-4513-b7b0-c8573cfeb25a.png]   [cid:cyberessentials_certificationmarkplus_colour_d2b9bdd6-13a2-4c5b-9dc6-fac017514fc3.png]
                   <https://www.twitter.com/terrafixlimited> [cid:twitter_social_icon_circle_color_2a5aaf5e-275b-4881-80a2-aaf5cecfdfeb.png] <https://www.twitter.com/terrafixlimited>

The content of this message is confidential.  If you have received it by mistake, please inform us by email reply and then delete the message.  It is forbidden to copy, forward or in any way reveal the contents of this message to anyone.  The integrity and security of this email cannot be guaranteed over the internet.  Therefore, Terrafix Limited will not be held liable for any damage caused by this message.  Please do not print this email unless it is necessary.
Terrafix Limited is a limited company registered in England and Wales.  Registration number: 1650825.  Registered office: Bladon House, Festival Way, Stoke-on-Trent, Staffordshire, ST1 5SH.

**Comment by kenarsa** [comment]
got it. in that case, please reach out to your point of contact at picovoice directly. then we can look into it and see how we can help out. I am closing this issue and await your direct contact.
