### ISSUE TITLE
pvporcupine.create has no access key in my code, yet it functions?

### ISSUE THREAD

**Issue by TrackLab** [Picovoice/porcupine#692]
From what I have taken from the documenation, when creating a procupine object, a access key is required. 
However, in the code I am using currently, which is taken from the porcupine demo, no access key is set.

```
porcupine = pvporcupine.create(
                library_path=self._library_path,
                model_path=self._model_path,
                keyword_paths=self._keyword_paths,
                sensitivities=self._sensitivities)
```

Why is that? I have sent my project to a friend, and for some reason, he gets the error 
`TypeError: create() missing 1 required positional argument: 'access_key'`

**Comment by kenarsa** [comment]
you are probably on an old version of Porcupine.

**Comment by TrackLab** [comment]
> you are probably on an old version of Porcupine.

I am using pvporcupine 1.9.5
