### ISSUE TITLE
[PorcupineActivationError: Initialization failed.]

### ISSUE THREAD

**Issue by umorjyoti** [Picovoice/porcupine#698]
let porcupineManager;
async function createPorcupineManager() {
  try {
    porcupineManager = await PorcupineManager.fromBuiltInKeywords(
      accessKey,
      [BuiltInKeywords.ALEXA, BuiltInKeywords.BLUEBERRY],
      detectionCallback,
    );
    addListener();
    console.log(porcupineManager);
    console.log('porcupine started');
  } catch (err) {
    console.log(err);
  }
}
let detectionCallback = keywordIndex => {
  if (keywordIndex === 0) {
    // detected `porcupine`
    console.log('HI');
  } else if (keywordIndex === 1) {
    console.loh('Hello');
  }
};

async function addListener() {
  await porcupineManager.start();
  console.log('started');
}

This is my react native code, I am getting these error while calling createPorcupineManager()

**Comment by mrrostam** [comment]
I cant see the error you're getting. Can you send it here as well?

**Comment by umorjyoti** [comment]
Hey , before I was getting the Initialization failed error, its solved, but now the problem is with the ppn file.
![Screenshot_1649304444](https://user-images.githubusercontent.com/52374373/162118270-7fe42336-c649-4deb-945d-f0ef1209e8e3.png)

**Comment by umorjyoti** [comment]
Hi, I was getting the Initialization failed error, (the issue label), its solved now, I was also setting the ppn file path as the './android/app/src/main/asset/wakeWord.ppn', whereas I only need to set 'wakeWord.ppn', anyways thanks its solved now

**Comment by abhidharme** [comment]
[PorcupineActivationRefusedError: Porcupine init failed:
  [0] Picovoice Error (code `00000136`)
  [1] Picovoice Error (code `00000136`)
  [2] Picovoice Error (code `00000136`)]
I am getting this error , can any one help me to resolve this
