### ISSUE TITLE
Repository size > 3 gig

### ISSUE THREAD

**Issue by jefhil** [Picovoice/Porcupine#70]
You might consider reducing size to speed up downloads

**Comment by kenarsa** [comment]
Thanks for the suggestion. There is a compromise between accuracy and size of the repository. You need about a 1 GB of data to run optimizer properly. I suppose we can remove the history for them and save some space. Also, LFS is an option. But quite expensive on GitHub considering the current traffic.

**Comment by lasote** [comment]
Maybe you could store the data in a different place and provide a simple script to download it. Maybe bintray.com could be a good match? If you only need the data to run the optimizer is not a bad idea in my opinion
