### ISSUE TITLE
Can't run the porcupine_demo_file demo

### ISSUE THREAD

**Issue by unebonnevie** [Picovoice/porcupine#704]
Hi,

I am trying out Porcupine.  I had created an account with Picovoice and have the access key.  However, every time I try to run the demo on WINDOWS via Cygwin shell, I keep getting the INVALID ARGUMENT error. I had copied all the files that I supplied to the command line options in the build directory for ease of run.

I know have a legit access key that I created months ago, and I make sure I do an **`export ACCESS_KEY=<the access key I got when I signed up for a Picovice account in Nov. 2021.>`**

Please direct me where I can help on this!  Thank you very much!

./porcupine_demo_file.exe -l ./libpv_porcupine.dll -m ./porcupine_params.pv -k ./my_trained_model.ppn -t 0.5 -w ./sample-16bits.wav -a ${ACCESS_KEY}

'pv_porcupine_init' failed with 'INVALID_ARGUMENT'

![image](https://user-images.githubusercontent.com/14103779/164802853-b3e97121-92e4-4fd5-b87c-95429c984c75.png)

**Comment by unebonnevie** [comment]
I have the `status` echoed out.

'pv_porcupine_init' failed with 'INVALID_ARGUMENT' **status=3**

**Comment by kenarsa** [comment]
I think all you need to do is to literally replace `${ACCESS_KEY}` with yours. This is not an environment variable.

**Comment by unebonnevie** [comment]
> I think all you need to do is to literally replace `${ACCESS_KEY}` with yours. This is not an environment variable.

Hi,

Please note that I also set the environment var $ACCESS_KEY.  Also, I did try the literal form that, that is, "-a <the actual key string>", but it still does not work.

The error status returned is 3.  If you could look up the code of pv_porcupine_init(...) and share what exactly the error code is, I would greatly appreciate it.

Thanks.

**Comment by unebonnevie** [comment]
Btw, I decide to try on the Linux platform, using the same trained model that I created 6 months ago, and I get the below.

I can understand that Picovoice wants to encode the platform information into the model for restricted/licensing purposes, but would you want to do that when people, like me, are trying to evaluate Porcupine for possible usage of a product, as in paying for usage?

One of key points in my evaluation is also looking at Picovoice's support of its Porcupine product and other products.

`[ERROR] keyword file has incorrect format or belongs to a different platform
[ERROR] loading keyword file at './hey_davinci_trained_model.ppn' failed with 'INVALID_ARGUMENT'`

On WINDOWS platform, I get the mysterious "INVALID_ARGEMENT" with status = 3 with the below run. 

`./porcupine_demo_file.exe -l ./libpv_porcupine.dll -m ./porcupine_params.pv -k ./my_trained_model.ppn -t 0.5 -w ./sample-16bits.wav -a <my access key string>

'pv_porcupine_init' failed with 'INVALID_ARGUMENT'`

**Comment by unebonnevie** [comment]
Ok, it could be my .ppn model, which was created via picovoice.ai web site 6 months ago, is too old.  I substitute my .ppn file with the alexa_windows.ppn that comes from this github site, and I get the below error.

**'pv_porcupine_init:' failed with 'RUNTIME_ERROR'**

RUNTIME_ERROR is status=7

**Comment by unebonnevie** [comment]
The problem is now resolved!  The .ppn model that I created 6 months ago is NOT compatible with the latest Porcupine V2.1!!!!

I just made a new model for the Linux platform and it works!

Your library is not very user friendly!!!!!  It needs to report the problem specifically if something is wrong!

Picovoice/Porcupine could go far with this software and making $$$$ if you can make your software user friendly AND better support!

**Comment by kenarsa** [comment]
you should have gotten an error log saying that your model is incompatible with the version of the library.

**Comment by unebonnevie** [comment]
@kenarsa I don't see any log.

Btw, when I first tried Porcupine in Nov 2021,it works really well.  Now, V2.1 detects only 4 out of 6 wake words in the 16Khz sample .wav that I've been using.  I've noticed also V2.1 now requires 16-bit PCM; whereas, the Porcupine version in Nov. 2021 works with 32-bit audio samples.
