### ISSUE TITLE
frame length

### ISSUE THREAD

**Issue by oziee** [Picovoice/Porcupine#71]
is the min frame length for porcupine 512??

using Python3.6 for testing

i have an audio file with a frame length of 256.. and when running porcupine.process on this it never picks up the hotword

the audio stream i am using is 

ChunkID= b'RIFF'
TotalSize= 556
DataSize= 512
Format= b'WAVE'
SubChunk1ID= b'fmt '
SubChunk1Size= 16
AudioFormat= 1
NumChannels= 1
SampleRate= 16000
ByteRate= 32000
BlockAlign= 2
BitsPerSample= 16
SubChunk2ID= b'data'
SubChunk2Size= 512

**Comment by kenarsa** [comment]
correct. It accepts 512 samples per frame. You can buffer the audio and pass it to engine every other frame.

**Comment by oziee** [comment]
to make sure im not going mad.. i added pyaudio output 

pa = pyaudio.PyAudio()
stream = pa.open(format=pyaudio.paInt16, channels=1, rate=16000, output=True, frames_per_buffer=512)

and just before the 
result = porcupine.process(pcm)

i added stream.write(pcm)
i can hear the audio just fine.. nice and clear.. but porcupine does not pick up the hotword (yet as i said above, using the same stream and porcupine code and ppn files etc it does work )

**Comment by oziee** [comment]
maybe im not understanding samples or frames correctly

so the stream comes in as a wave file.. so when i look at the wav info i get
`_wave_params(nchannels=1, sampwidth=2, framerate=16000, nframes=256, comptype='NONE', compname='not compressed')`

so i set nFrames = 256

and in code 
b = io.BytesIO(msg.payload)
audio = wave.open(b, 'rb').readframes(nFrames)
result = porcupine.process(audio)

and result never fires the hotword being found

thought maybe the audio code is bad.. so added pyAudio to listen to the stream
pa = pyaudio.PyAudio()
stream = pa.open(format=pyaudio.paInt16, channels=1, rate=16000, output=True, frames_per_buffer=nFrames)

and then the code is
            b = io.BytesIO(msg.payload)
            audio = wave.open(b, 'rb').readframes(nFrames)
            stream.write(audio)
            result = porcupine.process(audio)

the audio playing is crystal clear so its not bad code converting the audio.. and so added the code print(len(audio)) before the stream write.. it outputs to console 512. 512. 512 ....

so then though as you said porcupine like 512.. so i changed the stream to 512.. and ran again
`_wave_params(nchannels=1, sampwidth=2, framerate=16000, nframes=512, comptype='NONE', compname='not compressed')`
and changed nFrames = 512

again the audio playing from pyAudio is crystal clear.. now the console logs 1024. 1024. 1024..
but again porcupine never picks up the hotword

any idea what might be wrong? im not sure if the sample width being 2 and nFrames 512 makes the console len print 1024? but with the stream at 256 or 512.. and the len outputting 512 or 1024 porcupine never fires

**Comment by oziee** [comment]
so i changed using wave to soundfile
replaced the code for opening the wave with
`audio, sample_rate = soundfile.read(b, dtype='int16')`

the len of audio console prints 512.. good :)
porcupine fires on the hotword.. good :)

pyAudio does not sound good at all.. its all choppy
nFrames = 512
pa = pyaudio.PyAudio()
stream = pa.open(format=pyaudio.paInt16, channels=1, rate=16000, output=True, frames_per_buffer=nFrames)
...
stream.write(audio)

sounds choppy.. not clear like it was using the wave lib to open it.. but porcupine works with soundfile whereas it does not with wave.. using the same code

**Comment by kenarsa** [comment]
Could it be an endianness issue?

**Comment by oziee** [comment]
i have removed wave from the imports and just using soundfile now
everything is working well
