### ISSUE TITLE
sensitivity 0.1 - 0.9 seems to have no difference

### ISSUE THREAD

**Issue by oziee** [Picovoice/Porcupine#72]
so i created a ppn file for mac x86_64
"hey janet"

even with the sensitivities set to [0.1] it picks up odd words when i say things like
"hey jant"
"hey jan Bert" (and i really make sure the Bert sound comes out strong)

i even tried setting the sen to [0.00001] and it still fires with odd sounds

i would have thought the sensitivity closer to 1 would false positive lots.. but even 0.001 it false positives with close sounding words.. but "jan BERT" really has a B sound which i would have expected with a low sensitivity to not accept

**Comment by kenarsa** [comment]
Hmmm. That is odd. what is the miss rate roughly?

**Comment by oziee** [comment]
I have not had long enough to test this enough

I was just trying to think of sounds and words that sound like "hey janet" but had other words
"hey jan vant"
"hey jan bert"
"hey john et"
these make it false positive.. and they have very different vowel sounds.. making sure to have the B or V H sounds very pronounced as to not sound like janet

"hey vanet".. things like this do not false positive

I will leave it running in the TV room with the kids to see how often it fires as i know they won't say things like hey janet in there

**Comment by oziee** [comment]
i would say that it falsely fires off 3 times every hour with just background noise and talking.. even with the sensitivity set to 0.1

**Comment by kenarsa** [comment]
Thanks. Did you have a chance to measure the miss rate? I'll take whatever information you can provide and use it to improve the next version.

**Comment by oziee** [comment]
its slow.. its still running.. and i cut it down to only 61000 other files.. but here is it currently testing just for JANET

INFO:loaded background speech dataset with 61444 examples
INFO:loaded keyword dataset with 10 examples
INFO:PocketSphinx (1e-10):
INFO:false alarms per hour: 29.683759 (2306 / 77.685579)
INFO:miss detection rate: 0.000000 (0 / 10)
INFO:[Pocketsphinx][1e-10] took 180.30022630213332 minutes to finish
INFO:Porcupine (0.0):
INFO:false alarms per hour: 0.038617 (3 / 77.685579)
INFO:miss detection rate: 0.100000 (1 / 10)
INFO:[Porcupine][0.0] took 194.5665965698333 minutes to finish
INFO:PocketSphinx (2.1544346900318867e-07):
INFO:false alarms per hour: 14.494325 (1126 / 77.685579)
INFO:miss detection rate: 0.000000 (0 / 10)
INFO:[Pocketsphinx][2.1544346900318867e-07] took 178.7614756802167 minutes to finish
INFO:Porcupine (0.1111111111111111):
INFO:false alarms per hour: 0.064362 (5 / 77.685579)
INFO:miss detection rate: 0.100000 (1 / 10)
INFO:[Porcupine][0.1111111111111111] took 198.77709024325 minutes to finish
INFO:PocketSphinx (0.0004641588833612782):
INFO:false alarms per hour: 7.092693 (551 / 77.685579)
INFO:miss detection rate: 0.000000 (0 / 10)
INFO:[Pocketsphinx][0.0004641588833612782] took 169.37341605933332 minutes to finish

**Comment by oziee** [comment]
testing on just Porcupine and the same 10 example waves i created with the word JANET in it

INFO:loaded keyword dataset with 10 examples
INFO:Porcupine (0.0):
INFO:false alarms per hour: 0.000000 (0 / 0.015278)
INFO:miss detection rate: 0.100000 (1 / 10)
INFO:[Porcupine][0.0] took 0.030388567350000003 minutes to finish
INFO:Porcupine (0.1111111111111111):
INFO:false alarms per hour: 0.000000 (0 / 0.015278)
INFO:miss detection rate: 0.100000 (1 / 10)
INFO:[Porcupine][0.1111111111111111] took 0.0305519017 minutes to finish
INFO:Porcupine (0.2222222222222222):
INFO:false alarms per hour: 0.000000 (0 / 0.015278)
INFO:miss detection rate: 0.100000 (1 / 10)
INFO:[Porcupine][0.2222222222222222] took 0.03067208155 minutes to finish
INFO:Porcupine (0.3333333333333333):
INFO:false alarms per hour: 0.000000 (0 / 0.015278)
INFO:miss detection rate: 0.100000 (1 / 10)
INFO:[Porcupine][0.3333333333333333] took 0.02965097188333332 minutes to finish
INFO:Porcupine (0.4444444444444444):
INFO:false alarms per hour: 0.000000 (0 / 0.015278)
INFO:miss detection rate: 0.100000 (1 / 10)
INFO:[Porcupine][0.4444444444444444] took 0.029683797033333327 minutes to finish
INFO:Porcupine (0.5555555555555556):
INFO:false alarms per hour: 0.000000 (0 / 0.015278)
INFO:miss detection rate: 0.100000 (1 / 10)
INFO:[Porcupine][0.5555555555555556] took 0.02974773215 minutes to finish
INFO:Porcupine (0.6666666666666666):
INFO:false alarms per hour: 0.000000 (0 / 0.015278)
INFO:miss detection rate: 0.100000 (1 / 10)
INFO:[Porcupine][0.6666666666666666] took 0.03171585428333333 minutes to finish
INFO:Porcupine (0.7777777777777777):
INFO:false alarms per hour: 0.000000 (0 / 0.015278)
INFO:miss detection rate: 0.100000 (1 / 10)
INFO:[Porcupine][0.7777777777777777] took 0.03366428501666669 minutes to finish
INFO:Porcupine (0.8888888888888888):
INFO:false alarms per hour: 0.000000 (0 / 0.015278)
INFO:miss detection rate: 0.100000 (1 / 10)
INFO:[Porcupine][0.8888888888888888] took 0.035393756266666694 minutes to finish
INFO:Porcupine (1.0):
INFO:false alarms per hour: 0.000000 (0 / 0.015278)
INFO:miss detection rate: 0.100000 (1 / 10)
INFO:[Porcupine][1.0] took 0.031140240250000003 minutes to finish



sensitivity | false_alarm_per_hour | miss_rate
-- | -- | --
0 | 0 | 0.1
0.11111111 | 0 | 0.1
0.22222222 | 0 | 0.1
0.33333333 | 0 | 0.1
0.44444444 | 0 | 0.1
0.55555556 | 0 | 0.1
0.66666667 | 0 | 0.1
0.77777778 | 0 | 0.1
0.88888889 | 0 | 0.1
1 | 0 | 0.1

**Comment by aqiank** [comment]
I seem to be having the same experience on Linux x86_64 (multiple false alarms with mostly background noise). Let me know if you want the audio data. I can provide them (although I'm not sure how long the audio needs to be before the detection).

**Comment by kenarsa** [comment]
@oziee  this is really good information. I believe I have identified the problem. Let me work on the fix and I will get back to you in a few days time. Thanks!

**Comment by kenarsa** [comment]
@aqiank  could you please just provide the information @oziee  did? I will look into that as well.

**Comment by kenarsa** [comment]
[hey janet_mac.ppn.tar.gz](https://github.com/Picovoice/Porcupine/files/2337616/hey.janet_mac.ppn.tar.gz)

@oziee  can you please try this file with your experiment?

**Comment by oziee** [comment]
i ran the experiment on ubuntu.. i can have a play with it on mac

**Comment by oziee** [comment]
i hacked the wake word benchmark to run on the mac using that file and the same test wave files used to test before under ubuntu
here is the output.. seems to miss 40% even with a sensitivity of 1


sensitivity | false_alarm_per_hour | miss_rate
-- | -- | --
0 | 0 | 0.8
0.11111111 | 0 | 0.7
0.22222222 | 0 | 0.6
0.33333333 | 0 | 0.6
0.44444444 | 0 | 0.6
0.55555556 | 0 | 0.5
0.66666667 | 0 | 0.5
0.77777778 | 0 | 0.4
0.88888889 | 0 | 0.4
1 | 0 | 0.4

**Comment by kenarsa** [comment]
Ok. That makes sense now. What's the sensitivity you are using with the new model?

**Comment by oziee** [comment]
0.5

**Comment by kenarsa** [comment]
OK. Let's reduce the sensitivity. If you have time/interest I suggest reducing by 0.1 iteratively until you get to a point that you are happy with it. Otherwise just try 0!

**Comment by oziee** [comment]
Ok.. good that sensitivity is working now:)

**Comment by oziee** [comment]
my bad.. i just checked.. its set to sensitivities = [0.00001] 
so "jan Bert" etc are still being detected with basically a 0 sensitivity

I tested the same phrases on the snowboy test webpage and they also detected the incorrect sounding words too

I am creating a few different sets of sound samples to test with
Set 1 - all files contain "hey janet" and miss rate from sensitivity 0-1 was 0
Set 2 - 2 files contain "hey janet" 8 contain just "janet".. sensitivity 0 missed 8, sen 1 missed 4

looking good so far.. setting to 0 might be the best place to start :)

**Comment by oziee** [comment]
so i have had it running all day with the tv on in the background... its firing off 4-5 times an hour

the sensitivity is set to 0

**Comment by kenarsa** [comment]
that seems odd as you mentioned that the old model was firing 3 times with a higher sensitivity. In order to help I need to reproduce. I will get back to you in a few days time.

**Comment by oziee** [comment]
i am adding some buffer code to collect the audio when the wake word triggers just to see what its hearing

**Comment by oziee** [comment]
i have been running it for 48hrs now and not one false alarm.. wonder if i restarted it then copied the file instead of copying the file and restarting.. i can bet it was something i did wrong.. but set to 0 its has been working a treat with no problems so far

**Comment by abramovi** [comment]
@oziee regarding your last test - is it with the patched model ? (hey janet_mac.ppn.tar.gz)

**Comment by oziee** [comment]
@abramovi correct the patched model

**Comment by jscottsf** [comment]
We've been having the same issue. Even at 0 sensitivity, we get a fair amount of false triggers when just casually speaking. This is on Linux.

**Comment by kenarsa** [comment]
you need to wait for v1.5 release. If you have a commercial application reach out via email and we can provide you an updated model faster

**Comment by jscottsf** [comment]
> you need to wait for v1.5 release. If you have a commercial application reach out via email and we can provide you an updated model faster

Thank you so much. Sending an email to your sales team now.
