### ISSUE TITLE
Error: Cannot build player while editor is importing assets or compiling scripts

### ISSUE THREAD

**Issue by ykmak001** [Picovoice/porcupine#725]
Error pops when I tried to click on 'Build' button. Googled online and led me to URL below, and it points me to something related to 'Using UnityEditor'.....
https://forum.unity.com/threads/i-cant-build-my-game.803667/

Context to the error....
Besides Porcupine I'm dealing with, I'm integrating SCORM. Integrating SCORM as a standalone, separate from Porcupine doesn't pop the error. But when done together with Porcupine the error below pops.
https://github.com/rstals/Unity-SCORM-Integration-Kit

![image](https://user-images.githubusercontent.com/42117169/170216126-35a195fc-32d9-493b-9b21-2d1c2ca6112c.png)

**Comment by kenarsa** [comment]
are you trying to build for web?

**Comment by ykmak001** [comment]
> are you trying to build for web?

To provide some context. It is SuccessFactor LMS that the developed e-contents will be loaded and the e-contents viewed using mobile (Chrome / Safari) - build for web?

**Comment by kenarsa** [comment]
What I am trying to say is that I don't think Porcupine's Unity binding supports browsers. Check the [doc](https://github.com/Picovoice/porcupine/tree/master/binding/unity#compatibility).

**Comment by ykmak001** [comment]
> What I am trying to say is that I don't think Porcupine's Unity binding supports browsers. Check the [doc](https://github.com/Picovoice/porcupine/tree/master/binding/unity#compatibility).

Sad...shall look at alternatives! TQVM!
