### ISSUE TITLE
Android library does not support native C linking

### ISSUE THREAD

**Issue by pabloxid** [Picovoice/Porcupine#73]
### Expected behavior
Use porcupine in C/C++ Android NDK native program.

### Actual behavior
"undefined reference" to every porcupine function.

### Steps to reproduce the behavior
Write a C program;
include porcupine C headers;
call API C functions;
link against libpv_porcupine.so found in android arm_v7a folder;
build with android NDK v15c.

**Comment by kenarsa** [comment]
That seems to be the expected behavior as shared objects are exporting functions with JNI signature. Does that make sense?

**Comment by kenarsa** [comment]
This is just how Android build system works by default. We didn't get any request for alternatives. What is your use case?

**Comment by pabloxid** [comment]
I'm working on a project in which there is an Android application with a native part in a shared library. It's an embedded system and we need maximum performance. We want to integrate a voice command, but, by the way code is organized, audio and video parts are developed in C/C++. On the other hand, I think that it's more efficient to directly access the C API than to use the JNI interface, in this case.

**Comment by kenarsa** [comment]
OK. Yeah, you might get some extra efficiency there. But it is minimal in this case as processing is done all in C and moving audio data around is fairly lite compared to image/video due to much smaller size.

I made a task to look into if we can expose extra functions in the shared object for v1.5 release. That would be the preferred solution.

In the meantime, the library is accessible from Java through JNI.

**Comment by pabloxid** [comment]
Thank you.

For now, can you send me a compiled version to try? I'll confirm if it works.

**Comment by kenarsa** [comment]
We have a task for it in our queue. I will update you when we start working on it.

**Comment by rtumelty** [comment]
+1 to this request - I have been struggling to get Porcupine working in Unity for Android, as it expects developers to be using Java. Unity uses Mono (C#) or IL2CPP (C++) frameworks, which experience segmentation faults whenever I try to call the init function. It would be much more straightforward to interact directly with the Porcupine library.

**Comment by kenarsa** [comment]
@rtumelty why not build against the shared object for Linux/Mac/Windows?

**Comment by rtumelty** [comment]
I am building for Android devices with ARMv7 and ARM64 architectures. x86/64 libraries won't work for the platform.

**Comment by kenarsa** [comment]
We didn't get to this feature. But we will be working on it. It is being tracked here as well #115. There are few candidate solutions and we are in the decision-making process.

**Comment by pabloxid** [comment]
In fact, I don't understand why this issue occurs and why it's so difficult to fix it out. 

The library is written in C, so the C API functions are there anyway. How is it possible to "hide" them? I include the .h header, so my code just compiles. Then the linker should find the functions there in the library, since the functions are there for sure, aren't they? That's very strange.

What I asked you by mail, since I actually work for a company that has bought or will buy a license, is that, in the meantime, simply take the source code you used for, say, the Linux library, and build it using NDK. I think that would be enough as a temporary solution for us. We don't need the JNI API, if the C API just works.

Thank you.

**Comment by kenarsa** [comment]
The Android binding is designed to be used via a Java interface and using the lib from C is not supported currently. There are use cases that would benefit from using the lib on Android directly from C. This is NOT supported yet. I do appreciate your input. But it is a decision on the Picovoice side if we want to support it when to prioritize it, and how to get it done.

**Comment by kenarsa** [comment]
we decided that we won't offer static libs for android. our offering for Android will be limited to shared objects and JNI interface.
