### ISSUE TITLE
Porcupine Issue: RUNTIME_ERROR

### ISSUE THREAD

**Issue by Pinocolo** [Picovoice/porcupine#730]
I get a RUNTIME_ERROR when I try to create a Poircupine instance using C# for .NET 6.0 under Android (Xamarin).
I can't guess the cause since the error seems to be thrown by the library.
[TestAndroidPorcupine.zip](https://github.com/Picovoice/porcupine/files/8903639/TestAndroidPorcupine.zip)
.

**Comment by kenarsa** [comment]
.NET SDK does not support Xamarin. Check the [doc](https://github.com/Picovoice/porcupine/tree/master/binding/dotnet#compatibility) before opening issues.
