### ISSUE TITLE
How do you make a decision whether one device is authorized

### ISSUE THREAD

**Issue by hrjRai** [Picovoice/porcupine#739]
I would like to ask you some questions.

1.How do you make a decision whether one device is authorized? We found that the license (free edition, for voice wake-up) worked well for a while, but it changed to invalid after the OS (Android) updating/upgrading. We had to apply for a new  license (free edition) to enable the voice wake-up function.

2. Can one device be authorized "permanently"? I mean if we can use some formal license method after buying formal edition, NOT free edition. Of course I know the device should connect to your service once a month.
So in the case we buy the formal edition, will the license be bound to e.g. the MAC address of Android device? Becoz the Android ID may change after updating or upgrading, while MAC address may be a fixed information for license

I'm looking forward to your prompt reply.

**Comment by kenarsa** [comment]
@hrjRai we use GitHub strictly for technical discussions. Please use the [sales form](https://picovoice.ai/contact/) for any commercial inquiries. 

The Android is bound to your application and hence if you install/reinstall it will be counted as a new device. We do not plan to change this behaviour for free or enterprise users.
