### ISSUE TITLE
Python integrate error

### ISSUE THREAD

**Issue by fredrikj31** [Picovoice/Porcupine#74]
I have problem with how to import porcupine to my python script. I had many problems with it, that i said that it could not import the library and so on, but that is fixed.

My code:
import sys
import soundfile
import os
import pyaudio

sys.path.append(r'E:/Desktop/Python/WakeWord/Porcupine/binding/python/')

from porcupine import Porcupine

library_path = 'Porcupine/lib/windows/amd64/libpv_porcupine.dll'
model_file_path = 'Porcupine/lib/common/porcupine_params.pv'
keyword_file_paths = 'Porcupine/resources/keyword_files/alexa_windows.ppn'
sensitivities = [0.5]
handle = Porcupine(library_path, model_file_path, keyword_file_paths=keyword_file_paths, sensitivities=sensitivities)

def get_next_audio_frame():
    pass

while True:
    pcm = get_next_audio_frame()
    keyword_index = handle.process(pcm)
    if keyword_index >= 0:
        # detection event logic/callback
        pass

And my error:
`Traceback (most recent call last):
  File "program.py", line 15, in <module>
    handle = Porcupine(library_path, model_file_path, keyword_file_paths=keyword_file_paths, sensitivities=sensitivities)
  File "E:/Desktop/Python/WakeWord/Porcupine/binding/python\porcupine.py", line 84, in __init__
    raise ValueError("Different number of sensitivity and keyword file path parameters are provided.")
ValueError: Different number of sensitivity and keyword file path parameters are provided.`

**Comment by kenarsa** [comment]
change

keyword_file_paths = 'Porcupine/resources/keyword_files/alexa_windows.ppn'

to

keyword_file_paths = ['Porcupine/resources/keyword_files/alexa_windows.ppn']

**Comment by fredrikj31** [comment]
Ok thanks for the quick reply. I have another error... It says that i have problems importing porcupine... But i have set my dir right up, and and the other error is that it cant run `get_next_audio_frame()` because it says that is is empty. 

I have included my code and the file dir in the image...

![desktop](https://user-images.githubusercontent.com/31306224/44739709-d6f82c80-aaf8-11e8-91a0-46e376e075d9.PNG)

**Comment by kenarsa** [comment]
Hey @fabioknoedtbcgdv 

Happy that the other issue is resolved. Please use the issue template we have for the repository and try to give detailed information and directed requests using the template so we can help out. Closing the issue for now. But if you still have the problem please open another one using the template.
