### ISSUE TITLE
Porcupine Issue: PorcupineBuilder: ai.picovoice.porcupine.PorcupineActivationException: Initialization failed.

### ISSUE THREAD

**Issue by ArezooNazer** [Picovoice/porcupine#745]
I've got this error while the record audio permission is granted and my sample app is set as the default assistant app. 

porcupine-android: 2.1.2
Android versions: 6, 11, 12
Devices: SM-G610F, Xiaomi Poco x3, Pixel 2 (emulator)

[My code](https://github.com/ArezooNazer/VoiceInteractionSample/blob/develop/app/src/main/java/com/arezoonazer/voiceinteractionsample/util/PorcupineHandler.kt):

```
 try {
            porcupineManager = PorcupineManager.Builder()
                .setAccessKey(ACCESS_KEY)
                .setKeywords(
                    arrayOf(
                        Porcupine.BuiltInKeyword.ALEXA,
                        Porcupine.BuiltInKeyword.HEY_GOOGLE
                    )
                )
                .setSensitivities(floatArrayOf(0.7f, 0.7f))
                .build(applicationContext) { keywordIndex: Int ->
                    Log.d(TAG, "onReady: $keywordIndex")
                }

            porcupineManager?.start()
        } catch (e: PorcupineException) {
            Log.e(TAG, e.toString())
        }
        
```
Usage: [MyVoiceInteractionService](https://github.com/ArezooNazer/VoiceInteractionSample/blob/develop/app/src/main/java/com/arezoonazer/voiceinteractionsample/service/MyVoiceInteractionService.kt)
Logcat: 
```
I/PICOVOICE:  [INFO] Porcupine model path : '/data/user/0/com.voiceinteractionsample/files/porcupine_params.pv'
I/PICOVOICE:  [INFO] Porcupine keyword path [0] : '/data/user/0/com.arezoonazer.voiceinteractionsample/files/alexa.ppn'
I/PICOVOICE:  [INFO] Porcupine keyword path [1] : '/data/user/0/com.arezoonazer.voiceinteractionsample/files/hey_google.ppn'
I/PICOVOICE:  [INFO] Porcupine sensitivity [0] : 0.70
I/PICOVOICE:  [INFO] Porcupine sensitivity [1] : 0.70
E/PorcupineBuilder: ai.picovoice.porcupine.PorcupineActivationException: Initialization failed.
```

**Comment by kenarsa** [comment]
Did you enter your `ACCESS_KEY`?

**Comment by ArezooNazer** [comment]
yes, you can see the complete implementation [here](https://github.com/ArezooNazer/VoiceInteractionSample/blob/develop/app/src/main/java/com/arezoonazer/voiceinteractionsample/util/PorcupineHandler.kt)

**Comment by kenarsa** [comment]
Thanks. You might want to keep your AccessKey secret. I would not put it in public code. 

1- Can you run the android demo on the repository successfully?
2- Is the device connected to the internet?

**Comment by ArezooNazer** [comment]
This is a public repository so the AccessKey visibility doesn't matter.
1. Yes the demo app works correctly on the same devices. Also, the 1.9.0 version of the library works correctly.
2. Yes

**Comment by ArezooNazer** [comment]
The problem was solved by adding internet permission.
