### ISSUE TITLE
Porcupine Issue: 

### ISSUE THREAD

**Issue by glcos** [Picovoice/porcupine#753]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour

Italian language wake word working

### Actual behaviour

Italian language wake word raising an error in Python SDK

### Steps to reproduce the behaviour

I'm testing an italian wake word on a fully working system and getting this error:

/porcupine.py", line 158, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()

The same exact installation works fine with a previously generated english language wake word.
SDK updated to the latest version 2.1.4
The same AccessKey works with the english wake word.
Raspberry PI running Raspbian GNU/Linux 11 (bullseye)
armv71

**Comment by laves** [comment]
Great!
