### ISSUE TITLE
Chinese support in free version

### ISSUE THREAD

**Issue by jinlife** [Picovoice/porcupine#755]
We are international company and our biggest markets are English and Chinese regions.
We would like to demo it with 2 different languages in one technique, we would like to evaluate it with free version at first.

Is it possible to support Chinese in free version? We would like to know the performance and accuracy for both the languages.

**Comment by kenarsa** [comment]
Support for Chinese is not publicly available yet. If you want early access have your business person submit a inquiry with details of business opportunity and someone from enterprise team can reach to you: https://picovoice.ai/contact/
