### ISSUE TITLE
Porcupine Issue: Porcupine failed to initialize on raspberry pi 3 with NodeJS

### ISSUE THREAD

**Issue by Nymmh** [Picovoice/porcupine#756]
I was trying to run my own project that works on Windows 11, however, after moving it to my Pi I started getting a Porcupine failed to initialize error. After validating that the access key is correct I tried to run the ppn-mic-demo from the Porcupine NodeJS quickstart and got the same error.

### Expected behaviour
For Porcupine to initialize and allow the test of keywords.

### Actual behavior
Throws Porcupine failed to initialize the error.

### Steps to reproduce the behavior
It can be reproduced by following the same quickstart guide in the SDK.
npm install -g @picovoice/porcupine-node-demo
ppn-mic-demo --access_key KEY --keywords porcupine

**Comment by kenarsa** [comment]
paste the full error log, please. I can't help you without it...

**Comment by Nymmh** [comment]
Is there a directory where it will dump the full error log? The image is all it gives me in the terminal.
![h54an9u9](https://user-images.githubusercontent.com/19233434/183533220-562f889b-cd2f-456b-ae9f-e1dda376c39c.png)

**Comment by kenarsa** [comment]
that's odd and prob means that something basic is not working. What's your RPI model? Can you put a try/catch around [this](https://github.com/Picovoice/porcupine/blob/master/demo/nodejs/mic.js#L143-L149) and log the type of exception?

**Comment by Nymmh** [comment]
The model is Pi 3 Model B Rev 1.2.
![8xsq6gbz](https://user-images.githubusercontent.com/19233434/183534826-8aecbd54-6c2b-4c8f-a2e4-ab8d13add78b.png)

**Comment by kenarsa** [comment]
what's the node version you are using? I just tried on RPI3 with node 12 and 16 and both worked

**Comment by Nymmh** [comment]
I'm using 18.7

**Comment by kenarsa** [comment]
I tried that and that worked as well

**Comment by Nymmh** [comment]
Are there any other troubleshooting steps I could do?

**Comment by kenarsa** [comment]
can you try to use the LTS version? you can also try to reinstall the package or use a different SD card if you have any

**Comment by Nymmh** [comment]
I changed to the LTS version, I don't have another SD card, however, I tried to uninstall and reinstall the package and I'm getting the same initialize error.

**Comment by kenarsa** [comment]
What's the OS you are using?

**Comment by Nymmh** [comment]
Raspbian 11

**Comment by kenarsa** [comment]
I did try to reproduce on that OS as well and I didn't manage to. I am closing the issue.
