### ISSUE TITLE
Help: Multiple keywords using porcupine C sdk.

### ISSUE THREAD

**Issue by Koujin22** [Picovoice/porcupine#759]
Hi, so I'm trying to reproduce a python program using C++. I've managed to set up all the dll, lib and linking and have a working demo. 

(Working demo snippet)
``` 
const char* keyword_file_path = "C:/../../../smth.ppn";
const float sensitivity = 0.5f;

const pv_status_t status = pv_porcupine_init(
        ACCESS_KEY,
        model_file_path,
        1,
        &keyword_file_path,
        &sensitivity,
        &porcupine);
```

The issue I'm encountering is when I try to apply multiple keywords. In python you can just pass a list of paths. In here I've tried that, but it only takes the first keyword. Ignoring the other 2.  

```
const char* const keyword_file_path[3] = {
        "C:/../../../smth1.ppn",
        "C:/../../../smth2.ppn",
        "C:/../../../smth3.ppn"};
const float sensitivity[3] = { 0.5f, 0.5f, 0.5f };

const pv_status_t status = pv_porcupine_init(
        ACCESS_KEY,
        model_file_path,
        1,
        keyword_file_path,
        sensitivity,
        &porcupine);
```

In your doc (see: https://picovoice.ai/docs/api/porcupine-c/#pv_porcupine_init) it says plural paths. But i cannot figure out how to do that. I've also tried one single string containing all 3 paths, separated by space, coma, semicolon, and quotes to define each path. And all these times it throws an IOError. 

Can someone help me figure out how to achive this?

**Comment by laves** [comment]
@Koujin22 - in your second snippet it looks like you're setting the `numKeywords` to `1`. If you set that to the length of your `keyword_file_path` array or just to `3`, it should pick up all three of your keywords.

**Comment by Koujin22** [comment]
omg. LOL thank you very much. I saw a hard-coded 1 and forgot to check it. <3
