### ISSUE TITLE
Install Picovoice on Asus Tinker Board

### ISSUE THREAD

**Issue by MarianaTS** [Picovoice/Porcupine#76]
We want to install Picovoice service in Asus Tinker Board (https://en.wikipedia.org/wiki/Asus_Tinker_Board)
We have arm71 machine. 
But we've got an axception  "Cannot autodetect the binary type. Please enter the path to the shared object using --library_path command line argument."
What library do we need ?
Can we run Picovoice service on this board at all ?

Thanks

**Comment by kenarsa** [comment]
this is a copy paste from Readme here https://github.com/Picovoice/Porcupine/blob/master/demo/python/README.md

Why am I getting "Exception: cannot autodetect the binary type ..."?

The demo application cannot auto-detect the CPU type on all variants of Raspberry Pi. Hence you need to provide the path to correct library file manually using --library_path command line argument. Please refer to README.md.

BTW, we are not supporting your specific ARM cortex. But you can probably use the RPi2 binary without a problem.

**Comment by MarianaTS** [comment]
Thanks!
Also there are other problem
I got other error. Do I need other keyword for this lib (arm11)?
When I was using armlinux or just linux keyword I got an error
![screenshot from 2018-09-05 10-51-51](https://user-images.githubusercontent.com/14802962/45099424-e518ff00-b12f-11e8-9229-e7b6152795ac.png)

**Comment by kenarsa** [comment]
You are using a raspberry-pi build and hence need to use a raspberry-pi keyword file such as americano_raspberrypi.ppn
