### ISSUE TITLE
Convert .ppn to older version

### ISSUE THREAD

**Issue by chaffinched** [Picovoice/porcupine#762]
Is there a tool to convert .ppn files created on https://console.picovoice.ai/ppn to files that will work on previous versions of Porcupine?

The file created by the console works fine online, but I'm stuck with version 1.9.x on Rhasspy, on HomeAssistant Supervisor on a Raspberry Pi. The file is detected as expected, but the wake word never triggers.

**Comment by kenarsa** [comment]
No, `PPN` files are NOT backward compatible

**Comment by chaffinched** [comment]
That's why I was asking for a converter... 

...never mind.

**Comment by F1st3K** [comment]
May be.
