### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/porcupine-android/)

### ISSUE THREAD

**Issue by jeannekamikaze** [Picovoice/porcupine#765]
### What is the URL of the doc?

https://picovoice.ai/docs/quick-start/porcupine-android/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

Why does using a wake word with Porcupine require an access key? PicoVoice presumably allows the voice recognition to work offline, is this page missing a documented example for that use case?

**Comment by kenarsa** [comment]
You need AccessKey for authentication and authorization. i.e. AccesKey assures your usage is within your [tier](https://picovoice.ai/pricing/).

**Comment by jeannekamikaze** [comment]
Sorry, I don't understand. The [main page](https://picovoice.ai/docs/) says:

```
Private & Secure: Voice recognition is entirely offline. Intrinsically private; HIPAA and GDPR compliant.
```

Is it just Rhino that is offline, but not Porcupine?

**Comment by kenarsa** [comment]
voice recognition is offline but the software call serves to make sure your usage is within limits. It applies to ALL engines.

**Comment by jeannekamikaze** [comment]
Ok, thank you for your fast response at least, this has been a waste of time. You also claim:

```
Avoid hefty API-based pricing, limitations, and control imposed by big tech.
```

Trading one master for another.
