### ISSUE TITLE
FileNotFoundException Android documentation

### ISSUE THREAD

**Issue by JulienLecoq** [Picovoice/porcupine#767]
### What is the URL of the doc?
https://picovoice.ai/docs/api/porcupine-android/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
I don't understand where Porcupine is looking for the keywordPaths from the method on Porcupine.Builder.setKeywordPaths(). I have tried many paths but none is successful. I always get FileNotFoundException. The last one I tried is : "/app/src/main/res/raw/fr_translation.ppn". The doc claims that it is looking from the absolute path. Isn't /app/src/main/res/raw/fr_translation.ppn the absolute path according to an Android folder?

**Comment by mrrostam** [comment]
You need to provide an **on the device** absolute path; the one you tried is the path within the package, which is different.

A quick way around it would be copying the keyword model to the asset folder and follow the steps for the [Custom Wake Word Integration](https://github.com/Picovoice/porcupine/tree/master/binding/android#custom_wake_word_integration). If you really want to put your files somewhere else, you can refer to the [extractResource](https://github.com/Picovoice/porcupine/blob/efdfe1338fe9f6670c6d3e8e316a9e8e7174ed79/binding/android/Porcupine/porcupine/src/main/java/ai/picovoice/porcupine/Porcupine.java#L235) function inside the binding.

**Comment by JulienLecoq** [comment]
Oh cool, that's exactly what I needed. I put file inside the assets directory, it works now :)
