### ISSUE TITLE
Missing file in repository and subscribe function issue

### ISSUE THREAD

**Issue by bert003** [Picovoice/porcupine#769]
In this repository file: `https://github.com/Picovoice/porcupine/blob/master/demo/web/index.html`, there is a link to a file named _porcupine_params.js_.

However the file does not exist here: `https://github.com/Picovoice/porcupine/tree/master/demo/web` and therefore when I try to implement it, it gives an error that modelParams is not defined.

Can you kindly provide the file _porcupine_params.js_?

**Comment by mrrostam** [comment]
As mentioned in the demo's readme, you need to run `yarn` first. It converts [porcupine_params.pv](https://github.com/Picovoice/porcupine/blob/master/lib/common/porcupine_params.pv) to `porcupine_params.js` for you and put it inside the demo folder.

**Comment by bert003** [comment]
Thanks for your reply. Can you kindly explain to me what is the use exactly of `porcupine_params.js`?

I would like to use a custom wake word "Hi Computer" and not the word "Porcupine" as specified in the demo. I already have my access key, the ppn file and the base64 string.

Can you kindly help as to how I should configure the `PorcupineWeb.Porcupine.create` parameters?

Thanks in advance.

**Comment by mrrostam** [comment]
In addition to keyword files (`.ppn`), Porcupine engine needs a [parameter model](https://github.com/Picovoice/porcupine/tree/master/lib/common] (`.pv`). This parameter model enables Porcupine to understand different languages and can't be skipped.

In the demo, it's already shown how to use custom wake words in both `.ppn` format (`porcupine` wake word in the demo) and `base64` one (`papaya whip`). So you only need to creat a keyword object, similar to `Papaya whip`'s), and it should work. 

For more detailed information about the web SDK, please refer to [the binding README](https://github.com/Picovoice/porcupine/tree/master/binding/web) or [the doc section on Picovoice's website](https://picovoice.ai/docs/quick-start/porcupine-web)

**Comment by bert003** [comment]
Thanks for your feedback. Now I managed to make it work BUT when it comes to:
```
window.webVp = await WebVoiceProcessor.WebVoiceProcessor.instance();
window.webVp.subscribe(porcupine);
window.webVp.start()

```
it outputs an error: `TypeError: window.webVp.subscribe is not a function`

Kindly advise.

**Comment by mrrostam** [comment]
What if you try the demo in an incognito window? do you still get that error?

**Comment by mrrostam** [comment]
That's expected as no audio frame is sent to the engine anymore.

The demo just got updated to work with new version of web-voice-processer. Hopefully that solves the issue you're facing, can you try the new demo as well and see if it gives you any errors?

**Comment by bert003** [comment]
Hi, now everything works flawlessly. Thanks for your support on this. I appreciate.

The only issue I have (which is separate from the main issue of this thread) is that I only used porcupine on my laptop (Google Chrome and Firefox) and loaded the same page on my mobile. Now on my mobile I am getting an error: `Device Activation Limit Reached`. I checked online and I have marked 3 of 3 devices when I only used 2 devices.

Can you kindly explain please? Can I remove a device from the console which I will not be using Porcupine on for sure? And does the keyword expire after 30 days?

**Comment by mrrostam** [comment]
Glad to be of help.

For manually stopping wake word detection, you need to `unsubscribe` the engine from wvp; the control process is explained thoroughly in the [web-voice-processor](https://github.com/Picovoice/web-voice-processor) repo.

Regarding the activation limit, as long as you are in dev mode and running your website from localhost, each browser should be counted as only one device. There is no way to delete/reset it, but the number of active-devices is reset after 30 days.

Since the main issue for this thread is resolved, I will close it. Feel free to open a new one if you face any other problems.
