### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by PhDacountBassel** [Picovoice/Porcupine#77]
Hey there!

"Support for various ARM Cortex-A/M processors and a growing number of DSPs is available."

I was wondering if can I get support for ARM, because I am developing a prototype as part of my PhD study, and I need trigger to work using a cheap microcontroller?
thanks in advance!

**Comment by kenarsa** [comment]
You may use the RPi binaries or the one for ARM Cortex-A9. Have a look here: https://github.com/Picovoice/Porcupine/tree/master/lib

**Comment by kenarsa** [comment]
Now, this is supported. Check out the readme for more info!
