### ISSUE TITLE
UnsatisfiedLinkError when calling ai.picovoice.porcupine.Porcupine.init

### ISSUE THREAD

**Issue by Olical** [Picovoice/Porcupine#78]
### Expected behavior

For the class to instantiate through Java JNI (via Clojure on 64 bit Linux).

### Actual behavior

An error is thrown on the call to the native `init` method.

```
user=> (Porcupine. "wake-word-engine/Porcupine/lib/common/porcupine_params.pv" "wake-word-engine/hey snowball_linux.ppm" 0.5)
UnsatisfiedLinkError ai.picovoice.porcupine.Porcupine.init(Ljava/lang/String;[Ljava/lang/String;[F)J  ai.picovoice.porcupine.Porcupine.init (Porcupine.java:-2)
```

### Steps to reproduce the behavior

You could run `make` in my [Clojure project](https://github.com/Olical/snowball/tree/0557572e3c609236b8fbc57ffa17c87ab49c8f5c) although I doubt that will be needed. I think either the header files / `.so` are slightly out of sync or it's to do with the JVM I'm running it on. I'm trying to use this on my laptop, not an Android device. Here's my `java -version` output:

```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

So I think this will either be very quickly closed with "you're using the wrong thing" or something is behaving weirdly and out of sync. I'm sorry if this isn't enough info just yet, happy to provide more soon! I just can't work this out and I feel like it's a deeper problem.

**Comment by kenarsa** [comment]
I think the correct approach would be to use ".a" library files for x86 and your OS. Then create a JNI interface for it and create a ".so". The reason is that the ".so" files for Android rely on Android runtime libraries which is not available on your laptop. If you decide to go down this path feel free to submit a pull request and add it to the repo.

**Comment by Olical** [comment]
Ah I see, thanks a lot, sorry for opening an issue for this. I probably should've asked elsewhere, I just wasn't sure if it was an "issue" or a problem on my part.

I'll take a look at compiling my own and submit a PR if I get something presentable. I'll mention this issue in any PR for future internet people.

**Comment by Olical** [comment]
What I find odd is that I'm loading the `.so` from https://github.com/Picovoice/Porcupine/tree/master/lib/linux/x86_64 - should that not be compatible? Or do I need to create my own JNI header file / Java class and compile it for my system?

Maybe I've got the wrong idea about that existing `.so` I was trying to use. I suppose I am trying to use the Android example file, I just hoped that class would work, probably naively.

**Comment by Olical** [comment]
So I'm definitely loading the Linux 64 shared object on the correct system. The entire library loads, the failure is on the call to init but it doesn't give me any more information than that. Maybe the JNI interface is out of sync with the current C code? (wild guess though...)

**Comment by Olical** [comment]
So I'm even compiling my own `.so` using the Linux `.a` and Android Java binding source now (using my [Makefile](https://github.com/Olical/snowball/blob/9891c7e82772f68316be8ac1f1a9337c26d36ec9/Makefile)). I still get the same exception:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: snowball.Porcupine.init(Ljava/lang/String;[Ljava/lang/String;[F)J
	at snowball.Porcupine.init(Native Method)
	at snowball.Porcupine.<init>(Porcupine.java:49)
```

:thinking: maybe this `.a` is out of date or something?

**Comment by Olical** [comment]
Ah! `error: symbol lookup error: undefined symbol: Java_snowball_Porcupine_init` - so i think this is just me being dumb and new to the whole JNI thing. But I think I need to write a C file that implements the functions in this generated header file that calls through to the plain old C tooling. I thought I could just link in the existing `.a` and my generated header :grimacing:

I now realise that was pretty naive of me. Hopefully this work yields you a `.so` others can use for their desktop Java applications.

**Comment by Olical** [comment]
I'm so sorry for the spam, please ignore. I'm making progress now and will hopefully be able to submit a PR with full Java / Clojure support in the not _too_ distant future. If I get all of this working I'll happily write a post up on it too, so far this tool looks amazing, thank you for all of your hard work on it!

**Comment by kenarsa** [comment]
@Olical happy that you are making progress. If you can do a PR and share your learnings it would be great. Community will greatly appreciate it :-)

**Comment by Olical** [comment]
Will hopefully provide you with Java (and by extension Clojure) bindings in the not too distant future, I'll hack out an MVP version in my project first. What would be _super_ useful would be the C source for the Android binding `.so` file. If such a file exists and doesn't contain anything proprietary, that is.

I'm happily implementing my own, it's just that I'm not a C aficionado so I worry my C will be a little bit... bad. I suppose any issues could be addressed in a future PR too though.

**Comment by kenarsa** [comment]
Our current JNI implementation has some Android-specific dependencies and also some proprietary stuff. Both can be removed and put somewhere else to make JNI reusable. I will create a task for it. But will take a while. If you decide to take a lead on this I'll be happy to do code reviews. C is easy. I am sure we come through!

**Comment by Olical** [comment]
Ah, don't worry about it then, I'll get my implementation going then you can review it when it's PR worthy. If you do get the C cleaned up and posted somewhere though I'll be happy to grab and use it. I'll carry on with my own hacking about though :smile: thanks!

**Comment by sarthak-m** [comment]
was there ever a PR made for the above conversation? I am facing the same error mentioned in the title. I am completely new to JNI and don't know what I need to do to fix this.

**Comment by Olical** [comment]
Afraid not, no, but you might be able to find the code you need in my project: https://github.com/Olical/snowball/blob/master/src/java/snowball/porcupine/Porcupine.java

I've got a few scripts in there to compile the required classes, I won't be able to walk you through it but I hope it's easy enough to follow!
