### ISSUE TITLE
Porcupine Issue: Porcupine throws runtime error on running

### ISSUE THREAD

**Issue by nalistic** [Picovoice/porcupine#782]
Try running Unity sdk demo using custom Keyword. When running the demo code (updated to accept my custom keyword) it returns the error "Make sure your access key 'vzhanAD[*******]pnYziQ==' is a valid access key". Tested in both porcupine 2.1.3 and 2.0.2 version. Tested on Windows (Editor) and Android 8.0.0. I am using a 2.1.0 custom keyword version but I can only locate 2.1.3 package [In Github](https://github.com/Picovoice/porcupine/tree/master/binding/unity). When using Built in keywords, code runs successfully.

### Expected behaviour

Run without errors

### Actual behaviour

`"Make sure your access key 'vzhanAD[*******]pnYziQ==' is a valid access key"`

### Steps to reproduce the behaviour

Create (SPANISH) custom keyword, download and place it in Streaming Assets folder.

Update PorcupuineDemo.cs code to

`            
PorcupineManager porcupineManager = PorcupineManager.FromKeywordPaths(
           "${vzhanAD[************]nYziQ==}",
           new List<string> { Application.streamingAssetsPath + "/[CUSTOM_WORD]_es_android_v2_1_0.ppn" },
           OnWakeWordDetected,
           modelPath: Application.streamingAssetsPath + "/porcupine_params_es.pv");
`

(Include enough details so that the issue can be reproduced independently.)

Unity Version: 2019.4.27.f1
Porcupine Package Version: 2.1.3
Porcupine Language: Es (Spanish)
SO Develop: Windows 10
SO Tested: Windows 10, Android 8

**Comment by kenarsa** [comment]
remove `${}` around your `AccessKey`

**Comment by ErisMik** [comment]
We place that message `Make sure your access key ...` as a hint since the most common mistake users make when trying the demo is not putting in an `AccessKey`. But it will show up for any case of `InvalidArgument`, any of the arguments provided to Porcupine may be incorrect.

If the `${}` around your `AccessKey`. Please double check your paths to all the files.  Are you testing the demo on Windows or on an Emulator / Android device?

**Comment by nalistic** [comment]
Hello ErisMik, as kenarsa pointed out, when copying the AccessKey I ended up moving the "". from $"AccessKey" to "$AcessKey". Updated the code and now is fully working on Android devices.
