### ISSUE TITLE
Porcupine Issue:porcupine_respeaker_demo --access_key  Traceback (most recent call last):   File "/usr/local/bin/porcupine_respeaker_demo", line 8, in <module>     sys.exit(main())   File "/usr/local/lib/python3.9/dist-packages/ppnrespeakerdemo/porcupine_demo.py", line 105, in main     o.run()   File "/usr/local/lib/python3.9/dist-packages/ppnrespeakerdemo/porcupine_demo.py", line 70, in run     recorder = PvRecorder(device_index=self._device_index, frame_length=self._porcupine.frame_length)   File "/home/pi/.local/lib/python3.9/site-packages/pvrecorder/pvrecorder.py", line 81, in __init__     raise self._PVRECORDER_STATUS_TO_EXCEPTION[status]("Failed to initialize pv_recorder.") ValueError: Failed to initialize pv_recorder

### ISSUE THREAD

**Issue by techstud1** [Picovoice/porcupine#787]
I am getting this error while running 

porcupine_respeaker_demo --access_key 
Traceback (most recent call last):
  File "/usr/local/bin/porcupine_respeaker_demo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/ppnrespeakerdemo/porcupine_demo.py", line 105, in main
    o.run()
  File "/usr/local/lib/python3.9/dist-packages/ppnrespeakerdemo/porcupine_demo.py", line 70, in run
    recorder = PvRecorder(device_index=self._device_index, frame_length=self._porcupine.frame_length)
  File "/home/pi/.local/lib/python3.9/site-packages/pvrecorder/pvrecorder.py", line 81, in __init__
    raise self._PVRECORDER_STATUS_TO_EXCEPTION[status]("Failed to initialize pv_recorder.")
ValueError: Failed to initialize pv_recorder

**Comment by kenarsa** [comment]
things you did wrong:

1- included your `AccessKey` which you should have kept private
2- Using a backtrace instead of an informative issue title 
3- not providing enough information to be helpful.

if you can't respect maintainers' time, we have zero obligation to help out. closing ...
