### ISSUE TITLE
version `GLIBC_2.29' not found error on Debian 10

### ISSUE THREAD

**Issue by RafigRzayev** [Picovoice/porcupine#788]
We are using Rock Pi 4B in conjunction with Debian OS. 

When running porcupine, we get following error:

> version `GLIBC_2.29' not found 

Full error message:

> Traceback (most recent call last):
>   File "KWD/alexa_picovoice_[trigger.py](https://trigger.py/)", line 21, in <module>
>     from pvrecorder import PvRecorder
>   File "/home/rock/.local/lib/python3.7/site-packages/pvrecorder/__init__.py", line 12, in <module>
>     from .pvrecorder import PvRecorder
>   File "/home/rock/.local/lib/python3.7/site-packages/pvrecorder/[pvrecorder.py](https://pvrecorder.py/)", line 20, in <module>
>     class PvRecorder(object):
>   File "/home/rock/.local/lib/python3.7/site-packages/pvrecorder/[pvrecorder.py](https://pvrecorder.py/)", line 203, in PvRecorder
>     _LIBRARY = cdll.LoadLibrary(_lib_path.__func__())
>   File "/usr/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
>     return self._dlltype(name)
>   File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in init
>     self._handle = _dlopen(self._name, mode)
> OSError: /lib/aarch64-linux-gnu/[libm.so](https://libm.so/).6: version `GLIBC_2.29' not found (required by /home/rock/.local/lib/python3.7/site-packages/pvrecorder/lib/raspberry-pi/cortex-a53-aarch64/libpv_[recorder.so](https://recorder.so/))

When typing `ldd --version`
Output is: 

> ldd (Debian GLIBC 2.28-10+deb10u1) 2.28

Kernel and Debian version info:

> 5.10.131-2-rockchip-g8802564cbf09

> Distributor ID: Debian
> Description: Debian GNU/Linux 10 (buster)
> Release: 10
> Codename: buster

Do you have any recommendations how to fix it? 

Previously we were using Armbian OS, it was working ok there (I believe linux version was 4.4).

**Comment by kenarsa** [comment]
@RafigRzayev This is not an officially supported platform. Check [here](https://github.com/Picovoice/porcupine#porcupine). Can you reproduce on RPI, Jetson, or BeagleBone?
