### ISSUE TITLE
open-sourced

### ISSUE THREAD

**Issue by TKNgu** [Picovoice/Porcupine#79]
### Expected behavior
Doc for build wake-word engine for my cat.
### Actual behavior
Can't find paper or doc for it.

Hi Kenarsa I want build a wake-word engine for my cat (wake-word : meow or somthing else) but I can't find paper, doc or source code pv_porcupine. Can you share some public paper or document for build it ?

Sorry for my English.

**Comment by kenarsa** [comment]
Thanks for reaching out. The algorithms in pv_porcupine our proprietary and not published publicly.
