### ISSUE TITLE
Porcupine Issue: Porcupine Activation Error

### ISSUE THREAD

**Issue by ee21m578** [Picovoice/porcupine#794]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.
When running the create command for porcupine, I get the below error:
porcupine = pvporcupine.create(access_key='u.....................=',keywords=['picovoice', 'bumblebee'])

Traceback (most recent call last):
File "<pyshell#2>", line 1, in
porcupine = pvporcupine.create(access_key='..............',keywords=['picovoice', 'bumblebee'])
File "C:\Users\akelkart\AppData\Local\Programs\Python\Python38\lib\site-packages\pvporcupine_init_.py", line 77, in create
return Porcupine(
File "C:\Users\akelkart\AppData\Local\Programs\Python\Python38\lib\site-packages\pvporcupine\porcupine.py", line 158, in init
raise self._PICOVOICE_STATUS_TO_EXCEPTION[status](https://github.com/Picovoice/porcupine/issues/792)
pvporcupine.porcupine.PorcupineActivationError
Capture
### Expected behaviour
Activates the porcupine

### Actual behaviour
Activation error

### Steps to reproduce the behaviour
Install version, run in cmd prompt. I guess the above command I have used is not specific to any device and is generic
![image](https://user-images.githubusercontent.com/113116843/193436097-c4c1813b-8338-4bfb-852f-71e50b8546e5.png)

Version: pvporcupine in ......\site-packages (2.1.4)
Python version: 3.8.3

The issue is with pvcobra as well. There might be something I am missing

**Comment by kenarsa** [comment]
@ee21m578 closing this and re-opening the existing issue. please re-open rather than opening new ones so the context is not lost. when assigning tags be data-driven. how do you know this is a bug and not a problem on your system? `question` or `help wanted` or more proper
