### ISSUE TITLE
Init-Picovoice without Internet

### ISSUE THREAD

**Issue by bmt1596** [Picovoice/porcupine#798]
Hello everyone and Picovoice developers. Currently I am testing an embedded device running an application compiled from C/C++ and using the free version of Picovoice. I noticed that the device must always be connected to the Internet for Picovoice to be able to initialize successfully. Is there any other way to make our device work Offline with Picovoice? That is, without Internet, Picovoice can still successfully initialize?

**Comment by kenarsa** [comment]
@bmt1596 you don't need constant connevtivity. You only need connectivity for the initial `init` and then it can work 100% offline for days. You do need connectivity every couple of weeks though. Connectivity is needed for license management.

**Comment by douglasg14b** [comment]
So, this is cloud connected, online-only, software advertised as `on device`?

Big oof.
