### ISSUE TITLE
[ERROR] wake phrase is too short or long.

### ISSUE THREAD

**Issue by pauldelmusica** [Picovoice/Porcupine#80]
I need to create a set of hotwords for my program. I tried "stop" using the optimizer

The command line is:
C:\Porcupine-master\tools\optimizer\windows\i686\pv_porcupine_optimizer -r resources/ -w stop -p windows -o . 
I got an error:
[ERROR] wake phrase is too short or long.

I then gave it a long word, tensorflow:
C:\Porcupine-master>C:\Porcupine-master\tools\optimizer\windows\i686\pv_porcupin
e_optimizer -r resources/ -w tensorflow -p windows -o .
[ERROR] could not find the pronunciation for 'tensorflow'

Is it possible for users to create his own hotword set?

**Comment by kenarsa** [comment]
It is possible. The explanation for both issues you mentioned is in the FAQ of the tool [here](https://github.com/Picovoice/Porcupine/tree/master/tools/optimizer).

For the first one, you should use something longer such as "stop it" or whatever is appropriate for your use-case. For the second issue, the tool does not know the pronunciation for tensorflow. If you want it added open a separate issue USING THE TEMPLATE PROVIDED and we'll add it to the next release.
