### ISSUE TITLE
Porcupine Issue: AccessKey Activation error

### ISSUE THREAD

**Issue by Kiru3014** [Picovoice/porcupine#800]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Application need to run properly

### Actual behaviour
getting foloowing error 
![image](https://user-images.githubusercontent.com/36956488/196872082-e5729ce0-d15b-4165-95d9-b8e4fe877b3a.png)

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

define access key also in string
    private final String ACCESS_KEY = "zuB14JVFg6HFtKbjXsopUJ0h5GRPXhxoJspo9EABovUyrjwN8oT9qQ=="; // AccessKey obtained from Picovoice Console (https://picovoice.ai/console/)

**Comment by Kiru3014** [comment]
When i turn on mobile internet it worked I need to know how it will work off line with out internet

**Comment by kenarsa** [comment]
your `AccessKey` is supposed to be private but now everyone can see it here. Not OK! You need an internet connection every few days for authentication and authorization.
