### ISSUE TITLE
Porcupine Issue: v2.1.5 on Windows/.NET

### ISSUE THREAD

**Issue by jwoodwardtfx** [Picovoice/porcupine#802]
When running on Windows (.NET), if Porcupine is used in the context of a normal app (for example, Windows Forms or WPF) then the call to Porcupine.FromKeywordPaths() causes a black console window to open for a short period. This happens each time the application is opened and isn't good for user experience.

This does not happen when running as a console application.

I assume this is related to the license check. Please, could this window be hidden or the code reworked so it isn't needed?

This can be demonstrated by taking the code from the .NET/C# example MicDemo and changing it to a Windows Form or WPF based application.

Thanks.

**Comment by laves** [comment]
@jwoodwardtfx - thanks for the report. We've reproduced it and are looking into a fix. We'll update you in the coming weeks when it has been addressed.

**Comment by laves** [comment]
@jwoodwardtfx - this should be resolved in the latest release on NuGet, Porcupine v2.1.6. Can you confirm?

**Comment by laves** [comment]
Great!
