### ISSUE TITLE
Do we need internet connectivity always to verify the access key?

### ISSUE THREAD

**Issue by ee21m578** [Picovoice/porcupine#804]
Even if the processing is offline for porcupine, it requires an access key to create an instance. 
So, ideally, does this mean we need some sort of connectivity always? Or, can we just create an instance once and run the other part of offline processing algo (detection) completely and truly offline?
Working on Windows system and RaspberryPi.

**Comment by jackloomen** [comment]
What about devices which remain offline for weeks or months? Will they just suddenly stop working?

**Comment by ee21m578** [comment]
Yes,  according to the communication

**Comment by NathanSweet** [comment]
Given this, calling it "offline" is disingenuous. I can't be sure of online connectivity and I can't have it cease to function, so I'll have to look for another solution.

**Comment by Nojahhh** [comment]
It's a shame that communication has to be done every few days. Doesn't seem logical to have it set up that way since it's a software for a specific type of application which not always imply that there is a network connection. It should be enough with one -time verification only!
