### ISSUE TITLE
How can I view the words that have been trained by Porcupine and download？

### ISSUE THREAD

**Issue by mrhanCH** [Picovoice/porcupine#807]
The new console version has no word list。
![image](https://user-images.githubusercontent.com/16829340/202079142-eac8d034-dc1e-4af7-aee0-d397c283357c.png)

**Comment by kenarsa** [comment]
@mrhanCH the new design does not store already downloaded models. You need to store them yourself.

**Comment by mrhanCH** [comment]
OK,Thanks
