### ISSUE TITLE
How to generate wakeword for raspberry pi 4 cortex a53 ?

### ISSUE THREAD

**Issue by Devanshi1510** [Picovoice/Porcupine#81]
I want to generate the keyword 'adbot' for rasberry pi 3 cortex a53. I could not find pv_optimizer tool for raspberry pi platform.

**Comment by PhDacountBassel** [comment]
I have the same issue with orangepi!

**Comment by kenarsa** [comment]
The first FAQ in the README of optimizer tool mentions the explanation for this:

https://github.com/Picovoice/Porcupine/tree/master/tools/optimizer
