### ISSUE TITLE
Porcupine Issue: 

### ISSUE THREAD

**Issue by MatsGej** [Picovoice/porcupine#845]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
The wake word functionality is not working

### Actual behaviour
Does not respond to wake word

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)
It is an access key problem. But we cannot understand why it is happening. When looking at the console the acccess key statistics shows that we have three Monthly Active Users (3/3).  It worked in the VScode development environment, but not when deploying it to one ios app and one andoid app, that are only used by one person on his ios and android devices. 

How is usage detected so this can be avoided?

Thanks

**Comment by ksyeo1010** [comment]
What do you mean by running in VScode development environment? If you meant running in a simulator, then it is the expected behavior as you are using 3 devices.

**Comment by MatsGej** [comment]
But to test the functionality in both ios and android I get a problem. When using Testsuite to test it at ios, the apple team is most likely using at least one license and then I run out of licenses very quickly. Right now I cannot test it at android or ios due to this. Has to wait until next month. And then when errors occur, I will have to wait another month again. Is there a way around this problem without paying for the full license?

**Comment by kenarsa** [comment]
@MatsGej you can test on iOS and Android simulators as much as you need and it will only use 2 licences. This will keep you unblocked without needing to purchase a license. If you have gone above 2, you have deployed to something else.

**Comment by MatsGej** [comment]
What exactly does the monthly active users mean? Does it break on month, i.e. at the end of each month I would have three possibilities again, or does it break after a months usage? Or something else?
