### ISSUE TITLE
Dart usage/demo

### ISSUE THREAD

**Issue by jaumard** [Picovoice/porcupine#846]
**Is your feature request related to a problem? Please describe.**
I plan to make my backend in Dart and want to use porcupine as wake word. 

**Describe the solution you'd like**
Have Dart package that can be used to have porcupine working

**Describe alternatives you've considered**
Is there some doc on how I can achieve that myself and maybe contribute to the repo?

**Comment by kenarsa** [comment]
Thanks for bringing this up. You can use the Flutter binding as a starting point I believe. Once you have a working binding with unit tests passing (you can look at how they are done for other bindings) please submit a PR and someone from the Picovoice team will help you push that through. Happy coding!
