### ISSUE TITLE
cortex-a53 & cortex-a7 bug

### ISSUE THREAD

**Issue by oziee** [Picovoice/Porcupine#85]
compiling on a RPi3B+ the lib cortex-a53 or cortex-a7 produces this error during pv_porcupine_init 
"[ERROR] loading parameter file failed with 'IO_ERROR'"
This error does not occur with the same RPi3B+ and code when compiled against arm11

To Reproduce 
using alsa c++ code and RPi3B+

g++ -O3 -I../../include -L../../lib/raspberry-pi/cortex-a53 -Wl,-rpath ../../lib/raspberry-pi/cortex-a53 main.cpp -lpv_porcupine -lasound -o alsademo

OR

g++ -O3 -I../../include -L../../lib/raspberry-pi/cortex-a7 -Wl,-rpath ../../lib/raspberry-pi/cortex-a7 main.cpp -lpv_porcupine -lasound -o alsademo

HOWEVER.. if it is compiled with arm11 there is no error and the program runs fine

**Comment by kenarsa** [comment]
Could you see if you can use the python demo on RPi2/3? with the .so file under cortex-a7/53 ? Then I'll look into this. Thanks.

**Comment by oziee** [comment]
was old version 1.3 files.. i must have only copied over the new 1.4 files for arm11 folder only
my bad
all works fine:)
