### ISSUE TITLE
Microcontroller  Support Question

### ISSUE THREAD

**Issue by johnkelton** [Picovoice/porcupine#862]
In the documentation of "Porcupine Wake Word", its is mentioned that the support exists for cross platform like:
"Arm Cortex-M, STM32, Arduino, and i.MX RT"
Does that mean for Arm Cortex-M0, Arm Cortex-M0+, Arm Cortex-Mx..?
For STM32 it could be any STM32xxxx?
and for All Arduinos?
provided that we can capture the audio in 16bit PCM format and hand it over to Picovoice engine?

"Picovoice Platform Microcontroller Quick Start" Guide only mentions two platforms:
Arm Cortex-M4
Arm Cortex-M7
Only these two platforms mentioned because you have dev kit code available for only these?

**Comment by kenarsa** [comment]
You can see the list of available MCU libs [here](https://github.com/Picovoice/porcupine/tree/master/lib/mcu). That is all Picovoice supports.

**Comment by johnkelton** [comment]
I appreciate your prompt responses but I would really really appreciate if you really help with the questions I am asking. Your responses are giving me an impression that beyond what is documented,  PicoVoice admin/dev would not clarify or extend their support. 

I will again request that help me answer few of my questions and these will definitely benefit other people who want to incorporate your awesome engine into their projects. 

Does PicoVoice support all variants of Arm Cortex-Mx? This is not clear from your online documentation. Moreover, only examples of Arm Cortex-M4 and Arm Cortex-M7 are provided. Does that mean that only these variants are supported and nothing else?

Your online documentation says Arduino, as you know their are many many "Arduino" boards! so only the Arm Cortex-M4, Arm Cortex-M7 Arduino boards are compatible?

 Same is the question for STM32, you do have libraries that you pointed to and the way you responded it appears that only the MCUs on the DEV kits of these libraries are supported. 

I am requesting PicoVoice to clarify their own online documentation so makers like me wont waste time on wrong MCUs and spend time building and learning from your engine.

**Comment by mrrostam** [comment]
Hey @johnkelton
Thank you for your interest in the Porcupine engine; 

> In the documentation of "Porcupine Wake Word", its is mentioned that the support exists for cross platform like:
> "Arm Cortex-M, STM32, Arduino, and i.MX RT", Does that mean for Arm Cortex-M0, Arm Cortex-M0+, Arm Cortex-Mx..?

We do have some internal ports of the engine for other variants of Arm Cortex-M, such as Arm Cortex-M0+; however, all supported boards which are available to the public at the moment are either Arm Cortex-M4 or Arm Cortex-M7. If you need something specific for a commercial application and you are at a point to engage formally you can contact the [sales team](https://picovoice.ai/contact/) and they might find a way to accommodate your request.

> For STM32 it could be any STM32xxxx?

Again, we only officially support those STM32 MCUS listed [here](https://github.com/Picovoice/porcupine/tree/master/lib/mcu), but you might be able to use the same lib files for other STM32 MCUs as long as they belong to the same series.

> and for All Arduinos?

Please refer to [Porcupine Wake Word Arduino Quick Start](https://picovoice.ai/docs/quick-start/porcupine-arduino/) for the list of supported boards.
