### ISSUE TITLE
Android - Bluetooth SCO 16khz -> 8khz

### ISSUE THREAD

**Issue by dagsystel** [Picovoice/Porcupine#87]
Your Detection use 16khz to detect the wake word. 
But to use an Android device with a Bluetooth Headset you need to activate Bluetooth SCO, which allows only 8khz input streams. (https://developer.android.com/reference/android/media/AudioManager#startBluetoothSco())
So I’m not a sound engineer, therefore I don’t know anything about up sampling but this could be a possible solution for this problem.
So in your code there is the Class “AudioRecoder” with record():
 
```
private void record() throws PorcupineManagerException {
    int bufferSize = Math.max(sampleRate / 2,
            AudioRecord.getMinBufferSize(sampleRate, AudioFormat.CHANNEL_IN_MONO,
                    AudioFormat.ENCODING_PCM_16BIT));

    // use short to hold 16-bit PCM encoding
    short[] buffer = new short[frameLength];
    AudioRecord record = null;
    try {
        record = new AudioRecord(MediaRecorder.AudioSource.MIC, sampleRate,
                AudioFormat.CHANNEL_IN_MONO, AudioFormat.ENCODING_PCM_16BIT, bufferSize);
        record.startRecording();

        while (!stop.get()) {
            int r = record.read(buffer, 0, buffer.length);
            //if there are enough audio samples pass it to the consumer.
            if (r == buffer.length) {
                audioConsumer.consume(buffer);
            } else {
                LogUtils.debug(TAG, "Not enough samples for the audio consumer.");
            }
        }
        record.stop();

    } catch (IllegalArgumentException | IllegalStateException e) {
        throw new PorcupineManagerException(e);
    } finally {
        if (record != null) {
            record.release();
        }
        stopped.set(true);
    }
}
```
 
So before calling record() I need to set up the Bluetooth SCO. 
Afterwards the AudioRecord should be up sampled before sending to AudioConsumer.consume(buffer).
But I don’t know if this works, because after this you call the JNI and native code to analyze the bytes and this is a black box for me.
 
Maybe you have a solution for this problem. 
Another idea would be to allow also 8khz input for detecting wake words, but maybe it’s too bad??

**Comment by kenarsa** [comment]
1- Do you need to upsample yourself? You can probably ask for 16K audio and AudioRecord will upsample internally? If not you can just repeat every sample twice to upsample.
2- When feeding upsampled 8KHz audio the performance is suboptimal because the frequency content between 4-8 KHz is set to zero.

But I still expect this to work but not as good as 16KHz audio.

**Comment by kenarsa** [comment]
good. closing the issue for now.
