### ISSUE TITLE
Porcupine throws runtime error on running 

### ISSUE THREAD

**Issue by Nawal25** [Picovoice/porcupine#881]
Hi, I have been trying to use porcupine in python with [pvpocrupine on PyPI](https://pypi.org/project/pvporcupine/), with a very basic example of instantiating the porcupine object with access_key and keywords, it throws an unknown runtime error.
**Here is the code.**

import pvporcupine
access_key = "My-access-key"
porcupine = pvporcupine.create(access_key=access_key, keywords=['computer'])

**Here is the error stack trace** 

PorcupineActivationLimitError             Traceback (most recent call last)
[<ipython-input-10-4cd6f2fddc6f>](https://localhost:8080/#) in <module>
      1 import pvporcupine
      2 access_key = "-------------------------"
----> 3 porcupine = pvporcupine.create(access_key=access_key, keywords=['computer'])

1 frames
[/usr/local/lib/python3.8/dist-packages/pvporcupine/porcupine.py](https://localhost:8080/#) in __init__(self, access_key, library_path, model_path, keyword_paths, sensitivities)
    156             byref(self._handle))
    157         if status is not self.PicovoiceStatuses.SUCCESS:
--> 158             raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
    159 
    160         self._delete_func = library.pv_porcupine_delete

PorcupineActivationLimitError:

**system spec:**
windows:  10  64bit
python 3.9.13
pvporcupine 2.1.4

**Earlier it runs flawlessly great.
any help is highly appreciated!**

**Comment by ksyeo1010** [comment]
This error means you reached your limit on the number of device activations with your access key. You have up to 3 devices in the free tier.

**Comment by Nawal25** [comment]
Thanks a lot for the support.
