### ISSUE TITLE
Can't run python demo on raspberry pi 3 model B

### ISSUE THREAD

**Issue by bd05** [Picovoice/Porcupine#89]
### Expected behavior
Python demo on Raspberry pi 3 Model B should run as in demo video.
### Actual behavior
Upon trying to run python demo on Raspberry pi 3 Model B, am getting this error:

```
python demo/python/porcupine_demo.py --keyword_file_paths ./resources/keyword_files/blueberry_raspberry-pi.ppn --library_path ./lib/raspberry-pi/cortex-a53/libpv_porcupine.so
listening for:
- blueberry (sensitivity: 0.500000)
Traceback (most recent call last):
  File "demo/python/porcupine_demo.py", line 222, in <module>
    input_device_index=args.input_audio_device_index).run()
  File "demo/python/porcupine_demo.py", line 100, in run
    sensitivities=self._sensitivities)
  File "demo/python/../../binding/python/porcupine.py", line 88, in __init__
    raise IOError("Could not find keyword file at '%s'" % x)
IOError: Could not find keyword file at './resources/keyword_files/blueberry_raspberry-pi.ppn'

```

### Steps to reproduce the behavior
1. `cd` into `Porcupine directory`
2. run `python demo/python/porcupine_demo.py --keyword_file_paths /resources/keyword_files/blueberry_raspberry-pi.ppn --library_path ./lib/raspberry-pi/cortex-a53/libpv_porcupine.so`

Tried using `cortex-a7` and `arm11` instead just in case, and for each, also tried the `ibpv_porcupine.a` files. Got the same errors for all of the `.so` files, and got the following output for the `.a` files:

```

listening for:
- blueberry (sensitivity: 0.500000)
Traceback (most recent call last):
  File "demo/python/porcupine_demo.py", line 222, in <module>
    input_device_index=args.input_audio_device_index).run()
  File "demo/python/porcupine_demo.py", line 100, in run
    sensitivities=self._sensitivities)
  File "demo/python/../../binding/python/porcupine.py", line 69, in __init__
    library = cdll.LoadLibrary(library_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./lib/raspberry-pi/cortex-a53/libpv_porcupine.a: invalid ELF header

```

**Comment by kenarsa** [comment]
you have a typo. Change blueberry_raspberry-pi.ppn to blueberry_raspberrypi.ppn
there is no "-" in file name.

**Comment by bd05** [comment]
Hi, I had tried with `blueberry_raspberrypi.ppn` as well, but receive the same errors:

````

 python demo/python/porcupine_demo.py --keyword_file_paths /resources/keyword_files/blueberry_raspberrypi.ppn --library_path ./lib/raspberry-pi/cortex-a53/libpv_porcupine.so
listening for:
- blueberry (sensitivity: 0.500000)
Traceback (most recent call last):
  File "demo/python/porcupine_demo.py", line 222, in <module>
    input_device_index=args.input_audio_device_index).run()
  File "demo/python/porcupine_demo.py", line 100, in run
    sensitivities=self._sensitivities)
  File "demo/python/../../binding/python/porcupine.py", line 88, in __init__
    raise IOError("Could not find keyword file at '%s'" % x)
IOError: Could not find keyword file at '/resources/keyword_files/blueberry_raspberrypi.ppn'

```

**Comment by mamacker** [comment]
Which mic did you find to use?  Not finding a good obvious answer - most appear to be locked at 41kHz. Thanks!

**Comment by oziee** [comment]
use can set in alsa that the mic should use 16khz no matter what mic it is

**Comment by mamacker** [comment]
Thanks!  I actually was able use the more flexible software sink.  It took care of it.  I wrote up documentation on how to get started on raspberry PI here:
https://bloggerbrothers.com/2019/02/20/hot-wording-on-a-raspberry-pi-computer-do-my-bidding/

In case you have others trying to get started on raspberry pi 3.
