### ISSUE TITLE
can you add Cortex-A55 in python of pvporcupine  

### ISSUE THREAD

**Issue by kalous12** [Picovoice/porcupine#897]
I want to use pvporcupine  in python ,but it tell me do not support this cpu.my chip is Cortex-A55 .

I hope you can update it that can support more arm64 chip

**Comment by mrrostam** [comment]
Unfortunately, I don't think we can include this in our immediate roadmap at this moment. 
However, you can hack the [python/util.py](binding/python/util.py) script and make it work for your chip, although this might lead to sub-optimal performance.

**Comment by kalous12** [comment]
can i use the lib/android/arm64-v8a/libpv_porcupine.so to instead lib/raspberry-pi/*/*.so ?
i use pvporcupine in linux python

**Comment by kalous12** [comment]
i use a55 ,is it gona  be okay that i use different chip

**Comment by kalous12** [comment]
can you git me the source code? i want to build it in my device

**Comment by kalous12** [comment]
I have some confuse , Why do you use cortex-a53 instead of arm64-v8a
