### ISSUE TITLE
Porcupine Issue:  [PorcupineActivationError: Initialization failed.] React Native

### ISSUE THREAD

**Issue by blipo26** [Picovoice/porcupine#898]
I am having troubles trying to initialize the porcupine manager, i didn't change any of the code and my quota limits are fine.
The error i am getting when i try to initialize the porcupine manager is:

``[PorcupineActivationError: Initialization failed.]``

The code i use to initialize the manager is:

let detectionCallback = keywordIndex => {
        if (keywordIndex === 0) {
            handleNotification(i18n.t('openApp'), i18n.t('openAppText'));
            appActivated(false);
            uiStore.updateOnActivation(true);
        }
    };

const loadPorcupine = async () => {
        try {
            porcupineRef.current = await PorcupineManager.fromKeywordPaths(
                "${MY_KEY}" ,
                [KEYWORD_PATH],
                detectionCallback,
                error => {
                    porcupineRef.current?.stop();
                    console.log(error);
                },
                'porcupine_params_es.pv',
                [0.5],
            );
            await porcupineRef.current?.start();
            console.log('porcupine started');
        } catch (e) {
            console.log('loadPorcupine', e);
        }
    };

We tried everything: we changed the version of package.json, we tried many versions of the dependency with no success.

**Comment by ksyeo1010** [comment]
Closing issue as bug cannot be reproduced everything is working fine. If you come across the bug, re-open and provide step-by-step instructions so we can reproduce on our end.
