### ISSUE TITLE
Support for Coral Dev Boards

### ISSUE THREAD

**Issue by asmirnou** [Picovoice/porcupine#909]
Could you add support for Coral Dev Board and Dev Board Mini? Running porcupine on these boards results in "Unsupported platform" error. Is there a possible workaround until then?

**Comment by mrrostam** [comment]
I dont think there is a way to run `Porcupine` on this board with the available lib files on Github.
Our immediate roadmap does not include adding support for `Coral Dev Board` and `Dev Board Mini`, but if you are developing a commercial product and are willing to engage formally, you can reach out to our sales team to inquire about obtaining this support through an enterprise package.
