### ISSUE TITLE
Build errors on Apple Watch using Xcode 10 

### ISSUE THREAD

**Issue by dyah10** [Picovoice/Porcupine#91]
### Expected behavior
We expect the demo project for Apple Watch to build and run on Xcode 10.

### Actual behavior
When building, we get the following build error:
`ld: warning: ignoring file /Downloads/Porcupine-master/lib/watchos/libpv_porcupine.a, file was built for archive which is not the architecture being linked (arm64_32): /Downloads/Porcupine-master/lib/watchos/libpv_porcupine.a
Undefined symbols for architecture arm64_32:
ld: symbol(s) not found for architecture arm64_32
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

### Steps to reproduce the behavior
Download the demo project and attempt to run the app on an Apple Watch device.

Please include enough details so that the issue can reproduced independently by the resolver.

**Comment by kenarsa** [comment]
Built the lib with latest xcode. please give it a try.

**Comment by dyah10** [comment]
Thank you @kenarsa for looking into this. I'm still getting the same error. I've downloaded the directory again to make sure I'm working off of the latest demo and lib and unfortunately it's giving me the same error. 

`ld: warning: ignoring file /Downloads/Porcupine-master/lib/watchos/libpv_porcupine.a, file was built for archive which is not the architecture being linked (arm64_32): /Downloads/Porcupine-master/lib/watchos/libpv_porcupine.a Undefined symbols for architecture arm64_32: ld: symbol(s) not found for architecture arm64_32 clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Is there a build setting I need to change?

**Comment by kenarsa** [comment]
Hmmm ... I don't think so. Can you actually run the watchOS demo app?

@herlihalim kindly did a refactor for iOS/watchOS binding. He might have some extra information.

**Comment by dyah10** [comment]
No it's not letting me run the watchOS demo app because of the build errors :/

**Comment by kenarsa** [comment]
@herlihalim could you please help out?

**Comment by herlihalim** [comment]
@kenarsa This is due to the change in Xcode 10, Apple Watch Series 4 has a new architecture arm64_32. I'm not sure about Porcupine's build chain, however, you'll need to recompile the binary ensuring that the new architecture is included.

Also similar thing asked https://github.com/Picovoice/Porcupine/issues/68, the "libpv_porcupine.a" is targeted for watchOS 4.3, however, the demo app target is 4.0.

Course of action from here is to produce new binary, ideally, you set the deployment target for watchOS to 4.0 and iOS to 11.0 as well.

**Comment by herlihalim** [comment]
@dyah10 If all you want is to give this a go, you can workaround this by removing "arm64_32" from "Build Settings > Valid Architecture" for "PorcupineWatchDemo" and "PorcupineWatchDemo Extension". You should be able to compile it after you do that.

**Comment by dyah10** [comment]
@herlihalim thank you for the help. If I remove "arm64_32" we won't be able to run it on an Apple Watch Series 4. We get the following error: "This application does not support this device’s CPU type."

@kenarsa can you produce a new binary that includes the new architecture? It seems like that's all that needs to be done. 

Thank you to you both!

**Comment by herlihalim** [comment]
Yes, that’s correct. Unfortunately, as I have mentioned, it’s just a workaround to get it compilable to non series 4 watch.

@kanersa will be the only one that could help with this.

**Comment by dyah10** [comment]
Fixed. Thank you!
