### ISSUE TITLE
Custom wake word

### ISSUE THREAD

**Issue by Marcin-st** [Picovoice/porcupine#916]
Hello,
After reading about Porcupine i decided to try to replace my current hotword detection with Porcuine. My family is used to use current word/name. But Porcupine console (which generates new model) says word is to short. Is there any chance to get model anyway - even if it will be little bit less accurate. Or maybe there is way to generate model from samples?

**Comment by ksyeo1010** [comment]
The methods you mentioned are not supported by Porcupine. You may want to add some keywords before or after your word if it is too short.

**Comment by Marcin-st** [comment]
No i cant add as mentioned, we are using this phrase for long time and are used to it. It is 4 letters long. Starting from 5 letters console is accepting :(
