### ISSUE TITLE
Porcupine Issue: PorcupineIOError on Windows

### ISSUE THREAD

**Issue by Kanorto** [Picovoice/porcupine#947]
py main.py
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    porcupine = pvporcupine.create(access_key='SWK2wbt0RF/f5bAb3OuwTb+vK+Jfaea+CbFaRhGmC+fb2tX2T2QgQQ==',keywords=['jarvis'],sensitivities=[1])
  File "C:\Program Files\Python38\lib\site-packages\pvporcupine\_factory.py", line 69, in create
    return Porcupine(
  File "C:\Program Files\Python38\lib\site-packages\pvporcupine\_porcupine.py", line 164, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineIOError

windows 10, pip23.1, pvporcupine-2.2.0.
Project https://github.com/Priler/jarvis
access_key edited

**Comment by laves** [comment]
I just successfully initialized `pvporcupine-2.2.0` on Windows 10 with the command you've posted here (with my access_key). Can you provide more information about the environment you're running it in? Could you provide a minimal reproducible example for us? The repo you've linked has too many other components to it.

**Comment by Kanorto** [comment]
Thanks for your reply, unfortunately I don't know python, so I turned to you, hoping for help in fixing this bug. I am running it on python 3.8.3. Please help me get this project started. The main code is in main.py, on line 46. When you try to remove the error code from your package, the program starts to partially work. You can give your initiation script, I will try to insert it in a separate file.

**Comment by laves** [comment]
We are unable to provide general coding help through this forum. If there is an issue with Porcupine or one of the Porcupine SDKs, please provide enough details so that we can reproduce it and we'll get to fixing it ASAP. I suggest you check out our [docs](https://picovoice.ai/docs/) or try out the [Porcupine Python demo](https://github.com/Picovoice/porcupine/tree/master/demo/python) if you want to familiarize yourself with the Porcupine Python SDK.

**Comment by Kanorto** [comment]
Thanks for your reply. I will try demo version. Sorry

**Comment by MaksimSergin** [comment]
@laves I tried [Porcupine Python demo](https://github.com/Picovoice/porcupine/tree/master/demo/python) and error remained

I am using `python 3.8.3`, `pvporcupine 2.2.0` and `windows 10`. After command ```
./porcupine_demo_mic --access_key "my token" --k
eywords picovoice porcupine ```

I am getting this error:

```
(venv) PS C:\porcupine-master\demo\python> ./porcupine_demo_mic --access_key "my token" --k
eywords picovoice porcupine
Failed to initialize Porcupine
Traceback (most recent call last):
  File "C:\porcupine-master\demo\python\porcupine_demo_mic.py", line 159, in <module>
    main()
  File "C:\porcupine-master\demo\python\porcupine_demo_mic.py", line 113, in main
    raise e
  File "C:\porcupine-master\demo\python\porcupine_demo_mic.py", line 89, in main
    porcupine = pvporcupine.create(
  File "C:\porcupine-master\demo\python\venv\lib\site-packages\pvporcupine\_factory.py", line 69, in create
    return Porcupine(
  File "C:\porcupine-master\demo\python\venv\lib\site-packages\pvporcupine\_porcupine.py", line 164, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineIOError
```
Which other information I can provide for you?

**Comment by Kanorto** [comment]
i too

D:\jarvis-master\poptest>py porcupine_demo_mic.py --access_key SWK2wbt0RF/f5bAb3OuwTb+vK+Jfaea+CbFaRhGmC+fb2tX2T2QgQQ== --keywords jarvis
Failed to initialize Porcupine
Traceback (most recent call last):
  File "porcupine_demo_mic.py", line 159, in <module>
    main()
  File "porcupine_demo_mic.py", line 113, in main
    raise e
  File "porcupine_demo_mic.py", line 89, in main
    porcupine = pvporcupine.create(
  File "C:\Program Files\Python38\lib\site-packages\pvporcupine\_factory.py", line 69, in create
    return Porcupine(
  File "C:\Program Files\Python38\lib\site-packages\pvporcupine\_porcupine.py", line 164, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineIOError

**Comment by harchock** [comment]
in pvporcupine folder
there are lib, resource folders
![image](https://user-images.githubusercontent.com/103359803/232981222-be588d2f-d026-47ff-9303-ef124ce782c7.png)
these folders are not empty
![image](https://user-images.githubusercontent.com/103359803/232981343-be47ee0d-d15a-415d-af1d-4159444ba453.png)
![image](https://user-images.githubusercontent.com/103359803/232981368-74403580-9548-494c-8228-b49898508bda.png)

**Comment by harchock** [comment]
when starting the project itself and the demo version that we downloaded from your github site
it throws an error on its own files, namely _factory.py
_porcupine.py

**Comment by harchock** [comment]
I slightly tweaked the code that was in that project, but I didn’t fix the error with picovoice
![image](https://user-images.githubusercontent.com/103359803/232983986-7ef950bf-53b9-4296-9d0d-c16fd7db755d.png)
here is the code snippet
```python
porcupine = pvporcupine.create(
    access_key='my api code',
    keywords=['jarvis'],
    sensitivities=[1])
```

**Comment by belnek** [comment]
> Thank you for the information. We were finally able to reproduce it and are actively working on a fix.

Excuse me, but how long will it take?

**Comment by belnek** [comment]
Maybe there is some workaround trick?:)

**Comment by Priler** [comment]
> Thank you for the information. We were finally able to reproduce it and are actively working on a fix.

Is it related only to Python SDK or other SDKs are also affected?

**Comment by laves** [comment]
There will be a fix in the coming weeks, but I cannot commit to an exact timeline at this time. The issue affects all SDKs in a Windows environment.

**Comment by Priler** [comment]
![image](https://user-images.githubusercontent.com/11755312/235184154-68d8418c-8f29-441e-bbd6-c50e65d0bd0a.png)

I can confirm, Rust SDK in a Windows environment also affected.

**Comment by Priler** [comment]
Hello @laves,
I hope you are doing well; is there an update on this bug?

**Comment by xador70** [comment]
Hi @laves,

Are you going to do a fix on Windows anytime soon? I would appreciate it if you could. Thanks!

**Comment by laves** [comment]
Hello folks - thank you for your patience. We've released a patch that should address this issue. Upgrade `pvporcupine` to `2.2.1` to grab the release.

**Comment by laves** [comment]
This has been addressed so I'm going to close the issue. Feel free to reopen if it you see the error again.

**Comment by lonngxiang** [comment]
same error

**Comment by lonngxiang** [comment]
> Hello folks - thank you for your patience. We've released a patch that should address this issue. Upgrade `pvporcupine` to `2.2.1` to grab the release.

pvporcupine-2.2.1，aslo error

```

porcupine = pvporcupine.create(access_key="VInSKF4MK***84R5NllrROuaey9ysv2PTbjQ==",keyword_paths=[r'C:\User***ds\xiaojie_zh_windows_v2_2_0\***.ppn'])

```

\pvporcupine\_porcupine.py", line 164, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineInvalidArgumentError

**Comment by ksyeo1010** [comment]
> > Hello folks - thank you for your patience. We've released a patch that should address this issue. Upgrade `pvporcupine` to `2.2.1` to grab the release.
> 
> pvporcupine-2.2.1，aslo error
> 
> ```
> 
> porcupine = pvporcupine.create(access_key="VInSKF4MK***84R5NllrROuaey9ysv2PTbjQ==",keyword_paths=[r'C:\User***ds\xiaojie_zh_windows_v2_2_0\***.ppn'])
> ```
> 
> \pvporcupine_porcupine.py", line 164, in **init** raise self._PICOVOICE_STATUS_TO_EXCEPTIONstatus pvporcupine._porcupine.PorcupineInvalidArgumentError

this is not the same error. If you believe this is a bug, open a new thread with more details.
