### ISSUE TITLE
Porcupine Issue: Web demo not working

### ISSUE THREAD

**Issue by ddsky** [Picovoice/porcupine#949]
### Expected behaviour
Following the readme tutorial at https://github.com/Picovoice/porcupine/tree/master/demo/web I expect the local server to start

### Actual behaviour
When running yarn, I get "no such file or directory, lstat '....\porcupine\demo\web\resources\keyword_files\wasm\papaya'

This folder does not exist nor is explained where to get these resources from.

### Steps to reproduce the behaviour
run:
yarn
yarn start

**Comment by laves** [comment]
The files are located in the repo [here](https://github.com/Picovoice/porcupine/tree/master/resources/keyword_files/wasm), so if the repo has been cloned then the keyword file should be present in that location. Are those files present in your clone of the repo? If so, are you running the yarn commands from the `demo/web` subdirectory?

**Comment by ddsky** [comment]
@laves thanks. Yes, I cloned the repo and the files are under `resources/keyword_files`. When running `yarn`, in `demo/web`, the files are expected to bei in `demo/web/resources/keyword_files` though. Should I just copy or have I missed some configuration?

If it matters, I'm running this on Windows.

**Comment by laves** [comment]
@ddsky - there was indeed an issue with copy script on Windows. I've addressed it with https://github.com/Picovoice/porcupine/pull/952. Pull latest and it should work for you now.

**Comment by laves** [comment]
Reopen if you're still experiencing issues.

**Comment by ddsky** [comment]
@laves works wonderfully, thanks for the quick fix! 👍
