### ISSUE TITLE
Porcupine demo issue on french version

### ISSUE THREAD

**Issue by gigi35** [Picovoice/porcupine#953]
Hi,
I am working with MCU version for STM32F411.
On STM32F411Ediscovery kit, I ran successfully english version of demo. When I changed for the french version, it always fails during initialization with this message : "Picovoice init failed with 'INVALID_ARGUMENT'".
I am using a custom generation environment based on Linux with CMake  : to switch from the english to the french versions, I replaced :
#define __PV_LANGUAGE_ENGLISH__
with
#define __PV_LANGUAGE_FRENCH__
and linked with 
sdk/mcu/lib/stm32f411/fr/libpicovoice.a
instead of 
sdk/mcu/lib/stm32f411/en/libpicovoice.a
Anything else missing ?

Thanks for your support

**Comment by mrrostam** [comment]
Thanks for reporting the issue. The problem with the default French keyword model is now fixed. Can you please try again and confirm if it's working for you?

**Comment by gigi35** [comment]
Bug fixed : correct execution with your correction. Thanks a lot.
