### ISSUE TITLE
porcupine-web-react-demo not working

### ISSUE THREAD

**Issue by prototypersf** [Picovoice/porcupine#955]
Getting an error when trying the local demo version of the app. Getting a similar error when trying to use my own phrase model.

Error: "'pv_porcupine_init' failed with status INVALID_ARGUMENT\nDetails: "

The error above happens when I try to init porcupine.

Demo: https://github.com/Picovoice/porcupine/tree/master/demo/react
Platform: Mac M1, Ventura 13.3, latest Chrome browser.

![image](https://user-images.githubusercontent.com/112650326/233143681-a0696485-4277-4966-95eb-030ad8204972.png)

**Comment by ksyeo1010** [comment]
Demo is working correctly on my end. Can you make sure your access key is correct and valid? Do you get any errors on the console?

**Comment by prototypersf** [comment]
The access key is correct, There is the same error in the console: [ERROR] loading parameters failed with `INVALID_ARGUMENT`

**Comment by prototypersf** [comment]
Could it be in any way related to M1?

**Comment by ksyeo1010** [comment]
Can you ensure the file `src/lib/porcupine_params.js` exists relative to the react demo directory? (run `yarn` again to ensure files are being copied correctly) It should not be an M1 issue as I tested it on an M1 with the same details as you described.

**Comment by prototypersf** [comment]
Same thing after restart, I even updated Chrome to the latest version just now. 
I also tried setting up my own model following https://picovoice.ai/blog/wake-word-detection-with-reactjs/
and receiving a similar error:
[ERROR] keyword file has incorrect format or belongs to a different platform
b2cc573f-fe41-4e1b-a8ae-260371ecc971:2343 [ERROR] loading keyword file at `Hey Speaker` failed with `INVALID_ARGUMENT`
I tried recreating the model 3 times so far... I think the errors are related. What are good steps for me to troubleshoot this?

**Comment by prototypersf** [comment]
That magic flag made it work :) 
![image](https://user-images.githubusercontent.com/112650326/233189254-06a1f16d-a30a-4a4b-b71e-197af65c4f49.png)

**Comment by ksyeo1010** [comment]
Great! You can read more about model initializer flags here: https://github.com/Picovoice/porcupine/tree/master/binding/react#porcupine-model.

**Comment by prototypersf** [comment]
Thank you!
