### ISSUE TITLE
Newbie needing assistance

### ISSUE THREAD

**Issue by sekomike910** [Picovoice/porcupine#960]
I am using Windows and python is not able to recognize the file. When I open the windows hey google_wondows.ppn file it appears as gibberish / Chinese and VS Code returns the following error when I attempt to open. 'The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Here is a sample from notepad. 

梽ⴓꔇና꒩짮罿๖ꊌ칧ꦽ뒂녖豄쯢뉜꫒ꖄ聘䌢⑭㓄荬Ʌ㺚笯㩩ચ鴝웯㫞덇蓍ꁿ䓚崓抅觮꜆勍㈵髲摤હ灏痿ⵝ鈋⣧稑쳗ᓕ欔岘﻽흊칲郋婮ھ酦�㙽㻕횼繆征ᤉﾲ꼧ﰡᒢㅼ訯∞໮鐶ൗ벛邰ꡬ䫽㘢ꮻ䯍㮿ᕊ챋⫍鱚꾻곬힏∣ﮘ濏뽆覮쉩Ή亊ꛪ웤⃳�᪋⃚覗榎݌඙�䲍Ⅵשּߒ쇲㶂ᘎ襋鶰ᧇ窵齂ổ嚱힋鎪﹦Ỉ䀷︳뗡쑰킏㒵疞ۻ˼恈죳䍽逃፿黬䀅ꐍ鶴긣뉸㢼摓﹄담὘뻭㓦析᫜溶⏁跬郥᫂ឥ舅㳜満ᛨ쒧⣧쮞℘�᣶䎸衍愑ლ䌺쉊③︢ྫྷ㼳Ă�쭰�㒷恥꧲韰궘᳇ꊬ엞瀓쯨뀥ﴜỐ園娀�뺈烌竕�躨緆륞

Is there something I am doing incorrectly?

**Comment by mrrostam** [comment]
It is expected as "hey google_windows.ppn" is a binary file that must be provided as input to Porcupine during initialization. It's not clear why you would want to open it in an editor. I recommend starting with the [documentation on our website](https://picovoice.ai/docs/quick-start/porcupine-python/) or checking out the [Python demo](https://github.com/Picovoice/porcupine/tree/master/demo/python) available on our Github page.
