### ISSUE TITLE
The program can't start because libgccsdw2-1.dll is missing from your computer

### ISSUE THREAD

**Issue by harris7** [Picovoice/Porcupine#97]
I have successfully managed to produce a keyword file in windows 7 (x64) using the following command in the cmd:

C:\Users\User\Documents\Porcupine-master\Porcupine-master\tools\optimizer\windows\amd64/pv_porcupine_optimizer -r resources/ -p windows -o C:\Users\User\Documents\Porcupine-master\Porcupine-master -w "jarvis"

I have then tried to test it by running the following command:

C:\Users\User\Documents\Porcupine-master\Porcupine-master\demo\python\porcupine_demo_non_blocking.py --keyword_file_paths C:\Users\User\Documents\Porcupine-master\Porcupine-master\jarvis_windows.ppn

Which has given the error:

The program can't start because libgccsdw2-1.dll is missing from your computer. Try reinstalling the program to fix this problem.

Does anyone have any tips on how to fix this issue?
And also (not-essential), does anyone have any pointers on how to start integrating this into a python script

Many thanks in advance

Oliver Harris

**Comment by kenarsa** [comment]
You need to install http://www.mingw.org/

**Comment by harris7** [comment]
> You need to install http://www.mingw.org/

It seems I may have spoken too soon. It worked on my windows 10 laptop but did not work on my windows 7 pc (the intended use). Any other suggestions?

**Comment by kenarsa** [comment]
please use the template for opening an issue. You need to provide enough details so I can point you in the right direction.
