### ISSUE TITLE
Porcupine Issue: rpi microphone (repeaker 2-mic hat) not found

### ISSUE THREAD

**Issue by mph070770** [Picovoice/porcupine#971]
I have a Respeaker 2-mic HAT which is shown in arecord/aplay but not in porcupine_demo_mic when using --show_audio_devices.

How do I get the HAT to work?  Thanks

pi@raspberrypi:~/porcupine $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 2: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 [bcm2835-i2s-wm8960-hifi wm8960-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

pi@raspberrypi:~/porcupine $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: vc4hdmi0 [vc4-hdmi-0], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: vc4hdmi1 [vc4-hdmi-1], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 [bcm2835-i2s-wm8960-hifi wm8960-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

pi@raspberrypi:~/porcupine $ ./porcupine_demo_mic --show_audio_devices --access_key xxx==
Device 0: Monitor of Built-in Audio Digital Stereo (HDMI)

**Comment by kenarsa** [comment]
Have you tried the [official demo](https://github.com/Picovoice/porcupine/tree/master/demo/respeaker)?

**Comment by mph070770** [comment]
Thanks for your suggestion @kenarsa.  I was hopeful that this might solve the problem but I get the same issue:

pi@raspberrypi:~/porcupine $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 2: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 [bcm2835-i2s-wm8960-hifi wm8960-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

pi@raspberrypi:~/porcupine $ porcupine_respeaker_demo --access_key xx
[Listening ...]
[WARN] Input device might be muted or volume level is set to 0.
[WARN] Input device might be muted or volume level is set to 0.
[WARN] Input device might be muted or volume level is set to 0.
[WARN] Input device might be muted or volume level is set to 0.
[WARN] Input device might be muted or volume level is set to 0.
Stopping ...

**Comment by kenarsa** [comment]
The messages indicate that there is probably no audio from your mic. It could be an HW or config problem. I suggest using `arecord` to debug and see if you get audio in.

**Comment by mph070770** [comment]
I've made some progress.  I used the rpi0 demo, as follows:

built the demo:

`pi@raspberrypi:~/porcupine $ gcc -std=c99 -O3 -o demo/respeaker-rpi0/porcupine_demo_mic -I include/ demo/respeaker-rpi0/porcupine_demo_mic.c -ldl -lasound`

ran the demo, using the library for the Arm used on a PI400 (cortex-a72):

```
./demo/respeaker-rpi0/porcupine_demo_mic \
xxx== \
lib/raspberry-pi/cortex-a72-aarch64/libpv_porcupine.so \
lib/common/porcupine_params.pv \
0.65 \
plughw:CARD=seeed2micvoicec,DEV=0 \
resources/keyword_files/raspberry-pi/alexa_raspberry-pi.ppn \
resources/keyword_files/raspberry-pi/computer_raspberry-pi.ppn \
resources/keyword_files/raspberry-pi/hey\ google_raspberry-pi.ppn \
resources/keyword_files/raspberry-pi/hey\ siri_raspberry-pi.ppn \
resources/keyword_files/raspberry-pi/jarvis_raspberry-pi.ppn \
resources/keyword_files/raspberry-pi/picovoice_raspberry-pi.ppn \
resources/keyword_files/raspberry-pi/porcupine_raspberry-pi.ppn \
resources/keyword_files/raspberry-pi/bumblebee_raspberry-pi.ppn \
resources/keyword_files/raspberry-pi/terminator_raspberry-pi.ppn
```

This works:

```
[Listening]
detected 'Porcupine'
detected 'Alexa'
detected 'Terminator'
```

This will get me going but perhaps there's an issue with the respeaker demo and seeedmic2?

**Comment by kenarsa** [comment]
I doubt it. I think it's an audio setup issue. The other demo is using `ALSA` directly. If that works you can use it.
