### ISSUE TITLE
python error after compiling to exe with pvporcupine library

### ISSUE THREAD

**Issue by KnlCE** [Picovoice/porcupine#978]
After compiling the python file to exe, the following error appears:
Traceback (most recent call last):

 File "test1.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "pvporcupine\__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "pvporcupine\_factory.py", line 17, in <module>
  File "pvporcupine\_util.py", line 136, in pv_keyword_paths
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'C:\\Users\\ampli\\AppData\\Local\\Temp\\_MEI144722\\pvporcupine\\resources/keyword_files\\windows'
In the script I work with the pvporcupine library

**Comment by laves** [comment]
it seemed as though the program had trouble finding the following path: `C:\Users\ampli\AppData\Local\Temp\_MEI144722\pvporcupine\resources/keyword_files\windows`

Does that path exist and have `.ppn` files in it? Internal resources that the SDK uses should be located there.

**Comment by KnlCE** [comment]
> казалось, что программа не может найти следующий путь:`C:\Users\ampli\AppData\Local\Temp\_MEI144722\pvporcupine\resources/keyword_files\windows`
> 
> Существует ли этот путь и есть ли `.ppn`в нем файлы? Внутренние ресурсы, которые использует SDK, должны быть расположены там.
This path does not exist and therein lies the problem. Why is he looking for this path? I showed him another way, or how to change it

**Comment by KnlCE** [comment]
??

**Comment by laves** [comment]
Depending on how the Python was compiled, the compilation process may have broken the links between the Porcupine library and its internal resources. Can I ask how you compiled it? Please provide enough information so that we can reproduce the process fully on our side.

**Comment by KnlCE** [comment]
> Depending on how the Python was compiled, the compilation process may have broken the links between the Porcupine library and its internal resources. Can I ask how you compiled it? Please provide enough information so that we can reproduce the process fully on our side.

The file was compiled with PyInstaller. And the compilation went through the command line in Visual Studio. The compilation command looks like this:
pyinstaller -F -i "D:\My doc\Nikita\python\Amy.ico" --add-data "tts.py;." --add-data "config.py;." Amy2.1.py

**Comment by laves** [comment]
@KnlCE - thanks. We'll try to reproduce this on our side.

**Comment by KnlCE** [comment]
> @KnlCE, I was able to reproduce this. The PyInstaller compilation was indeed not packaging any of the resources we include with the `pvporcupine` python library. By default, it seems that PyInstaller only includes Python files in its compilation when you use the `-F` option. This applies to all libraries that your application depends on. To fix this, you need to tell PyInstaller that you also want to include the non-python files that `pvporcupine` requires. To do this, add `--collect-all pvporcupine` to your compilation command:
> 
> ```
> pyinstaller -F -i "D:\My doc\Nikita\python\Amy.ico" --add-data "tts.py;." --add-data "config.py;." --collect-all pvporcupine Amy2.1.py
> ```
> 
> If you're using our `pvrecorder` package, you'll also need to use `--collect-all pvrecorder`. Let us know if that helps.

PROBLEM SOLVED! I assumed that the solution would be simple, but I could not do it myself. Thank you so much

**Comment by laves** [comment]
Great!
