### ISSUE TITLE
[ERROR] failed to parse AccessKey

### ISSUE THREAD

**Issue by veslo228** [Picovoice/porcupine#980]
Good afternoon. It says my AccessKey is wrong, but I'm sure it's right. I copied it from the website to the AccessKey menu

**Comment by laves** [comment]
@veslo228 - please supply more information when posting GitHub issues in the future. What SDK were you using? Did this occur in one of our demos or was it a program of your own? How did you enter your AccessKey? Please do not share your AccessKey in your responses.
