### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/porcupine-android/)

### ISSUE THREAD

**Issue by nahakiole** [Picovoice/porcupine#994]
### What is the URL of the doc?

https://picovoice.ai/docs/quick-start/porcupine-android/
Although the issues are apparent in most of the other pages as well, but I noticed it while trying to get started with Android.

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

I'm writing to share some feedback about the Porcupine Android documentation.

```
dependencies {
    // ...
    implementation 'ai.picovoice:porcupine-android:${LATEST_VERSION}' // replace with latest version
}
```

It's currently a bit tedious to search for the latest version of the Porcupine Android library. Providing a direct link to the version list in the documentation would greatly streamline the setup process. Or it would be nice if the latest version would already be in the example code. Currently you have to search yourself for the latest version.

```
import ai.picovoice.porcupine.*;

PorcupineMananger porcupineManager = new PorcupineManager.Builder()
  .setAccessKey("${ACCESS_KEY}")
  .setKeywords([Porcupine.BuiltInKeyword.PORCUPINE, Porcupine.BuiltInKeyword.BUMBLEBEE])
  .build(context, wakeWordCallback);

PorcupineManagerCallback wakeWordcallback = new PorcupineManagerCallback() {
  @Override
  public void invoke(int keywordIndex) {
    if (keywordIndex == 0) {
      // porcupine detected
    } else if (keywordIndex == 1) {
      // bumblebee detected
    }
  }
}
```

It would be great to have a fully working version as a class instead of having to copy paste together a working version which takes a lot of time and trial and error. 

```
PorcupineManager porcupineManager = new PorcupineManager.Builder()
  .setAccessKey("${ACCESS_KEY}")
  .setKeywordPaths(["${KEYWORD_FILE_PATH}"])
  .setModelPath("${MODEL_FILE_PATH}")
  .build(context, wakeWordCallback);
```

Instead of using placeholders the values should rather be example values, which would help know which values go where. So instead of the above you could use a code example like this:

```
models = new String[]{
            "model_de_android_v2_2_0.ppn"
    };
}

porcupineManager = new PorcupineManager.Builder()
        .setAccessKey("hereisthekeyfromthe")
        .setKeywordPaths(models)
        .setModelPath("porcupine_params_de.pv")
        .build(context, wakeWordcallback);
```

I think a lot of people have issues getting started, as theses issues are the same for all the sdks and products. Fixing them throughout your docs would help people get started.

If possible, I also suggest considering a publicly editable version of your docs. This way, your user community could contribute to improving the documentation through pull requests.

Finally, I would love if there were more flexible licensing options for academic use or small-scale projects. The current pricing structure, with its artificial usage limits, can be prohibitive for users like me who are eager to use your products but find the cost challenging to justify.

I hope you find this feedback useful, and I'm happy to provide any additional details if required. Could you please consider these suggestions to help improve your documentation and services?

PS: Seeing your models running on physical robots is really cool: https://www.youtube.com/shorts/_6jtz-nFu3E

PPS: I noticed you are using a picture of mine in your blog 😃 
![image](https://github.com/Picovoice/porcupine/assets/4542479/708a32f0-c695-4a2e-a074-acdb6395960e)
https://unsplash.com/de/fotos/zP7X_B86xOg

**Comment by ksyeo1010** [comment]
Thank you for your feedback, we will take it under advisement.
